### ISSUE TITLE
Avoid the multiple connections

### ISSUE THREAD

**Issue by hinter1992** [opensource-socialnetwork/opensource-socialnetwork#1001]
there is new database connection for every database operation.
i think that's not recommended.
i think that you should keep one database connection (singleton) and use it for all database request.

**Comment by lianglee** [comment]
+1

**Comment by lianglee** [comment]
I just checked ,   Ossn close connection after each request,  so i don't think there should be problem.  If you this is issue and effect the site please explain i discuss this with team again.

**Comment by hinter1992** [comment]
you shouldn't connect multiple times. The overhead of opening and closing the connection all the time is bigger than the cost of keeping it open during the relative small time your scripts run. So you should create an instance of the db connection at the start and keep it in a global variable.

**Comment by lianglee** [comment]
Fixed with next version.
