### ISSUE TITLE
Issue on OssnSite.php 

### ISSUE THREAD

**Issue by IanG29** [opensource-socialnetwork/opensource-socialnetwork#1002]
Help ! I got this when I try joining the admin page

Warning: Invalid argument supplied for foreach() in ......\ossn\classes\OssnSite.php on line 36

Notice: Undefined variable: result in ........\ossn\classes\OssnSite.php on line 39

**Comment by githubertus** [comment]
Please run PHPMyAdmin from your provider's cpanel.
And verify the existence of the ossn_site_settings table:
![ossn_site_settings](https://cloud.githubusercontent.com/assets/9904364/21542036/6779478e-cdbb-11e6-97a7-d7d26e36696b.png)

1. Can you confirm having a table like that?
2. What is "joining the admin page"? Please, provide the exact URL where the problem occurs.
