### ISSUE TITLE
New install admin error when logging in.

### ISSUE THREAD

**Issue by remichie** [opensource-socialnetwork/opensource-socialnetwork#1004]
System: Mint Linux 18.1 Serena Mate 64-bit, PHP 7, Apache 2.4.18, MySQL 5.7.16

Installed OSSN with no problems.

After installing v4.3.1 I can log in as admin, but when I go to Administrator from the menu I get this error:

A system error has occurred. Please try again later. You may email the details of this error to the system administrator at info@*******.com.

OssnDatabaseException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ossn.ossn_users.time_created' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by SELECT DATE_FORMAT(FROM_UNIXTIME(time_created), '%Y') AS year, DATE_FORMAT(FROM_UNIXTIME(time_created) , '%m') AS month, COUNT(guid) AS total FROM ossn_users WHERE(time_created > 0) GROUP by DATE_FORMAT(FROM_UNIXTIME(time_created) , '%Y%m') ; in /var/www/html/ossn/classes/OssnDatabase.php:77 Stack trace: #0 /var/www/html/ossn/classes/OssnDatabase.php(175): OssnDatabase->execute() #1 /var/www/html/ossn/classes/OssnUser.php(950): OssnDatabase->select(Array, true) #2 /var/www/html/ossn/system/plugins/default/javascripts/dynamic/admin/dashboard/users/users.php(13): OssnUser->countByYearMonth() #3 /var/www/html/ossn/libraries/ossn.lib.views.php(27): include('/var/www/html/o...') #4 /var/www/html/ossn/libraries/ossn.lib.views.php(50): ossn_include('/var/www/html/o...', Array) #5 /var/www/html/ossn/libraries/ossn.lib.plugins.php(75): ossn_view('/var/www/html/o...', Array) #6 /var/www/html/ossn/system/plugins/default/pages/administrator/contents/dashboard.php(156): ossn_plugin_view('javascripts/dyn...') #7 /var/www/html/ossn/libraries/ossn.lib.views.php(27): include('/var/www/html/o...') #8 /var/www/html/ossn/libraries/ossn.lib.views.php(50): ossn_include('/var/www/html/o...', Array) #9 /var/www/html/ossn/libraries/ossn.lib.plugins.php(75): ossn_view('/var/www/html/o...', Array) #10 /var/www/html/ossn/libraries/ossn.lib.admin.php(204): ossn_plugin_view('pages/administr...') #11 /var/www/html/ossn/libraries/ossn.lib.page.php(67): ossn_administrator_pagehandler(Array, 'administrator') #12 /var/www/html/ossn/index.php(21): ossn_load_page('administrator', Array) #13 {main}

![screenshot at 2017-01-04 13-01-55](https://cloud.githubusercontent.com/assets/17544556/21643197/f815dba0-d27e-11e6-94c7-6221674473bf.png)

![screenshot at 2017-01-04 13-02-17](https://cloud.githubusercontent.com/assets/17544556/21643198/f81692f2-d27e-11e6-9344-ba908008d75d.png)

**Comment by lianglee** [comment]
Please see: https://www.opensource-socialnetwork.org/discussion/view/2104/error-message-i-cant-create-user

**Comment by remichie** [comment]
Thanks Lianglee, It works now.
