### ISSUE TITLE
when i go to upgrade

### ISSUE THREAD

**Issue by budafuko** [opensource-socialnetwork/opensource-socialnetwork#1005]
i installed 2.0 flawlessly but when i go to upgrade to new one it says PHP allow_url_fopen is required and MOD_REWRITE REQUIRED. is this my hosting provider or no? cause in 2.0 it says mod rewrite is good and i dont see any pink ones

**Comment by lianglee** [comment]
2.0 ? You installed 2.0 first time/fresh installation?  what is 2.0 ?

**Comment by budafuko** [comment]
ossn 2.0 a previous version. and mod rewrite is green.. i was able to get my provider to fix the other issue but with mod rewrite they indicated that since it is enabled by default on their server and it worked in a previous installation that it may be an issue with your application. i told them other people are using the application just fine and they elevated my ticket. i am waiting to hear back from them but am hoping you may be able to help as well

**Comment by budafuko** [comment]
i am aware that once my community grows i will need to upgrade to a vps but should shared hosting not be fine to start and test?

**Comment by budafuko** [comment]
and yes 2.0 was a fresh install then i just completely removed it and tried to do a fresh install of the latest version and got those issues. and than as i have said

**Comment by budafuko** [comment]
for instance i can make it so that mywebsite.com will come up with an error with mod rewrite required but test.mywebsite.com comes up as an old installation with mod rewrite working.. if you want me to do this and send you the links let me know

**Comment by budafuko** [comment]
like right now test.itsyourquarter.com is up and running 2.0 but itsyourquarter.com wont install with mod_rewrite required as the error. before i got my hosting ocmpany to correct some issues  it would say available update : error but now it says 4.4 dev under update

**Comment by githubertus** [comment]
The major number of mod_rewrite problems in the past resulted from wrong installation directory ownership and write permissions.
Make sure that the directory of your choice has mode `755`
and that it is owned by the webserver. In most cases this is `www-data` - in doubt ask your provider, please.

**Comment by budafuko** [comment]
yes 755 is enabled on all my directories. and set to www which the guy i was talking to said meant it was owned by the webserver

**Comment by budafuko** [comment]
i was able to bypass the mod_rewrite form once but php something wasn't installed at the time and it failed. but after my provider installed that the only prerequisit which is pink is mod_rewrite. my provider assures me it is enabled and every time i try to bypass the form i get an internal server error. i have had to upload the files multiple times because after the innitial load i get error 500 every time. there is no error log and it has been elevated to highest priority with my hosting provider

**Comment by budafuko** [comment]
has anyone ever had success with ipage? i mean i know i will eventually need vps but this should be good to start out untill i need to upgrade my database.. no?

**Comment by githubertus** [comment]
> there is no error log 
I remember no error 500 condition without error log. Contact your provider regarding the location of the server log file and verify that error logging isn't configured to something special.

**Comment by budafuko** [comment]
they were the ones who told me there was no error log. i can access my error logs on my site but they told me it wasn't causing a log to be created

**Comment by budafuko** [comment]
would u like my error logs?

**Comment by budafuko** [comment]
lets get this ipage issue sorted out once and for all so that future patrons may be delighted by our tribulation

**Comment by budafuko** [comment]
do all files need to be 755? i noticed some files in the installation are 644

**Comment by budafuko** [comment]
i can fully install 2.0 and in the prerequisite area mod rewrite is enabled. and it works perfect. thats why i asume it must be a problem with the application... i am so confused

**Comment by githubertus** [comment]
I can't see no running 2.0 on http://itsyourquarter.com/ ?!
If your provider is not able/willing to tell you the location of the error log - better think of changing to another one. We need this log - without there's no chance to track down what's going wrong. FYI:
I have just been at https://webhostinggeeks.com/user-reviews/ipage/?page=1 and the majority of the reviews are indeed not very promising. 

Nevertheless, to give it a last try:
Tell us:
a) the filename of your Ossn installation zip.archive
b) the exact size of that file
Next, clean the installation directory on your server completely and create a file named "info.php" with a simple text editor like notepad with the following lines
```
<?php
  phpinfo();
 ?>
```
Move it to your installation directory and leave us a note when your ready.

**Comment by budafuko** [comment]
https://www.opensource-socialnetwork.org/discussion/view/2042/ossn-v42-has-been-released-please-upgrade-your-website

i had to remove 

+SymlinksIfOwnerMatch

 from .htaccess and.installation/configs/htaccess.dist

and omg i am so happy. ipage are retarted considering it was an answer they gave a customer previously why was it not in the knowledgebase? who knows but thank you for keeping it on yours. i love u lol

**Comment by budafuko** [comment]
sorry the reason 2.0 was no longer on the test server is because i was constantly testing new things to try and get it to work... however this fix was a lot easier than i anticipated.. i think that even without using the .htaccess file from 2.0 that this would have worked regardless. removing that one line of code from .htaccess.dist was all that was necessary.. in the future people from ipage will definatly have this issue and i hope my struggles over the last couple days will help them fix it with ease! i would love so much for our troubles to make other people happy in the future :) 🥇 💯 👍 👍 👍 👍 👍
