### ISSUE TITLE
URL in chat or post doesnt work 

### ISSUE THREAD

**Issue by magnus505** [opensource-socialnetwork/opensource-socialnetwork#1008]
ULR is chat is shows but not clickable 
URL in Post doesnt show up
Theme: goblue
Help!

**Comment by githubertus** [comment]
I just tried a post with http://games.z-mans.net - and it shows up and is clickable.
Please install the the system info component and provide the url of your site.

**Comment by magnus505** [comment]
https://www.sawsumnet.net/socialnetwork

**Comment by githubertus** [comment]
Thank you.
You've installed a lot of addtional components. Try to disable them one after another and check whether it makes a difference. Candidates I would start with are 1. Readmore, 2. Fancybox

Next, I started to register as Santa Claus but your site is sending no activation mail. Maybe you can activate me manually from your admin panel

**Comment by magnus505** [comment]
I added it for a few mins ago.. it cant be that wrong i tryed it then it was new installed without any components

**Comment by githubertus** [comment]
Thanks for activating my account. Just posted a Url and it shows up and is clickable

**Comment by magnus505** [comment]
I attemped to send exemple youtube its gone..

**Comment by magnus505** [comment]
I adde u let me attempt to send a link on the chat

**Comment by githubertus** [comment]
Okay, to sum things up:
@lianglee 
I registered an account at magnus505's site
urls in posts and comments are clickable and working flawlessly - no problem.
To my opinion this thread can be closed.
@magnus505 
currently, clickable urls in the chat window are simply not implemented. this is no bug.
as for futurre reports: please open different threads for each issue

**Comment by magnus505** [comment]
send a link on a post on youtube.com for me it doesnt show up

**Comment by lianglee** [comment]
@githubertus  thanks i am closing it now,
@magnus505 as @githubertus  said,  URL only works in posts, comments.  Did you tried posting URL after disabling all non-core components?

**Comment by githubertus** [comment]
Read my last posting again and please respect that we have to to solve separate issues separately. Otherwise we would end in a big mixup and no fixed problem could be marked as closed.
Aside from that I have posted you the fix for the video problem already in your coummunity
(https://www.opensource-socialnetwork.org/discussion/view/2077/youtube-videos-not-appearing-when-i-upload-the-url)
