### ISSUE TITLE
Sponsored links in ossn

### ISSUE THREAD

**Issue by angelsresist** [opensource-socialnetwork/opensource-socialnetwork#1009]
Hi, for some unknown reason the sponsored links block has moved down below my wall posts. How can I re position it back to where it was?
thank you
Angel

**Comment by githubertus** [comment]
please install system info component and provide url of your site. I'll have a look.

**Comment by angelsresist** [comment]
I don't know how to install system info component. You can look at my website and you will see that it looks fine in Firefox but in other browsers the sponsered links block has dropped down to the bottom of the post wall. I really need help with this. Welcome! : AngelsResist
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Welcome! : AngelsResist
   |   |

  |

  |

 
If I have to pay you I will.Angel
 

    On Thursday, 12 January 2017, 14:40, githubertus <notifications@github.com> wrote:
 

 please install system info component and provide url of your site. I'll have a look.—

**Comment by lianglee** [comment]
Please provide URL/address of your website.

**Comment by angelsresist** [comment]
Welcome! : AngelsResist
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Welcome! : AngelsResist
   |   |

  |

  |

 
It looks ok in Firefox but not other browsers. The only thing I done was to add a couple of links on the top bar.appreciate your helpAngel
 

    On Thursday, 12 January 2017, 16:43, Arsalan Shah <notifications@github.com> wrote:
 

 Please provide URL/address of your website.—

**Comment by angelsresist** [comment]
Ok, I have done that.

Angel

**Comment by angelsresist** [comment]
I have installed system information at http://www.angelsresist.com/ossn/
It's the sponsored ads block which has become misplaced.
Appreciate any help.
Angel

**Comment by githubertus** [comment]
Your problem is the outdated Oinitial theme you're running. Oinitial is based on Ossn's 3.x and no more compatible with the responsive core framework of Ossn 4.x. Simply change to Goblue, and your issue will be solved.

**Comment by angelsresist** [comment]
Thank you.

Angel
