### ISSUE TITLE
users being duplicated 

### ISSUE THREAD

**Issue by matrixshopping** [opensource-socialnetwork/opensource-socialnetwork#1012]
people are signing up on my website but some of the users are being duplicated or even sometimes 3 or 4 times the users are showing up.

https://www.dropbox.com/s/4xad2l23pc1ea70/Users%20List%20%20%20AbadeezdemTalk1.png?dl=0

https://www.dropbox.com/s/9xcufjmzl32qll1/Users%20List%20%20%20AbadeezdemTalk.png?dl=0

 please look at screen shot

**Comment by lianglee** [comment]
It seems you are using social login,  please contact here: https://www.softlab24.com/contact
