### ISSUE TITLE
set_exception_handler issue

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1014]
I became aware that calling set_exception_handler() is TURNING OFF error reporting temporarely.
Currently, the user is getting a nice 'A system error has occurred...' message, but the site admin has no idea what was causing the exception even with error reporting turned on.

With the reason already passed to system/handlers/errors.php, there should be at least a line like
`error_log($params['exception']);` 
or perhaps some more lines of code in order to mail the problem-log to the admin.

**Comment by keya254** [comment]
Post

 
Privacy
VipiConnect_test
A system error has occurred. Please try again later. You may email the details of this error to the system administrator at brianosiemokeya@gmail.com.
Error: [] operator not supported for strings in /storage/h7/715/1426715/public_html/components/OssnWall/classes/OssnWall.php:345 Stack trace: #0 /storage/h7/715/1426715/public_html/components/OssnWall/plugins/default/wall/siteactivity.php(19): OssnWall->getAllPosts(Array) #1 /storage/h7/715/1426715/public_html/libraries/ossn.lib.views.php(27): include('/storage/h7/715...') #2 /storage/h7/715/1426715/public_html/libraries/ossn.lib.views.php(50): ossn_include('/storage/h7/715...', Array) #3 /storage/h7/715/1426715/public_html/libraries/ossn.lib.plugins.php(75): ossn_view('/storage/h7/715...', Array) #4 /storage/h7/715/1426715/public_html/components/OssnWall/plugins/default/wall/pages/wall.php(27): ossn_plugin_view('wall/siteactivi...') #5 /storage/h7/715/1426715/public_html/libraries/ossn.lib.views.php(27): include('/storage/h7/715...') #6 /storage/h7/715/1426715/public_html/libraries/ossn.lib.views.php(50): ossn_include('/storage/h7/715...', Array) #7 /storage/h7/715/1426715/public_html/libraries/ossn.lib.plugins.php(75): ossn_view('/storage/h7/715...', Array) #8 /storage/h7/715/1426715/public_html/libraries/ossn.lib.initialize.php(121): ossn_plugin_view('wall/pages/wall') #9 /storage/h7/715/1426715/public_html/libraries/ossn.lib.page.php(67): ossn_user_pagehandler(Array, 'home') #10 /storage/h7/715/1426715/public_html/index.php(21): ossn_load_page('home', Array) #11 {main}

**Comment by githubertus** [comment]
Your issue has been fixed already with #999. It is not related to this thread.
