### ISSUE TITLE
consecutive tagging doesn't work without page refresh

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1015]
I start with a post and tagging one friend
![tagging1](https://cloud.githubusercontent.com/assets/9904364/22062892/51e94722-dd7c-11e6-9e22-bfdd485f5b6a.png)
After having submitted my post, the screen looks like this
![tagging2](https://cloud.githubusercontent.com/assets/9904364/22062942/88735cce-dd7c-11e6-97fa-6c66633e703f.png)
but the tagging icon appears to be dead and is no more clickable.
I have to refresh /home to make the icon come alive again

**Comment by lianglee** [comment]
There seems issue with event handler will check.
