### ISSUE TITLE
Default SMTP Mail and Personal Background

### ISSUE THREAD

**Issue by Phineasx** [opensource-socialnetwork/opensource-socialnetwork#1016]
1- I would like to change default e-mail in to **SMTP**. How can i do this?

2-  I would like to change the **background** image for user **homepage and other pages**. How can i do this?

Thanks for helping.

**Comment by lianglee** [comment]
Please see the community website for help,  there is already many topics exists,  you can create a new topics for seeking help.

The SMTP component exists  https://github.com/opensource-socialnetwork/SMTP

Closing due to its not a bug report, use community for help.
