### ISSUE TITLE
config adding home to end of url

### ISSUE THREAD

**Issue by budafuko** [opensource-socialnetwork/opensource-socialnetwork#1017]
i changed my site from itsyourquarter.com to social.itsyourquarter.com in the config file and everything was working except the side bar so i started messing with the config file. nothing major just changed social.itsyourquarter.com to itsyourquarter.com/../root and all of a sudden home started appearing at the end of my url. if you go to social.itsyourquarter.com its like that now and i changed it back in the config file already

**Comment by budafuko** [comment]
and if i remove the line 
$Ossn->url = 'http://social.itsyourquarter.com';
it just goes to social.itsyourquarter.com/:///home

**Comment by budafuko** [comment]
i can not find the file with home aligned with a variable of the website in front of it or even the line of code /:///home in it

**Comment by budafuko** [comment]
ok there im stupid i got it working i was missing the / at the end but now it brings me back to my original issue of the sidebar not working.. i didn't move the location of any files just changed my site pointers

**Comment by githubertus** [comment]
See
https://www.opensource-socialnetwork.org/discussion/view/2126/how-to-change-the-path-when-the-network-is-installed-and-configured
which way to manage a transfer like yours without headache.

**Comment by budafuko** [comment]
thank you very much but i did do these steps however when users log into my website the context menue that drops down to allow users to search for other users or start groups is not opening on.click

**Comment by githubertus** [comment]
Please install the system info component.
(https://www.opensource-socialnetwork.org/component/view/1963/system-info)

Additionally enable error_reporting and verify whether there are any errors logged to the file named `error_log`

**Comment by budafuko** [comment]
i have removed every component that wasn't developed by core team. what do you mean by extra libraries? i installed the facebook theme and a couple components but everything was working fine before the transfer? i added system info component

**Comment by githubertus** [comment]
i meant something like propellerads. they're clobbering all your javascript files.

**Comment by budafuko** [comment]
did i do that let me checki remember putting a file in my root maybe its adding scripts

**Comment by budafuko** [comment]
thank you. since i added a file in my root and didn't add the script to index.php myself i had no idea it was there. thank you very much for your help!
