### ISSUE TITLE
SymLinksIfOwnerMatch

### ISSUE THREAD

**Issue by olunak** [opensource-socialnetwork/opensource-socialnetwork#1018]
ISP Forpsi.com (Czech) do not allow SymLinksIfOwnerMatch. Installation does not work, either manually or even via Softaculous 4.7.7 which Forpsi.com uses.

**Comment by lianglee** [comment]
You have to change your hosting provider to meet the requirements :)

**Comment by olunak** [comment]
:-) rather unsecure project.
