### ISSUE TITLE
/home Afther login - A system error has occurred

### ISSUE THREAD

**Issue by asthmasocial** [opensource-socialnetwork/opensource-socialnetwork#1019]
When a new user logs in all he sees is a page with the following

__________________________________________________________________________________________________________
Post
Box here. What's on your mind?
.
.
.
.
Privacy

A system error has occurred. Please try again later. You may email the details of this error to the system administrator at

**Comment by asthmasocial** [comment]
If i type in another url everything seems oke!

**Comment by lianglee** [comment]
try to login with admin account and you will find error.

**Comment by asthmasocial** [comment]
The admin account is logd out

**Comment by lianglee** [comment]
open a new browser,  login with admin account and take screenshot of error and paste it here.

**Comment by asthmasocial** [comment]
This what i see if i login with a normal user account. (When admin is logout)

![asthma social network](https://cloud.githubusercontent.com/assets/25405090/22398392/dbbe6c80-e587-11e6-8a7a-f0b50ee38120.png)

This what i see with admin acount.

![asthma social network 1](https://cloud.githubusercontent.com/assets/25405090/22398410/67033ac8-e588-11e6-9803-5960a0fc19af.png)

**Comment by lianglee** [comment]
Are you using larger than php 7.0 ?  like 7.x ?  The issue has been already fixed,   you can try to replace your  existing installation files with development files : https://github.com/opensource-socialnetwork/opensource-socialnetwork/archive/v4.x.zip

Please take backup before replacing files.

**Comment by asthmasocial** [comment]
I now use php7.0 and it work great thanks
