### ISSUE TITLE
Walltag friend notification not working

### ISSUE THREAD

**Issue by evilchis94** [opensource-socialnetwork/opensource-socialnetwork#1021]
Ossn v4.3.1
PHP v5.5.35

In OssnNotification there's a callback that triggers when a post is created, and its function is to create notification when friends are tagged in this post. This is not working. I guess because in OssnWall class in line [85](https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/components/OssnWall/classes/OssnWall.php#L85) there's an incorrect name for a variable. This line has `$params['object_guid'] = $this->wallguid;` and is supposed to be `$params['subject_guid'] = $this->wallguid;` in order to pass [callback validations](https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/components/OssnNotifications/ossn_com.php#L231) and create the notification.

**Comment by lianglee** [comment]
Hi, we will look into issue and will revert back to you , thank for reporting it with fix..
