### ISSUE TITLE
sever error/follisness

### ISSUE THREAD

**Issue by anuragbatra** [opensource-socialnetwork/opensource-socialnetwork#1024]
add add plugin is available but link to promote page not available from where will person would get an add also link to add ads by code not available!! then from where to add that.
there should be a promote page or promote group button that should charge fee and then create add for the same according to the plan by the user

**Comment by lianglee** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/wiki/How-to-report-a-issue-on-github
