### ISSUE TITLE
admin cant delete comments

### ISSUE THREAD

**Issue by snitch567** [opensource-socialnetwork/opensource-socialnetwork#1027]
trying to delete members comments and all that comes up is edit and i cant edit them either 
![screen shot 2017-02-17 at 20 11 42](https://cloud.githubusercontent.com/assets/3769596/23081580/667e1a08-f54d-11e6-95b5-a8c31ef033bb.png)

**Comment by githubertus** [comment]
thanks for reporting. 
deleting should be fixed with #1028 
I don't see no issue with editing, though.

**Comment by lianglee** [comment]
Fixed , in next release : enable admin to delete any member's comment #1028
