### ISSUE TITLE
Help me to solve problem

### ISSUE THREAD

**Issue by Alfastation** [opensource-socialnetwork/opensource-socialnetwork#1031]
I have downloaded ossn latest virson and set it up to my localhost(wamp server) for test. But when I login with my admin id & password then it returns me a error message like this;
exception 'OssnDatabaseException' with message 'Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ossn.ossn_users.time_created' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by SELECT DATE_FORMAT(FROM_UNIXTIME(time_created), '%Y') AS year, DATE_FORMAT(FROM_UNIXTIME(time_created) , '%m') AS month, COUNT(guid) AS total FROM ossn_users WHERE(time_created > 0) GROUP by DATE_FORMAT(FROM_UNIXTIME(time_created) , '%Y%m') ; ' in C:\wamp64\www\ossn\classes\OssnDatabase.php:77 Stack trace: #0 C:\wamp64\www\ossn\classes\OssnDatabase.php(175): OssnDatabase->execute(1) #1 C:\wamp64\www\ossn\classes\OssnUser.php(950): OssnDatabase->select(Array, true) #2 C:\wamp64\www\ossn\system\plugins\default\javascripts\dynamic\admin\dashboard\users\users.php(13): OssnUser->countByYearMonth() #3 C:\wamp64\www\ossn\libraries\ossn.lib.views.php(27): include('C:\\wamp64\\www\\o...') #4 C:\wamp64\www\ossn\libraries\ossn.lib.views.php(50): ossn_include('C:/wamp64/www/o...', Array) #5 C:\wamp64\www\ossn\libraries\ossn.lib.plugins.php(75): ossn_view('system/plugins/...', Array) #6 C:\wamp64\www\ossn\system\plugins\default\pages\administrator\contents\dashboard.php(156): ossn_plugin_view('javascripts/dyn...') #7 C:\wamp64\www\ossn\libraries\ossn.lib.views.php(27): include('C:\\wamp64\\www\\o...') #8 C:\wamp64\www\ossn\libraries\ossn.lib.views.php(50): ossn_include('C:/wamp64/www/o...', Array) #9 C:\wamp64\www\ossn\libraries\ossn.lib.plugins.php(75): ossn_view('system/plugins/...', Array) #10 C:\wamp64\www\ossn\libraries\ossn.lib.admin.php(204): ossn_plugin_view('pages/administr...') #11 [internal function]: ossn_administrator_pagehandler(Array, 'administrator') #12 C:\wamp64\www\ossn\libraries\ossn.lib.page.php(67): call_user_func('ossn_administra...', Array, 'administrator') #13 C:\wamp64\www\ossn\index.php(21): ossn_load_page('administrator', false) #14 {main}

please help me to fix this error.

**Comment by githubertus** [comment]
you need to change your sql server settings. see https://www.devside.net/wamp-server/mysql-error-incorrect-integer-value-for-column-name-at-row-1

Besides that:
Windoze Wamps are unsupported. We strongly recommend not to proceed on that platform.
See https://www.opensource-socialnetwork.org/wiki/view/706/how-to-install-open-source-social-network
for prerequisites
