### ISSUE TITLE
1.Multiple upload not working 2. Video uplading problem

### ISSUE THREAD

**Issue by Gunajit2001** [opensource-socialnetwork/opensource-socialnetwork#1032]
1) I am using OSSN latest  4.3. premium version. All component installed but the multiple photo upload option is not available. Component is there but no front end option for users available. How can i fix this problem please let me know. 

2) Can't add video. whenever we try to add a video the file uploaded but conversion rate is showing only 1% and video upload failed. So please let me know how can i fix this problem

**Comment by lianglee** [comment]
You can only upload multiple photos in to album photos.
2, Make sure you have added ffmpeg tools settings into your video settings page of admin panel.

**Comment by Gunajit2001** [comment]
Dear Arsalan Shah
I don't find any ffmpeg tools settings please help me, where i will find it.

**Comment by Gunajit2001** [comment]
Sir
Is there any option to add mobile apps in my own project name. If so please let me know.

**Comment by lianglee** [comment]
Hi,  i don't know how do you mean by app,  if you are using some premium version,  please contact directly to softlab24

**Comment by Gunajit2001** [comment]
Ok sir but what about ffmpeg tools. I am searching such file in my control panel but i couldn't get it.

**Comment by Gunajit2001** [comment]
Look sir something massive problem in my system. I am telling you what step i was followed- 
1. in connection to ffmpeg tool i was downloading ffmpeg tool from google then i tried to upload it from my admin panel in component installer, but could not  upload, but immediately after the strange happening start in my system a) Photo posting in news feed from mobile stopped, 
2. By mistake i had clicked on disable button of Karnel (component) then you cann't believe the whole  system gone missing and displaying like
"Fatal error: Call to undefined function ossn_register_system_sdk() in /home/gofufuuc/public_html/www.profileindia.com/components/Userban/ossn_com.php on line 12   

I don't know what to do  Arsalan my lord help me.

**Comment by Gunajit2001** [comment]
One more thing sir for premium version i had paid $249 after that why i should worry about no ffmpeg or some other issues. It will be good for us if you put such feature (which are very important to make a component functional) with the system. I don't have any knowledge i just follow what you suggest. 
In connection to ffmpeg now i had facing problem in my system. so please help me
