### ISSUE TITLE
Massive Problem

### ISSUE THREAD

**Issue by Gunajit2001** [opensource-socialnetwork/opensource-socialnetwork#1034]
Look sir something massive problem in my system. I am telling you what step i was followed- 
1. in connection to ffmpeg tool i was downloading ffmpeg tool from google then i tried to upload it from my admin panel in component installer, but could not  upload, but immediately after the strange happening start in my system a) Photo posting in news feed from mobile stopped, 
2. By mistake i had clicked on disable button of Karnel (component) then you cann't believe the whole  system gone missing and displaying like
"Fatal error: Call to undefined function ossn_register_system_sdk() in /home/gofufuuc/public_html/www.profileindia.com/components/Userban/ossn_com.php on line 12   

I don't know what to do  Arsalan my lord help me.

**Comment by lianglee** [comment]
Please note that this repository is for reporting issues in free version, as the both free and other version managed by different team of people , please report it to softlab24.com about your issue.
