### ISSUE TITLE
error on installation

### ISSUE THREAD

**Issue by ngoussong** [opensource-socialnetwork/opensource-socialnetwork#1036]
I got this error when installing. Can someone help me please??

A system error has occurred. Please try again later. You may email the details of this error to the system administrator at arthurngoussong@gmail.com.
Error: Call to undefined function mcrypt_get_iv_size() in /var/www/html/ossn/libraries/ossn.lib.system.php:651 Stack trace: #0 /var/www/html/ossn/libraries/ossn.lib.initialize.php(199): ossn_string_decrypt('&\xFA\xABG\x89\xF9T\xBA', 'ossn') #1 /var/www/html/ossn/libraries/ossn.lib.initialize.php(62): ossn_pow_lnk_args() #2 /var/www/html/ossn/libraries/ossn.lib.system.php(226): ossn_initialize('ossn', 'init', NULL) #3 /var/www/html/ossn/system/start.php(40): ossn_trigger_callback('ossn', 'init') #4 /var/www/html/ossn/installation/pages/account.php(12): require_once('/var/www/html/o...') #5 /var/www/html/ossn/installation/libraries/ossn.install.php(76): include('/var/www/html/o...') #6 /var/www/html/ossn/installation/libraries/ossn.install.php(149): ossn_installation_include('/var/www/html/o...') #7 /var/www/html/ossn/installation/index.php(32): ossn_installation_page() #8 {main}

**Comment by githubertus** [comment]
Please ask your provider to enable the PHP mcrypt extension. It is essential for encrypting passwords - without Ossn won't work.

**Comment by ngoussong** [comment]
Alright can you send me a link so I can intall all php extensions? I am using php7.0
@githubertus

**Comment by githubertus** [comment]
Please understand that it's beyond the scope of Ossn giving detailed instructions on how to set up apache or PHP correctly. There are numerous dedicated threads in the net where to search for and find help.
