### ISSUE TITLE
I Enable error log in error log file its show following errors:

### ISSUE THREAD

**Issue by malikdevelopers** [opensource-socialnetwork/opensource-socialnetwork#1038]
I Enable error log in error log file its show following errors:
php 5.6
ossn version : 4.3.1
website : http://md-social.tk
system information: http://md-social.tk/ossninfo

show the following error in error log file 
`[01-Apr-2017 02:32:43 UTC] PHP WARNING: 2017-04-01 02:32:43 (UTC): "exif_read_data(phpAjEJVi): Illegal IFD size" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 452) [01-Apr-2017 02:36:32 UTC] PHP WARNING: 2017-04-01 02:36:32 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:36:32 UTC] PHP WARNING: 2017-04-01 02:36:32 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:37:45 UTC] PHP WARNING: 2017-04-01 02:37:45 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:37:45 UTC] PHP WARNING: 2017-04-01 02:37:45 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:37:53 UTC] PHP WARNING: 2017-04-01 02:37:53 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:37:53 UTC] PHP WARNING: 2017-04-01 02:37:53 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:41:07 UTC] PHP WARNING: 2017-04-01 02:41:07 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:41:07 UTC] PHP WARNING: 2017-04-01 02:41:07 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:42:45 UTC] PHP WARNING: 2017-04-01 02:42:45 (UTC): "Creating default object from empty value" in file /storage/h7/313/1233313/public_html/classes/OssnComponents.php (line 476) [01-Apr-2017 02:42:45 UTC] PHP WARNING: 2017-04-01 02:42:45 (UTC): "in_array() expects parameter 2 to be array, boolean given" in file /storage/h7/313/1233313/public_html/classes/OssnEntities.php (line 200) [01-Apr-2017 02:50:35 UTC] PHP WARNING: 2017-04-01 02:50:35 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:50:35 UTC] PHP WARNING: 2017-04-01 02:50:35 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:51:19 UTC] PHP WARNING: 2017-04-01 02:51:19 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 02:51:19 UTC] PHP WARNING: 2017-04-01 02:51:19 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 03:09:04 UTC] PHP WARNING: 2017-04-01 03:09:04 (UTC): "mysqli::mysqli(): MySQL server has gone away" in file /storage/h7/313/1233313/public_html/classes/OssnDatabase.php (line 20) [01-Apr-2017 03:09:04 UTC] PHP WARNING: 2017-04-01 03:09:04 (UTC): "mysqli::mysqli(): Error while reading greeting packet. PID=10699" in file /storage/h7/313/1233313/public_html/classes/OssnDatabase.php (line 20) [01-Apr-2017 03:09:04 UTC] PHP WARNING: 2017-04-01 03:09:04 (UTC): "mysqli::mysqli(): (HY000/2006): MySQL server has gone away" in file /storage/h7/313/1233313/public_html/classes/OssnDatabase.php (line 20) [01-Apr-2017 03:09:04 UTC] PHP Fatal error: Call to a member function set_charset() on boolean in /storage/h7/313/1233313/public_html/classes/OssnDatabase.php on line 73 [01-Apr-2017 03:49:43 UTC] PHP WARNING: 2017-04-01 03:49:43 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 03:49:43 UTC] PHP WARNING: 2017-04-01 03:49:43 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 03:53:20 UTC] PHP WARNING: 2017-04-01 03:53:20 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 03:53:20 UTC] PHP WARNING: 2017-04-01 03:53:20 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 03:54:31 UTC] PHP WARNING: 2017-04-01 03:54:31 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 03:54:31 UTC] PHP WARNING: 2017-04-01 03:54:31 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 03:57:17 UTC] PHP WARNING: 2017-04-01 03:57:17 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 03:57:17 UTC] PHP WARNING: 2017-04-01 03:57:17 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:40:44 UTC] PHP WARNING: 2017-04-01 05:40:44 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:40:44 UTC] PHP WARNING: 2017-04-01 05:40:44 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:45:19 UTC] PHP Fatal error: Call to undefined function posix_getpwuid() in /storage/h7/313/1233313/public_html/components/system-info/ossn_com.php on line 56 [01-Apr-2017 05:47:43 UTC] PHP WARNING: 2017-04-01 05:47:43 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:47:43 UTC] PHP WARNING: 2017-04-01 05:47:43 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:53:11 UTC] PHP WARNING: 2017-04-01 05:53:11 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:53:11 UTC] PHP WARNING: 2017-04-01 05:53:11 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:53:31 UTC] PHP WARNING: 2017-04-01 05:53:31 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:53:31 UTC] PHP WARNING: 2017-04-01 05:53:31 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:53:56 UTC] PHP WARNING: 2017-04-01 05:53:56 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:53:56 UTC] PHP WARNING: 2017-04-01 05:53:56 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:54:21 UTC] PHP WARNING: 2017-04-01 05:54:21 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:54:21 UTC] PHP WARNING: 2017-04-01 05:54:21 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:54:45 UTC] PHP Fatal error: Call to undefined function posix_getpwuid() in /storage/h7/313/1233313/public_html/components/system-info/ossn_com.php on line 56 [01-Apr-2017 05:56:34 UTC] PHP WARNING: 2017-04-01 05:56:34 (UTC): "rmdir(/storage/h7/313/1233313/public_html/cache/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 05:56:34 UTC] PHP WARNING: 2017-04-01 05:56:34 (UTC): "rmdir(/storage/h7/313/1233313/ossn_datasystem/): No such file or directory" in file /storage/h7/313/1233313/public_html/classes/OssnFile.php (line 34) [01-Apr-2017 06:06:36 UTC] PHP Fatal error: Call to undefined function posix_getpwuid() in /storage/h7/313/1233313/public_html/components/system-info/ossn_com.php on line 56`

**Comment by githubertus** [comment]
Why are you telling us all that?

You insist to run Ossn on any free hosting provider.
And when you are getting errors from the Ossn installer, you simply remove the pre-requisite checking.
Consequently, you should not turn error reporting ON, should turn it OFF.
Next, you should remove all other lines from Ossn which are throwing follow-up errors.
The safest way for not getting any errors is: having no program code at all.
