### ISSUE TITLE
OSSN is missing Elgg licenses

### ISSUE THREAD

**Issue by mrclay** [opensource-socialnetwork/opensource-socialnetwork#1041]
Hello! OSSN contains numerous instances of code segments copied from the Elgg project. Although namespace and identifier names have been changed, it's very clear this is the case from [these examples](http://mrclay.org/ossn-violations/code-comparison.html).

As Elgg is released under the GPL and MIT licenses, this is not a problem, but you are obligated to include in your codebase our license including its copyright owners. I suggest you do this by adding [this file](https://github.com/Elgg/Elgg/blob/2.3.2/LICENSE.txt) to the root of your codebase as `Elgg-LICENSE`, and prefacing it with an attribute statement such as "OSSN includes code from the project Elgg."

While we recognize OSSN is a distinct product that is serving its users well, I feel it's in very poor etiquette to release a derivative product *as your own* without any attribution, then collect donations, sell commercial licenses, and tell Elgg community members that it was created "[from scratch](https://elgg.org/comment/view/2163085/2159109)". I don't know the ins-and-outs of the GPL terms but because Elgg plugins are *not* MIT-licensed, you would be wise to take notice of the licensing requirements of any Elgg and 3rd-party plugins you may be tempted to copy from and release commercially.

Thanks.

**Comment by lianglee** [comment]
HI , Thank you for your message please let us know which part is copied from Elgg and we are happy to include license on that file as we created in https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/classes/OssnTranslit.php

Please also take a look at : https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/LICENSE.txt#L21-L23 It is already mentioned there about GPL and other licenses.

And about commercial things please contact the company directly as we are affiliated with them.

Thanks

**Comment by lianglee** [comment]
And yes it is created from scratch,  please see the older releases and you'll know,  there is no direct relation between Elgg and this product.

We did included some code from Elgg and we mentioned the license ,  if you think its missing license in comments of that code please let me know i am happy to include that.

**Comment by lianglee** [comment]
@mrclay, i have added the license file and mentioned in code at mentioned in references above,  i respect your team specially Brett.  If there is code in some file that i missed to comment please let me know.
