### ISSUE TITLE
Location autocomplete not working over https

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1043]
First problem: The hardcoded http on line 143 of OssnWall's javascript
`"http://gd.geobytes.com/AutoCompleteCity?callback=?&sort=size&q=" + request.term,`
leads to a "mixed content" error when running a https Ossn site.

But even after changing that line to
`"//gd.geobytes.com/AutoCompleteCity?callback=?&sort=size&q=" + request.term,`
it doesn't work, because this time ERR_INSECURE_RESPONSE comes in return.

Indeed, calling gd.geobytes.com via https manually gives a "Your connection is not secure page" because of an invalid/outdated or whatever certificate.

Just found on their homepage, that in fact https access needs VIP membership ... :(
so maybe we should change to another geo-location service...

**Comment by lianglee** [comment]
Agree,   we need to find alternative...

**Comment by lianglee** [comment]
Replaced it with good alternative : 

![image](https://cloud.githubusercontent.com/assets/805066/24837374/422c6872-1d4c-11e7-91b9-423786f3356d.png)
