### ISSUE TITLE
error installation

### ISSUE THREAD

**Issue by joecliq** [opensource-socialnetwork/opensource-socialnetwork#1045]
Am having errors in installation due to the external folder for the ossn_data, chmod problem

**Comment by githubertus** [comment]
The Ossn data directory

- must be located outside of your installation directory
- must be owned by the webserver process (apache)
- must be writable by the webserver process

Please contact your hosting provider how to set up owner and permission accordingly

**Comment by joecliq** [comment]
Can I send you my website details to install it for me

**Comment by lianglee** [comment]
Are you installing on shared hosting ? or on vps ?

**Comment by joecliq** [comment]
Vps

**Comment by lianglee** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork#directory-permissions
