### ISSUE TITLE
UserBlock issue report by premium user

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1046]
When user [A] has Block User [B] -- User [B] can still POKE user [A]
When user [A] has Block User [B] -- User [B] can still send messages to user [A]

Need to verify the above two issues

**Comment by lianglee** [comment]
Tested with latest version 👍 
If userA blocks UserB,  then UserB can not send message to UserA/poke.

**Comment by githubertus** [comment]
yep,
but `case 'ossnchat/send':`
is blocking chat unconditionally now. :)
no block check in place
