### ISSUE TITLE
Non-logged in user able to access user pages via URL editing

### ISSUE THREAD

**Issue by EzraCc** [opensource-socialnetwork/opensource-socialnetwork#1047]
One issue I did notice while testing for issue 1037 was that user pages, including their posts, are accessible to a non-logged in user if they know the URL of that users profile. E.g., if you type in the address suffix /u/username in the URL, it will show the page. There are multiple scenarios where that could happen (user deleted for bad behavior has link in their history, users reusing username from other sites). 

During the DB orphan test, I had OSSN open in multiple browsers as 3 users: admin, user2keep, user2delete. The user2delete was looking at user2keep's user page when admin deleted the account. When I refreshed the page of user2delete, I was still able to see the content. 

I tested again by posting something by a newuser, signing out, and then going to /u/newuser, which had never been visited directly. The content was visible. If anotheruser comments on one of user2keep's post, a non-logged in user can visit /u/user2keep, and "Another User"'s name will be hyperlinked to /u/anotheruser, allowing the non-logged in user to anonymously crawl the network for all public posts.

I don't think that is desired behavior. 

/home?offset=n correctly redirects to the log in screen, even with the site configured to show all posts on the main feed (and not just friends).

**Comment by lianglee** [comment]
For non-loggedin users you can try to use Private Network component which is available for free.
About /home?offset=n  (where n is any 1, 2, 3...) /home is configured only for loggedin users....

**Comment by EzraCc** [comment]
Thanks lianglee. I was intentionally not using any add-on components for troubleshooting issue 1037. I'll test that out.
