### ISSUE TITLE
getting incomplete object records of type user:wall

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1049]
with missing double quote and bracket in the end of description like
`{"post":"Coba coba `

No idea which way this has been produced. The posting itself is there, but text doesn't show
Maybe Malik has forced this some way when trying to insert Android emoticons?

**Comment by Lablnet** [comment]
Android as well as  Windows 10 mobile emoticons
Its show blank in post and comment

**Comment by Lablnet** [comment]
And i post in this site https://newblue.ongolito.net/home
8hour ago my Emojis post show blank not coba .
😀😁😂😐☺☹😍😄😘😂😒😐😘👧👧 🤵👴 🤶
Here is some emojies i try to post

**Comment by Lablnet** [comment]
Emojis also not show in messenger
And also in 4 inch device its difficult to open comment edit or delete options

**Comment by githubertus** [comment]
Ok, I'm able to reproduce the broken object record:
1. goto a page like http://unicode.org/emoji/charts/full-emoji-list.html
2. copy emoji from first column with mouse hover and control-c
3. goto Ossn newsfeed 'what's on your mind' and paste it with control-v
emoji like 😂 appears correctly
4. click "Post"
posting appears empty now - and object record has incomplete end in description.

The good news: Ossn is already able to display these emojis.
They only have to be correctly escaped for the database like `&#x1f602;` 
(See my posting with manually edited object record on https://newblue.ongolito.net)

**Comment by Lablnet** [comment]
So database not support these

**Comment by Lablnet** [comment]
I see your post its show Emojis but when i post mine its not show unicode emlnjes

**Comment by githubertus** [comment]
I did some debugging meanwhile:
Our json is built up correctly like {"post":"😂"}
BUT: mysql's normal utf-8 encoding is unable to handle these 4-byte chars, it would need utf8mb4 instead.
So, currently our json gets cut-off when inserted to the description column.
Just found the explanation here:
http://andy-carter.com/blog/saving-emoticons-unicode-from-twitter-to-a-mysql-database

So what to do? I don't think that converting our databases like that is a solution people feel happy with.
On the other hand we can't stay with broken records.
So maybe there's a clever parser somewhere to recognize these 4-byte babies in advance and convert them to `&#x.....;` entities

**Comment by Lablnet** [comment]
Ok

**Comment by Lablnet** [comment]
Hay check my simple chat system http://chat.lablnet.tk/
I post some windows 10  keyboard Emojis its world if you want try to post.
I am making and save all data in database (MySQL) and Emojis is not work in ossn 
If its database problem why this work in my problem

**Comment by Lablnet** [comment]
My website instead of my problem

**Comment by Lablnet** [comment]
In my database it show like that my chat website """"Hay Emojis Windows 10 mobile ðŸ“±ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€â˜ºðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜ðŸ˜€ðŸŽˆðŸŽ‡ðŸŽƒðŸŽƒðŸŽƒðŸŽƒðŸŽƒðŸŽƒðŸ•ðŸ”ðŸŸðŸ ðŸ¥™ðŸš ðŸ¥šðŸœðŸ– ðŸ¥šðŸœðŸ–ðŸ™ ðŸ¥™ðŸ–ðŸ–ðŸš…ðŸš„ðŸšðŸðŸš›ðŸšžðŸšðŸš‰ðŸšŽðŸ›µðŸššðŸš„ðŸš›ðŸš›ðŸššðŸðŸš” """"
But properly appear on screen.
I my database the chwrset also UTF-8 Unicode (utf8).
Ok thanks
