### ISSUE TITLE
Ossn v4.4 dev chat!

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1051]
Today i install v4.4 after downloading form GitHub
ossn version v4.4 dev
xampp version v3.2.2
hay @lianglee and @githubertus  check this please 
check this video https://lablnet.tk/ossn_report/ossn.mp4
in Firefox when we send message page going to reload and message is not send
and in google chrome also message is not send and user show offline but i open another account in firefix check this video for better understand

**Comment by Lablnet** [comment]
in small screen message work fine check this screen short https://lablnet.tk/ossn_report/ossn23.png

**Comment by githubertus** [comment]
thanks. I've reported that to Arsalan in #1046 now.
If you're in a hurry for chatting, you can fix the Block component yourself or disable it.

**Comment by Lablnet** [comment]
Thanks when i disable block component its work see screenshot https://lablnet.tk/ossn_report/ossn24.png
but in version v4.3.1 chatting work without disable any component check  version v4.3.1  https://lablnet.tk/ossn_report/ossn25.png
Thanks for your reply and i am not hurry i run these on my localhost this is not my live site
Thanks again!!!!!!!!!!!!!!

**Comment by githubertus** [comment]
> but in version v4.3.1 chatting work without disable any component ....
Yes, Malik, yes.
Simply remember that you are running a _development_ snapshot. So some parts may give strange results, some parts may not work at all ... that's quite normal.
In the meantime, Arsalan has merged a fix. So copy over the latest Block component, enable it and you can continue chatting with yourself.

**Comment by Lablnet** [comment]
Ok 👌 thanks you .
I am checking more when find bug i report us .
