### ISSUE TITLE
code of comment picture preview ignores EXIF header

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1056]
With pic from http://lablnet.tk/ossn_report/Ma.png

I'm getting a rotated preview in comments, see
https://newblue.ongolito.net/photos/view/402

After saving the comment, the pic is displayed correctly

**Comment by lianglee** [comment]
The reason is Malik seems captured photo in landscape mode,  chrome automatic rotates images on view,  while OssnFile fixes the rotation to portrait form.  #981

http://stackoverflow.com/questions/28251338/jquery-image-preview-exif-rotation-issue

**Comment by Lablnet** [comment]
Hellow sir this image is not landscape mode try to open http://lablnet.tk/ossn_report/Ma.png

**Comment by githubertus** [comment]
First of all: This has nothing to do with Chrome. Got the same effect with Firefox and edge.
Regarding the file:
- physically it has landscape dimensions.
- but the EXiF header says: it's 90° rotated
- that's why in most cases it'll be displayed as portrait
And that means: The comment's photo priview code is ignoring the EXIF information

**Comment by lianglee** [comment]
sorry for typo , i meant browser instead of chrome......  yes photo preview is ignoring exif info.  i'll take care of this.. this need to be done via js
