### ISSUE TITLE
strange display problems on win10/chrome with album thumbnail

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1057]
A link like
https://newblue.ongolito.net/album/getcover/1/fedb119837ca60a140476cb4598e6d75.png?type=1
leads to unfinished loading on CHROME
and as a result the thumb is not displayed
Without "?type=1" it's loading successfully.

No issues like that with Firefox and Edge on Win10

**Comment by lianglee** [comment]
that is strange,  we can try to add ob_flush() before echo $image;  or before headers in file.

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/components/OssnPhotos/ossn_com.php#L392
