### ISSUE TITLE
URL being passed as text in CHAT

### ISSUE THREAD

**Issue by ultapultaashwin** [opensource-socialnetwork/opensource-socialnetwork#1068]
Hi,

On chat if we send any url it is being passed as normal text.
I am using OSSN premium and am facing this issue.
Please let me know what changes are need to be done.

Thanks,

**Comment by shreyashsrk555** [comment]
hey i am trying to create my own social network by the ossn(open source social network) and i have uploaded all its files to the server but the only thing is that when i search my link in url it sows error 404 that page not found . what should i do now ??? reply asap please

**Comment by lianglee** [comment]
Can u check with this latest commit?
