### ISSUE TITLE
Composer ?

### ISSUE THREAD

**Issue by Cryde** [opensource-socialnetwork/opensource-socialnetwork#1069]
Why don't you use composer ?

**Comment by lianglee** [comment]
Hi Cryde ,  We don't support composer at the moment because many of users don't know the installation via composer and its difficult for them to use it.

**Comment by lianglee** [comment]
+ the external libraries we uses are modified by us so we don't see any advantage to use composer within project.

**Comment by Cryde** [comment]
Composer is nice for **autoload** and for **managing dependencies**.
Composer is like the most used tool in the **open source PHP ecosystem**, you should think about it (REALLY).
With that in mind "more advanced user" could manage upgrade.

About installation for lambda user : why not doing a "build" ?
About external lib : it's a really bad practice. Or the library doesn't fit to yours need. (check https://packagist.org/ there is a lot of lib over there)

It's too bad that a nice project like this doesn't use PHP best practice.

**Comment by Cryde** [comment]
And please use NPM or Yarn for assets deps :(

Please ... :'(

**Comment by lianglee** [comment]
Hi, we shall take a look into composer for v5,  after v4.4 there will be v5.0

**Comment by RafaelMorenoSteenwinckel** [comment]
BIG +1000 for cryde...
For a project like this, composer is a standard (php side) and yarn or npm (client side).
Composer was made to simplify life of developers.

**Comment by lianglee** [comment]
@RafaelMorenoSteenwinckel as you said composer was made to simlify life of developers yes i agree with you but not the life of non-developers.  

I am working in large organization where we have hundred of non-developers and they think composer is load of work for them.

**Comment by Cryde** [comment]
@lianglee you could create a "build" (in release github section) with all of the "composer vendor" allready installed :)

To me composer is not a no-go for "non-developers"

**Comment by lianglee** [comment]
@Cryde ,  i am re-opening it and shall take a look for v5.0 release.  However if you provide us some useful links for composer that would be much appreciated.

**Comment by Lablnet** [comment]
Hellow sir using compressor is difficult to install script and also in cpanel there is no option for directly install in web host,i request if you want to provide compressor don't remove this amazing easily installer make two setups one is compressor two is other like currently
Thanks in advance

**Comment by CaddyDz** [comment]
@Lablnet What do you mean by compressor?

**Comment by Lablnet** [comment]
Oh sorry its typing mistake composer

**Comment by githubertus** [comment]
@Cryde 
It's said: Composer is a dependency manager for PHP.
Actually, I have no idea in which way this may be of any help for the development of Ossn.
Could you tell me which dependencies exactly have to be managed in this project?

**Comment by Cryde** [comment]
Dependency manager AND autoload :) 

Currently your are loading all your classes with a big foreach ... Not a good idea.
Composer support Autoload with PSR0 (http://www.php-fig.org/psr/psr-0/ but no more recommended) and PSR4 (http://www.php-fig.org/psr/psr-4/) :) 
In other words PSR are recommendations that a lot of developers follow to have some normalization in your project (like codebase project structure based on namespace etc...)

About dependency : if you don't use any dependency ... shame on you... Sorry but there A LOT of dependency out there that could respond to your (DB, File, Image, ...) need and that could avoid you to reinvent the wheel EVERY TIME 😔  (plus all of thoses dependencies are unit tested ... you won't have to re-test all of this)

You should also have a look to **NPM/YARN**
**Composer** : PHP deps
**NPM/YARN** : JS/CSS deps

**Comment by githubertus** [comment]
https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassLoader.php

That's what they call "AUTOload" ?!?
In fact you know where your class is located. But of course it would be too simple to include it directly. So you better build a complicate puzzle around and use composer to resolve it.

**Comment by lianglee** [comment]
I am closing this due to owner of issue used inappropriate word.

Autoloading,  you still need to create your own function to tell where the files are located,  in fact loop and that autoload is a same thing (in both cases you'll require_once/include your files)

We don't follow the other world to justify them and we don't have any dependency for our project so please take a look into project before saying any inappropriate,  we don't tolerate such a words about our team.
