### ISSUE TITLE
Emojies

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1071]
Thanks for providing Emojis bit here is some issues 
When i add emojies in post and click post button appear message post successful but the emojies panel can not hide automatically
When post created in comment there is no icon show for Emojis when i refresh page icon show please support ajax and also same issue Emojis panel is not hide automatically.
And in message emojies panel show like that and also smae issue emojies panel is not hide autommaticcally
![ossn](https://cloud.githubusercontent.com/assets/27757785/26132861/8597f60c-3abc-11e7-9d59-29bb2b6687a1.png)
![ossn3](https://cloud.githubusercontent.com/assets/27757785/26132859/857a7956-3abc-11e7-80a2-36dbd6b51497.png)
![ossn2](https://cloud.githubusercontent.com/assets/27757785/26132860/858e47ba-3abc-11e7-89ef-07c45faede08.png)
![ossn1](https://cloud.githubusercontent.com/assets/27757785/26132862/859e76b2-3abc-11e7-92ef-b371fee734dc.png)

.  For your information i am trying to post mobile. (windows 10 mobile) Emojis in post,comment and also message its work fine without any error

**Comment by lianglee** [comment]
Yes that is right ,  it is not a bug. Thanks for reporting

**Comment by Lablnet** [comment]
Ok sir
