### ISSUE TITLE
Emojies panel not work in google chrome windows 7

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1073]
Here is emojies panel is google chrome windows 7  
![screenshot_13](https://cloud.githubusercontent.com/assets/27757785/26237741/d0f952a6-3c8f-11e7-875b-c5ab7216878f.png)
Here is emojies panel is firefox windows 7  work fine in firefox
![screenshot_12](https://cloud.githubusercontent.com/assets/27757785/26237894/5b7e3be4-3c90-11e7-9137-88c7b39ac024.png)
and my google chrome browser are update i also face this problem in your newblue website thanks
![screenshot_14](https://cloud.githubusercontent.com/assets/27757785/26237808/10374af4-3c90-11e7-9d2f-68e8e9cd774f.png)

**Comment by lianglee** [comment]
We can not reproduce issue there must be issue with your chrome.

**Comment by Lablnet** [comment]
Thanks for your reply yes this is issue is my google i test in google chrome in android 5.1 
Its work fine https://newblue.ongolito.net/photos/view/622

**Comment by djbencrazy** [comment]
Google chrome is not up to date because you have windows 7 update your pc use firefox

**Comment by Lablnet** [comment]
Yes you are write firefox work and google chrome not work ans windows is not update

**Comment by djbencrazy** [comment]
Redirect in google chrome the emoji are not working and those using windows emoji then
