### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lucas1209** [opensource-socialnetwork/opensource-socialnetwork#1074]
1. Ossn v4.3.1
2. 5.6
3. Fatal error: Class 'OssnSession' not found in /home/u438596587/public_html/classes/OssnBase.php on line 11
4. http://prntscr.com/f9t5xi
7. Apache version 2.4
9. Website link: fprime.esy.es

**Comment by githubertus** [comment]
Ossn v4.3.1 IS the latest available version.
What were you trying to upgrade?
