### ISSUE TITLE
Notification and tag section not working properly.

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1075]
no mercy like my post but i show two notification 
ref:  https://newblue.ongolito.net/photos/view/596
Tag section not work but friend already register or add friend 
ref:   https://newblue.ongolito.net/photos/view/595

**Comment by githubertus** [comment]
Thanks for reporting, Malik.
But PLEASE again: Open a separate threads for separate issues. As we have to handle and solve issues separately.

As for the double notification:
Yes, it's true: Unliking doesn't remove the notification record. Thus, consecutive liking/un-liking will give numerous notifications on the same subject. This should be fixed.

The section issue needs no investigation as there is no user named Mlaik on newblue.ongolito.net.

**Comment by Lablnet** [comment]
Thanks for your reply ok tag system work

**Comment by Lablnet** [comment]
Ok thanks you sir
