### ISSUE TITLE
Profile picture and profile cover 

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1076]
Sir when i delete profile picture and cover from timeline its goes to hide not deleted
Its show in profile pic location and profile cover location also show in profile pic,cover album
Thanks 

Ref; https://newblue.ongolito.net/u/lablnet/

**Comment by lianglee** [comment]
This is not a bug of course it hides from wall not a original photo,  to delete original photo go to photos page.

**Comment by Lablnet** [comment]
Ol thanks for reply
