### ISSUE TITLE
Group

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1081]
Disable Emojis in group name
https://newblue.ongolito.net/group/181/

**Comment by githubertus** [comment]
Why?

**Comment by Lablnet** [comment]
Because i think only Emojis in group name is not good

**Comment by Lablnet** [comment]
Otherwise as you wish

**Comment by Lablnet** [comment]
In user profile required disable Emojis. 
https://newblue.ongolito.net/u/emojis
Please

**Comment by githubertus** [comment]
Why?
I know a guy named Malik for example who registered twice as Mlaik.
So what? Next time he might register as penguin ... or Lamik. Which seems to make more sense at first but in fact is wrong, too. 
In the end it's up to the admin whether to sort these kind of "funny" people out or not.
With a serious forum you might want to have stronger restrictions - with another forum focussed on having fun you might want to allow everything. It's almost impossible to handle things like that automatically.

**Comment by Lablnet** [comment]
Ok sir

**Comment by Lablnet** [comment]
But sir in username emojies not work how?
