### ISSUE TITLE
Request accpet no notification

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1082]
I create tow account malik umer. , malik umer 2
I send request form umer to umer 2
When umer 2 accept my request i have no notify thought notifications
Thanks

**Comment by Lablnet** [comment]
I create account in newblue website

**Comment by lianglee** [comment]
The friend request is it self a notification,  it is not part of OssnNotifications

**Comment by Lablnet** [comment]
Ok sir
