### ISSUE TITLE
blocking not working properly 

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1084]
I create tow account newblue malik umer. , malik umer 2
Umer 2 block umer after blocking umer 2 access umer profile and access to send message when send message umer recieve message when click show blocked
I think user not send when block anyone.
Thanks here is screenshort 
![wp_ss_20170522_0001](https://cloud.githubusercontent.com/assets/27757785/26294364/85055df0-3edc-11e7-886b-abc1bd9d2ecd.png)

**Comment by lianglee** [comment]
i am not sure if user can send message if he is blocked by someone,   however you can still see old notification.

**Comment by Lablnet** [comment]
Please check your self see image again plzzz

**Comment by lianglee** [comment]
I checked,  i can not reproduce your issue:

1. User A blocked User B
2. User B can not send messages,  or view user A profile.

If you are asking that messages still appears still in messages yes they do,   and User A can still contact B.

**Comment by Lablnet** [comment]
If you are asking that messages still appears still in messages yes they do, and User A can still contact B.
Sir when user A send message to user B  , user B receive Message when click appear blocked ?
User B can not access to view or reply message to user A
