### ISSUE TITLE
friend list not working properly

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1085]
When i visit no mercy profile in newblue its show unfriend other then add friend
Its show no mercy is my friend but when i visit frend section in no mercy profile show like that no i am not show in no mercy profile
![wp_ss_20170522_0003](https://cloud.githubusercontent.com/assets/27757785/26294671/ec764042-3ede-11e7-9aee-d96b4d3612e5.png)
And also in my profile friend section no mercy not show 
Thanks

**Comment by lianglee** [comment]
The other use need to accept request after receiving it,

**Comment by Lablnet** [comment]
Yes sor i login to my other account and accept request and back to my account there is no notification

**Comment by Lablnet** [comment]
Sorry for wrong reply sir i think no mercy accept my request i have enable to post his profile
