### ISSUE TITLE
Group Post not working properly

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1086]
see this
 https://lablnet.tk/ossn.html

**Comment by Lablnet** [comment]
i think this video not work so download plz and see https://lablnet.tk/ossn.zip

**Comment by lianglee** [comment]
Please elaborate what is the exact issue,  your video seems not working.

**Comment by Lablnet** [comment]
Ok let's try yourself create group and post simple text see what happen

**Comment by Lablnet** [comment]
For simple explain when post created the image moves not stop 
See https://newblue.ongolito.net/photos/view/671

**Comment by lianglee** [comment]
Please download latest v4.4 from our website,  the issue should be fixed in that.

**Comment by Lablnet** [comment]
ok i will try

**Comment by Lablnet** [comment]
sir issue not fix issue is in group when we create post image move in circle when post success and also appear in post section image not stop and also content that we write in box not remove but post created also message appear on top "Successfully created post!"

**Comment by lianglee** [comment]
Hi Malik,  i am sorry,  please check it seems the file you downloaded was cached

https://www.opensource-socialnetwork.org/download_ossn/latest/build.zip?cache=false.

**Comment by Lablnet** [comment]
Thanks You Sir issue solved
