### ISSUE TITLE
profile cover gives error but it is uploaded if you refresh page.

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1087]
see for information https://www.youtube.com/watch?v=WKnGFrzE6NA&feature=youtu.be
i post this video on YouTube because my web host not work properly
when you see comment here i delete this from youtube

**Comment by Lablnet** [comment]
no i delete video

**Comment by githubertus** [comment]
Malik, please remember how to report a bug correctly. Just telling "gives error" is of no help.
https://www.opensource-socialnetwork.org/wiki/view/705/how-to-report-a-issue-on-githubcommunity

**Comment by Lablnet** [comment]
Sir I provide t your team video I delete because privacy issue when Arslan change the name of topic i delete the video if you want to confirm ask to sir Arslan

**Comment by lianglee** [comment]
Malik please provide video, i haven't seen it i just make title correct.

**Comment by Lablnet** [comment]
https://www.youtube.com/watch?v=UHFPxzo9vOU&feature=youtu.be

**Comment by lianglee** [comment]
Malik please provide original photo,  upload original photo in zip file and send us link for zip file

**Comment by Lablnet** [comment]
here is link for download original image in zip file 
lablnet.tk/amazing_clouds-wallpaper-10915601(1).zip

**Comment by Lablnet** [comment]
here is link for download original image in zip file
https://lablnet.tk/amazing_clouds-wallpaper-10915601(1).zip

**Comment by githubertus** [comment]
Thanks for the image.
I have tried to make it my profile cover and the cover of my group "Ongolito Ville" on https://newblue.ongolito.net.
Without success. (Got error and old pic stays in place)

Please try to do the same on your profile/group.

**Comment by Lablnet** [comment]
Sorry for late reply because there are loadshadding 
I try for upload but it's work fine image not uploaded when got error
But in my localhost why image uploaded
Please try to your localhost pc

**Comment by githubertus** [comment]
Believe me Malik, I'm running more than one server locally for development. 
But in opposite to you, I'm not working with an unsupported Windows server.

The prerequisites for Ossn are clearly listed on
https://www.opensource-socialnetwork.org/wiki/view/706/how-to-install-open-source-social-network
(Ubuntu server - NOT windows)

And that's why I don't see any good reason to follow you on the same wrong path you're currently on.

**Comment by Lablnet** [comment]
Sir  install ossn v4.4 during installation there is no error why? And sir can you help me I think the apache are same in Windows and other.  Supported server as well as mysql
