### ISSUE TITLE
Grup cover gives error but it is uploaded if you refresh page.

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1088]
Grup cover gives error but it is uploaded if you refresh page.
![screenshot_1](https://cloud.githubusercontent.com/assets/27757785/26347966/a3f2741c-3fc4-11e7-87ca-482bb6902ab0.png)

**Comment by githubertus** [comment]
What exactly do you mean with "gives error"?

I see no error message on your screenshot.

**Comment by Lablnet** [comment]
Sir when image resolution is less then that you provide show error bit when we upload  refresh page image uploaded

**Comment by githubertus** [comment]
I cannot follow.
Did the following steps:
1. go to my Group page "Ongolito Ville"
2. click "Change Cover" button
3. choose a picture which is too small (480x800)
4. click "open"
5. get error message "The cover pic must be at least 850x300 or greater"
6. message disappears - (old cover still in place)
7. refresh page with CTRL-F5 or CTRL-R
old cover still not changed, I see no issue

**Comment by Lablnet** [comment]
I am on Windows xampp

**Comment by githubertus** [comment]
Fine. I had coffee with my breakfast.

**Comment by Lablnet** [comment]
Why you write i had coffee with my breakfast and what is fine?
