### ISSUE TITLE
Need restrictions in search 

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1089]
When I visit https://newblue.ongolito.net/search?type=users 
Appear all the user that register in new blue

**Comment by githubertus** [comment]
If you want to restrict your community from being viewed by registered and logged in members only, you can make use of the "Private Network" component. I have activated it on newblue.ongolito.net now.

**Comment by Lablnet** [comment]
Sir I means when register user visit that link all of member appear

**Comment by githubertus** [comment]
Yes, and that's correct.
If you do not specify a member name or part of a membername you will get ALL member records. The more specific your search term is, the more specific the result will be.

`https://newblue.ongolito.net/search?type=users&q=Mal`
gives Malik Umer and Malkk Umer 2

`https://newblue.ongolito.net/search?type=users&q=Mali`
gives only Malik Umer

**Comment by Lablnet** [comment]
Sir I want register and login member never see all member records
Thanks
