### ISSUE TITLE
Cannot create post

### ISSUE THREAD

**Issue by SloRunner** [opensource-socialnetwork/opensource-socialnetwork#109]
When i try to upload image it shows "Cannot create post" error, everything worked and then i got this error :/

**Comment by elkis2** [comment]
When i try to upload image it shows "Cannot create post" error, everything worked and then i got this error :/

hey, i will like to know where i can edit it ? send me the code , html ,,,, ?

**Comment by lianglee** [comment]
@elkis2,
See: https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug
