### ISSUE TITLE
profile picture and covwr picture missing styling in button

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1090]
When I go to mytineline then photo the profile pictures image appear when I click i age image open 
See image for more detail 
![wp_ss_20170523_0003](https://cloud.githubusercontent.com/assets/27757785/26350238/f0049400-3fcb-11e7-877c-9dee978c76e4.png)
Back button need style

**Comment by githubertus** [comment]
Thanks for reporting. Pull request sent.

**Comment by Lablnet** [comment]
Ok sir thanks
