### ISSUE TITLE
Notification panel and profile cover options repositon change overlap

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1091]
Notification panel and profile cover options repositon change overlap
See image 
![wp_ss_20170523_0005](https://cloud.githubusercontent.com/assets/27757785/26350498/dc349262-3fcc-11e7-98ce-0e1c044673c1.png)

**Comment by githubertus** [comment]
This is a good example that providing the exact details of your environment would save a us lot of time. As this isn't reproducable neither with firefox nor with chrome. It's a Microsoft special: Under certain conditons the z-index is ignored if the position of the parent element is not explicitely set.

I have applied a patch to newblue now. Please refresh your browser with CTRL-F5 and check whether it is fixed for you now. (With edge on Windows 10 it's fixed.)

**Comment by Lablnet** [comment]
Ok sir issues solved within Microsoft edge on Windows 10 mobile 
Thanks
