### ISSUE TITLE
No option/section for see who is online

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1098]
There is no option/section is small screen for seen who is online e.g I send the message to user A, I not know this is online now or not when I use mobile or tablet/ipad

**Comment by githubertus** [comment]
I've just verified that the "Who is online" component displays correctly even on smallest devices.

**Comment by Lablnet** [comment]
Sir who is online show all of member

**Comment by Lablnet** [comment]
I am asking only friends
