### ISSUE TITLE
posting a apostrophe in post shows html entities

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1099]
apostrophe shows numbers in posts

**Comment by githubertus** [comment]
? don't get it: what character code?

**Comment by lianglee** [comment]
Yup wait,  fixed the title 'posting a apostrophe in post shows html entities' sorry last title was copied directly from bug reporter.

1. Post a single quotation mark or double quotation mark ' it shows a html entities in post,.... 

![image](https://cloud.githubusercontent.com/assets/805066/26620115/dccccf8a-45fa-11e7-80ac-9f2f93d9ab47.png)

![image](https://cloud.githubusercontent.com/assets/805066/26620127/ec46b3e0-45fa-11e7-8139-b50b47bdf64d.png)


It seems it is not  bug in core,  i just checked it is issue in something else on premium client side..
