### ISSUE TITLE
message inbox update problem

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#110]
system: ossn 1.8 / chrome 39.0.2171.71m or firefox 33.1.1 / windows7

open your messages page (messages/all)
normally, the LAST message is shown in the inbox window, too
leave the messages page open and ask the same user to send you another message
while the right window gets updated correctly, the inbox still shows the old one

![ossn-message-problem-1](https://cloud.githubusercontent.com/assets/9904364/5237095/bc218d12-786a-11e4-9ed2-d7500efe97ee.png)

**Comment by lianglee** [comment]
I think there will be a load on site if we update sidebar of messages again and again.
@moneya , @sathish4fri what you think? should we leave as it is?

**Comment by sathish4fri** [comment]
No buddy we must update  other wise we dont need that sidebar itself
