### ISSUE TITLE
In OSSN Group members not exceeding more than 10

### ISSUE THREAD

**Issue by ultapultaashwin** [opensource-socialnetwork/opensource-socialnetwork#1102]
Please check on http://ec2-52-66-15-9.ap-south-1.compute.amazonaws.com/
with creds
username : ashwin
password : ashwin100181

> Goto Group testing
> try to add new user to the group

Expected: Member should be added to the group and total number count should be 11.

Result: The total count is still as 10

**Comment by githubertus** [comment]
As http://ec2-52-66-15-9.ap-south-1.compute.amazonaws.com/group/53/members?offset=2
shows, adding more than 10 members to your groups is basically working.

In fact there seems to be a problem with the widget on the front side and the counter, though.
