### ISSUE TITLE
cannot post anything

### ISSUE THREAD

**Issue by NnaemekaStanley** [opensource-socialnetwork/opensource-socialnetwork#1105]
I cannot post anything on the site..... no user can post anything, it keeps saying, something went wrong, please refresh and try again

**Comment by lianglee** [comment]
can you share a link of website?

**Comment by NnaemekaStanley** [comment]
Beheardd.com

**Comment by lianglee** [comment]
Try to install this component and let us know once you installed : https://www.opensource-socialnetwork.org/component/view/1982/translation-check

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/component/view/1963/system-info

**Comment by NnaemekaStanley** [comment]
How do I install it ?

**Comment by Lablnet** [comment]
login into admin panel then goto component and expend drop menu and installer when success goto component and enable

**Comment by NnaemekaStanley** [comment]
I have tried to install, says error 404

**Comment by NnaemekaStanley** [comment]
please nobody is saying anything, I or any of my user cannot make any post, the component cannot install
what sort of spaghetti coding is this ?

**Comment by lianglee** [comment]
Will you eat the spaghetti before cooking? In the same way, did you logged into administrator panel before trying to install the component from component installer page?

**Comment by NnaemekaStanley** [comment]
yes, I did
I have even read the code to see if anything is wrong in actions/administrator/component/com_install ?
the installer is not still working

**Comment by NnaemekaStanley** [comment]
If I or my users cannot post anything, then what is the use of the script ?

**Comment by NnaemekaStanley** [comment]
why is the installer taking me to cgi-sys/amplugin.shtml ?

**Comment by lianglee** [comment]
That seems your website hosting issue,  please change your website hosting.

**Comment by githubertus** [comment]
[http://z-mans.net/ossn-reports/gh1105/cannot-post.jpg](url)
A good decision to close this "issue". As the screenshot shows, members of that community in thruth ARE able to post, to comment, to like, whatever..
