### ISSUE TITLE
For security, the data should be encrypted with MD5 or SHA1

### ISSUE THREAD

**Issue by Lucas-Developer** [opensource-socialnetwork/opensource-socialnetwork#1107]
**At the time of user registration, save the encrypted password in the database, which would help make such information more secure. For example, if a hacker discovers a failure in some database server and gets access to the tables with the passwords and logins, if the password is encrypted, a priori it will not be able to do much with them.

Saving unencrypted passwords to a database without security vulnerabilities is still risky, as anyone with access to your web server can view user passwords. This includes support users, technicians, server owners, etc.**

**Comment by lianglee** [comment]
Where it said that we are storing passwords in plaintext?  
The passwords are stored in md5 salt method.
