### ISSUE TITLE
Disable long string in Name

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1108]
Please disable long string in First and last name 
See image what happen
![wp_ss_20170611_0002](https://user-images.githubusercontent.com/27757785/27008133-4fe096d8-4e83-11e7-95d7-9183e3df06aa.png)

**Comment by githubertus** [comment]
To what lenght? To 10? To 20? With a limit like that, the next time this guy would change his name to "Fuck Bitch". And you would want to have a bad word filter. And he'll change his name to "Sunny Morning" and you're ending up with trying to build a table of worldwide known REAL names to compare with ...

You see: Whatever you're doing, if a member really wants to fool the admin - he will do. Thus, the only effective solution is to remove the accounts of childish idiots manually.

**Comment by Lablnet** [comment]
First this is me try to change name what happen!
i think the limit of  name at least 30 character 
"And you would want to have a bad word filter. And he'll change his name to "Sunny Morning"
what you means
