### ISSUE TITLE
if user didn't exists not wall item

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1110]
if user didn't exists not wall item should be displayed (to avoid error), In case user deleted manually or its data isn't deleted.

**Comment by githubertus** [comment]
Hmm ... I doubt this would be helpful. If someone is actually manipulating the database without intimate knowledge which way the records are related to each other - everything evil can happen. And we would end up in thousends of additonal and performance killing checks to make Ossn run even with a corrupted db.
My simple advice in a case like that would be: Install a backup without that manipulation - and you'll be fine. :)

**Comment by lianglee** [comment]
I agree,  i just checked the wall item.php in that we are already calling $user = ossn_get_user_by_guid() (so for check in wall item , we don't need to make db connection again) and when we call ->anyMethod() and if user didn't exists it throw errors,   so we can simply do following in start of item.php (only this wall post item.php)
```
If(!$user){ 
    error_log('user_didn't exists');
    return;
}
```
