### ISSUE TITLE
I am installing and having issues..why?

### ISSUE THREAD

**Issue by kinkyjewel** [opensource-socialnetwork/opensource-socialnetwork#1112]
Uncaught exception 'Exception' with message 'Cannot include all classes

found insystem/start.php  ..line 32

i get this error on installing

how do i resolve it?

**Comment by lianglee** [comment]
The error is clear that OSSN can not include all classes,  you are missing files , upload all files.

**Comment by kinkyjewel** [comment]
Can you please identify the files and a link to the source of the files.
i installed and configured and on re opening.. i go that error

thanks for responding.

regards.

**Comment by lianglee** [comment]
1. What is your hosting provider?
2. What is your OSSN version?
3. How did you uploaded files?

**Comment by kinkyjewel** [comment]
whogohost.com is my hosting provider? i got in touch with them and they
asked me to add the class function that is missing
i installed the latest version of OSSN, and i installed from Softaculous
should i use VM ware to run it.

please advice me on what to do.

regards

Tony

**Comment by lianglee** [comment]
Hello Tony,  

If you installed software via Softaculous it should work,   the error indicates that some files are missing from your installation,  Did you tried to run on your local computer?

You can run VM image on your local computer.

Thanks

**Comment by kinkyjewel** [comment]
thanks for responding.. i have reinstalled...however the little challenge i
am battling with this morning is that i downloaded the privacy  component
and enabled it ( that component that moves my page from public to private
except they login)...and since then everything went blank.
How do i restore it back.

all i see now is white screen both on mobile and desktop.

expecting response

**Comment by lianglee** [comment]
Which privacy component? please contact developer directly.
