### ISSUE TITLE
how to make search by usernames and emails?

### ISSUE THREAD

**Issue by mohattia22** [opensource-socialnetwork/opensource-socialnetwork#1113]
I tried to searh by usernames but no result appears.

**Comment by githubertus** [comment]
Please see:
https://www.opensource-socialnetwork.org/wiki/view/705/how-to-report-a-issue-on-githubcommunity
and provide exactly all steps to reproduce the problem

**Comment by mohattia22** [comment]
ossn version 4.4
Cache disabled
Php version 5.6
No error log nor messages
the problem that when I search users by email or username , I have no results found
So is there away to search users by usernames or email
Web url.            http://lzoz.tk

**Comment by githubertus** [comment]
I cannot reproduce your problem.
Searchterm "Harr" gives "Harris Delong"
Searchterm "Mur" gives "Dewayne Muriel"
... just to name 2 examples.
Ossn search works on firstname and lastname.
