### ISSUE TITLE
Having issues with my new OSSN site newsfeed.

### ISSUE THREAD

**Issue by DukeVicBoss** [opensource-socialnetwork/opensource-socialnetwork#1114]
Hello community, brand new. Friends and I developed a site specifically geared for roleplaying since Facebook does not allow anonymous roleplaying accounts.

Everything has worked fine until this morning we discovered the newsfeed displays only in plain text. The profiles work just fine if you know the URL, comments work fine.

Messaging does not work at all. Brings a blank page. My friend that codes it said the issue happened after an edit but then she reinstalled the backup back to the way it was and it's still doing it. We haven't exceeded our bandwidth. Please help!

**Comment by lianglee** [comment]
What did your developer added? What did developer changed?  Did you deleted user ?

**Comment by Lablnet** [comment]
Hello Sir the @DukeVicBoss means the homepage (newspage) was crash

**Comment by DukeVicBoss** [comment]
Ah, yes. I looked up a similar issue another user had. My developer created a test user then deleted it and that was when all the problems had started. We had a backup luckily. One member lost their account in the mess but we're back now.

**Comment by githubertus** [comment]
Thank you for the update.
Up to now we were unable to reproduce the problem, except with deleting a member record from the database directly, which shouldn't be done under no circumstances.
Hence, it would be very helpful, if your developer would remember exactly the steps she did, in detail:

1. Which way was the member added (registration form or admin panel) ?
2. Which actions did that member perform (postings/uploading profile pic/profile banner, etc.) ?
3. Which way was the member deleted (database or admin panel) ?

**Comment by DukeVicBoss** [comment]
I'll remember that from now on. It was a direct deletion instead of a ban. I'll share it here in case anyone else hits this problem.
