### ISSUE TITLE
Emoticons no color and drop down won't close

### ISSUE THREAD

**Issue by alhefner** [opensource-socialnetwork/opensource-socialnetwork#1115]
I am testing out the platform at my site, [http://www.afreshpath.com/ossn/](http://www.afreshpath.com/ossn/)

When using the emoticons for commenting, they have no color EXCEPT when using an android smart phone. Using a regular laptop, they are all monochrome.

Also, when you click the emoticon image to open them all up, the only way to get the drop down to go away is to reload the page.

**Comment by lianglee** [comment]
Can you please share a screenshot?  also from which browser you tried ?

**Comment by alhefner** [comment]
I answered via email but I'll answer here too. I used both Firefox and Chrome.
![ossn_screen](https://user-images.githubusercontent.com/29808127/27774525-93521b28-5f48-11e7-90b5-729535458a1e.jpg)

**Comment by lianglee** [comment]
I assume you are using windows 7? if so windows 7 or 8.0 didn't have a color emoji fonts within it.

**Comment by Lablnet** [comment]
Yes sir you sre true tere is no emojies show in windows 7,8 as you know i also face this problem when i install Windows 10 its automatically solved

**Comment by alhefner** [comment]
Hmmm... so, why is it that every other site that offers emoji has them in color even though people are using Windows 7? Sorry, that excuse simply does not fly...

**Comment by lianglee** [comment]
Those emoji are the static images not the real unicode emojis , OSSN uses unicode emoji
