### ISSUE TITLE
Adding Finnish translation problem with 4.4

### ISSUE THREAD

**Issue by Gh0stSnipu** [opensource-socialnetwork/opensource-socialnetwork#1116]
Hi, i am new to this system and i have been tested this around and i come this problem.
everytime i try to translate en to fi (finnish language) site vanished...yes i use variable $en -> fi and Ä and Ö letters aint reconized at all they comes as ? mark. Can someone help me out with this problem? English version works just fine no problems but soon after "enable finnish" language everything vanish or goes messed up, even admin panel.

**Edit**
i have been translated fully English -> Finnish language, but everytime i turn Finnish language on admin panel goes into Finnish language but when try to go mainpage of site it vanished?? And then turn site language back to english it works...but when i turn finnish language via user settings(account settings) after that all vanished...cant login at all...not even admin panel.

I could buy this onetime packet but if it has this kinda problem then i am seeking something else.

**Comment by lianglee** [comment]
Please turn the error log on before enabling any other language and then see what is in error_log file
