### ISSUE TITLE
not working properly 

### ISSUE THREAD

**Issue by matrixshopping** [opensource-socialnetwork/opensource-socialnetwork#1119]
i am having a problem when a person is log out of the website they can not see a persons posts lets say i post 5 things and i am log out i will only see the person picture with out the other 5 posts but if i am log in i will see everything. is it a privacy setting or something that stop people who are not log in so they can't see the other 5 posts. 

also if you look at this picture when i search for a person more than one account shows up why is this.

![glendon](https://user-images.githubusercontent.com/17859659/27988730-677f979c-63f7-11e7-96fa-c94dfb1288d3.png)

**Comment by lianglee** [comment]
Did you tried to remove duplicate users from admin panel?
2. Some posts are for friends only and some posts are for public ,  so if you logged out you'll see public posts.

**Comment by matrixshopping** [comment]
oh that is why ok nice thank you so much now about the dupicate accounts why is it happening

**Comment by githubertus** [comment]
Please follow the guidelines on https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error

**Comment by Lablnet** [comment]
Do you install fake user component?

**Comment by matrixshopping** [comment]
www.matrixshopping.com/abadeezdemtalk 

version of browser should be a issue in this matter but the person has a s5 galaxy 

i sent the screen shot 

simply create a file name in the root of your ossn where and how i can do this is there a video

**Comment by githubertus** [comment]
![glendon](https://user-images.githubusercontent.com/9904364/28080753-4c25c91c-666d-11e7-9138-4fb3c2aae3cb.jpg)

As you can see from my screenshot, doing a search like
http://matrixshopping.com/abadeezdemtalk/search?q=glen
results in three users named Glendon Lawrence.

If you hover the name links however, you'll notice that all three Glendons have in fact DIFFERENT usernames: Glendon, Gpower and Glendon123.

That is: Ossn is working completely correctly - only usernames and emails have to be unique - while Firstname / Lastname are allowed to appear more than once.

In Germany, Peter Meier is a very widespread name for instance, we have hundreds of them. Thus, a community software like Ossn MUST allow the registration of the same name than once, otherwise you would lock out all the others unintentionally.

**Comment by Lablnet** [comment]
The problem is your site when delete post page refresh but ossn standard page never refresh during delete post comment etc...

**Comment by matrixshopping** [comment]
ok i think your missing what i am saying so let me tell you about a situation that can help me and help you understand. a new user signed up her name is mellyann she used the facebook login which she donot have a email. now it goes to the edit profile part. here is a video explaining what is happening...

https://www.dropbox.com/s/7eu4bumcajozigd/mobizen_20170714_105109.mp4?dl=0 

here are some screen shots....

https://www.dropbox.com/s/47u94xboia06jl7/dup.png?dl=0

https://www.dropbox.com/s/pybc5w77dnx0lp5/dup1.png?dl=0

**Comment by matrixshopping** [comment]
facebook has this feature where you don't need a email to sign up on facebook you can do this with a mobile number. so she does not have a email. i don't know if this is causing the problem but please fix it as i am willing to buy more commponents but if this can't be fix then i will be very disappointed

**Comment by matrixshopping** [comment]
![dup](https://user-images.githubusercontent.com/17859659/28218049-53535258-6885-11e7-89fe-9e99346ae69b.png)
![dup1](https://user-images.githubusercontent.com/17859659/28218053-5815d96e-6885-11e7-8dfa-4c947b3d5bed.png)

**Comment by matrixshopping** [comment]
samething is happening with Glendon Lawerence

**Comment by matrixshopping** [comment]
how rich nobody is answering now???????

**Comment by lianglee** [comment]
@matrixshopping we received your request on softlab24 and we are processing we shall delete invalid users and upload fix within next 24 hours.

**Comment by matrixshopping** [comment]
ok great thanks so much
