### ISSUE TITLE
allow duplicate group names?

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#112]
Not really a bug, but currently 2 different users are able to create a group with the same name. Worth a thought whether this should be allowed in the future or not. If yes, it makes sense to display the owner's name and the number of members below the group name in order to help other users decide which one they want to be a member of.

![ossn-group-problem-2](https://cloud.githubusercontent.com/assets/9904364/5237380/f544c8dc-7880-11e4-8f25-d81b531afe4a.png)

**Comment by lianglee** [comment]
I think we should allow to duplicate names but we should show total members

**Comment by lianglee** [comment]
I agree, we need owner name

**Comment by lianglee** [comment]
fixed
