### ISSUE TITLE
Post appearing Blank once post is posted and later edited with same details

### ISSUE THREAD

**Issue by shishukamal** [opensource-socialnetwork/opensource-socialnetwork#1121]
#Ossn version : 4.3.1
PHP version : 7.0.18-0ubuntu0.16.04.1
Error message : Check Screenshot

Error Log : 
1. Login to http://bjslearnings.in/
2. Enter Walkin details walkin.txt and click on Post
3. Goto that Walkin post and click on Edit
4. Enter same walkin Details again and click on Save
5. Post Appearing Blank 
6. Click on Edit ,"//" symbol appears...

Expected Result : Black Space should not appear and "//" should not appear

Issue screenshots : -
![after first edit original post](https://user-images.githubusercontent.com/30159044/28234787-5794fa82-6921-11e7-9494-dce649bb0b3a.png)
![after second edit original post](https://user-images.githubusercontent.com/30159044/28234789-579961d0-6921-11e7-831e-3afdec5723c3.png)
![before edit original post](https://user-images.githubusercontent.com/30159044/28234788-579784f0-6921-11e7-84b9-0cacd19da938.png)
[Walkin.txt](https://github.com/opensource-socialnetwork/opensource-socialnetwork/files/1149909/Walkin.txt)

Cache enabled/disabled : Disabled
MySQL version (if possible) : 5.6
Your website link (if possible) : http://bjslearnings.in/

**Comment by lianglee** [comment]
Did you tried v4.4 ? Multiple spaces to singe space issues has been fixed in newer version.

**Comment by lianglee** [comment]
closing as no response
