### ISSUE TITLE
Cannot Proceed with Installation

### ISSUE THREAD

**Issue by TitanTF** [opensource-socialnetwork/opensource-socialnetwork#1122]
![sadasdasdasd](https://user-images.githubusercontent.com/12863023/28275593-e0c0d6e2-6b46-11e7-8cd6-b2d4d38189d5.PNG)

It shows this screen after pressing next on the database making screen.

PHP 7.0.12
MYSQLI ENABLED
APACHE ENABLED
MOD_REWRITE
PHP CURL
PHP GD LIBRARY
CONFIGURATION DIRECTORY WRITEABLE
PHP allow_url_fopen ENABLED
PHP ZipArchive ENABLED

**Comment by worraps** [comment]
I get the same error. All prerequisites are confirmed. Database host settings work fine. Database gets built. Put account page is actually blank for me. no explicit errors found in the apache logs. 


Todd 
----- Original Message -----

**Comment by TitanTF** [comment]
weird

**Comment by lianglee** [comment]
Did you tried to install on your vps ? did you tried to enable php mcrypt extension?

**Comment by worraps** [comment]
Yes, installed on Ubuntu 14.04 VPS. 
mcrypt installed. 
php 5.5.9

**Comment by githubertus** [comment]
Please follow the guidelines in https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error.
It's very unlikely to get a blank page without getting a corresponding line in the server log file.
Consult the ubuntu and/or apache community on how to set up error logging of your server correctly. Or simply write your own wrong mistake.php like
```
<?php
echow 'hello';
?>

```
call it from your browser, and verify that the error has been logged.

**Comment by lianglee** [comment]
Closing as no response
