### ISSUE TITLE
Emoji issue

### ISSUE THREAD

**Issue by skenigma** [opensource-socialnetwork/opensource-socialnetwork#1123]
When a user tries to post a comment with an emoji, they are not able to post, sometimes they get an error sometimes not, but the Apache Logs shows the following.
`[Mon Jul 17 19:53:44.829235 2017] [:error] [pid 13909] [client xxx.xxx.xxx.xxx:53230] OssnDatabaseException: Incorrect string value: '\\xF0\\x9F\\x98\\x81' for column 'value' at row 1 \n INSERT INTO ossn_entities_metadata (`guid`, `value`) VALUES ('105', '\xf0\x9f\x98\x81');  in /WebSites/ossn/classes/OssnDatabase.php:82\nStack trace:\n#0 /WebSites/ossn/classes/OssnDatabase.php(44): OssnDatabase->execute()\n#1 /WebSites/ossn/classes/OssnEntities.php(109): OssnDatabase->insert(Array)\n#2 /WebSites/ossn/classes/OssnAnnotation.php(70): OssnEntities->add()\n#3 /WebSites/ossn/components/OssnComments/classes/OssnComments.php(50): OssnAnnotation->addAnnotation()\n#4 /WebSites/ossn/components/OssnComments/actions/post/comment.php(22): OssnComments->PostComment('14', '1', '\\xF0\\x9F\\x98\\x81')\n#5 /WebSites/ossn/libraries/ossn.lib.actions.php(51): include_once('/WebSites/ossn/...')\n#6 /WebSites/ossn/system/handlers/actions.php(12): ossn_action('post/comment')\n#7 {main}, referer: https://www.xxx.xxx/home
`

**Comment by lianglee** [comment]
This seems your server database issue make sure your database accept utf8 encoding text and can accept unicodes.

**Comment by skenigma** [comment]
My Mysql Server instance is configured for utf8mb4 with utfmb4_unicode_ci collation   Which appears to be correct.

**Comment by skenigma** [comment]
Found the problem.  
./classes/OssnDatabase.php
Line 78  Sets Charset to "utf8"  needs to be "utf8mb4"
