### ISSUE TITLE
request for a more complete list of pre-requisites

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1126]
since especially with dedicated servers we can't rely that everything necessary is already in place

**Comment by lianglee** [comment]
Added php mcrypt extension which was missing from requirements and was causing issue. (wiki https://www.opensource-socialnetwork.org/wiki/view/706/how-to-install-open-source-social-network)

We also need to add that to installation and checking requirements everytime ossn loads #941 #1035

**Comment by lianglee** [comment]
Since pre-requisite list updated,  i don't think its necessary to check pre-requisites every time start.php classed or on every request (which will result into extra load on installation)
