### ISSUE TITLE
Adding an emoji to end of comments causes a system error message

### ISSUE THREAD

**Issue by kidzsearch** [opensource-socialnetwork/opensource-socialnetwork#1127]
I have tried this on different computers and can duplicate the results. If an emoji symbol using the emoji picker is placed at the end of a comment, it most of the time causes a system error message 

"(site name) is having system issues. Reload the page and try again in a minute. If the problem continues, please contact us about it."

After you exit the warning, the entire comment is blank. If you try reloading the page and entering the same comment, it does not help. However, if you then change the text to something else and submit it again with an emoji at the end, it often accepts it (maybe cache related?). Things work fine if the emoji is at the start of the comment. 

Regular posts with an emoji in any position work fine. It is just with comments. There is no error output when it happens that I could find in the JavaScript or error_log files.

**Comment by lianglee** [comment]
That seems due to text() fetch using content-editable box... will check it out.

**Comment by kidzsearch** [comment]
I can add a picture to a comment, just not an emoji at the end of a text message. I can post an emoji by itself on a comment without any issues.

**Comment by githubertus** [comment]
this issue isn't actually caused by emojis
it's caused by the additional blank in front of the emoji
adding your own blank after a word will lead to 
`word&nbsp; emoji`
and this 'non breaking space' is causing the system error
(you'll run into the same error by inserting more than once blank between two words)
As a first workaround simply insert the emoji directly after a word.

**Comment by kidzsearch** [comment]
Yes, it looks like it is the non breaking space and not just the emoji that was initially triggering it. Is there a file can I edit to strip out duplicate nbsp; spaces causing the error? We are getting a lot of complaints about this error.

**Comment by lianglee** [comment]
Fixed it should be available in next release,  take a look https://github.com/githubertus/opensource-socialnetwork/commit/3e7915fdb6235e0e6b3e6f9da3746f2b45a14917

**Comment by kidzsearch** [comment]
Works now. Thanks!  Something for my wishlist would be support for something like tinymce for posts and comments.
