### ISSUE TITLE
access problem with public groups

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#113]
![entities-posting-public-group](https://cloud.githubusercontent.com/assets/9904364/5237774/cb19ff9c-789d-11e4-91fe-8cd5d83a8bbf.png)
![entities-meta-posting-public-group](https://cloud.githubusercontent.com/assets/9904364/5237777/d98387ec-789d-11e4-8883-5a0364ed339e.png)

what I did:
46: created a CLOSED group
47: created a PUBLIC group
48-49: posted to the CLOSED group
50-51: posted to the PUBLIC group

First, I became aware, that although having posted to a public group - the lock icon is shown:
![public-posting](https://cloud.githubusercontent.com/assets/9904364/5237805/6a499d6a-789f-11e4-8ef8-6045e576480b.png)

I expected to get the globe icon here. But even after setting the value in database line 51 from 1 to 2 (which in fact gives the globe icon)  users who are NOT a member of this group cannot see the posting.

![group-non-member-view](https://cloud.githubusercontent.com/assets/9904364/5237840/8d35b24e-78a1-11e4-8327-1e2c47ddc76f.png)

**Comment by lianglee** [comment]
fixed

**Comment by githubertus** [comment]
I'm sorry, not.
Yeah: my report was a little misleading. What I really meant is documented in zfix 113, see
http://ossn.z-mans.net/components/OssnWall/actions/wall/post/group.txt
