### ISSUE TITLE
can add emoticon full with curl???

### ISSUE THREAD

**Issue by budybacod** [opensource-socialnetwork/opensource-socialnetwork#1130]
hi,
i have full `emoticon`
i need add to OSSN ,
can help me???
i have curl emoticon full
![untitled](https://user-images.githubusercontent.com/30666229/28887221-9050b3a6-77e6-11e7-8780-2c14b5028803.png)

**Comment by lianglee** [comment]
OSSN v4.4 use emojis not emoticon,  however we suggest you to look OssnSmiles js and you can add more emoji codes  https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/components/OssnSmilies/plugins/default/js/smilies/emojii.php#L2-L9
