### ISSUE TITLE
forum replies

### ISSUE THREAD

**Issue by nilzolin** [opensource-socialnetwork/opensource-socialnetwork#1134]
When replying on the forum, the replies always get header "Save". Not sure what this is or if it's broken?

**Comment by lianglee** [comment]
Hi,  Premium/Paid components should be reported to softlab24.com, can you confirm if you are referring Forum. paid component?

**Comment by nilzolin** [comment]
Hi,

Yes I am. I'll report it to softlab24 instead. Thanks
