### ISSUE TITLE
OssnPhotos still exists when user delete

### ISSUE THREAD

**Issue by flochman** [opensource-socialnetwork/opensource-socialnetwork#1142]
Hi,

after discussion with Arsalan, I am reporting that after testing Site Monderators component I discovered that after deleting user remain photos files for that user in ossn_data folder. 

Photos files remain after deleting user also from admin dashboard not necessary from Site Moderators component.

I have installed OSSN on Debian Stretch Linux 9.1, PHP 7.0.19, MariaDB 10.1.23

I passed test with only Content Report and Site Moderators components added to the OSSN.

It was fresh install tested under virtualbox.

**Comment by lianglee** [comment]
Can you confirm if user profile photos/cover remains or the album photos too?

**Comment by flochman** [comment]
I tested only album photos.

I did not tested profile photos/cover. I will do now.
