### ISSUE TITLE
Versions and Components as Composer package

### ISSUE THREAD

**Issue by adrianraeuchle** [opensource-socialnetwork/opensource-socialnetwork#1143]
It would be cool to have all ossn versions available at packages.org. so you could easy update the core plus installed components without having the need to upload a zip archive. 

is this possible?

**Comment by lianglee** [comment]
Packages.org isn't found... however we aren't moving to composer as its dependencies manager and OSSN didn't depends on others.

**Comment by Lablnet** [comment]
https://packagist.org/

@lianglee

**Comment by Lablnet** [comment]
@lianglee  i know i just inform you about the correct url
