### ISSUE TITLE
Likes (like-share div) does not appear only on Mobile Safari iOS 10

### ISSUE THREAD

**Issue by JoryAnick** [opensource-socialnetwork/opensource-socialnetwork#1144]
The likes display div under posts, (like-share div), ie: "You and 1 Person liked this" appears on desktop browsers and other mobile browsers at any resolution - except in Safari on iOS 10. This is with the stock theme as shipped in v4.4. Thanks in advance for your assistance.

**Comment by githubertus** [comment]
Thanks for reporting - but it looks like this issue should be better addressed to the Apple staff.
If one plug fits to 9 of 10 sockets, you wouldn't replace the plug, right?
