### ISSUE TITLE
Administrator fail.. Need help!

### ISSUE THREAD

**Issue by stalkerdab** [opensource-socialnetwork/opensource-socialnetwork#1146]
OssnDatabaseException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'facebook.ossn_users.time_created' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by SELECT DATE_FORMAT(FROM_UNIXTIME(time_created), '%Y') AS year, DATE_FORMAT(FROM_UNIXTIME(time_created) , '%m') AS month, COUNT(guid) AS total FROM ossn_users WHERE(time_created > 0) GROUP by DATE_FORMAT(FROM_UNIXTIME(time_created) , '%Y%m') ; in /var/www/html/classes/OssnDatabase.php:82 Stack trace: #0 /var/www/html/classes/OssnDatabase.php(181): OssnDatabase->execute() #1 /var/www/html/classes/OssnUser.php(950): OssnDatabase->select(Array, true) #2 /var/www/html/system/plugins/default/javascripts/dynamic/admin/dashboard/users/users.php(13): OssnUser->countByYearMonth() #3 /var/www/html/libraries/ossn.lib.views.php(27): include('/var/www/html/s...') #4 /var/www/html/libraries/ossn.lib.views.php(50): ossn_include('/var/www/html/s...', Array) #5 /var/www/html/libraries/ossn.lib.plugins.php(75): ossn_view('/var/www/html/s...', Array) #6 /var/www/html/system/plugins/default/pages/administrator/contents/dashboard.php(156): ossn_plugin_view('javascripts/dyn...') #7 /var/www/html/libraries/ossn.lib.views.php(27): include('/var/www/html/s...') #8 /var/www/html/libraries/ossn.lib.views.php(50): ossn_include('/var/www/html/s...', Array) #9 /var/www/html/libraries/ossn.lib.plugins.php(75): ossn_view('/var/www/html/s...', Array) #10 /var/www/html/libraries/ossn.lib.admin.php(204): ossn_plugin_view('pages/administr...') #11 /var/www/html/libraries/ossn.lib.page.php(67): ossn_administrator_pagehandler(Array, 'administrator') #12 /var/www/html/index.php(21): ossn_load_page('administrator', Array) #13 {main}

**Comment by lianglee** [comment]
https://stackoverflow.com/questions/41887460/select-list-is-not-in-group-by-clause-and-contains-nonaggregated-column-inc

You have to disable  sql_mode=only_full_group_by...
