### ISSUE TITLE
allow to reset password with username or email

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1149]
allow to reset password with username or email

**Comment by githubertus** [comment]
I just became aware of this change
and honestly I'm not really happy with it.
Now, any evil community member can use any other member's username and run the reset action.
He can do it as often as he wants, so this may result in a real spamming pain. And besides all that: you don't even know who the idiot was.
If we want to stay with this option it should be combined at least with a second parm (e.g. date of birth) to be checked.
