### ISSUE TITLE
Handling of components with too long ids

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1152]
We need to spend some thoughts on that:
I've just tried to upload a component with id 'ResponsiveFileManager' = 21 chars
but the com_id column is limited to 20.
The component installed correctly, but the db entry gets truncated, leading to an empty entry in the admin panel.
As a first aid I updated the doc in https://www.opensource-socialnetwork.org/wiki/edit/739/naming-convention-for-creating-components accordingly

**Comment by lianglee** [comment]
Yup, the comid is set to varchar 20 chars

**Comment by lianglee** [comment]
Maybe we should set it to 50 or 100 characters
