### ISSUE TITLE
Logging out reloads newsfeed/main wall

### ISSUE THREAD

**Issue by jackpinesavage67** [opensource-socialnetwork/opensource-socialnetwork#1153]
I have noticed this happening from time to time, I will go to log out and the site reloads the news feed wall? Sometimes after 2 or three attempts, it will end my session and log me out, other times I must go into the admin area and log out from there. Any idea's?

**Comment by lianglee** [comment]
Admin area logout works but form newsfeed area it didn't?

**Comment by jackpinesavage67** [comment]
Yes, every once in a while, I have to click the log out  numerous times before it will, otherwise it just reloads the news feed. it is almost like it is failing to terminate the session.

**Comment by jackpinesavage67** [comment]
Could this be because I have my web server wireless connected for testing and the response times are maybe causing it? I was planning on upgrading to 4.4 as I am running version 4.3 and then connect directly to my modem/router.

**Comment by lianglee** [comment]
That is bit strange,  we'll take a look and will let you know..

**Comment by jackpinesavage67** [comment]
Since I have upgraded to version 4.4, it appears to have disappeared. Mind you, I am using awesome theme, have not tried new version with any other theme yet. PS.... awesome is awesome.
