### ISSUE TITLE
Tried upgrading and got this

### ISSUE THREAD

**Issue by jackpinesavage67** [opensource-socialnetwork/opensource-socialnetwork#1156]
I was just disabling my first component that was non ossn and got this for my efforts

Error: Call to undefined function ossn_register_system_sdk() in C:\wamp64\www\www.facecrack.net\components\BanUser\ossn_com.php:13 Stack trace: #0 C:\wamp64\www\www.facecrack.net\classes\OssnComponents.php(164): include_once() #1 C:\wamp64\www\www.facecrack.net\libraries\ossn.lib.components.php(65): OssnComponents->loadComs() #2 C:\wamp64\www\www.facecrack.net\system\start.php(36): include_once('C:\\wamp64\\www\\w...') #3 C:\wamp64\www\www.facecrack.net\index.php(11): require_once('C:\\wamp64\\www\\w...') #4 {main}

It was working just fine, then I disabled a component.

**Comment by jackpinesavage67** [comment]
The first component i disabled was softlab24 premium kernel for ossn 1.0.... I am going to assume that was a mstake. If so, the upgrade instructions need to reflect this as all it say's is to save your data directory and configuration directory.

**Comment by lianglee** [comment]
Please contact softlab24 for premium version upgrades and installations.

**Comment by lianglee** [comment]
Please contact softlab24 for premium version upgrades and installations. As you posted in free version forum , both premium and free version are managed by different team.

**Comment by jackpinesavage67** [comment]
That's good to know. I just went to softlab24 and was told my subscription had expired... I thought core upgrades were supposed to be free, at least that is what it says you check out what is offered for version 4.4. I purchased premium version 4.3? Am I wrong? If so, I will pay the $49 for the subscription and just hope that the next upgrade comes out before my subscription expires.

Sent from my BlackBerry 10 smartphone on the TELUS network.
From: Arsalan Shah
Sent: Tuesday, September 26, 2017 7:23 AM
To: opensource-socialnetwork/opensource-socialnetwork
Reply To: opensource-socialnetwork/opensource-socialnetwork
Cc: jackpinesavage67; Author
Subject: Re: [opensource-socialnetwork/opensource-socialnetwork] Tried upgrading and got this (#1156)



Please contact softlab24 for premium version upgrades and installations. As you posted in free version forum , both premium and free version are managed by different team.

**Comment by jackpinesavage67** [comment]
How do I upgrade from version 4.3 to 4.4? I just paid $49 to renew my subscription "stack service" but still can not download 4.4. Why is this?
