### ISSUE TITLE
Repositioning cover pics on mobile devices

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1157]
I just added a small component to support this missing feature on https://www.opensource-socialnetwork.org/component/view/2571/touchpunch

Maybe we can add it to the next release...

For more info have a look at http://touchpunch.furf.com/

**Comment by lianglee** [comment]
That is nice, let see what people says about it.

**Comment by revvin76** [comment]
tested on Samsung S8 in chrome browser.  works in landscape but not portrait.

**Comment by lianglee** [comment]
Shall we move this to OssnProfile js?

**Comment by githubertus** [comment]
I had a last look into this: This library seems to be no longer maintained, has 192 issues.
And finally it doesn't really work on my Google PixelC and latest Android/Chrome.
I'm going to remove this from the component division today.
Found a promising alternative...
