### ISSUE TITLE
Enter comment alert open 

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1158]
its happen due to https://www.opensource-socialnetwork.org/component/view/2531/homelancer-scroller component installed when there are more then 5 post i delete all post form my profile page and then enter alert not open when there are more post when we write comment and press enter alert box open thanks
![screenshot 598](https://user-images.githubusercontent.com/27757785/30915409-97ed6042-a34b-11e7-850b-74d50d1bd66b.png)
![screenshot 596](https://user-images.githubusercontent.com/27757785/30915427-a7b3d02e-a34b-11e7-8fbe-2de577fa7e66.png)

**Comment by githubertus** [comment]
@lianglee
Simply ignore and close this thread.

@Lablnet
Remember, that I already banned you on NewBlue some time ago because of all the trash you were leaving there. I had released that ban in hope you understood my warning and changed your mind. But it seems I was wrong.
So one last time again: I DON'T need numerous copies of Lorem Ipsum on my newsfeed as I DON'T need a complete copy of your ugly development stuff in my filemanager area.

**Comment by Lablnet** [comment]
Oh zet you'r so angry, as you say I post dummy text It's for test if dout try tour self posting comment and ugly development stuff I have three developer one form Nepal two form Pakistan after some time you see ugly web top in Google , if anyone take time for checking ssues or component your unfairmind become angry don't know what you want I think if you continue do this ossn become bad form world law ..
I close this issue i am not mad take time for checking your issue development components/themes my age are 16.5 year  check this website It's my social First project https://lablnet.tk/social/ login with username Malik password 920647  (it's not completed in development) see and feels/things at this age you are able to make this type web? I only work on thia no one can help me , if you thing no so feel embraced. Thanks

**Comment by lianglee** [comment]
Malik please beware that homelancer scroller is not a core component you should contact the developer directly.

**Comment by Lablnet** [comment]
Sorry sir because i think you will make a party of ossn next release .

**Comment by lianglee** [comment]
@Lablnet yes i'll try to look into the open source scroller component that can work with OSSN current license.

**Comment by Lablnet** [comment]
@githubertus  see my ugly development website https://malikopensources.com/public/
