### ISSUE TITLE
Upload fails

### ISSUE THREAD

**Issue by jackpinesavage67** [opensource-socialnetwork/opensource-socialnetwork#1160]
I have php file size set to 1024 meg and video file upload works for other files up to 100-200 meg in size, but for some reason when I tried to upload a 600 meg video, I get an error as soon as it tries to do the conversion. Is there a setting in ffmpeg causing this? Is there a hard coded max file size in the video component that can be changed?

I will create a guest account for you to try for yourself so you can see the error as it happens, user name guest -  password ossnguest

I was getting this with version 4.3 and I thought it was maybe a bad install or some code issue, so I upgraded to version 4.4 and still it continues. I have the system info component installed if there is something there that might explain this.

The site is http://www.facecrack.net  and of course the system info is http://www.facecrack.net/ossninfo

I hope you can figure this out as what I wanted to do was a "Movie of the week", I have video compression tools and can try reducing the file size further. I will try that and see if there is indeed a max file size.

Thanks

**Comment by githubertus** [comment]
My first idea would be turning on Ossn Error Reporting and have a look into the error_log file in your installation directory after trying to upload that file.

Next, searching the web for wamp64 gives a real large list of all kind of issues. So, running Ossn on a base like this (which is not recommended right because of that) might lead to unexpected surprises, too.

**Comment by jackpinesavage67** [comment]
Then why does it not fail all uploads? I understand what you are saying, as this was meant to run on Linux. It uploads just fine, it just seems as though ffmpeg stumbles on larger files for some reason. I will look into warp 64 and if need be, look at doing a,linux install to see if the problem. In the mean time, I will turn on error reporting, double check all php and apache settings for upload file size and start there. I will also attach screen shots.

Sent from my BlackBerry 10 smartphone on the TELUS network.
From: githubertus
Sent: Monday, October 2, 2017 3:55 AM
To: opensource-socialnetwork/opensource-socialnetwork
Reply To: opensource-socialnetwork/opensource-socialnetwork
Cc: jackpinesavage67; Author
Subject: Re: [opensource-socialnetwork/opensource-socialnetwork] Upload fails (#1160)



My first idea would be turning on Ossn Error Reporting and have a look into the error_log file in your installation directory after trying to upload that file.

Next, searching the web for wamp64 gives a real large list of all kind of issues. So, running Ossn on a base like this (which is not recommended right because of that) might lead to unexpected surprises, too.

**Comment by githubertus** [comment]
Thanks for your feedback.
To sum up what we know:
Files of 100-200 mb size seem to work, and a file of 600 mb fails.
That said: we're very much focused on file sizes up to now. But what, if the 600 mb file comes with something special inside ffmpeg can't cope with? And since we're dealing with uncountable combinations of audio and video codecs in video files, the chance is not that bad.

Hence, the easiest way to nail things down is in fact to call ffmpeg directly from the command line with the same parameters Ossn is using like:
`ffmpeg -i INPUT_FILENAME -vcodec libx264 -profile:v baseline -level 3 OUTPUT_FILENAME.mp4`

please check whether this will result in a playable new file, and/or you'll get any warnings/errors in your command window.

**Comment by jackpinesavage67** [comment]
I assume that I should try that command line after uploading the video file? And if not, is full directory required in the input file name and full directory ‎required for the output filename and destination?


Sent from my BlackBerry 10 smartphone on the TELUS network.
From: githubertus
Sent: Monday, October 2, 2017 12:32 PM
To: opensource-socialnetwork/opensource-socialnetwork
Reply To: opensource-socialnetwork/opensource-socialnetwork
Cc: jackpinesavage67; Author
Subject: Re: [opensource-socialnetwork/opensource-socialnetwork] Upload fails (#1160)



Thanks for your feedback.
To sum up what we know:
Files of 100-200 mb size seem to work, and a file of 600 mb fails.
That said: we're very much focused on file sizes up to now. But what, if the 600 mb file comes with something special inside ffmpeg can't cope with? And since we're dealing with uncountable combinations of audio and video codecs in video files, the chance is not that bad.

Hence, the easiest way to nail things down is in fact to call ffmpeg directly from the command line with the same parameters Ossn is using like:
ffmpeg -i INPUT_FILENAME -vcodec libx264 -profile:v baseline -level 3 OUTPUT_FILENAME.mp4

please check whether this will result in a playable new file, and/or you'll get any warnings/errors in your command window.

**Comment by githubertus** [comment]
step 1 is to download that 600mb source video manually to your server - let's say to C:\mydownloads
step 2 is to open a command window and jump to C:\mydownloads
step 3 is running the command `ffmpeg -i SOURCE_FILENAME -vcodec libx264 -profile:v baseline -level 3 OUTPUT_FILENAME.mp4`

ffmpeg itself doesn't do any up- or downloading, the given paths must be locally available

**Comment by jackpinesavage67** [comment]
That is what I thought, just wanted to verify first. Thank you.

**Comment by githubertus** [comment]
He James,
we're unable to solve this issue without your feedback.
So: were you able to convert that 600mb video successfully from the command-line or not?

**Comment by jackpinesavage67** [comment]
Unfortunately, my real job has kept me from being able to do this. I should be able to try this tonight.

Sent from my BlackBerry 10 smartphone on the TELUS network.
From: githubertus
Sent: Thursday, October 5, 2017 8:50 AM
To: opensource-socialnetwork/opensource-socialnetwork
Reply To: opensource-socialnetwork/opensource-socialnetwork
Cc: jackpinesavage67; Author
Subject: Re: [opensource-socialnetwork/opensource-socialnetwork] Upload fails (#1160)



He James,
we're unable to solve this issue without your feedback.
So: were you able to convert that 600mb video successfully from the command-line or not?

**Comment by jackpinesavage67** [comment]
I tried what you told me, ffmpeg ran and made a copy of the movie. Needless to say, both played well if I selected them from the folder and used VLC to play them. so i deleted the old movie from site, and uploaded new version.... still does not play - uploads just fine, just will not play. At this point, I am going to try another video file to see what happens. I even increased php post size, file upload size, max allowed memory to larger amounts (upload size 1 gig, post size 2 gig....) I am using php7, I guess I could try 5 and see what happens.

**Comment by jackpinesavage67** [comment]
This is what the movie does when you click play and then try to stop it....
![video_page](https://user-images.githubusercontent.com/29686751/31259605-371e93d8-aa05-11e7-90f4-ea673df6f59e.png)

**Comment by lianglee** [comment]
Try to open browser console to see if there is something there to see.

**Comment by jackpinesavage67** [comment]
From the console:

POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 63188ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 60750ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 61324ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 58887ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 57371ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 56872ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 54418ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 54012ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 52528ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 49982ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 50559ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 48091ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 46715ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 46325ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 43841ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 43324ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 41841ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 39388ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 39996ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 37622ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 36136ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 35638ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 33153ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 32746ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 31310ms]
POST XHR http://facecrack.net/notification/count [HTTP/1.1 200 OK 28825ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 29310ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 29792ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 27403ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 26058ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 25653ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 23247ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 22793ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 21356ms]
GET http://facecrack.net/video/file/62/44f683a84163b3523afe57c2e008bc8c.mp4 [HTTP/1.1 206 Partial Content 28857ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 18920ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 19449ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 16938ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 15532ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 15096ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 12705ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 12266ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 10751ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 8250ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 8706ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 6235ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 4860ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 4438ms]
POST XHR http://facecrack.net/video/progress/undefined [HTTP/1.1 200 OK 2547ms]
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js [HTTP/1.1 200 OK 2157ms]
GET http://facecrack.net/video/file/62/44f683a84163b3523afe57c2e008bc8c.mp4 [HTTP/1.1 206 Partial Content]
POST XHR http://facecrack.net/video/progress/undefined 
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js 
POST XHR http://facecrack.net/video/progress/undefined 
POST XHR http://facecrack.net/video/progress/undefined 
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js 
POST XHR http://facecrack.net/video/progress/undefined 
POST XHR http://facecrack.net/video/progress/undefined 
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js 
POST XHR http://facecrack.net/video/progress/undefined 
POST XHR http://facecrack.net/notification/count 
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js 
POST XHR http://facecrack.net/video/progress/undefined 
POST XHR http://facecrack.net/video/progress/undefined 
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js 
POST XHR http://facecrack.net/video/progress/undefined 
POST XHR http://facecrack.net/video/progress/undefined 
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js 
POST XHR http://facecrack.net/video/progress/undefined 
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js 
POST XHR http://facecrack.net/video/progress/undefined 
POST XHR http://facecrack.net/video/progress/undefined 
GET XHR http://facecrack.net/ossnchat/boot/ossn.boot.chat.js 
POST XHR http://facecrack.net/video/progress/undefined

**Comment by jackpinesavage67** [comment]
Very odd, it just started working...... I am watching it now. Poor video to begin with audio is out of sync.

**Comment by jackpinesavage67** [comment]
It works fine on the server, but not on another computer connected to the same network, accessing server.

**Comment by githubertus** [comment]
I can't confirm this. Godzilla takes a minute to load and start- yes - but except from an out of sync audio track it's running flawlessly here.

But aside from that: Why don't we concentrate on the initial problem? 

In the beginning you said:
"...but for some reason when I tried to upload a 600 meg video, I get an error as soon as it tries to do the conversion...."

Now you say:
"... so i deleted the old movie from site, and uploaded new version.... still does not play - uploads just fine, just will not play ...."

So please try to describe exactly again what happens after uploading: Are you getting a player with the movie inside - as you do with Godzilla - or are you getting no player at all and an error? And if the latter one is true: What error message are you getting exactly? Additionally, you may give us the link to the video source file so we can have a look at it.

**Comment by jackpinesavage67** [comment]
I am getting a player with an initial image that is displayed, but when you press play you have no movie length in the indicator bar below (should tell you the length of the video),and the movie buffer icon just spins endlessly. sometimes you click play and you get nothing at all, no buffering, no play bar , nothing.

**Comment by jackpinesavage67** [comment]
Clicked play again, buffering icon spun for a while, but movie finally played. I am going to try a larger one now and see what happens.

**Comment by angelblessing** [comment]
a shorter way to enable ffmpeg  watch the video install ffmpeg on linux shared hosting https://www.youtube.com/watch?v=FJZT-J_fYxU       place the files in   /public/sites/www. YOURSITENAME.com/usr/bin/    set permissions ffmpeg 777   use in the configuration at your admin panel   under videos   /public/sites/www. YOURSITENAME.com/usr/bin/    that will do

**Comment by angelblessing** [comment]
after i managed to enable the video comp with ffmpeg there are some bugs  fe searchig uploaded videos in main search menu wont work.. and the sharepost componen wont work for videos ass well mention   the fileuploadsize has limits as set in the ini file or ht acces but thats a matter of adjusting by means of your notepad editor
