### ISSUE TITLE
404 error thrown when add friend button is used

### ISSUE THREAD

**Issue by jackpinesavage67** [opensource-socialnetwork/opensource-socialnetwork#1161]
I asked a friend in another city to log in and try the site, he registered and logged in, but when he went to add me as a friend, it threw a 404 error. I have attached a screen capture of this.

![broken add friends](https://user-images.githubusercontent.com/29686751/31060129-f642f292-a6ca-11e7-8c22-53080c3a1e64.png)

I used the invite friend component to invite the wife, she registered with the invite link, logged in and went to add me as a friend and got the same error, she showed it to me on her iphone.

I have set up a guest account to see this for yourself:

http://www.facecrack.net
user - guest
password - ossnguest

**Comment by lianglee** [comment]
Hi, try to download the v4.4 premium and replace your awesome theme from latest .zip file (we updated awesome theme in v4.4 that should fix your issue)
