### ISSUE TITLE
Impossible to create and "add" in the admin

### ISSUE THREAD

**Issue by legrandseb** [opensource-socialnetwork/opensource-socialnetwork#1171]
We use : OSSN core 4 - OssnAds 3.0 - Softlab24 Premium Kernel for OSSN 1.0 

In the admin: impossible to create an "add" -> when we validate we get a message "all fields required" even though they are all filled in...

Screen filled in 

![image](https://user-images.githubusercontent.com/4365643/32142994-1d0890ec-bca3-11e7-98e0-6ab8b3b93571.png)

System response

![image](https://user-images.githubusercontent.com/4365643/32143007-3da35a8a-bca3-11e7-994e-3b82083a8cf7.png)

**Comment by lianglee** [comment]
Please send us your login details at softlab24.com/contact and our team shall take a look into the issue.
