### ISSUE TITLE
When we add carriage return in the posts, posts created are empty

### ISSUE THREAD

**Issue by legrandseb** [opensource-socialnetwork/opensource-socialnetwork#1172]
We use : OSSN core 4 - Softlab24 Premium Kernel for OSSN 1.0  - Popular Posts 2.1 - Post Share 1.4 ... and several other component.

On "public" part; when we add carriage return in the posts, posts created are empty.

Screen filled in

![image](https://user-images.githubusercontent.com/4365643/32143063-090c6194-bca4-11e7-8390-e54075bac0b3.png)

System response

![image](https://user-images.githubusercontent.com/4365643/32143070-228c1de4-bca4-11e7-9c60-6af5ffb3dbf0.png)

**Comment by lianglee** [comment]
Confirmed as a bug in v4.4

**Comment by legrandseb** [comment]
Hello, we have a customer who bought the "premium" version and is complaining about this pretty blocking bug. Do you have any insights regarding the planning for fix ?

**Comment by lianglee** [comment]
@legrandseb,  Our team is taking a look into it since we are humans it takes time to understand from where the issues is coming,  We don't have seventh sense to know immediately the fix.

**Comment by legrandseb** [comment]
@lianglee : I know debugging is always complex and time consuming. I don't want to put any pressure or blame anyone, I simply need to inform my customer that there is a follow up regarding the issue he reported. I can now inform him that you are investigating, and that's all I needed to know. Thanks.

**Comment by lianglee** [comment]
The issue tested on latest development version and there is no error found,  please contact softlab24.com/contact they shall upgrade your site to dev version.
