### ISSUE TITLE
Emoticon window/modal stays open after "post"

### ISSUE THREAD

**Issue by legrandseb** [opensource-socialnetwork/opensource-socialnetwork#1173]
We use : OSSN core 4 - Softlab24 Premium Kernel for OSSN 1.0 - OssnSmilies 4.4 

When creating a post with emoticon in it : emoticon window/modal stays open after "post", even though the post is correctly created.

Screen filled in

![image](https://user-images.githubusercontent.com/4365643/32143101-ea35fe00-bca4-11e7-811c-313ecc53b8f9.png)

System response

![image](https://user-images.githubusercontent.com/4365643/32143106-0233e314-bca5-11e7-81bc-b8d974192cd5.png)

**Comment by githubertus** [comment]
Maybe we should think about closing the box automatically after picking up an emoji, anyway?
I'm experimenting with a change like that already on my site and it feels quite comfortable to me.
Of course this doesn't guarantee the box's closing if you choose no emoji at all, but I'd consider this to be a rather seldom case.
