### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function ossn_isAdminLoggedin()

### ISSUE THREAD

**Issue by poinT1501** [opensource-socialnetwork/opensource-socialnetwork#1175]
Hello !!! 
First of all , I'm sorry for my bad english.
Then , my problem is that I can't access my site anymore . I have to mention that I have installed the ossn on my localhost for testing , and I don't know what the heell I did , but when I'm trying to access it , it gives the next error: 
"Fatal error: Uncaught Error: Call to undefined function ossn_isAdminLoggedin() in C:\xampp\htdocs\myfiles\system\handlers\errors.php:31 Stack trace: #0 C:\xampp\htdocs\myfiles\libraries\ossn.lib.views.php(27): include() #1 C:\xampp\htdocs\myfiles\libraries\ossn.lib.views.php(50): ossn_include('C:/xampp/htdocs...', Array) #2 C:\xampp\htdocs\myfiles\libraries\ossn.lib.system.php(769): ossn_view('C:/xampp/htdocs...', Array) #3 [internal function]: _ossn_exception_handler(Object(ParseError)) #4 {main} thrown in C:\xampp\htdocs\myfiles\system\handlers\errors.php on line 31"
Then , if I delete "ossn.config.db.php" and "ossn.config.site.php" from configurations , it gives "It seems the Open Source Social Network is already installed" . 
Any suggestions , please ?

**Comment by lianglee** [comment]
Did you changed something ? please re-upload the files to your system Seems missing some files.

**Comment by poinT1501** [comment]
I've changed only the romanian language pack , the translation wasn't correct.

**Comment by poinT1501** [comment]
Nothing is missing . I have verified .

**Comment by lianglee** [comment]
Try to upload all files again and see if it solves the issue
