### ISSUE TITLE
How to fix the photo uploading problem in mobile device

### ISSUE THREAD

**Issue by rifatuddin** [opensource-socialnetwork/opensource-socialnetwork#1176]
Sir,
Please tell me how to fix the mobile photo uploading problem. When I want to upload a profile picture or any picture it show error. The error text is "unable to complete previous operation due to low memory.
Thanks

**Comment by rifatuddin** [comment]
Sir,
Please tell me how to fix the mobile photo uploading problem. When I want to upload a profile picture or any picture it show error. The error text is "unable to complete previous operation due to low memory.
Thanks

**Comment by lianglee** [comment]
Contact your hosting provider!
