### ISSUE TITLE
malayalam letter ഠ not working

### ISSUE THREAD

**Issue by avrpayyyur** [opensource-socialnetwork/opensource-socialnetwork#1177]
please provide the solution
malayalam one of the word  പഠ in that 'ഠ ' unable to post
while posting that letter showing cannot create post

please help me

**Comment by lianglee** [comment]
You can alternatively use the following component : https://github.com/lianglee/Input/archive/master.zip

**Comment by avrpayyyur** [comment]
thank you so much....
