### ISSUE TITLE
missing reconversion of html escaped characters in messages

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#118]
As I saw, umlauts and other special characters are converted (ä becomes \&auml;) before they are stored in the database. In almost all places of ossn, they get correctly reconverted back for display. But with messages and the chat, this reconversion is missing.
Besides that: Is this forth and back converting necessary at all? Why not storing everything just 1:1 in the database?

**Comment by lianglee** [comment]
fixed

**Comment by lianglee** [comment]
Similar to #277
