### ISSUE TITLE
Using OOSN on the web host

### ISSUE THREAD

**Issue by Bagsdto75** [opensource-socialnetwork/opensource-socialnetwork#1185]
Im currently using AwardSpace To Create my website, so I tried to make it, it didnt work, i contacted support, and said there was an error with my .htaccess file, I need help resolving this issue

**Comment by githubertus** [comment]
I'm afraid it'll take some to find your .htaccess file among millions of others. So you'll need a little patience.

**Comment by CaddyDz** [comment]
@githubertus Why not add `ISSUE_TEMPLATE.md` file on the root folder of the repository with guidelines for opening issues? it may help avoiding these kind of things in the future.  
[Example](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md)

**Comment by lianglee** [comment]
@CaddyDz  it is already exists when you report issue here  please see : 

![image](https://user-images.githubusercontent.com/805066/32826172-318ea11e-ca09-11e7-84f0-da8e75f0c652.png)
