### ISSUE TITLE
The \ are escaped in the posts

### ISSUE THREAD

**Issue by legrandseb** [opensource-socialnetwork/opensource-socialnetwork#1215]
When there is an \ in a post, it is lost. To be precise: when there is a string with backslashes, the first one is escaped and doesn't appear in the post.
We use ossn 4

**Comment by lianglee** [comment]
Does this appear with the input component i mentioned to you?

**Comment by lianglee** [comment]
Thanks for reporting i confirm this as bug,  
Steps to reproduce : 
\ is is removed from post view but can be viewed when you edit the post.
