### ISSUE TITLE
Message box not showing in groups

### ISSUE THREAD

**Issue by andrefecs** [opensource-socialnetwork/opensource-socialnetwork#1220]
Hi guys,
I just can't post anything on groups of my OSSN website. There is no message box at any group's page. The rest of the components are working perfectly, including the message box of my wall and news feed.

Does someone know what is happening and how can I fix it?

Thanks.

**Comment by githubertus** [comment]
Please follow the steps (case B) outlined on https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error
