### ISSUE TITLE
Can't send a with accent:  "à"

### ISSUE THREAD

**Issue by michaelvd123** [opensource-socialnetwork/opensource-socialnetwork#1222]
Hello,
I am using the product for french users. Whenever they want to enter the "à" letter, it is failing, nothing is sent.
I believe it is on the JS part, because it is already empty in the php part.
Best regards,

**Comment by githubertus** [comment]
Thanks for reporting, michael.

A fix has been applied  already here to the development code (see https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/a3d0d0e17003d2365c1fcb4d8a86b96ba9b34907)

and will be available with Ossn 4.5 in short terms.
