### ISSUE TITLE
Broken profile images after uploading [SOLVED]

### ISSUE THREAD

**Issue by rikMY** [opensource-socialnetwork/opensource-socialnetwork#1223]
Dear Zet man.

I solve the problem, I overlooked to install the PHP GD Library.

[PROBLEM SOLVED]
no need to troubleshoot and raise a case B.......

R

**Comment by lianglee** [comment]
In community you said you change the code which we didn't recommend it,  so it make sense to look into your hosting in first place instead of blaming the default code you changed.
