### ISSUE TITLE
premium website login problem

### ISSUE THREAD

**Issue by firtinagetiren** [opensource-socialnetwork/opensource-socialnetwork#1224]
![adsiz](https://user-images.githubusercontent.com/34338263/33951588-0b8357d6-e038-11e7-86f4-d003f300a190.png)

[12-Dec-2017 17:09:12 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}
[12-Dec-2017 17:09:24 UTC] PHP WARNING: 2017-12-12 17:09:24 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/ossn_com.php (line 70)
[12-Dec-2017 17:09:24 UTC] PHP WARNING: 2017-12-12 17:09:24 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/plugins/default/user/fields/item.php (line 21)
[12-Dec-2017 17:10:27 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}
[12-Dec-2017 17:18:51 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}
[12-Dec-2017 20:03:26 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}
[12-Dec-2017 20:03:27 UTC] PHP WARNING: 2017-12-12 20:03:27 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/ossn_com.php (line 70)
[12-Dec-2017 20:03:27 UTC] PHP WARNING: 2017-12-12 20:03:27 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/plugins/default/user/fields/item.php (line 21)
[13-Dec-2017 03:35:30 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/system/handlers/actions.php(11): require_once('/home/u34209567...')
#8 {main}
[13-Dec-2017 05:20:56 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}
[13-Dec-2017 05:21:04 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}
[13-Dec-2017 05:21:07 UTC] PHP WARNING: 2017-12-13 05:21:07 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/ossn_com.php (line 70)
[13-Dec-2017 05:21:07 UTC] PHP WARNING: 2017-12-13 05:21:07 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/plugins/default/user/fields/item.php (line 21)
[13-Dec-2017 14:10:49 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}
[13-Dec-2017 16:36:21 UTC] PHP WARNING: 2017-12-13 16:36:21 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/ossn_com.php (line 70)
[13-Dec-2017 16:36:21 UTC] PHP WARNING: 2017-12-13 16:36:21 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/plugins/default/user/fields/item.php (line 21)
[13-Dec-2017 16:36:49 UTC] PHP WARNING: 2017-12-13 16:36:49 (UTC): "in_array() expects parameter 2 to be array, boolean given" in file /home/u342095670/public_html/classes/OssnEntities.php (line 206)
[13-Dec-2017 16:38:15 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}
[13-Dec-2017 16:38:23 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}
[13-Dec-2017 16:38:28 UTC] PHP WARNING: 2017-12-13 16:38:28 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/ossn_com.php (line 70)
[13-Dec-2017 16:38:28 UTC] PHP WARNING: 2017-12-13 16:38:28 (UTC): "Invalid argument supplied for foreach()" in file /home/u342095670/public_html/components/CustomFields/plugins/default/user/fields/item.php (line 21)
[13-Dec-2017 16:53:40 UTC] exception 'OssnDatabaseException' with message 'MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.subtype='user:category' AND o.type='site') ORDER by o.guid ASC  ; ' in /home/u342095670/public_html/classes/OssnDatabase.php:82
Stack trace:
#0 /home/u342095670/public_html/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/u342095670/public_html/classes/OssnObject.php(456): OssnDatabase->select(Array, true)
#2 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(40): OssnObject->searchObject(Array)
#3 /home/u342095670/public_html/classes/OssnSystem.php(42) : eval()'d code(51): Categories->getAll()
#4 [internal function]: categories_menu_sidebar('ossn', 'init', NULL)
#5 /home/u342095670/public_html/libraries/ossn.lib.system.php(234): call_user_func_array('categories_menu...', Array)
#6 /home/u342095670/public_html/system/start.php(40): ossn_trigger_callback('ossn', 'init')
#7 /home/u342095670/public_html/index.php(11): require_once('/home/u34209567...')
#8 {main}

**Comment by lianglee** [comment]
It seems you are using free hosting,  please contact your hosting provider as error is clearly about your hosting provider : MySQL server has gone away
