### ISSUE TITLE
Emoji panel open at bottom and disable after click on emojies

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1225]
Emoji panel open at bottom and when add emoji click on item it hide box and we need open again for adding more emoji in input field
tested on chrome 
https://i.imgur.com/nXsE3j1.png
test on firefox
https://i.imgur.com/GXvS6uW.png

**Comment by lianglee** [comment]
This is not a bug ,  in v4.5 emoji box made in such a way.

**Comment by Lablnet** [comment]
but it look like messy sir

**Comment by Linux4Life531** [comment]
Is emoji box open source, and if so, does it have a git hub page?
