### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by alexraynes** [opensource-socialnetwork/opensource-socialnetwork#1236]
Fatal error: Uncaught OssnDatabaseException: User '1471604_ossn' has exceeded the 'max_questions' resource (current value: 50000) SELECT * FROM ossn_site_settings ; in /srv/disk1/2471674/www/james.com/classes/OssnDatabase.php:82 Stack trace: #0 /srv/disk1/1071674/www/ljames.com/classes/OssnDatabase.php(181): OssnDatabase->execute() #1 /srv/disk1/2471674/www/james.com/classes/OssnSite.php(35): OssnDatabase->select(Array, true) #2 /srv/disk1/2471674/www/james.com/libraries/ossn.lib.system.php(29): OssnSite->getAllSettings() #3 /srv/disk1/2471674/www/james.com/system/start.php(36): include_once('/srv/disk1/2471...') #4 /srv/disk1/2471674/www/james.com/index.php(11): require_once('/srv/disk1/2471...') #5 {main} thrown in /srv/disk1/2471674/www/james.com/classes/OssnDatabase.php on line 82

I keep experiencing this problem,  in that process I change my hosting provider, to another hosting company, but stay getting the fatal error. Please can some one help

**Comment by lianglee** [comment]
Use VPS and you'll never face such a issue
