### ISSUE TITLE
Composer : new try

### ISSUE THREAD

**Issue by Cryde** [opensource-socialnetwork/opensource-socialnetwork#1238]
Hello !

Do you still not consider using composer as autoloader and dependencies manager ? 
Because your project is very ambitious, but I think that it could attract more PHP dev if it follow some recommendations :)
I could help !

**Comment by lianglee** [comment]
Hello Crydle,  OSSN didn't depends on other projects so we are not using dependencies manager.   However auto-loader php classes is still something we are thinking to implement in next version.

**Comment by Cryde** [comment]
Nice ! 

But why don't you use other dependencies ?
As I say previously, those one are already unit tested

**Comment by githubertus** [comment]
Okay, so you're a drummer - and I can't find the right picture...
But simply ask your guitar playing band mate to add numerous effect devices (he would never use) to his input lead - just in order to take care about some more dependencies and things that could be broken. ;)

**Comment by Cryde** [comment]
This is a poor exemple.
What I propose you is just use something that is established and use by a lot of people. (and also unit tested, do you test your code (behat & phpunit for instance) ?)

I can also see that there is no "rules" in the code : indentation is different on each place, camelCase / sneek_case.

I just don't get why such a big (and ambitious) project like this is again using the work of other smart people (and don't say that it will lead to errors & bug, it's not true)

You could for instance use dependencies for manipulating image, upload, database (doctrine, propel, ...)

**Comment by lianglee** [comment]
We use K&R Indentation style,     And about camel_case and sneek_case they depend on developer what they really wanted to use,  its just for naming the function with underscores or not.

>I just don't get why such a big (and ambitious) project like this is again using the work of other smart people (and don't say that it will lead to errors & bug, it's not true)

So you are saying we use the parts of 90s truck in our car and continue using it,  Until its stop getting in market. 

So if we use the others works and they stop doing what you gonna do? find alternative work? writing own? its waste of time.

Further when someone decided to make things working differently then we have to update our code completely which is waste of time.

**Comment by Cryde** [comment]
I think you take "extrem" example to make you point right. In those days, when you choose a dependency you take care if it is : unit tested, maintain (not to much issues openened), stars and so on ...

The power of tool like "git" is that you can fork a project that is eventually not maintenained anymore and fix/customize it like you want.

PHP word (and not only) have semver that is kind of rules to not break API in minor version. But even if the API is broken, you won't have to rewritte ALL your project... But some piece of code only :)
Use "small" and focused dependencies (not a dependency that manage image, db access and make coffee)

**Comment by lianglee** [comment]
> The power of tool like "git" is that you can fork a project that is eventually not maintenained anymore and fix/customize it like you want.

Why would i maintain anyone project?

> .... not a dependency that manage image but also db access and making coffee)

And why would i use someone else database library so that my project can work?

Ok here is a code 

```
<?php
 function add_two($a, $b){
       return $a+$b;
}
```

Tell me why would i use dependencies in above function?  To make simple stuff more complex.? If you can able to handle above function by yourself i don't think there is a need of any dependencies.
