### ISSUE TITLE
Fix for PHPMail and local characters

### ISSUE THREAD

**Issue by tellhere** [opensource-socialnetwork/opensource-socialnetwork#1239]
I figured out why sometimes e-mail does not work with local characters (Russian). You use "vsprintf" in "ossn_print" function, but it does not properly work with UTF-8 characters. It spoils strings enough to make PHPMailer fail. I do not have a good solution for this but I have a workaround:

				if($args) {
						$string = vsprintf($string, $args);
						$string = iconv("UTF-8", "UTF-8//IGNORE", $string); // THIS IS MY FIX
				}

After this e-mails started working fine on my site. You may want to implement a better fix in the next release or at least use my workaround.

**Comment by githubertus** [comment]
Thanks for reporting.

In order to reproduce, could you please 
- provide your PHP version
- and replace chars/strings in below example with NOT working ones:

```
$s1 = 'from start яндексвиде arg1: %s - arg2: %s to the end';

$a1 = 'яндексвидео';
$a2 = 'Смешные';

$s1 = vsprintf($s1, ([$a1, $a2]));
$s2 = iconv("UTF-8", "UTF-8//IGNORE", $s1);

if ($s1 != $s2) {
	echo 'Problem string found!';
}
else {
	echo 'ok';
}

```
