### ISSUE TITLE
output missing with OssnDatabaseException 

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#124]
I just did a little test what would happen if one or more database credentials are wrong:
We're getting a blank page - that's all.
Adding the line:
echo ("database connect error: {$connect->connect_error} <br> error code: {$connect->connect_errno}");
to the Connect function gives  in fact a reasonable result like:

database connect error: Access denied for user 'ruth'@'localhost' (using password: YES)
error code: 1045

But there's no output from the regular OssnDatabaseException call.

**Comment by githubertus** [comment]
just checked with latest 2015-01-03 release:
I'm still getting a blank page with wrong db creditials or mysql shut down

**Comment by lianglee** [comment]
Ok thats cool!
