### ISSUE TITLE
friends page error

### ISSUE THREAD

**Issue by bouman4** [opensource-socialnetwork/opensource-socialnetwork#1242]
/u/admin1/friends

exception 'OssnDatabaseException' with message 'User '2558277_wpressb21f1e88' has exceeded the 'max_questions' resource (current value: 12000) SELECT * FROM ossn_users WHERE(username='admin1') ; ' in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/classes/OssnDatabase.php:82 Stack trace: #0 /srv/disk1/2558277/www/vrienden.mywebcommunity.org/classes/OssnDatabase.php(181): OssnDatabase->execute() #1 /srv/disk1/2558277/www/vrienden.mywebcommunity.org/classes/OssnUser.php(168): OssnDatabase->select(Array) #2 /srv/disk1/2558277/www/vrienden.mywebcommunity.org/libraries/ossn.lib.users.php(100): OssnUser->getUser() #3 /srv/disk1/2558277/www/vrienden.mywebcommunity.org/components/OssnProfile/ossn_com.php(230): ossn_user_by_username('admin1') #4 [internal function]: profile_page_handler(Array, 'u') #5 /srv/disk1/2558277/www/vrienden.mywebcommunity.org/libraries/ossn.lib.page.php(67): call_user_func('profile_page_ha...', Array, 'u') #6 /srv/disk1/2558277/www/vrienden.mywebcommunity.org/index.php(21): ossn_load_page('u', 'admin1/friends') #7 {main}

**Comment by lianglee** [comment]
Move to dedicated server.
