### ISSUE TITLE
send message error

### ISSUE THREAD

**Issue by bouman4** [opensource-socialnetwork/opensource-socialnetwork#1243]
messages/message/

Eve Feest

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: session_start(): Cannot send session cache limiter - headers already sent in /srv/disk1/2558277/www/vrienden.mywebcommunity.org/system/start.php on line 11

**Comment by lianglee** [comment]
This seems issue with your hosting provider,  you'll need to change it

**Comment by bouman4** [comment]
thanks i run a test site on a free host maybe thats the problem

**Comment by lianglee** [comment]
free hosts are not recommended
