### ISSUE TITLE
IIS as server

### ISSUE THREAD

**Issue by net4u** [opensource-socialnetwork/opensource-socialnetwork#1246]
Hi

Is possible to install on IIS instead of Apache?

**Comment by lianglee** [comment]
If you can convert apache .htaccess configuration to iis then you should able to use it but we don't support other servers.

**Comment by githubertus** [comment]
I think that finding the right replacement of mod_rewrite is the most important part, but there's a lot of help available on that like https://manage.accuwebhosting.com/knowledgebase/2415/How-to-Enable-modrewrite-on-IIS-Web-Server.html. Good luck.
