### ISSUE TITLE
ACTIVATION EMAIL IS NOT FOUND

### ISSUE THREAD

**Issue by lxamir** [opensource-socialnetwork/opensource-socialnetwork#1250]
Your account has been registered! We have sent you an account activation email. If you didn't receive the email, please check your spam/junk folder.

after this message, no mail will be received by the ossn

**Comment by githubertus** [comment]
Please follow the guidelines in https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error (case B)

**Comment by SMotaee** [comment]
Hi! I have setup a demo version on m host to test the website, when I invite my friends, i get error. please help me to solve the problem. also, I the problem is attached on this message.
![error](https://user-images.githubusercontent.com/16328109/149725555-09187f8f-2df0-4e7f-a046-5228f5f719c2.jpg)
