### ISSUE TITLE
Error when tagging friend

### ISSUE THREAD

**Issue by thiagoanselmo** [opensource-socialnetwork/opensource-socialnetwork#1253]
When making a post, I tried to bookmark my friend, but just keep looking and do not find any friends.
![error marked friend](https://user-images.githubusercontent.com/12956934/36361521-6dfda03a-150b-11e8-9902-8e6ef31beb23.png)

Version OSSN: 4.6 Premium
Chrome Version: 63.0.3239

**Comment by lianglee** [comment]
Please share your website URL and the non admin login details

**Comment by thiagoanselmo** [comment]
My URL IS: 159.203.186.14

User: teste
Pass: 123456

Server test.

**Comment by lianglee** [comment]
Can you try to search by wildcard keyword *

**Comment by lianglee** [comment]
please make sure you have php mb extension enabled on your cpanel

**Comment by thiagoanselmo** [comment]
Yes, the mb was missing. It is working, when a user is registered, in a publication the user does not receive a marked notification in my publication, is there any more package missing for this to happen?
