### ISSUE TITLE
I am not receiving group publications alert

### ISSUE THREAD

**Issue by thiagoanselmo** [opensource-socialnetwork/opensource-socialnetwork#1255]
I created a test group and entered the test group. When someone posts something to the group, I, who am a member of the group, do not receive updates from the group, just know that there are new updates when I join the group.

Version OSSN: 4.6 Premium
Chrome Version: 63.0.3239

**Comment by lianglee** [comment]
There is no feature implemented in OSSN yet for such a thing.
