### ISSUE TITLE
Error loading smiles

### ISSUE THREAD

**Issue by thiagoanselmo** [opensource-socialnetwork/opensource-socialnetwork#1256]
When making a publication or comment if you have smiles it gives error in the publication or comment.

![capturar](https://user-images.githubusercontent.com/12956934/36361900-a2b7de5a-150e-11e8-9635-b3547ce2cf28.PNG)

Version OSSN: 4.6 Premium
Chrome Version: 63.0.3239

**Comment by lianglee** [comment]
Please provide the browser details too, the operating system etc.

**Comment by thiagoanselmo** [comment]
Client: Operating system windows 7 Professional x64

Browser: Version 64.0.3282.167 (Official version) 64-bit

Server: Ubuntu Server 16.04 x64Bits

* If necessary, provide SSH access. It's a digital ocean VPS.

I'm willing to pay for resolution issues # 1255 # 1254 # 1253

**Comment by thiagoanselmo** [comment]
Help-me #1255 #1254 #1253

**Comment by lianglee** [comment]
Can you share your website URL?

**Comment by thiagoanselmo** [comment]
My URL IS: 159.203.186.14

User: admin
Pass: 123456

Server test.

**Comment by lianglee** [comment]
It shows for me, it seems your windows is older  That seems bug with windows  https://answers.microsoft.com/en-us/windows/forum/windows_7-start/color-emojifont-support-on-windows-7/8010df8b-c628-4d2d-8cad-24b7bec8c444?auth=1

![image](https://user-images.githubusercontent.com/805066/36438966-4428b8a2-168d-11e8-9eeb-6cf5c5c498ac.png)

**Comment by lianglee** [comment]
https://blog.getemoji.com/post/82224498347/how-to-use-emoji-in-windows-7
