### ISSUE TITLE
Fonts missing on intranet hosted OSSN

### ISSUE THREAD

**Issue by HashirZahir** [opensource-socialnetwork/opensource-socialnetwork#1257]
While hosting the OSSN v4.4 on a Windows 10 Machine via XAMPP with PHP 5.7, MySQL and with cache enabled in administrator, fonts do not appear in Google Chrome, Internet Explorer 11 and Mozilla Firefox. Upon closer inspection, I noticed that even with cache enabled, several files still require internet access to download such as Awesome Fonts and some googleapi fonts. As a result, several of the buttons appear invisible (but clicking on them still has a function). 
![missing_fonts_ossn1](https://user-images.githubusercontent.com/17134332/36409733-32883b3a-1648-11e8-8eff-1184c33890b2.jpg)

Is there a way to solve it? the only way I can think of is to manually download all the files that require internet access and then have OSSN link to those files manually. For example, these lines: 
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/b8b03cf11843abe9f87403d70a055560f9f3d287/themes/goblue/ossn_theme.php#L38
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/b8b03cf11843abe9f87403d70a055560f9f3d287/libraries/ossn.lib.javascripts.php#L37
I have tried OSSN before with internet and it works just fine. However, now I would need to serve a local network. I have setup the OSSN in an internet environment and the cache setting downloaded all the necessary JS and CSS files before I tested it in the intranet setting. I would just like to add that sometimes Google Chrome has a cache of Awesome Fonts or googleapi fonts and hence these icons load even there is no internet. However, this is not the case for the freshly installed computers I serve which do not have internet. Is there a more convenient approach for intranet based OSSN rather than editing core files? Thanks.

**Comment by lianglee** [comment]
OSSN requires a valid internet to run,  as you see there are some files required  , If you wanted to run on local server without internet you need to take care of it,  You can create a new component/theme (not editing core file) you can load the js, css files manually.

Further please read the license https://raw.githubusercontent.com/opensource-socialnetwork/opensource-socialnetwork/v5.x/LICENSE.txt before trying to use the software.
