### ISSUE TITLE
please restrict sending empty messages

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1270]
please restrict sending empty messages
![screenshot 59](https://user-images.githubusercontent.com/27757785/36934572-9f6fd6c2-1f0d-11e8-975a-7b82c040efc5.png)

**Comment by lianglee** [comment]
You are trying message with multiple spaces ? or new line?

**Comment by Lablnet** [comment]
new lines

**Comment by Lablnet** [comment]
This issue also in post as well

**Comment by Lablnet** [comment]
This issue also commebt update

**Comment by lianglee** [comment]
@Lablnet the issue has not been solved yet please keep it open
