### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by iqbalridha** [opensource-socialnetwork/opensource-socialnetwork#1271]
This is the proposed logo I submitted. Tell you how you think sir. Thank you.
https://steemit.com/utopian-io/@iqbalridha/logo-design-proposal-for-open-source-social-network

**Comment by lianglee** [comment]
Hello Iqbal thank you working for OSSN making it better,  we'll discuss this internally and revert back to you.  I'll keep this open until we come up with final decision.

**Comment by iqbalridha** [comment]
Well sir, it's very happy for me, if I can contribute to a better one.
It does not matter to me if you want to discuss, it is also an honor
for me. Thanks.

**Comment by digitalworkforcech** [comment]
I like it 👍

**Comment by Lablnet** [comment]
Grate logp

**Comment by iqbalridha** [comment]
Thank you

**Comment by revvin76** [comment]
Nice logo but needs tidying up before being considered.  If you look at the curves through the middle of the logo,  they aren't smooth. A little finesse needed to finish it off I believe.

**Comment by iqbalridha** [comment]
Thanks you, sir, i try to fix it.
Pada tanggal 23 Apr 2018 12.43 AM, "revvin76" <notifications@github.com>
menulis:

**Comment by revvin76** [comment]
you are welcome.  good luck :)

**Comment by iqbalridha** [comment]
This is a logo that I have fixed. How do you think sir. This is a png file
![ossn rev](https://user-images.githubusercontent.com/36046668/39255057-d0b2abdc-48d5-11e8-9c42-c223c5cad34e.png)

**Comment by revvin76** [comment]
looks better.  is it perfectly symmetrical?

I'm not part of the OSSN team by the way,  just offering some advice to
help improve your logo :)

**Comment by iqbalridha** [comment]
No problem, thanks for your advice. It is symmetrical

**Comment by lianglee** [comment]
We have save the logo in our repository and will use it in some areas.

**Comment by iqbalridha** [comment]
Thank you sir
Pada tanggal 30 Jun 2018 1.11 PM, "Arsalan Shah" <notifications@github.com>
menulis:

**Comment by iqbalridha** [comment]
Hai,

Saya baru saja menandatangani petisi "Rektor @undip Yos Johan Utama, bentuk
tim investigasi INDEPENDEN kasus pelecehan seksual di UNDIP." dan ingin
tahu apakah Anda dapat membantu dengan menambahkan nama Anda.

Tujuan kami adalah untuk mencapai 300.000 tanda tangan dan kami membutuhkan
dukungan lebih banyak. Anda dapat membaca lebih banyak petisi dan
menandatanganinya di sini:

http://chng.it/9zg78wrB74

Terima kasih!
Iqbal
