### ISSUE TITLE
Don't show images

### ISSUE THREAD

**Issue by Harichat** [opensource-socialnetwork/opensource-socialnetwork#1273]
My network don't show any image...from profile, publications, wall profile, anyone....
![captura](https://user-images.githubusercontent.com/37180662/37151079-69ad6598-22d4-11e8-9f17-ff7f9a73c222.JPG)

**Comment by lianglee** [comment]
Did you tried to upload photo? if so is your data directory is writeable? did you tried to upload image less then 500kb ?

**Comment by Harichat** [comment]
concretly wich directory i must check for the permission?.....

**Comment by Harichat** [comment]
can you say me the route?....

**Comment by Harichat** [comment]
as you can see here it have the 755 permission.... 
![captura](https://user-images.githubusercontent.com/37180662/37207269-869d7d82-239c-11e8-95ad-b98fddbd0453.JPG)
in the route:  mynet-ossncomponents-ossnphotos

**Comment by lianglee** [comment]
When you install the social network it ask you for the data directory path you can find that path in configurations/ossn.config.site.php

**Comment by Harichat** [comment]
ok...problem fixed.....Thanks for all LianGlee.....one more question, how can i edit the CSS of my net?....color of the top bar and left bar, etc....

**Comment by Lablnet** [comment]
For colors the component is available free of cost take a look
https://www.opensource-socialnetwork.org/component/view/2793/malik-color

**Comment by lianglee** [comment]
@Harichat  you can use the component mentioned above by Malik, if you wanted to edit theme you should see https://www.opensource-socialnetwork.org/wiki/view/1063/how-to-develop-a-new-theme
