### ISSUE TITLE
need update in invite system 

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1275]
email validation When enter email Hmmm@hmmm.com then click send its say 
Your friends were invited. Invites sent: 1.
And 
When i invite one friend with email lets someone@gmail.com if i or my other friend invite again why email send again it should be track  ( means store in db) then verify either invited by someone or not 
Thanks

**Comment by lianglee** [comment]
Hi Malik,  that is fine to send invitation by other users.

**Comment by Lablnet** [comment]
@lianglee  
what you say about
email validation When enter email Hmmm@hmmm.com then click send its say
Your friends were invited. Invites sent: 1.

**Comment by lianglee** [comment]
@Lablnet ,  Hi Malik,  i can see that the emails addresses are been validated before it send the invitation,  hmmm.com is considered as the valid domain name   If you visit http://hmmm.com/ it'll show you valid domain.

If you wanted to restrict domain name there need to be added a restriction for @gmail.com , @yahoo.com etc...

**Comment by Lablnet** [comment]
@liangee i understand

**Comment by Lablnet** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/pull/1279
