### ISSUE TITLE
Always Show Up Crash Windows If OSSN Installed on Xammp 5.6.34 / PHP 5.6.34

### ISSUE THREAD

**Issue by azzus78** [opensource-socialnetwork/opensource-socialnetwork#1281]
Hi guys,

I want to tested OSSN on my local computer before i used this great apps. 

I have done installed ossn on my local computer with 5.6.34 / PHP 5.6.34 and win 7 OS . There was nothing error happened 

After that  when I accessed ossn alyways popup error window confirmed error.

I copy paste what the error said 

> Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	httpd.exe
>   Application Version:	2.4.29.0
>   Application Timestamp:	5a002ba8
>   Fault Module Name:	php5ts.dll
>   Fault Module Version:	5.6.33.0
>   Fault Module Timestamp:	5a4d3ceb
>   Exception Code:	c00000fd
>   Exception Offset:	0012c2c0
>   OS Version:	6.1.7601.2.1.0.256.1
>   Locale ID:	1057
>   Additional Information 1:	d4eb
>   Additional Information 2:	d4eb7cf28a4f910486e91a11f70d294f
>   Additional Information 3:	0b64
>   Additional Information 4:	0b64bebe2b785d8a2eaa209c20ce8325

I watched the error at apache error.log too. 

> [Tue Mar 20 15:12:03.620761 2018] [mpm_winnt:notice] [pid 5596:tid 148] AH00428: Parent: child process 6116 exited with status 3221225725 -- Restarting.
[Tue Mar 20 15:12:04.052785 2018] [ssl:warn] [pid 5596:tid 148] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Mar 20 15:12:04.088787 2018] [mpm_winnt:notice] [pid 5596:tid 148] AH00455: Apache/2.4.29 (Win32) OpenSSL/1.0.2n PHP/5.6.33 configured -- resuming normal operations
[Tue Mar 20 15:12:04.088787 2018] [mpm_winnt:notice] [pid 5596:tid 148] AH00456: Apache Lounge VC11 Server built: Nov  6 2017 10:38:49
[Tue Mar 20 15:12:04.088787 2018] [core:notice] [pid 5596:tid 148] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Mar 20 15:12:04.140790 2018] [mpm_winnt:notice] [pid 5596:tid 148] AH00418: Parent: Created child process 5616
[Tue Mar 20 15:12:05.351860 2018] [ssl:warn] [pid 5616:tid 164] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Mar 20 15:12:05.577873 2018] [ssl:warn] [pid 5616:tid 164] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Mar 20 15:12:05.615875 2018] [mpm_winnt:notice] [pid 5616:tid 164] AH00354: Child: Starting 150 worker threads.

Any suggestion to solved this issue  or this apps isnt stable using Xammp ?

Thanks for the advanced

**Comment by githubertus** [comment]
1. Fault Module Name: php5ts.dll: This bugtracker wasn't meant for solving internal Xamp issues
2. Running Ossn on native Windows isn't supported anyway

For local testing, please make use of the virtual Ossn image https://www.opensource-socialnetwork.org/download-vm-image instead
