### ISSUE TITLE
OSSN message different values

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1282]
OSSN message different values in pupup and message area
see screenshort for more detail

![screenshot 122](https://user-images.githubusercontent.com/27757785/37830616-7f9da8ee-2ec4-11e8-9fc8-5a3a2ab7d567.png)

i send message but my messages not appear at all only friend msg appear in popup????

sorry to say i edit this pic for security rreason you can check yourself

**Comment by lianglee** [comment]
The messages that you receive are updated in popup this is not a bug as there is no such a feature in OssnChat to update sent messages

**Comment by Lablnet** [comment]
Thanks for reply 
So i think if you implement this feature seems to good
