### ISSUE TITLE
want to create a logo representing your project in the future

### ISSUE THREAD

**Issue by damahsyari** [opensource-socialnetwork/opensource-socialnetwork#1283]
Hello @ctlui and @lianglee  ,
I'm a graphic designer and i want your permission to design a logo and an icon for your application.
Best regards.

**Comment by lianglee** [comment]
Hi @damahsyari , Please contact us at https://www.softlab24.com/contact

**Comment by damahsyari** [comment]
ok thanks sir

**Comment by damahsyari** [comment]
hi sir.. this is my design logo for OSSN

I have asked permission to create a logo https://www.softlab24.com/contact

![1](https://user-images.githubusercontent.com/35051643/37943020-fbea92a8-319f-11e8-962e-5e7ea12d00a0.png)
![varian](https://user-images.githubusercontent.com/35051643/37943028-07a6753a-31a0-11e8-9062-1053dcab3b53.png)

**Comment by damahsyari** [comment]
![idea](https://user-images.githubusercontent.com/35051643/37957722-e05acb8c-31d8-11e8-990c-d53e467a0858.png)

**Comment by lianglee** [comment]
Hi , We will surely use the logo as icons (favicon or the ossn icon on other pages), Thank you for your efforts in making OSSN better!

**Comment by damahsyari** [comment]
You're welcome sir

**Comment by damahsyari** [comment]
my url, 

https://drive.google.com/drive/mobile/folders/11jztd1WA088-3HBc9nKSNfmxRVB2Zrqz

Thanks
Regards
damahsyari
