### ISSUE TITLE
How to stop email confirmation?

### ISSUE THREAD

**Issue by jonasess** [opensource-socialnetwork/opensource-socialnetwork#1285]
Can you please tell me which file and lines i have to deal with to stop email confirmation on sign up?

**Comment by githubertus** [comment]
Please note that Ossn's github page is meant for solving ISSUES - feature requests go to https://www.opensource-socialnetwork.org/community

Aside from that: Make friends with the available docs and components FIRST - and you'll find there's already an existing component doing right that located at https://www.opensource-socialnetwork.org/component/view/243/user-auto-validation
