### ISSUE TITLE
No Components in Admin

### ISSUE THREAD

**Issue by zimbert** [opensource-socialnetwork/opensource-socialnetwork#1286]
Hello 
there does not seem to be any way to add any components to my install of OSSN 
i have read your documentation.
https://www.opensource-socialnetwork.org/wiki/view/2006/how-to-install-components
but this does not help as there is noting that looks like that on my admin and there is no components tab anywhere on any menu.
I have downloaded a few free components that i would love to add like the video chat but there is no way to upload any component to the website and certainly not the way you show in the documentation.
Any help would be amazing 
thank you

**Comment by lianglee** [comment]
And you are using free version of OSSN?

**Comment by zimbert** [comment]
Hello yes does the free version not have any components ?
if that is the case i will have to look for another script
i have been trying for months to set up a social network for my community
it seems like it is impossible, this is a hippie commuity in the south of
Spain
so i don't have a lot of money to spend so i was trying to find something
open source
to be able to create a competent social network so people here can use it
and commnuncate
and learn about the community so they don't shit in the river or something
like that.

I have tried almost every social networking script out there i can not find
one that will
work as i need it or it is not possible to add anything to the scrip and WP
and buddypress
are no good for building social networks i have tried they are useless
I have been so very very frustrated trying to set up a social network for
beneficio-family.com
OSSN seemed like the best option and i was willing to spend a little money
to set it up
but i dont have hundreds as i amy using my disability money to do this
hence trying to do it
with on open source script.
but it looks like as i only have the free version i will never be able to
get a decent social network
up and running for this community.

it is a pitty as i really liked the set up.
I will have to find something else don't know what but i will have to find
something else
to be able to create a competent multilingual social network.

Thank you

**Comment by lianglee** [comment]
Can you share your website URL and the administrator details ? (you can send administrator login details at (arsalan@softlab24.com)

The component installer place is in administrator panel (yourwebstie.com/administrator)  in grey topbar there is a option components -> installer.

If you share your administrator details i shall take a look for you.

**Comment by zimbert** [comment]
Hello thank you
i did read your documentation
there was no such tab on any menu anywhere
I have deleted OSSN form my servers i will try something else that will
actually work.
i even got someone on fiverr to try and add a component they could not find
any
such options components -> installer anywhere on the OSSN
i therefore deleted it as it was impossible to build anything without
components.
i am now trying Elgg but i am not liking it at all
i really would have prefered OSSN but it does not have any way to add any
components
i have tried and so has a friend on fiverr there is no such componet teb
anywhere on any menu
on the site.

i have been trying for months to set up a social network but nothing works
as it should
and i am sick of scripts that do not work as they are advertised.

Thank you

**Comment by zimbert** [comment]
P.S.
well in the end i deleted everything from my domain again for the 23rd time
now
i really really wish i could find a scrip that would work.

**Comment by githubertus** [comment]
Well,
you've told us a lot so far - but which feature(s) exactly are you missing with Ossn?

**Comment by zimbert** [comment]
The Install components there is no such thing on any menu
I can not install any components or anything there is no import on any menu
anywhere on the site
i dont know how i can make it much clearer i can not install Anything
as there is NO WAY to install anything at all on amny menu
there is no text anywhere on the site that says install

i have given up for now i really have
i have been trying for moths to set up a social network
i think i will just forget about it as it is impossible to do
even when i pay people to do it , i have wasted so much money
on this it is not funny.
it has been a total waste of time and money the whole project.
hence trying to find something that will not cost me any more money
this it seems will never happen as there not a single script
that i have tried that will work.
i have even had people from fiverr trying to help me to no avail

all i want to do is create a simple social network with a chat but it
has not been possible.
i am so very very frustrated as i have been trying for months
and there is not a single script that will work with everything i
i need for my social network.

thank you

**Comment by githubertus** [comment]
> all i want to do is create a simple social network with a chat

Ossn HAS a chat included.
So, once again: What feature are you missing?

**Comment by zimbert** [comment]
Again
and i dont know how to put this in any plainer english
i do not have any way to add any components so
int the most plain english that i can
i do not have any install function at all

i can not explain it any more

i had someone from fiverr try and do it and they could not find any way
to install anyhting either
I CAN NOT INSTALL any componets
I CAN NOT INSTALL as there is NO INSTALL FEATURE

i can not put it any clearer.

Thank you

**Comment by githubertus** [comment]
So I ask it this way: What _component_ are you missing exactly?
You must miss something in Ossn, otherwise you would not ask for adding extras.

**Comment by zimbert** [comment]
Forget ti there is no way i will be able to expaln myself

**Comment by lianglee** [comment]
I am closing your issue as without knowing your website address we can not able to assist you. If you wanted us to solve your issue you need to follow what i said above ,  we'll require your site address with administrator login details.
