### ISSUE TITLE
.htaccess file is not working (gives a Internal Server Error)

### ISSUE THREAD

**Issue by dave90dave** [opensource-socialnetwork/opensource-socialnetwork#1292]
By my hostingprovider is the .htaccess file not working correctly, css is not loaded in, and gives a Internal Server Error, when I delete/edit the .htaccess it is being overwrited by a new one, so that makes the installation quite inpossible.

**Comment by lianglee** [comment]
There is no way to run the software without .htaccess file.    To edit the file you need to edit it in installation/configs/htaccess.dist
