### ISSUE TITLE
how i can add a small script in ossn ?

### ISSUE THREAD

**Issue by rayan709** [opensource-socialnetwork/opensource-socialnetwork#1293]
hi 
pls help me
i want to add this script to ossn
<script>
    $(document).ready(function(){ 
	$('body').find('img[src$="https://cdn.rawgit.com/000webhost/logo/e9bd13f7/footer-powered-by-000webhost-white2.png"]').remove();
    }); 
</script>

**Comment by lianglee** [comment]
Since you are using the free web hosting we do not support the removal of such a things which are imposed by someone terms.
