### ISSUE TITLE
add visibility of admin postings to friends-only wall?

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1294]
I think it makes sense to retrieve admin users first and add them to the friends array in OssnWall->getFriendsPosts() before doing the final search, because admin announcements should be visible unconditionally to everyone.

**Comment by lianglee** [comment]
Yes i agree with the point,   so we bascially need to run OssnUser->serachUsers('type=admin, page_limit=false) and then run through the loop to get user->guid
