### ISSUE TITLE
Some Iphone devices unable to post 

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1295]
Some Iphone devices unable to post only the wall post.

**Comment by githubertus** [comment]
Related links we should keep in mind:

https://www.opensource-socialnetwork.org/discussion/view/2947/mobile-apps-particularly-for-ios-working-theme-for-mobile

https://www.opensource-socialnetwork.org/component/view/2571/touchpunch

**Comment by lianglee** [comment]
Sure,  the last case i remember someone told me that when they post on wall post (on newsfeed page) the circle rotates and nothing happens.  I have no iphone to check and in safari windows its works good ,  also in ipad it works fine.
