### ISSUE TITLE
Blocked loading mixed active content on OSSN instance behind load balancer + SSL

### ISSUE THREAD

**Issue by Salbei** [opensource-socialnetwork/opensource-socialnetwork#1297]
Client connection to load balancer is secure by ssl.
Load balancer connection to ossn instance is unsecure.

OSSN generate absolute path with ssl detection but it doesn't with this configuration.

**Comment by lianglee** [comment]
OSSN have configuration file to set https from http,   it uses absolute path.   You can change the http to https in configuration/ossn.config.site.php

**Comment by Salbei** [comment]
@lianglee I already tried and It isn't working. It make infinite redirection.

**Comment by lianglee** [comment]
It is redirecting from https to http then http to https?  can you share your website URL ?

**Comment by lianglee** [comment]
can you also send us your configuration file ossn.config.site.php ?

**Comment by lianglee** [comment]
I tried to fetch your website headers and it shows you are using nignix server?

**Comment by Salbei** [comment]
my ossn.config.site.php contains:
`$Ossn->url = 'https://www.hub.incolab.fr/';
$Ossn->userdata = '/usr/local/www/ossn_data/';`

My load balancer is nginx but my ossn instance is behind apache 2.4.

Load balancer config file:
`server {
        # Redirection vers www + HTTPS
        listen 80;
        server_name hub.incolab.fr;
        return 301 https://www.$host$request_uri;
}

server {
        # Redirection vers HTTPS
        listen 80;
        server_name www.hub.incolab.fr;
        return 301 https://$host$request_uri;
}

server {
        # Redirection vers www
        listen 443;
        server_name hub.incolab.fr;
        ssl_certificate /path/to/fullchain.pem;
        ssl_certificate_key /path/to/privkey.pem;
        return 301 https://www.$host$request_uri;
}

server {
        listen 443 ssl;
        server_name www.hub.incolab.fr;
        ssl_certificate /path/to/fullchain.pem;
        ssl_certificate_key /path/to/privkey.pem;

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                #freebsd jail
                proxy_pass http://192.168.122.44:80;
        }
}
`

Instance virtualhost:
`<VirtualHost *:80>
    ServerName www.hub.incolab.fr
    DocumentRoot /usr/local/www/ossn/
    <Directory /usr/local/www/ossn/>
        Options Indexes FollowSymLinks
        Require all granted
        AllowOverride All
    </Directory>
</VirtualHost>`

**Comment by lianglee** [comment]
i suggest you to not to do any self redirection (by changing the ngnix or apache file)  the redirection will be made automatically by OSSN,  so i suggest you to remove self redirection code from ngnix and apache and try again.

Further :80 port is for http,  433 port is for SSL in apache!

**Comment by Salbei** [comment]
I know 443 is for ssl. I explain that in my first post. Connection from load balancer to ossn instance isn't secure (between two virtual machine).

I check your code and I saw it isn't made to be used with this configuration. (specially the  function ossn_site_url() used by the core system and for create assets path)

But thank for trying to help me ;)

**Comment by lianglee** [comment]
The redirection are made from following function , you should take a look :+1: 
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v5.x/libraries/ossn.lib.javascripts.php#L323-L361

**Comment by lianglee** [comment]
Further please make sure you must redirect users somehow to your https if you removed redirect_absolute_url,  because that was added to overcome some errors caused by http url. 
Your server must treat all requests as https
