### ISSUE TITLE
User blockage ain't working

### ISSUE THREAD

**Issue by Awais-cb** [opensource-socialnetwork/opensource-socialnetwork#1303]
user blockage only comes in action when we try to visit user's profile 
otherwise user is almost unblocked everywhere which seems strange very strange

**Comment by lianglee** [comment]
By blocking,  user should not send you message, views your photos,   visit profile etc.   What else it works?  However if you make public post it may appear

**Comment by xbansh33** [comment]
I think what @Awais-cb means is that blocked users can still view each other's posts on the news feed. I noticed this as well and implemented a manual fix as described here: https://www.opensource-socialnetwork.org/discussion/view/2872/anyone-made-a-block-user-component

**Comment by lianglee** [comment]
@xbansh33 you are right! 

Public posts can be still viewed.
