### ISSUE TITLE
Posting group photo does not work

### ISSUE THREAD

**Issue by laugustofrontend** [opensource-socialnetwork/opensource-socialnetwork#1306]
Posting group photo does not work

Good afternoon, I installed the project here on my machine to do some tests on it to see how the social network to behave, I ended up noting that the photo posting is not working in the groups, all other types of posting work less than the photo .

I tested in the main feed and there the photo post works

Would that be a bugs or the social network does not have support for post group photos yet?

**Comment by lianglee** [comment]
Photos should work in groups i'll check and revert back to you,

**Comment by laugustofrontend** [comment]
thank you very much

**Comment by lianglee** [comment]
Any Status for this or shall we close this? (please follow above guidelines mentioned by githubertus)
