### ISSUE TITLE
404 Error on various files after install.

### ISSUE THREAD

**Issue by theone85ca** [opensource-socialnetwork/opensource-socialnetwork#1308]
Hey All,

Does anyone have any idea on what's causing this? Clean install.

![404](https://user-images.githubusercontent.com/4998260/41624143-c036193c-73e2-11e8-898a-0156655996b2.png)
It's obviously causing the site to not work as well as CSS Styles to not load.

**Comment by lianglee** [comment]
Your apache .htaccess is not working contact your hosting provider to make sure your mod_rewrite is enabled in your account and make sure you have .htaccess file present in root of your website files.

**Comment by theone85ca** [comment]
It should be noted that both the .htaccess file was in place and mod_rewrite was enabled.

![htaccess](https://user-images.githubusercontent.com/4998260/41658242-c62e879e-7463-11e8-93e6-2fa1b7e9b052.png)
![mod_rewrite](https://user-images.githubusercontent.com/4998260/41658243-c6484922-7463-11e8-9cbc-95429c5108e1.png)

Fixing this issue in CentOS 7 requires you to enable writing to that .htaccess file inside of '/etc/httpd/conf/httpd.conf'

`. . .
<Directory /var/www/html>
. . .
 # 
 # AllowOverride controls what directives may be placed in .htaccess files.
 # It can be "All", "None", or any combination of the keywords:
 # Options FileInfo AuthConfig Limit
 #
 AllowOverride All
. . .
</Directory>
. . .`

By default, allow override is set to 'No'.

**Comment by lianglee** [comment]
It seems you are using vps,    is it working now with above settings?

In VPS enabling the mod_rewrite didn't simply solve the issue,  you have to follow the above mentioned in your comment.

```
<Directory "/var/www/html">
 AllowOverride All
</Directory>
```
