### ISSUE TITLE
Site has turned into blank page

### ISSUE THREAD

**Issue by SaintClairHyena** [opensource-socialnetwork/opensource-socialnetwork#1311]
My website has turned into a blank page and nobody is able to access it. Cannot access the administrator panel either. 
There are no errors on cpanel error logs and all files are where they should be. Website was working a few days ago and no changes have been made to cause this.

**Comment by lianglee** [comment]
Please provide us your website link so we can try to guess what is error

**Comment by Darkeen** [comment]
Disable cache at the `ossn_site_settings` table.

**Comment by lianglee** [comment]
^  as darkeen suggested,  it can be cache issue to but i can not guess exactly the issue without have website url.
