### ISSUE TITLE
Paste images into a post

### ISSUE THREAD

**Issue by cgubi** [opensource-socialnetwork/opensource-socialnetwork#1320]
To facilitate migration of users from commercial social networking platform to OSSN, it is important to provide users with an user experience that resembles as much as possible the one of traditional social networking sites. 

I tried to copy-paste images with CTRL-V into a post on OSSN Premium Version like I used to do in Facebook but this feature is not working, that's why I am suggesting to add it here.

**Comment by lianglee** [comment]
Closing as enhancements , it will be addressed in future!

**Comment by cgubi** [comment]
Where is the community? :-)
