### ISSUE TITLE
Link to single posts

### ISSUE THREAD

**Issue by cgubi** [opensource-socialnetwork/opensource-socialnetwork#1322]
Good Morning, it would be useful to have links to single posts to share specific content. They could be in the date of the post like we are used to know from commercial social networking platforms.

![image](https://user-images.githubusercontent.com/10544025/43460623-72419c00-94d1-11e8-9446-a0aec48a8243.png)

**Comment by lianglee** [comment]
Hi , do you mean when you click to timestamp it should show the entire wall post on separate page?

**Comment by cgubi** [comment]
Yes, indeed. When I was an active Facebook user I found that feature very useful to send links to friends pointing to specific contents... This is a graphic summary of the behaviour that I'd like to reproduce on OSSN.

![image](https://user-images.githubusercontent.com/10544025/43510182-19ba9100-9575-11e8-9b97-541cf4d7d033.png)

**Comment by lianglee** [comment]
Added to the next version, see the reference above
