### ISSUE TITLE
Tagging users in comments

### ISSUE THREAD

**Issue by cgubi** [opensource-socialnetwork/opensource-socialnetwork#1323]
Good Morning,

It should be useful to tag people in comments putting an at sign before their names to call them in the conversation. I'm afraid that with the current features of premium OSSN installations this is not possible.

**Comment by lianglee** [comment]
Very nice idea!

**Comment by cgubi** [comment]
So how does it work now? I am new to the github process, so I don't know how to proceed in order to transform this suggestion into a working feature of the software. Thanks in advance.

**Comment by lianglee** [comment]
It can take time for our team to decide if the feature can be created or can be implemented in current ossn or not. No action is required form your side :)

**Comment by lianglee** [comment]
Public Note:
Closing as enhancements , it will be addressed in future, its better to address discussion regarding enhancements on community. Since github issues tracking is for reporting bugs
