### ISSUE TITLE
Missing Features in mobile app

### ISSUE THREAD

**Issue by cgubi** [opensource-socialnetwork/opensource-socialnetwork#1324]
Good Morning, I just installed and tested the mobile app on Android Nougat device. These are the features I am missing:

I tried to make a post tagging some friends, the autocomplete is missing and even writing correctly the person name the tag didn't appear in the post.

Same thing happens when trying to create a geotagged post, I write the name of the city but then the geotag is not saved.

When I click on the friends requests icon and on the messages Icon i get a blank screen. It would be advisable to have messages like "no pending friends requests" or "message inbox is empty".

If you really want to challenge commercial social network you should focus on the user experience and involvement of users until you reach a critical mass of users that will make your software the new de facto standard. This means considering that with a mobile client people is expecting at least the following:

- push notifications
- the option to share items directly from image galleries without the need to open the app
- buttons to share content published in OSSN to commercial platform of social networking in order to derail users to OSSN with some bait links.

Grateful if you could consider to implement these feature in your mobile app, at least the first two which seems to me a pre-condition in order to grow the user base of our installation.

Regards.

**Comment by lianglee** [comment]
Do you referring softlab24 mobile app?

**Comment by lianglee** [comment]
All commercial features and mobile app issues must be discussed to softlab24 directly,  as both versions are managed by two different companies!
