### ISSUE TITLE
Link and video thumbnails not shown in mobile app

### ISSUE THREAD

**Issue by cgubi** [opensource-socialnetwork/opensource-socialnetwork#1325]
Good Morning,

Here is a post with a link to a website. When accessing OSSN to the browser we see a thumbnail fetched from the site. Unfortunately there is no "share" link available.

![image](https://user-images.githubusercontent.com/10544025/43523873-04cd167c-959e-11e8-9b1e-3ff9bb4c02d8.png)

This is the same post on the mobile app. No image is shown, and the "DISLIKE" button disappears:

![image](https://user-images.githubusercontent.com/10544025/43524011-68b00d3e-959e-11e8-8109-ff44b50c869f.png)

Here is a post with a link to a youtube video. When accessing OSSN to the browser we see a thumbnail of the video. For youtube videos the "share" link is available.

![image](https://user-images.githubusercontent.com/10544025/43526339-41238eca-95a4-11e8-9093-f58a6b212e7b.png)

But in the mobile app when I see the same post the thumbnail is gone, the "share" and "dislike" links are missing too, and we see only the link that CANNOT BE CLICKED to open the video, you can only copy it to paste into youtube app.

![image](https://user-images.githubusercontent.com/10544025/43526682-1bf2f9fa-95a5-11e8-8057-20268581fb32.png)

I think that showing graphic content and allowing people to click on links in posts and share any type of post could improve UX of your software. Please consider fixing these issues.

**Comment by lianglee** [comment]
Please describe if you are visiting ossn from mobile browser or you are asking about softlab24 app?

**Comment by cgubi** [comment]
There is a double problem. In the DESKTOP BROWSERS there are "SHARE" links missings on posts with text + link and in the MOBILE APP images are disappearing and links don't work. I already opened a tickst to softlab24 for the app part of the problem.

**Comment by lianglee** [comment]
The post with linkpreview can not be shared i believe. The share post works on normal posts

**Comment by cgubi** [comment]
What is so "abnormal" in a post that ends with a link? Why it should be unsharable?

If I do the same thing with a Youtube links the post becomes "normal" and sharable... there is some logic here that I cannot grasp.

**Comment by lianglee** [comment]
I am sorry here i can not guide you about share ,  since its not a part of free system core. The github repository is for reporting bugs to free system core only!

**Comment by lianglee** [comment]
When you post youtube link and it show you a video in post,  that post should be shared with standard share post component.
