### ISSUE TITLE
Persistent link in app

### ISSUE THREAD

**Issue by cgubi** [opensource-socialnetwork/opensource-socialnetwork#1326]
Each time i open the app I have to login again. This can be really discouraging and preventing people to switch from commercial platform of social networking to OSSN.

Please check if some mechanism of persistent link can be introduced to make the UX of OSSN Client as smooth as the one of other mobile client for popular social networking platform.

Maybe two optional checkboxes "remember my username" and "save my password" will be enough. Then it is up to me to decide if PIN or gesture protection is enough for my phone, leaving OSSN credentials to be stored for automagic login.

**Comment by lianglee** [comment]
All commercial features and mobile app issues must be discussed to softlab24 directly,  as both versions are managed by two different companies!
