### ISSUE TITLE
Login to Facebook with the ossn_token and valid OAuth redirect URIs

### ISSUE THREAD

**Issue by pruanl** [opensource-socialnetwork/opensource-socialnetwork#1327]
Good morning, I have a problem in the login Facebook via SDK, I'm using version 5.6 of the SDK and it was working, so I believe the problem is because of the valid OAuth redirect URIs.

The OSSN requests a ossn_ts and Ossn_token via get to enter can work the return that comes from Facebook, but Facebook wants that we inform the return URI on your dashboard, because this information is dynamics not possible access. 

Is there any way to get around this or even let optional the token check in a specific URI?

**Comment by lianglee** [comment]
You are using the social login component? https://www.softlab24.com/product/view/67/social-login

**Comment by pruanl** [comment]
I got this project in progress but I believe not, but the login was working and stopped shortly after facebook forced the return URI to be passed in advance by the panel, and as ossn sends dynamic data has no way to predict, I just wanted to validate the data no / action / fb-callback, but if it does not pass via URI the ossn_ts and ossn_token give error in ossn: securitytoken

**Comment by lianglee** [comment]
Please post it on our community website.

**Comment by pruanl** [comment]
The site is: https://petconnect.com.br/, when the button on facebook will get an error, the return is a url like this:

https://www.facebook.com/v2.2/dialog/oauth?client_id=207108586781720&state=a5be2285ad59563454fb9460770fb731&response_type=code&sdk=php-sdk-5.6.2&redirect_uri=https://petconnect.com.br/action/fb-callback?ossn_ts=1533658107&ossn_token=db7f9c7da68a9c13f8b3971488e392fc&scope=email

there is no way to know which redirect_uri the site will return to put in the facebook panel, if I remove ossn_ts and ossn_token goes normal, but the application returns me an error because it does not have the token, if I have to get around this check, I believe that will work

https://www.facebook.com/v2.2/dialog/oauth?client_id=207108586781720&state=a5be2285ad59563454fb9460770fb731&response_type=code&sdk=php-sdk-5.6.2&redirect_uri=https://petconnect.com.br/action/fb-callback&scope=email
