### ISSUE TITLE
issue running Ossn on docker container

### ISSUE THREAD

**Issue by ricogu** [opensource-socialnetwork/opensource-socialnetwork#1331]
I tried to run ossn in docker container with image php-apche 5.6

Everthing look fine except for posting photo. In my local host it works all fine. But in docker, it generate image in data directory with size 0 byte and therefore in site I am not able to see the photo I have uploaded

**Comment by ricogu** [comment]
Dockerfile:

FROM php:5.6-apache

COPY . /var/www/html/
RUN mkdir /var/www/ossn_data
RUN apt-get update -y && apt-get install -y libmcrypt-dev libpng-dev
RUN docker-php-ext-install mysqli gd zip mcrypt && docker-php-ext-enable mysqli mcrypt
RUN a2enmod rewrite
RUN chmod -R 777 /var/www/html/configurations
RUN service apache2 restart

**Comment by lianglee** [comment]
Did you tried to upload photo from other device,  did you tried to upload smaller photo like 500KB?
