### ISSUE TITLE
OSSN http 500 error

### ISSUE THREAD

**Issue by parallex12** [opensource-socialnetwork/opensource-socialnetwork#1334]
Hello Please guide me .. i have installed ossn in my website through cpanel .. now after two days .. it is displaying this error parallextech.theknowledgebeam.com is currently unable to handle this request.
HTTP ERROR 500 ... i have tried every thing .. Every time reinstall the ossn after sometime it shows this error please help

**Comment by lianglee** [comment]
This sounds like you are using it on shared hosting provider. And they limited your MySQL queries

**Comment by parallex12** [comment]
can you guide me what should I do?

**Comment by lianglee** [comment]
Change your hosting provider,  user VPS or a good hosting provider.
