### ISSUE TITLE
Admin panel not loading (local installation)

### ISSUE THREAD

**Issue by float1** [opensource-socialnetwork/opensource-socialnetwork#1335]
Installation went ok and when I log in with my admin data just message shows that I am logged in.
![deepin-screen-recorder_google-chrome-beta_20180922031130](https://user-images.githubusercontent.com/7194552/45911585-8cc34c00-be15-11e8-8023-37effccc7f98.gif)

**Comment by lianglee** [comment]
See the reply i posted on community,  as its seems you are using php 7.x
