### ISSUE TITLE
Unsatisfying behaviour with Autopagination and editing a post or comment

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1347]
5.0 RC1

Let's say my newsfeed has 3 pages and I had edited an older posting at offset=3.

Without autopagination, I get a complete reload of the page after saving, which isn't really nice already, but at least the former offset=3 is reloading and I will stay on the same page.

With autopagination switched on, the reload starts at offset=1 instead. So I don't see at once anymore what I just had edited, but I have to scroll down to offset=3 again. That's not very comfortable.

Hence it would be a big step ahead, if this editing stuff would be rewritten to be handled by Ajax with 5.0

**Comment by lianglee** [comment]
Well ignore my above reply as its become more hard for replies,  so i found a normal way...
