### ISSUE TITLE
wrong time shown when deleting a message

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1354]
A line like "Message was deleted 4 hours ago" 
displays the message _creation_ time instead of when the message has been _deleted_.

**Comment by lianglee** [comment]
Actually when the message appear that 'it was deleted'  we should hide the time!

**Comment by githubertus** [comment]
Yes, or change it to something like "Message from 4 hours ago was deleted" ...

**Comment by lianglee** [comment]
Followed first one : hiding time when deleted!
