### ISSUE TITLE
Adopt an OSI approved Open Source license

### ISSUE THREAD

**Issue by downeym** [opensource-socialnetwork/opensource-socialnetwork#1356]
It would be nice since this project is using the term "open source", if it accordingly used an official open source license approved by the Open Source Initiative. For more information, see https://opensource.org/licenses or https://choosealicense.com/. Personally I would recommend the AGPLv3 given its network-based operation, but the author(s) should review carefully before choosing.

Hope to see an OSI approved license soon so I can try out this software!

**Comment by lianglee** [comment]
Hi @downeym after all of the discussion with team we decided to use our own license. Which is combination of various open source license like MIT,  GPL etc....

We have own rules and regulations that customers need to met before using our software.   As the word open source its mean it should be human readable and can be modified.  We don't believe we have to follow OSI as they have own rules and regulations. 

OSI is just a organization,  the license approved by them are written by different companies. Like MIT (The MIT License originating at the Massachusetts Institute of Technology)

**Comment by downeym** [comment]
It's unfortunate that "the team" thinks that way. It is certainly not aligned with the thinking of the general open source community.

OSI invented the term "open source" and is universally regarded as its steward. Its license approval is undertaken by the best open source legal minds, and that approval gives the peace of mind for organizations small and large to use open source licensed software with confidence.

The "problems" with your license is that, in your own words, you've combined legal aspects of multiple different licenses that are not designed to be compatible.

See https://anonymoushash.vmbrasseur.com/2018/04/09/do-i-have-to-use-an-free-open-source-license/ for details. I hope you'll reconsider, for the prospects of long-term adoption of your work!

**Comment by ericschultz** [comment]
Please just call it something else. The OSI is who we look to agreement as a community on what is or isn't open source. Your license is not approved and I have strong doubts whether it's open source compatible. More importantly, it's confusingly written.

**Comment by lianglee** [comment]
We are not going to change the license for already existing license,  as mentioned these license are written by the people doesn't mean everyone must use it.  

@ericschultz  perhaps you can send us what is confusing then we can help you understanding,  or perhaps you can send us a pull request with some modifications that you wanted to improve in wording.

@downeym you are right,  everyone have different thinking.  However as mentioned what is exactly you wanted to change in license and what is exactly is wrong ? perhaps you can help is to make it more better version of license.

Please let us know what is exactly in the existing license should be changed or to be improved for more readable form.

The licenses already written are too big for the normal user to read,  many of just ignore it and start using software,  our goal was to rollup a custom,  our own license with less number of pages, so a normal person can read it at least.

**Comment by lianglee** [comment]
@ericschultz,

Thank you for the feedback,  we'll matter regarding the section 2.2 its already in discussion,  we are removing the 'You need to take permission/authorization from us, in case of selling.' as they allowed to re-sell it keeping the copyrights,   notices, powered by etc.

**Comment by downeym** [comment]
I can't speak for @ericschultz but "bespoke" (project-specific) licenses don't do anything to make licensing easier. Rather, they make it more difficult for mere humans to understand. Why?

Organizations like OSI are volunteer-run groups of industry leaders, including lawyers and other experts, who come together to create standards for licensing that companies and humans can understand. "Open source" already has a definition agreed to by your industry of peers -- that definition is maintained at https://opensource.org/osd. This standardization allows web sites like https://tldrlegal.com/ to exist -- because the software industry has settled on a variety of standard licenses, a site like this can become expert in the various licenses and explain them to regular humans. Meanwhile, legal experts at organizations who would use "Software X" can adopt that program because they are confident in what the license allows and doesn't allow -- they don't have to become expert in Yet Another License.

A "better version" of the license going forward would be adopting an industry standard rather than continuing with a custom "hodgepodge" of language that you like, that is not necessarily compatible with any other licensed open source software out there.

**Comment by lianglee** [comment]
@downeym,  thank you for sharing your experience we'll be looking into it and will let you know about updates.

**Comment by lianglee** [comment]
The license that suites i believe is Attribution Assurance License but we are still looking forward for additional OSI approved licenses

**Comment by lianglee** [comment]
License is changed to months ago to : https://opensource.org/licenses/CAL-1.0 FYI
