### ISSUE TITLE
concerns about new ['options']['offset_name'] feature and autopagination

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1364]
I mean, it's supposed to fail with the currently hardcoded
`$offset = Ossn.AutoPaginationURLparam('offset', $url);` in OssnAutoPagination
if someone is really making use of that option.
Actually I have no idea how to make the Javascript part aware that a custom string is in use...

except we had a smarter URL parser to recognize what instead of 'offset' was used

**Comment by lianglee** [comment]
OssnAutoPagination is actually now for pre-defined pagination like newsfeed, users profile and groups all these are only for wall posts.  

So we know that these pages using the pagination with 'offset' if they changing 'offset' to something else this requires changes in $offset = Ossn.AutoPaginationURLparam(...).

Now ['options']['offset_name'] we are using in OssnMessages and OssnChat,  we know that these have different keyword than 'offset'  so we are using the exact keyword in OssnMessages and OssnChat.js

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v5.x/components/OssnMessages/plugins/default/js/OssnMessages.php#L138
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v5.x/components/OssnMessages/plugins/default/messages/pages/view/recent.php#L39

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v5.x/components/OssnMessages/plugins/default/js/OssnMessages.php#L221

So the name used in '['options']['offset_name']' must be same in  `Ossn.AutoPaginationURLparam('<name>',...)`

**Comment by githubertus** [comment]
> OssnAutoPagination is actually now for pre-defined pagination like newsfeed, users profile and groups all these are only for wall posts.

Ah, then it's okay. :)
