### ISSUE TITLE
You don;t have permission to access

### ISSUE THREAD

**Issue by middj2008** [opensource-socialnetwork/opensource-socialnetwork#1365]
You don't have permission to access /installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/:///installation/ on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

Have as well message my hosting company and they told me the issue is with the script

**Comment by githubertus** [comment]
make sure to install Ossn in a clean directory and there's no old .htaccess file lying around
in case you installed Ossn in a subdirectory, parent .htaccess files may have an unwanted influence,
so create a sub-domain pointing directly to your Ossn installation.
You may use the verifyperms.php tool which is part of https://www.opensource-socialnetwork.org/component/view/1963/system-info to check your installation.

**Comment by middj2008** [comment]
Like seriously i don't understand the clean directory order than the public_html/ where i unzipped the file already create the database and i have seen the installation where to insert the database credentials, have done all that before i ran into that You don't have permission to access n/:///installation/:///installation/:///installation/ on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
Please help to break it down

**Comment by middj2008** [comment]
helle
