### ISSUE TITLE
Profile and posts are publicly viewable to people not logged in

### ISSUE THREAD

**Issue by DanAugust** [opensource-socialnetwork/opensource-socialnetwork#1366]
When people browse to https://mydomain.com/u/userprofile, they can see the entire profile and all the posts of that person even when not logged in. I don't think this is supposed to work this way. Am I mistaken? Do I need to change a setting someplace?

**Comment by lianglee** [comment]
You that is correct they can see but can't reply / like any post or comment. Perhaps you should see : https://www.opensource-socialnetwork.org/component/view/1564/private-network

**Comment by lianglee** [comment]
Also please see : https://www.opensource-socialnetwork.org/discussion/view/3142/profiles-and-posts-publicly-viewable-from-non-logged-in-internet-viewers
