### ISSUE TITLE
Issues with the email verification message in my email

### ISSUE THREAD

**Issue by middj2008** [opensource-socialnetwork/opensource-socialnetwork#1367]
on a test run after registering a user, redirect page says:
Your account has been registered! We have sent you an account activation email. If you didn't receive the email, please check your spam/junk folder
Yet i can't find any email from my inbox, spam or junk to verify

Any help

**Comment by lianglee** [comment]
It seems the issue is with your hosting provider ask them if they using special email server?  ask them if php mail or the sendmail is enabled on your account? further ask them about SMTP
