### ISSUE TITLE
OSSN administrator login doesn't show any menu

### ISSUE THREAD

**Issue by ramatius** [opensource-socialnetwork/opensource-socialnetwork#1368]
Hi,
I've installed OSSN in our server - quantindia.in/ossn/ . There were no errors during installation. When I try logging in as admin through quantindia.in/ossn/administrator it says "You are now logged in!" but stays in the same login page. There is no admin panel shown. Also, I created a user, but it is not logging in with correct passwd either. Pls advise. 

It is a ubuntu 16 server with apache2, OSSN version 4.6, php 7.2.11

**Comment by githubertus** [comment]
That's a known  issue related to current Ossn version and PHP 7.2. It will be fixed with upcoming Ossn release 5.0.

To apply the smalll fix yourself in advance, please read
https://www.opensource-socialnetwork.org/discussion/view/3075/admin-panel-not-loading-local-installation

**Comment by ramatius** [comment]
That worked. Thanks for the reply.
