### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Tyranwyn** [opensource-socialnetwork/opensource-socialnetwork#1370]
I am creating a Dockerfile and docker-compose.yml file to easily set up ossn with Docker. I am cloning tag 4.6 and I've run into some problems. At this point it almost works, but when I try to log in, ossn doesn't redirect me. It just reloads the login page or administrator login page with the message that I've been logged in.

If you would like to take a look at the config:
https://gist.github.com/Tyranwyn/8762f168861991ed8b51bca3db3115b1

**Comment by githubertus** [comment]
very likely for the same reason as reported here:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/1368

for testing purposes use the current snapshot - it's thoroughly tested and really stable

**Comment by Tyranwyn** [comment]
ah i see, my bad.

**Comment by Tyranwyn** [comment]
Ok so now I have an issue because I'm behind an nginx reverse proxy. If I configure https in the ossn.config.site.php then it shows me ERR_TOO_MANY_REDIRECTS. But that problem I also had with the previous version.

This is my nginx config for ossn:
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server {
  listen 80;
  listen [::]:80;
  server_name *****.*****;
  # Useful for Let's Encrypt
  location /.well-known/acme-challenge/ { allow all; }
  location / { return 301 https://$host$request_uri; }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name *****.*****;

  ssl_protocols TLSv1.2;
  ssl_ciphers HIGH:!MEDIUM:!LOW:!aNULL:!NULL:!SHA;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;

  ssl_certificate     /etc/letsencrypt/live/*****.*****/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/*****.*****/privkey.pem;

  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 80m;

  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  add_header Strict-Transport-Security "max-age=31536000";

  location / {
    try_files $uri @proxy;
  }

  location @proxy {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";
    proxy_pass_header Server;


    proxy_pass http://127.0.0.1:8080;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    tcp_nodelay on;
  }

  error_page 500 501 502 503 504 /500.html;
}
```
I got this configuration from setting up mastodon, and i modified it but I'm not an expert on the reverse proxy thing.

**Comment by lianglee** [comment]
@Tyranwyn we actually didn't support Ngnix,  however if you find a good configurations for it , it would be much appreciated if you post working ngnix configurations here.

Further:   

`$Ossn->url = $_ENV["SITE_PROTOCOL"] . '://' . $_ENV["SITE_DOMAIN"]`
The OSSN url must be like `https://yourwebsite.com/`  the ending slash is important,  i am not sure if it is covered by ` $_ENV["SITE_DOMAIN"]`

**Comment by lianglee** [comment]
Further there are tools available that can convert apache configurations to ngnix.

**Comment by Tyranwyn** [comment]
I'm pretty sure my configuration is decent, the problem is the way site is programmed doesn't know how to handle a reverse proxy.

Nginx says that the forwarded protocol is https so I added:
```
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
        $_SERVER['HTTPS'] = 'on';
    }
```
to libraries/ossn.lib.javascripts.php

This solves the endless redirects but now the site is just empty... unless I go to the installation endpoint, but that's not the intention.

**Comment by lianglee** [comment]
The empty site means something is not loading (white page)

**Comment by lianglee** [comment]
Hi, did you succeed in installation using docker?
