### ISSUE TITLE
Smiley and camera icon uncovered by notification window

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1372]
![comment-attach-zindex](https://user-images.githubusercontent.com/9904364/47742494-0fdd8a80-dc7d-11e8-8b81-ae5191b6b94b.png)

I'm just wondering whether their was any special reason to add z-index: 2
to ` .ossn-comment-attach-photo ` 
because it results in the effect shown on the screenshot. 
Maybe it was necessary in the past with old themes ?! Anyway: I just verified it's not necessary with Goblue and Social, thus to my opnion it can be removed from **OssnComments** and **OssnSmilies** css.

**Comment by lianglee** [comment]
agree it was basically for old theme,  we can remove that

**Comment by githubertus** [comment]
fixed with #1378 and #1379
