### ISSUE TITLE
Facebook Page Feaure

### ISSUE THREAD

**Issue by DemonRem** [opensource-socialnetwork/opensource-socialnetwork#1376]
I wonder if it's possible to add a feature to the project like facebook have

It's called facebook page for 1 for bussnins and another one that I don't remember

**Comment by githubertus** [comment]
I'm afraid it'll be difficult to add a feature you don't even remember - but we'll try.
As for the business page: It's already available at https://www.softlab24.com/product/view/338/fan-and-business-pages
