### ISSUE TITLE
No theme applied on fresh install

### ISSUE THREAD

**Issue by nirvana74v** [opensource-socialnetwork/opensource-socialnetwork#1386]
Just installed OSSN for evaluation on our server, and looks like theme isn't applied on the app though it shows goblue theme as selected in administrator themes

![ossn_bug](https://user-images.githubusercontent.com/4522114/47953705-4c73f380-dfa7-11e8-8605-95ea54883219.jpeg)

Does it need something else to be done in order to make it work?

**Comment by nirvana74v** [comment]
Just found that all my css automatically are add with "cache/js/1541256663/view/" after site url for loading css

**Comment by nirvana74v** [comment]
I had to disable cache to get the theme working. I think this is a bug.

**Comment by lianglee** [comment]
This isnt bug but your server is not allowing to create cache,  you don't have correct permission on software files.

**Comment by amaroc** [comment]
> This isnt bug but your server is not allowing to create cache, you don't have correct permission on software files.

Hello! I have same problem (like in first image in this issue), i disabled cache, but it cant help me.
I have installed ubuntu 16, apache, nginx (like proxy), i have mode rewrite 
a2enmod rewrite
Module rewrite already enabled

i even manualy copy .httaccess.dist to  root of ossn as .htaccess
But nothing help me. So i delete ossn from server, i think many people do the same. 

It would be nice to make a more better Instruction how to install this product on site.
1. Where to place osn-data in right place for e.g. /home/osn-data ?
2. Which files need to be CHMOD`ed  
3. What we need to do with .htaccess 
... etc.
