### ISSUE TITLE
possible wrong sequence in message window

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1393]
Let's assume we have 20 messages in our inbox, message page just loaded and still not scrolled.
Thus our starting point is:

Page 1 [ 20 -> 11] already visible
Page 2 [ 10 -> 01] <-- next page pointer (yet not loaded)

Now, our chat partner sends 5 new messages, and we see
Page 1 [25 -> 11] 
but the database pagination view will change like
Page 1 [ 25 -> 16] 
Page 2 [ 15 -> 06] <-- next page pointer
Page 3 [ 05 -> 01]

Since the addressed records of our next page pointer have changed, scrolling to Page 2 in this case will 
result in a view like
[25 -> 11] + [ 15 -> 06] 
= message 15 to 11 shown twice :(

Honestly, I don't have no idea how to take care about it with a quick fix, because this would need unique selectors for each message to make jquery remove duplicates.

**Comment by lianglee** [comment]
The easy solution i think is :  
1. Each messages have the unique id.
2. When loading new messages (new messages via ajax)  we remove the duplicate ids first.
3. Sort message by ID (ASC/DESC)

**Comment by githubertus** [comment]
fixed by #1394 to #1397
