### ISSUE TITLE
issues with ossn-viewer-comments

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1411]
yesterday I verified what happens if you click the large user avatar on a profile page and became aware of several issues:
1. the camera icon isn't in line with the comment input field
2. the position of the 'smiley' icon (which is thought to appear next to the camera) is out of reach somewhere right in the darkened area
Basically, this could be fixed by changing some 'ossn-viewer-comments' styles. But these styles appear to be spreaded across OssnComments AND OssnPhotos which isn't really clean, too.
3. Next, you will run out of luck if that photo has a lot of comments already, as the input field is out of view. So it would need a defined max-height of that comment box plus overflow-y: scroll

Having applied all this in the end you'll find out: The whole viewer is not responsive and unusable on small devices.
Hence, instead of spending time on making it responsive, my idea was a completely different approach by replacing the Onclick->open viewer by a href leading to the user's Profile Photos albumg like `ossn_site_url()/photos/view/ID_OF_CURRENT_PROFILE_PIC`

To get an idea: I've implemented it like that on 5b now ...

**Comment by lianglee** [comment]
You are right. No need of viewer we can simply redirect to photo page
