### ISSUE TITLE
missing logic for not required fields on registration form

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1421]
I was trying to add a 'not required' field to the registration form manually which was in fact member of the 'non_required' userfields array. But that's of no influcence - I can't submit the form with this field left empty.

Having a closer look into the javascript core lib, I found that there's simply no code to handle these kind of fields: if the value is empty, there's no way out.

Finally I verified, whether the customFields component has a special workaround, but same problem: not required fields on registration page don't work.

So we need some convention how to stop the script from validating these fields ... maybe by adding an extra class ... whatever?

**Comment by lianglee** [comment]
That seems a bug with checking (js) we should add a option to ignore warning for non_required fields. A class to <div field calss='no-required' is good approach.
