### ISSUE TITLE
No images after fressh install + Mod Rewrite

### ISSUE THREAD

**Issue by amaroc** [opensource-socialnetwork/opensource-socialnetwork#1424]
What i have:
Ubuntu 16, apache2, nginx as proxi.

![image](https://user-images.githubusercontent.com/4218383/49847148-b621c180-fddf-11e8-9b2e-e260ba4539f1.png)

What i do?
git clone https://github.com/opensource-socialnetwork/opensource-socialnetwork
chown -R www-data:www-data ossn_data/
chown -R www-data opensource-socialnetwork/
chmod +777 ossn_data/
chmod +777 configurations/
cp installation/configs/htaccess.dist /var/www/html/social/opensource-socialnetwork/.htaccess

When i tried install i got warning\error that mod rewrite needed. But it works
![image](https://user-images.githubusercontent.com/4218383/49847257-3e07cb80-fde0-11e8-8b04-63ede787a5d1.png)

I even tried aply another thems, download it and upload by admin panel, aply it but same result.

Where i wrong?

**Comment by lianglee** [comment]
Well that make sense now we have no where said in requirements that you
need ngnix...

You should see
https://websiteforstudents.com/install-opensource-social-network-on-ubuntu-16-04-17-10-18-04-with-apache2-mariadb-and-php-7-1/

And
https://www.opensource-socialnetwork.org/wiki/view/706/how-to-install-open-source-social-network
