### ISSUE TITLE
issue with components/OssnMessages/plugins/default/forms/OssnMessages/send.php

### ISSUE THREAD

**Issue by xbansh33** [opensource-socialnetwork/opensource-socialnetwork#1427]
if the textarea (name="message") is left blank, and the "Send" button is clicked, a "0" is appended to the bottom of the message display area. See attached screenshot. In fact, if you click "Send" more than once and the textarea message is left blank, a "0" is appended EACH time Send is clicked (hence the two 0s in the screenshot). This bug is easily fixed (at least for html5 browsers) by adding a "required" attribute to the textarea element in question. 
![ossn_messages_page_bug](https://user-images.githubusercontent.com/5515614/50084922-2fddf480-01be-11e9-8e47-314579c76ff3.jpg)

**Comment by lianglee** [comment]
Hi, can you confirm if this exists in v5.0 ?
