### ISSUE TITLE
Why OSSN use md5 hash for generating password

### ISSUE THREAD

**Issue by Lablnet** [opensource-socialnetwork/opensource-socialnetwork#1438]
Why OSSN use md5 for generating/hashing password ?
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v5.x/classes/OssnUser.php#L254

http://php.net/manual/en/function.md5.php
According to PHP MENU => http://php.net/manual/en/faq.passwords.php#faq.passwords.fasthash
"Hashing algorithms such as MD5, SHA1 and SHA256 are designed to be very fast and efficient. With modern techniques and computer equipment, it has become trivial to "brute force" the output of these algorithms, in order to determine the original input.
Because of how quickly a modern computer can "reverse" these hashing algorithms, many security professionals strongly suggest against their use for password hashing.
"

what about to use password_hash() php function => http://php.net/manual/en/function.password-hash.php

**Comment by lianglee** [comment]
We are not using simple md5, further when someone get access to your database, he get most of the things he wanted, he won't worry about these passwords.

@Lablnet , Malik tell us why you are chasing our customers using ossn saying its not worth it? We go many complains about you from our customers.

**Comment by Lablnet** [comment]
Ah, yes but i still it vulnerable if you compare with it password functions

**Malik tell us why you are chasing our customers using ossn?**

If someone ask me to advice then i advice him (with proofs) because i have two years of experience in  modern development and i am connected with ossn , No doubt OSSN is powerful and i love thier components structure and working but if you compare it with others like WoWonder then you can realize the truth.

As far as there are many social networks available for php so there should be a solid purpose why OSSN in place?

On the other hand i already knows about ossn premium components and Mobile Applications mostly based on *YOUR CLOUD* so in case every data first come to your CLOUD server then send response back to customer website in this case it has two disadvantage 
1. It make website slightly slow and app also (compare with native or hybrid app)
![screenshot 33](https://user-images.githubusercontent.com/27757785/50804479-eb063300-130f-11e9-827a-e5ca974f795a.png)
2. Might be you used or sell customers data?
At last i remember your email where you says ** We use technical code to detect where OSSN is installed** 
i dont see this in your terms i dont know  why you cant got banned form Europeans countries might be its recommendation.

If you're not liar you see i provide details with proof 
Thanks for understanding

**Comment by lianglee** [comment]
As mentioned if someone have access to your so called weak database,  he can do shit out of it , you won't imagine. Password functions are still a hash. You just follow communist , who just try to destroy the industry and hides the actual things. 

1, I don't confirm the integrity of the image you post, it can be fake! as according to the email terms mentioned in each email, you can not share these confidential emails and it didn't have your name on it.
2. Its maybe time for your to open your eyes and look into the terms page carefully.

In the end you mean, 'If Malik is not a  liar.../'.. , yes you are not a liar but you are just stubborn child and before i stop replying to your silly reasons i ask you to think before replying and do experiments yourself before reading on internet what is insecure and what is secure.
