### ISSUE TITLE
everything creatable should be deletable

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#144]
Starting with the user who should be able to leave the community and delete his profile, other currently not deletable items are:
- cover photo => done [edited:$arsalanshah]
- photo albums
- messages
- groups
- group cover photo
... and maybe more ...
--------------------------------
ossn 2.0-dev (Dec 20 release)

**Comment by lianglee** [comment]
You are right

**Comment by lianglee** [comment]
cover photo is now delete able

**Comment by huckleberrypie** [comment]
Looking forward to the editable albums functionality too. +1

**Comment by lianglee** [comment]
you can now delete photo ablum

**Comment by lianglee** [comment]
(closing ticket too many tasks in one ticket)
