### ISSUE TITLE
Are you guys considering k8s? (No issues)

### ISSUE THREAD

**Issue by Jagermeister56** [opensource-socialnetwork/opensource-socialnetwork#1440]
any consideration for kubernetes? 
I know i'll be buying the premium package as well as almost all the plugins, love the work so far!

**Comment by githubertus** [comment]
see #1238

**Comment by Jagermeister56** [comment]
don't get your point.

**Comment by softlab24** [comment]
See the https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/1238

**Comment by lianglee** [comment]
You need to click above issue number it will take to you to other page.
