### ISSUE TITLE
Is it possible to deploy in Heroku?

### ISSUE THREAD

**Issue by joismar** [opensource-socialnetwork/opensource-socialnetwork#1441]

**Comment by githubertus** [comment]
Ossn's pre-requisites are documented in https://www.opensource-socialnetwork.org/wiki/view/706/how-to-install-open-source-social-network
Actually we're no Heroku experts, but if these services are available in Heroku I don't see any reason why deployment should fail.

**Comment by joismar** [comment]
I tried, I had to adapt the composer in the project to initialize some PHP settings. However, I could not configure the database because the database must have been created before. I have not found a way to do that yet.

**Comment by githubertus** [comment]
Usually Ossn admins are creating the database from a Web based frontend like PHPMyAdmin or something similar. But of course you may do it from the Unix command-line, too. And I doubt that there's no such interface in your environment. But as I said: We're no Heroku experts and I think these kind of questions better belong to a dedicated Heroku forum.
