### ISSUE TITLE
Blank page . 

### ISSUE THREAD

**Issue by hallucinik** [opensource-socialnetwork/opensource-socialnetwork#1444]
Hi, 
I tried to modify .htaccess for upload .  now i have  blank page and .htaccess is my old version. 
https://le-desobeissant.fr

in my error_log 

[06-Feb-2019 00:28:44 Europe/Paris] Error: Call to undefined function ossn_profile_subpage() in ~/.../mysite/components/OssnPhotos/ossn_com.php:59
Stack trace:
#0 ~/.../mysite/libraries/ossn.lib.system.php(258): ossn_photos_initialize('ossn', 'init', NULL)
#1 ~/.../mysite/system/start.php(39): ossn_trigger_callback('ossn', 'init')
#2 ~/.../mysite/index.php(12): require_once('~/my...')
#3 {main} 

cache in ossn_site_settings :  0 

I used a backup , but now i have only a list of emoticons on right of the site .

**Comment by lianglee** [comment]
The error is clear, not all files are uploaded, you have missing the libraries.  Your OssnProfile is disabled, please enable it
