### ISSUE TITLE
component installer needs better checking on already existing components

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1447]
It just happened that someone created a zip archive by mistake containing an already installed component (in this case OssnSearch).

- Unpacking of the subdirectories failed correctly (Diretory not empty)
- but original com and xml file got overwritten!

Aside from that: No error message on uploading - just the green "You can enable ..."

**Comment by lianglee** [comment]
agree, was thinking this too.

**Comment by githubertus** [comment]
fixed by #1448
