### ISSUE TITLE
MOD_REWRITE REQUIRED

### ISSUE THREAD

**Issue by Sankumar2368** [opensource-socialnetwork/opensource-socialnetwork#1452]
Hy
When i was trying to install OSSN on website with https was asking for mod_rewrite required and after removing ssl from website i was able to install it. But now i want to enable ssl on website. Then website redirecting so many times.
Help me
Waiting for positive and quick reply.

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/wiki/view/2671/how-to-enable-httpsssl-on-ossn
