### ISSUE TITLE
Posts having friends privacy are visible to public using direct URL

### ISSUE THREAD

**Issue by JelmerNB** [opensource-socialnetwork/opensource-socialnetwork#1484]
If you set all posts on private... (only visible for friends), still everybody can see the content when clicking on the link if the link has been shared on another social media site. Even when you logged out, you can still see the private post of a member.

Sample link: 
1. /post/view/4#comments-item-2
2. /post/view/422

Photo of a private post (logged out)
https://www.handola.nl/wp-content/uploads/2019/07/nb-private-settings-still-visable.png

How can we fix this?

Kind Regards 
Jelmer

******************************
Answer to:
Hello There,

It looks like a bug, can you report here please: http://github.com/opensource-socialnetwork/opensource-socialnetwork/issues

Thanks

Regards
Arsalan Shah | Chief Technology Officer

**Comment by lianglee** [comment]
Fixed
