### ISSUE TITLE
Change cover and reposition btn won't appear on small devices

### ISSUE THREAD

**Issue by andyroblesr** [opensource-socialnetwork/opensource-socialnetwork#1485]
Change cover and reposition btn won't appear on small devices.

![image](https://user-images.githubusercontent.com/18501682/61496945-dde79200-a98b-11e9-85a8-ed11667fb90d.png)

I check your other issues.. also tried changing btn size, to make space and make them fit on the cover container, but they won't appear..  also i tried with component TouchPunch, and didn't work neither: https://www.opensource-socialnetwork.org/component/view/2571/touchpunch

plz help

**Comment by lianglee** [comment]
@githubertus  can you help here a bit?

**Comment by githubertus** [comment]
I think I got it working (check Skype)

**Comment by githubertus** [comment]
Issue has been fix by #1488 to #1493 
and will be available with Ossn 5.2

**Comment by lianglee** [comment]
Thanks @githubertus
