### ISSUE TITLE
Fehlende Installationsvoraussetzung bei Stratohosting

### ISSUE THREAD

**Issue by dejosch** [opensource-socialnetwork/opensource-socialnetwork#1494]
Guten Tag,
es kommt bei Strato, bevor die Installation überhaupt erst startet, folgende Meldung.
Installationsvoraussetzung  Apache, PHP_SAPI, (cgi-fcgi).
Ich kann das Problem nicht lösen.
Können sie mir behilflich sein?
![ossn_intallationsfehler](https://user-images.githubusercontent.com/52787911/62545707-e5070f00-b86a-11e9-894c-51e7f3401c42.png)

**Comment by githubertus** [comment]
Get yourself the latest installer archive from
https://www.opensource-socialnetwork.org/download
