### ISSUE TITLE
Blank page after applying new language

### ISSUE THREAD

**Issue by domino4evers** [opensource-socialnetwork/opensource-socialnetwork#1497]
Hi there

I have tried to make a copy of the ossn.de.php - to ossn.da.php.

Changing the $de to $da and the last lines:
ossnregisterlanguages('de', $de); to ossnregisterlanguages('da', $da);

Now wy site is just blank, until I change it back to en.

**Comment by githubertus** [comment]
Yeah, you posted that already in the forum and I asked you to look into your error_log file and/or provide more details as requested in https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error.

Simply posting the same problem twice doesn't really help - a little more co-operation is very much appreciated.

**Comment by domino4evers** [comment]
Anymore info you need?

I am trying to make a danish translation.

**Comment by lianglee** [comment]
Please follow the above link of how to report bug it requires few information and provide that.

**Comment by domino4evers** [comment]
**URL: http://webzer.dk**
**Brower: Firefox and Chrome.**

[Link to my Danish Translation in txt format](http://webzer.dk/ossn.da.txt)


**System info:**
Ossn System Info 1.8
Server Environment
Operating System	Linux cp01.resellerhotel.dk 3.10.0-962.3.2.lve1.5.24.6.el7.x86_64 #1 SMP Tue Dec 4 03:50:32 EST 2018 x86_64
PHP Environment
Version	7.1.30
Server APi	litespeed
display_errors	off
 	
memory_limit	128M
register_globals	
post_max_size	8388608
upload_max_filesize	5242880
default_charset	UTF-8
MySQL Environment
Server Info	5.5.5-10.2.26-MariaDB-cll-lve
Host Info	Localhost via UNIX socket
Protocol Version	10
Ossn DataBase Size	66812 bytes
Ossn Environment
Version	5.0
Site URL	http://webzer.dk/
Install Dir	/home/webzer/public_html/
Install Dir Owner(Id) [Perms]	webzer [0750]
Data Dir	/home/webzer/ossn_data/
Data Dir Owner(Id) [Perms]	webzer [0777]
Data Dir Size	2980682 bytes
Site Notification Email	kim@fricomputer.dk
Cache State	0
Members	2
Error Reporting	off
Ossn Components
Component	Version	Active	Checksum
OssnProfile	3.0	+	4093ed55601bfd56b323a9ca676d243d
OssnWall	5.0	+	db4b1a3b218b94ac9ab179531a763c80
OssnComments	3.0	+	7509ac90fa11aba3649c963644bc9f7e
OssnLikes	3.0	+	9f4b14309e573f39206e9b8fc9a3c37a
OssnPhotos	5.0	+	95285babb11f7bee3fa8790a89d1bec6
OssnNotifications	5.0	+	42e2bd924c0d5178f77e8525aa7e4606
OssnSearch	3.0	+	63d70bea50067222a3d1c2dd14469596
OssnMessages	5.0	+	9e0d5a41c8f62dfe7c65f369d69d1776
OssnAds	3.0	+	e4ea4305dbdf06671c41d5f05b8d9eab
OssnGroups	3.0	+	6ba143375e2ac9b31a7d8ea0dcd03e05
Ossn Site Pages	3.0	+	36b3440574155d0dc53fcd2c41c6aa2d
OssnBlock	3.0	+	242ba32d93593652d93cace5a04f2534
OssnChat	5.0	+	26afe2dc3c9f6ba1a7531d4aa8160925
OssnPoke	3.0	+	6a86d2a375c381ad8c41783186eb79eb
OssnInvite	3.0	+	d1a433373b477e43247c03a693e9bad4
OssnEmbed	3.0	+	9079f79eeb83615a2445038051f2fc83
OssnSmilies	4.5	+	c143be463a00330f80493e861e34ebee
Ossn Sounds	1.0	+	7ec0bf5dcfa940fced024f97b6162a6b
OssnAutoPagination	1.1	+	00978d8b0f3bccbbb69f4ecb7c45cc1f
Bio	3.5	+	4277c3b6bf7bcb65da94136ec9fb0218
TextareaSupport	2.1	+	baf498df8d0e41de665209cdb82fa490
CountrySelector	1.3	+	a33be2317d9b276073e413da5e307542
GifSupport	1.0		16b197949c7abfd6184151b7ce38b943
GroupInvite	1.0	+	edd8f421f9395f650a410ebe701fe82b
About User	4.1	+	abccc8454e46036eb33083345653e35b
NEWPAGE 1	1.1		e76b01d7c344de021ca1684598b559f6
Footer Links	2.0	+	f0321e6042293c092c3816f57cd23aa8
System Info	1.8	+	09188bd38c6c937204fc49e32e6837f3
Metatags	3.0	+	f4c152ca033b0c969058f5cd184e7ceb
Blogs	2.4	+	1c3f0ad9f4d211cd512fe58e3929fd1b
First Time Login Redirect	1.1	+	9af8b4e941a6219517f0c73aeafc4118
MenuBuilder	1.0	+	9af2a3ca305a4b2cb904c0b01bb2823b
Ossn Themes
Theme	Version	Active	Checksum
Flexi	1.3		51f6075d025d96f1330ea5747eea4740
Facebook Like Theme	3.1		b3ce05656b0e40ab8fdb46e408f362ac
goblack	4.4		067a44bbec6742992c427bbb4258f5f4
GoBlue	4.4	+	2850ac5177e4ba072b9175e4866e4d9b
GoBlue WideWall	2.0		19028e49ed5b15c6c7df7d83196e73fc
Ossn Core
Division	Checksum
actions	6d331834be652f0221ec8d11313bf57e
classes	5819675e9ba4154a45e948679ede9a7d
libraries	5f81ab8d9a8fd94222f0a7d06dd11b6d
locale	3ea1a51f727c2f92815f3b0d596b328e
system	2675a6d13ad5c04ad303107af4a6a96f
upgrade	01dc46011997aecc9ff27be04e894639
vendors	c5148e7f5470de140cb6e8884225f5c4

**Comment by lianglee** [comment]
Thank you for reporting the issue.
Can you follow the last thing:  go to admin panel -> basic settings- > display errors to yes

Change the language and if white page appear see into your cpanel filemanager  error_log file.
