### ISSUE TITLE
My OSSN is 5.0 - but the readme files says other thing

### ISSUE THREAD

**Issue by domino4evers** [opensource-socialnetwork/opensource-socialnetwork#1498]
In my Dashboard, My OSSN is 5.0, It tells me that there is a 5.1 update. But if I open my readme files, it tells me that I already have 5.1, and that is also what I downloaded 5.1 LTS.

Any ideas?

**Comment by lianglee** [comment]
Hi seems bug in v5.1 release,  please download latest build of v5.1 from our community website https://www.opensource-socialnetwork.org/download_ossn/latest/build.zip  the issue was fixed in it.
