### ISSUE TITLE
Restore new lines in post edit form 

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1499]
ossn_restore_new_lines

```
<?php
/**
 * Open Source Social Network
 *
 * @package   (softlab24.com).ossn
 * @author    OSSN Core Team <info@softlab24.com>
 * @copyright (C) SOFTLAB24 LIMITED
 * @license   Open Source Social Network License (OSSN LICENSE)  http://www.opensource-socialnetwork.org/licence
 * @link      https://www.opensource-socialnetwork.org/
 */
 $description = json_decode(html_entity_decode($params['post']->description));
 $description = $description->post;
 ?>
 <div>
 	<textarea id="post-edit" name="post"><?php echo ossn_restore_new_lines($description);?></textarea>
    <input type="hidden"  name="guid" value="<?php echo $params['post']->guid;?>" />
    <input type="submit" class="hidden" id="ossn-post-edit-save" />
 </div>
```

**Comment by githubertus** [comment]
No idea for what this was meant?
Just tried:
1. new post like
l1
l2
l3
clicked 'Post' - and all linebreaks appeared correctly on newsfeed

2. clicked 'Edit' - and all linebreaks appeared correctly in editor box
3. added a new line (l4) and clicked 'Save'
newfeed looks correctly now like
l1
l2
l3
l4

Can't see anything going wrong ...

**Comment by lianglee** [comment]
Hi, sorry for not mentioning and creating it with less information.  Actually there is no bug in OSSN, but i was testing this with old database. That have \r\n saved into the posts (object) When i tried to edit the post it still shows \r\n because that was very old post and old database.
