### ISSUE TITLE
carriage return/newline handling in messages not satisfying

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#150]
Step 1: Creating a message with a newline
![message_creating](https://cloud.githubusercontent.com/assets/9904364/5568082/d567d2ec-8f51-11e4-8d0c-21fabdde6030.png)
Step 2: Message has been sent
![message_sent](https://cloud.githubusercontent.com/assets/9904364/5568094/14463814-8f52-11e4-9489-8e229b346335.png)
Step 3: Having done a page refresh
![message_refresh](https://cloud.githubusercontent.com/assets/9904364/5568107/4c5c55ee-8f52-11e4-80e4-e39a0971e420.png)

.........................................................
ossn 2.0-dev [released 2014-12-28]

**Comment by lianglee** [comment]
fixed
