### ISSUE TITLE
In order to be MySQL 8 & SSLMode compatible, inject this bit of SQL

### ISSUE THREAD

**Issue by johndmulhausen** [opensource-socialnetwork/opensource-socialnetwork#1502]
MySQL 8 and SSL Mode use auth methods that the PHP 7.2 MySQL driver can't deal with, so since you have the password in a config file already, associate it with the username by doing this:

```
ALTER USER myuser IDENTIFIED WITH mysql_native_password BY 'mypassword';
```

Or, at least, recommend to the user that they do this

**Comment by lianglee** [comment]
I believe this has been taken care for php 7.2 > 

https://www.php.net/manual/en/mysqli.requirements.php

**Comment by johndmulhausen** [comment]
https://mood.land/phpinfo.php
^ I have  7.2.19-0ubuntu0.18.04.2 running and I still had to do this to access my MySQL 8 cluster

**Comment by lianglee** [comment]
I mean php 7.3

**Comment by lianglee** [comment]
Sorry i beleive php suggested to edit mysql.conf

> This is because MySQL 8 defaults to caching_sha2_password, a plugin that is not recognized by the older PHP (mysqlnd) releases. Instead, change it by setting default_authentication_plugin=mysql_native_password in my.cnf. The caching_sha2_password plugin will be supported in a future PHP release. In the meantime, the mysql_xdevapi extension does support it
