### ISSUE TITLE
Storing Password

### ISSUE THREAD

**Issue by humhubuser** [opensource-socialnetwork/opensource-socialnetwork#1507]
Changing the password of a user (Admin oder User himself) results that the User can't log-in anymore. Neither with the new passw. nor the old one.

**Comment by lianglee** [comment]
This has been fixed, you may download latest build and replace your old files with new build : https://www.opensource-socialnetwork.org/download_ossn/latest/build.zip

**Comment by lianglee** [comment]
(you'll need to create new standard account using signup and then go to phpmyadmin -> ossn_users -> search your account change type normal to admin and then login into your website) 

Please replace those files before logging
