### ISSUE TITLE
cant upload photos and gwetting also 403 permission denied erorrs and cant find error_log file

### ISSUE THREAD

**Issue by lisawebcoder** [opensource-socialnetwork/opensource-socialnetwork#1509]
hello i registed to your forum but i dotn find the option to create a new topic so i found this hee and i hope you can help 
i followed all the stpes to setup the eror lof but i dont find this file anywhere neither in ossn folder and neither in cpanel error section in x10host
the support is very limited to none at this host

so my many issues are mainly i cant uplod pictures
i am 7,3 php

i did get this ossninfo 

i added pics cuz it doesnt show the inof as text here
![ossninfo1](https://user-images.githubusercontent.com/49798411/65273718-cc3b7b80-daef-11e9-9670-50ea2141c103.png)
![ossninfo2](https://user-images.githubusercontent.com/49798411/65273725-d0679900-daef-11e9-8360-864ee27e821f.png)
![ossninfo3](https://user-images.githubusercontent.com/49798411/65273729-d2315c80-daef-11e9-92ff-3c23152b21b5.png)
![ossninfo4](https://user-images.githubusercontent.com/49798411/65273732-d3fb2000-daef-11e9-8333-bae7e56c55b9.png)

ok thank you
lisa

**Comment by lianglee** [comment]
Dear Lisa,  x10 hosting is free hosting and i don't think you will be able to run Ossn on it,  you may try to use hostinger free hosting.

**Comment by lisawebcoder** [comment]
hell thank you for your reply
it works but with photo upload gliches and some 403 forbinned issues on components install and i forget somewhere else too 
i have it working really well on infinftyfree host but its real slow and i would need to take a paid account
the thing is i have a paid acount with 1and1 and sorry but it doesnt even work there at all all i get is a bare landing page with no CSS and then all links are 500 error and i know the support tries to help but they frankly have no idea how to run this software or know which extensaions are missing as i seem to think..pretty fristring

is 1and 1 not a recomemded compatble host for this software?
pretty its not

ok i will try hostinger an dupload there on 000freehost app and see

lisa

**Comment by lianglee** [comment]
We have installed OSSN on 1&1 but it requires additional .htaccess modification  ,  we don't support these free hosts.   Maybe you can give a try to arvixe hosting or a2hosting or some cheaper VPS.

Free hosting have limited resources and database queries limit within each hour.  If you hit threshold you will get 500, 403 etc errors , also they have some mod_security stuff which need to be adjusted.

**Comment by lisawebcoder** [comment]
ok thank you for the useful information
i will inform my current host and also check those other hosts you mentioned

lisa

**Comment by lisawebcoder** [comment]
hell support
im  leaning towards just saying with my cirent paid host 1and1 since i am making progresson the software being ablle to run

i have a basic shared plan but the webapp ossn runs pretty fast
so right now all is setup just like on my other hosts which are free and have slow display and lots of downtime
but here at 1and 1 i keep getting 404 erro when trying to login or join
all the folder and files are just as with the other hosts
and i configured the confgi dba nd config site and it seems all good

would you know why this 404 eror saying filepage deleted or not there?
is it the htaccess?
in the root?
wellanyways i passedd the mesage to their support already

thxz if you know 

lisa

**Comment by lisawebcoder** [comment]
here is the error
404
The page you requested is unavailable or may have been deleted.

where is the error log plz?
i setup the compnents to on and i have the ossninfo page
but i am still looking for the error log file
i willask the 1and1 host if they have ageneral log file
but it would be great if i could find the ossn error fiel
i know on the other working hosts even though i have error reprting on and i get other bugs i dont get the error log file anywhere either
lisa

**Comment by lianglee** [comment]
It looks like your .htaccess is not working,  as mentioned the issue is with your provider misconfiguration.

**Comment by lisawebcoder** [comment]
hello ossn support
thank you
i have informed the 1and1 tech support about this
if its resovled i will post here the fix for your information 

regards
On Fri, Sep 20, 2019 at 11:57 AM, Arsalan Shah  wrote: 

	It looks like your .htaccess is not working, as mentioned the issue is with your provider misconfiguration.

**Comment by lisawebcoder** [comment]
hello support
1and1 gave me this reply
but that  seemms very far from an htaccess issue
do you have a htaccess example or thats what they mean that i have to go to server plan and not host plan and then there the htaccess will be ok?

that doesnt seem right when we could confiure ourselsves

ot sure if i am wrong
any way i can maybe try the hosts you supplied

thxz
lisa

**Comment by lisawebcoder** [comment]
We have verified that your package cannot accommodate the open source application that you have, for your website to work you need to get Server package and not hosting package.

This is the things that our hosting package can accommodate, link the link below:

https://www.ionos.com/hosting/linux-hosting


sorry see above reply from my current host 1and1

**Comment by lisawebcoder** [comment]
hello ssupport
i attached the original and modified htaccess files
1and1 made a very subtle adition form what i can see and this improved the webapp alot where members can now join and received emails and added to the database but we still cant login netiehr the members or admin
do you no the further changes need to the htaccess?
or is it server host specific?
thxz alot
lisa
On Fri, Sep 20, 2019 at 11:57 AM, Arsalan Shah  wrote: It looks like your .htaccess is not working, as mentioned the issue is with your provider misconfiguration.

**Comment by lisawebcoder** [comment]
i sent the previous message by email and you should see the pics files htaccess
i see my host added the line

modrewrite base/
this made alot of progress where we van join but we cant login still 404 error and it goes to userlogin
noit users//login as in the folders..why?

also i added followsymlinks and uncommented moderwtie 1
i didnt see any difference either way

if you know any fix thxz

lisa

**Comment by lisawebcoder** [comment]
hello support this thresd looks very similiar and actually compeletely similr to the issue i am having with login error 4040 and url path is user/login but folder path is userslogin

https://www.opensource-socialnetwork.org/discussion/view/803/404-errors-on-almost-every-page-after-install
i cant login to that thread to comment 
do you know what was the fix in that link?
how can i contact these memebres?

lisa

**Comment by lisawebcoder** [comment]
hello sir here is your line reply above 
We have installed OSSN on 1&1 but it requires additional .htaccess modification

1and1 is my paid host and they and i are trying to modify the htaccess file so my webapp willallow us to login  cuz we still get 404 eroors
all else join  and email etc working

do you the modifitcation needed in htaccess?
thxz
lisa

**Comment by lisawebcoder** [comment]
# OpenSource-SocialNetwork
 #
 # @package   (Informatikon.com).ossn
 # @author    OSSN Core Team <info@opensource-socialnetwork.org>
 # @copyright 2014 iNFORMATIKON TECHNOLOGIES
 # @license   General Public Licence http://opensource-socialnetwork.org/licence 
 # @link      http://www.opensource-socialnetwork.org 

#i put this not sure if it will break the app
#Options +FollowSymLinks
#Options FollowSymLinks
Options Indexes FollowSymLinks MultiViews
#Options -Indexes FollowSymLinks MultiViews
#AllowOverride all
Order allow,deny
allow from all

Options -Indexes
Options +SymlinksIfOwnerMatch
DirectoryIndex index.php

<Files "error_log">
	order allow,deny
	deny from all
</Files>

<FilesMatch "(nginx|htaccess).dist">
	order allow,deny
	deny from all
</FilesMatch>

<IfModule mod_mime.c>
    AddType image/vnd.microsoft.icon .ico
</IfModule>

<IfModule mod_expires.c>
	ExpiresActive On
	ExpiresDefault "access plus 1 year"
</IfModule>

<FilesMatch "\.(jpg|jpeg|gif|png|mp3|flv|mov|avi|3pg|html|htm|swf|js|css|ico)$">
	FileETag MTime Size
</FilesMatch>

<IfModule mod_rewrite.c>
SetEnv HTTP_MOD_REWRITE 1
#SetEnv HTTP_MOD_REWRITE 1

RewriteEngine on
RewriteBase /
RewriteRule ^rewrite.php$ installation/tests/apache_rewrite.php [L]

RewriteRule ^action\/([A-Za-z0-9\_\-\/]+)$ system/handlers/actions.php?action=$1&%{QUERY_STRING} [L]

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([A-Za-z0-9\_\-]+)$ index.php?h=$1 [QSA,L]

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([A-Za-z0-9\_\-]+)\/(.*)$ index.php?h=$1&p=$2 [QSA,L]

</IfModule>

<IfModule mod_php5.c>
	php_value memory_limit 128M
	php_value register_globals 0
	php_value post_max_size 8388608
	php_value upload_max_filesize 5242880
	php_value default_charset "UTF-8"
</IfModule>

<IfModule mod_php7.c>
	php_value memory_limit 128M
	php_value register_globals 0
	php_value post_max_size 8388608
	php_value upload_max_filesize 5242880
	php_value default_charset "UTF-8"
</IfModule>

**Comment by lisawebcoder** [comment]
plz see above 
htaccess but still cant login getting 404 erros with path user/login but folers are users/login

if i change folder to user will it break the app?

lisa

**Comment by lisawebcoder** [comment]
ok i got it to work with that htaccess i had posted above b4 deletion
it seems that i had a subfolder with a duplciates of the fodler of the app and i was going to the duplicate url and so the original folder is wnere it runs fine now

sorry for the confusin and thxz to you and 1and1
lisa

**Comment by lisawebcoder** [comment]
hello
i dont know how to create a new topic anywhere here on the forul sory
so i will psot hee and you can move it and give me link plz if you do so

i am developing my own theme and i folowed all the instructions on your website and i gopt a blanl page which is normal since my new theme has no actual theme folder to point to for theme software but when i delelted the new theme and went back to my defaylt goblue i still get blank page

nothing is altered in the code at all
i flushed cache 10 times

i am on localhost
lisa

**Comment by lianglee** [comment]
Flush cache 10 times won't help you, please create account on https://www.opensource-socialnetwork.org/community and create topic using https://www.opensource-socialnetwork.org/discussion/add and profile all possible details about what you have done, what happened etc.
