### ISSUE TITLE
Incorrect number of current users being recorded

### ISSUE THREAD

**Issue by SAWD1507** [opensource-socialnetwork/opensource-socialnetwork#1522]
I am not sure where to post this as I have a current Softlabs ticket but I have indicated 2 current issues already in that one ticket. If it does not belong here, please guide me accordingly.

I have noticed that the numbers of actual (validated and unvalidated) users being recorded in OSSN5.1 appears to be incorrect.

From the LIST USERS option under the USER MANGER option of the Admin panel, we currently have 5 users testing the community site.
![users 1](https://user-images.githubusercontent.com/56605351/67142833-f43c0d00-f25c-11e9-893c-1f289c39b7ac.PNG)

However, the main Dashboard graph shows that we have 26 users:
![dashboard users](https://user-images.githubusercontent.com/56605351/67142857-4da43c00-f25d-11e9-8ab8-806aa000582c.PNG)

Whilst the SYSINFO component also shows we have 26 users:
![info users](https://user-images.githubusercontent.com/56605351/67142867-644a9300-f25d-11e9-98df-c2dd45a264cf.PNG)

There has been 26 users as beta testers of the site over the last few weeks. When they are no longer a tester or have simply deleted their account, then we have come down to our actual and real list of 5 users. That list will again grow shortly as the next stage of testing begins with other users.

I am not sure as to why there are 2 different numbers being shown, one actual and one that appears to not have noticed that the OSSN_USERS table has had a number of users (if anything by the guid) but now has only 5.

![db](https://user-images.githubusercontent.com/56605351/67142950-403b8180-f25e-11e9-8d73-0b89b5ccd9ad.PNG)

Is this an issue or not?

**Comment by SAWD1507** [comment]
Apologies......

Is this the same as #1516?

I have only just read the other issues.

If it is then please remove this issue.

**Comment by lianglee** [comment]
The other users must be under unvalidated users list.

**Comment by SAWD1507** [comment]
I would have thought so, but......

not according to the dashboard...
![users1](https://user-images.githubusercontent.com/56605351/67162811-be338180-f35f-11e9-9f1c-9ce93116a1cd.PNG)

or the Unvalidated Users list:-

![users2](https://user-images.githubusercontent.com/56605351/67162825-eae79900-f35f-11e9-82ac-1bd313641975.PNG)

**Comment by SAWD1507** [comment]
The OSSN_USERS table shows 5 users

there are no Unvalidated Users

But 26 users are showing

**Comment by lianglee** [comment]
Can't reproduce issue here,  please send us the cpanel details as requested on your ticket.
