### ISSUE TITLE
SQL construction security

### ISSUE THREAD

**Issue by gwillings** [opensource-socialnetwork/opensource-socialnetwork#1525]
I really appreciate the effort put into this project, but you might want to address the underlying issues with the way you build SQL. The manner in which SQL is built within this application relies on input validation and sanitisation without any protective SQL parameterisation or database escaping as far as I can see.  Personally, I'd recommend implementing parameterised queries at the very least.

**Comment by lianglee** [comment]
@gwillings we'll look into it as i believe converting already existing database solution to  parameterised queries is not that hard. Lets see what we least we can do.

**Comment by lianglee** [comment]
Draft for insert and update  ,  
https://gist.github.com/lianglee/8f41020c704403fd7183726d32f4c3cd

Not that easy to covert entire database class to Parameterized , as many components on community and many using custom stuff.

**Comment by lianglee** [comment]
- https://gist.github.com/lianglee/8f41020c704403fd7183726d32f4c3cd 
Second draft, supported the select, update, insert with parameterized values, and `wheres`

**Comment by lianglee** [comment]
Added support for parameterized values,  and moved to PDO.  I tried to implement same effect (above gist is with mysqli) but its bit complex and requires more messy code.
