### ISSUE TITLE
Error issue connection between file php etc

### ISSUE THREAD

**Issue by robert199524** [opensource-socialnetwork/opensource-socialnetwork#1526]
Hi this Robert Pera

Social Manager developer etc

https://fast24.yolasite.com/

visit my website  

i report you  have 12 error with your ossn script

i have fix 8 of this but 4  i wasn't able  to fix

**Comment by lianglee** [comment]
What are the errors?

**Comment by robert199524** [comment]
it seem that script

password hash string does  work 100%  it takes error

reloading sometimes get crash

when you upload  a component a lot component crash the site 

Only  way i can fix this error on php admin direct i was able  

because im technical fixer but this error must solved  on other people

You need more to do with this ossn  you need to setup  two factor authentication with  app generator

usb protection via usb etc 

your social script is low

and this need more feature like  change the size of photo upload and cover  make like facebook etc/

chat very low and  your ossn does recieve notification automatically without refresh page you need to fix that...

**Comment by lianglee** [comment]
You can not run it on free hosts if you really wanna run social network you need a dedicated hosting.
Not sure what USB have to do with it.
What you mean by password hashing.

**Comment by robert199524** [comment]
if someone use your script risk 100% be hacked
i advise that need FDU 2 Protection USB  is usb protection like have facebook and google authentication

**Comment by lianglee** [comment]
There is difference between script getting hacked and the server or account getting hacked.
