### ISSUE TITLE
feature request: display groups I'm a member of in left column

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#155]
Instead of displaying only groups I'm an owner of, I'd like to see all groups I'm a member of ...

As a first attempt I added a new function to OssnGroups classes:
	public function getMyGroups($member_guid) {
		$allGroups = $this->getGroups();
		$myGroups = array();
		foreach ($allGroups as $group) {
                     if ($this->isMember($group->guid, $member_guid)) {
                         $myGroups[] = $group;
                      }
                }
		return $myGroups;
	}

and replaced 
return $groups->getUserGroups($user->guid);
with 
return $groups->getMyGroups($user->guid);
in OssnGroups/libraries/groups.php

see issues #75 and #92

**Comment by lianglee** [comment]
Added, i changed the function you wrote,
If we use $this->getGroups(); this will get all site groups and if we have 2000 group it will slow down server.
