### ISSUE TITLE
group members total count becomes 0 when group cover is set

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#156]
$members = $params['group']->getMembers(); is missing in 
if ($cover) {
....
}
case.

As a result
(<?php echo count($members); ?>) </a></div>  gives zero

Perhaps it's better to put the $members query simply once right in the beginning of profile.php, since it will be used at least 1 time ... regardless of any condition
.......................................................
ossn 2.0-dev [2014-12-28 release]

**Comment by lianglee** [comment]
Fixed!
