### ISSUE TITLE
content of public group wall not visible for the public

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#157]
Missing
if ($params['group']->membership == OSSN_PUBLIC && $ismember !== 1)
....
}
condition in profile.php

**Comment by githubertus** [comment]
No, #113 referred to posting in groups, this one refers viewing a public group you're not a member of

I have started to make my fixes accessable. You can get the involved files from:
http://ossn.z-mans.net/components/OssnGroups/pages/profile.txt
http://ossn.z-mans.net/components/OssnWall/wall/group.txt
http://ossn.z-mans.net/components/OssnWall/templates/wall/group/item.txt

Simply search for "zfix", and you'll get an idea what I did
Of course you're welcome to join ossn.z-mans.net, too .... and have a look:)

**Comment by lianglee** [comment]
Fixed with #113

**Comment by githubertus** [comment]
Already mentioned drawback (comments are invisible) still open. See my commenting in
http://ossn.z-mans.net/components/OssnWall/templates/wall/group/item.txt

**Comment by lianglee** [comment]
Yes comments and likes are disabled.

**Comment by githubertus** [comment]
Sorry, but couldn't resist to include the last steps to switch comments and likes, too :) 
Involved files (in logic order) are:
http://ossn.z-mans.net/components/OssnWall/templates/wall/group/item.txt
http://ossn.z-mans.net/components/OssnComments/post/comments.txt
http://ossn.z-mans.net/components/OssnComments/templates/comment.txt
(these .txt files seem to need a browser refresh to get the latest version)
