### ISSUE TITLE
After login redirect user to referrer link?

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#158]
I was browsing discussion community and found some question that wanted to answer it, i loggedin to community but after login ossn system takes me to home page instead of discussion page.  

What you think? 

@githubertus , @sathish4fri

**Comment by githubertus** [comment]
Can't quite follow. Are you talking about http://community.opensource-socialnetwork.org/?
Even on http://community.opensource-socialnetwork.org/home I CAN see the latest discussions, where else should I be lead to? With http://community.opensource-socialnetwork.org/discussion I'm just getting a blank page...

**Comment by lianglee** [comment]
Actually i am talking about Ossn, not our community site. What i wanted to say is redirect user to referrer link after login.

**Comment by githubertus** [comment]
Okay, I think I got it. :)
If my base url is "mysite.com", then depending on being logged in or not I would like to get
- Logged off: mysite.com + community front page with ability to register
- Logged in: mysite.com + community thread page

Simply the same url, and I won't get a 404 error when visiting /home, but being logged off.
Another advantage: This solution is easier to integrate into existing websites. There a lot of sites with "/home" already in use for different content and you'll have to rename existing stuff first to make things fit together.
If ossn really needs that subdirectory, I'd suggest to use at least something more unpopular like "/ossnhome" or perhaps better "/community".

**Comment by sathish4fri** [comment]
Sorry bro now only seeing this I was busy with work . we must refer it .. If community or site have more page means they will def ask us to change .better we provide it first

**Comment by lianglee** [comment]
Changed now
* Go to yoursite/site/about
* Now on header enter login details and login. 
* You will be redirected to REFERRER page (site/about)

**Comment by githubertus** [comment]
So: why do I still get redirected to mysite.com/home/ 
when I enter mysite.com
?

**Comment by MSR-Saif** [comment]
Hi, is it possible to redirect users to a different page after login or which files need to modify to customize news feed view (after login page), thanks.

**Comment by lianglee** [comment]
@MSR-Saif, a commercial component is available if you are interested contact http://www.informatikon.com/contact

**Comment by MSR-Saif** [comment]
Thanks.
