### ISSUE TITLE
only group _owners_ are getting member lists of public groups

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#160]
others - even members - are redirected to the groups main page

Since I don't see no other meaningful usage in groups so far, I commented out the line, see zfix 160 in
http://ossn.z-mans.net/components/OssnGroups/ossn_com.txt

**Comment by lianglee** [comment]
You comment line in function  group_requests_page: this function is for only to view group join requests (for group owner)

group_members_page: To view member of any group simply visit:  group/<guid>/member

**Comment by githubertus** [comment]
To reproduce:
- create a test member
- log off
- log in as test member
- create a new PUBLIC group
- visit /group/ID_OF_PUBLIC_GROUP/members 
it works!
- log off test member
- log in as lianglee
- visit /group/ID_OF_PUBLIC_GROUP/members 
- it doesn't work. instead you're redirected to /group/ID_OF_PUBLIC_GROUP

function group_requests_page() throws you back because you're not the owner.
that's correct, but of no meaning in this context.
Of course the correct fix would be not to call group_requests_page() here, instead of disabling the function. :)

**Comment by githubertus** [comment]
Silly me1 :-1: !
My first hotfix allows even not owners to accept member requests
Updated http://ossn.z-mans.net/components/OssnGroups/ossn_com.txt in the meantime
Seems, that the function is called everytime because of the hook. So I moved the owner check inside the if ($page == 'requests') condition.

**Comment by lianglee** [comment]
fixed
