### ISSUE TITLE
language file access modes not in line with code

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#162]
language file defines
	//access
	'title:access1' => 'Private',
	'title:access2' => 'Public',
	'title:access3' => 'Friends',
code is using
	//access
	'title:access:1' => 'Private',
	'title:access:2' => 'Public',
	'title:access:3' => 'Friends',

**Comment by lianglee** [comment]
Yes will fix them

**Comment by lianglee** [comment]
fixed
