### ISSUE TITLE
comment likers list unreachable on touchscreens

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1620]
![unreachable-likers](https://user-images.githubusercontent.com/9904364/71090123-98312e80-21a2-11ea-96b4-d0df9bec3643.jpg)

touching the "1" here will open the comment-edit menu instead

a possible fix would be to remove the event from the comment div and have the litte down-arrow already in place - just the same like the down-arrow of the post

(personally I don't like this flickering of "down-arrow-visible/down-arrow-invisible" anyway)

**Comment by lianglee** [comment]
I tired to locate it , it seems on hover it shows that down error, a possible good solution would be to show that error by default (not invisible/disable) Any idea how we can achieve that?

On however hover the css is assigned to show-desc , maybe we add that css as default?

![image](https://user-images.githubusercontent.com/805066/71221261-e0109c80-22ed-11ea-8a01-83ecfe6eb396.png)
