### ISSUE TITLE
[E] feature request for a more flexible theme handling

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1623]
Currently a lot of calculations are very much based on the default Goblue theme,
and we're assuming things like cover width=1040px, cover height=200px, etc. to be the standard.
As a consequence we even do checking with hardcoded values like `'The cover picture must be at least 1040 x 300 or greater.` And the current scaling calculations are based on these 'magic' values, too.

But what if someone wants to develop a completely different theme? The more the values of that custom theme would differ from Goblue, the more the comparison of uploaded image dimensions with Goblue values will become senseless, and the more the scaling algorithm will become inaccurate.

To overcome this limitation and to get rid of hardcoded values in the scripts, my idea for future themes would be having something like a hidden 'theme configuration' div at the bottom of the page to hold these custom values which the scripts have to depend on and work with. Something like ...
`<div id="theme-config" data-desktop-cover-height="345" data-minimum-cover-image-width="1234" ... etc ...</div>`

This way we won't need to store these values in the database, and we had no extra queries to get them back. It's just up to the theme developer to place the correct values in this div.

**Comment by lianglee** [comment]
Added few tags to titles 

[E]   = Enhancement
[...R] = .... Request
[B]   = Bug

What you think?
