### ISSUE TITLE
issues on post/comment editing with backslash and plus chars

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1625]
1. add a new post like `\+`
2. edit the post - and save gives `\\`  (= extra backslash and plus removed)

3. add a new comment like `\+`
4. edit the comment and save gives `\\+`  (= extra backslash)

Ajax return issue only, refreshing the page gives correct output

**Comment by lianglee** [comment]
Seems issue with ajax request that is being sent.

**Comment by githubertus** [comment]
fixed
