### ISSUE TITLE
DigitalOcean marketplace droplet missing sendmail

### ISSUE THREAD

**Issue by pinheadmz** [opensource-socialnetwork/opensource-socialnetwork#1631]
After creating a DO droplet from the pre-fab OSSN template, I noticed user auth emails were not going out. I had to install `sendmail` myself and configure it to send emails and also use the right headers (see: https://unix.stackexchange.com/questions/79808/localhost-127-0-0-1-in-email-headers)

**Comment by lianglee** [comment]
Most of the account, usually new have email option disabled by digital ocean so we didn't focused on setting up a mail part.  However we suggest users to use https://github.com/opensource-socialnetwork/SMTP instead.
