### ISSUE TITLE
[B] strangeness of class extending in input modules

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1635]
Having a look at system/plugins/default/input/dropdown.php line 14

Let's assume I want to add my extra class 'timezone'
that would give
`$class = 'ossn-dropdown-inputtimezone'`

Was it really meant to be that way? I would expect to get
`$class = 'ossn-dropdown-input timezone'`

Even stranger: After the array_merge is done in line 34
the before enhanced `$class` will be overwritten by `$params['class']`
and I'm ending with
`$class = 'timezone'`
hence making the operation in line 14 obsolete.

So the question is: What did you really want to achieve?
- a complete replacement of 'ossn-dropdown-input' ?
- or extending 'ossn-dropdown-input' with an extra class?

**Comment by lianglee** [comment]
I believe it is bug a new class should be 'ossn-dropdown-input timezone'' means other class should be extended with extra class.
