### ISSUE TITLE
Maybe not be an issue but I am contributing - Timeline Photos

### ISSUE THREAD

**Issue by WizardKid** [opensource-socialnetwork/opensource-socialnetwork#1637]
The timeline photos are very large and when anyone share someone's photo post, part on the photo will be off the page. Is there a way to reduce the photo size? Also the email template is too basic.. where can I edit the email templates so it looks professional?

**Comment by lianglee** [comment]
Please provide the screenshot and we'll see the issue, also provide the 

1. Browser and its version,  
2. OS version
3. OSSN version
4. Type of OSSN (free/paid).

**Comment by WizardKid** [comment]
![Screenshot from 2020-01-17 16-56-12](https://user-images.githubusercontent.com/13104065/72630578-89c56680-394a-11ea-951f-00a833657d17.png)
![Screenshot from 2020-01-17 16-56-59](https://user-images.githubusercontent.com/13104065/72630579-89c56680-394a-11ea-9ccb-7e64480887e2.png)
![Screenshot from 2020-01-17 16-59-21](https://user-images.githubusercontent.com/13104065/72630680-c2654000-394a-11ea-9f1b-47e9ce5f078f.png)
Browser: Firefox 72.0.1 (64-bit
OS Version: CentOs7
OSSN Version: Latest Version | 5.2-build-114202001
Type: paid

**Comment by lianglee** [comment]
Please send a dummy account details for your website at https://www.softlab24.com/contact and will check.
