### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by sandeepsahni** [opensource-socialnetwork/opensource-socialnetwork#1638]
I face install error on local machine.
![image](https://user-images.githubusercontent.com/60036956/72676884-13487600-3abc-11ea-8cb7-fdda9ae64459.png)

**Comment by sandeepsahni** [comment]
No email comes, which is expected and no way to find the issue.

**Comment by githubertus** [comment]
the reason should be found in the log file of your webserver

**Comment by lianglee** [comment]
any status on this?
