### ISSUE TITLE
long comments overwriting camera icon

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#164]
![long-comments](https://cloud.githubusercontent.com/assets/9904364/5606221/e57edff4-9424-11e4-9b59-12c2f736b6eb.png)

http://ossn.z-mans.net/components/OssnComments/css/comments.txt
http://ossn.z-mans.net/components/OssnLikes/css/likes.txt

**Comment by lianglee** [comment]
Thanks!
