### ISSUE TITLE
[E] Default profile picture 

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1647]
OSSN uses the last uploaded photo as profile picture but what if user wanted to remove profile photo but does't want his previous photo set as profile photo.

We can set a flag default_profile_photo..... in this way user can remove current photo and not previous photo will be set.

I'll think to implement this with standalone component if possible with some other additional.

**Comment by githubertus** [comment]
My idea is to have a selector **[x]** on each photo (bottom right) on the **album/profile/x** page
and let the member choose which pic he wants to be displayed on the profile page.
This way the member may keep several pics in place and switch between them whenever he wants.
(Same for cover pics)

**Comment by lianglee** [comment]
Yes its a good idea!
