### ISSUE TITLE
Reduce the webste addresss?

### ISSUE THREAD

**Issue by Rebelee32** [opensource-socialnetwork/opensource-socialnetwork#1648]
mydomain.com/ossn-v5.2-1577836800/home/

**How can I reduce the address to mydomain.com/index**

There is 6 index pages in the /ossn-v5.2-1577836800/ folder
Somehow I lost one

Below are the 5 i have. Not sure what happened to one or where it was. find it and send it to me?

/ossn-v5.2-1577836800/index.php
/ossn-v5.2-1577836800/installation/index.php
/ossn-v5.2-1577836800/installation/pages/index.php
/ossn-v5.2-1577836800/system/plugins/default/pages/index.php
/ossn-v5.2-1577836800/system/plugins/default/pages/contents/index.php

**Comment by githubertus** [comment]
Simply unpack the archive one directory above (in the root of mydomain.com), so that it looks like
index.php
installation/index.php
.....

**Comment by lianglee** [comment]
@Rebelee32  please follow above advice.
