### ISSUE TITLE
Non required field not saved by admin ?

### ISSUE THREAD

**Issue by DedeLebon** [opensource-socialnetwork/opensource-socialnetwork#1666]
Hi,

Not sure if it is on purpose or not but the following lines:

foreach ($fields['non_required'] as $field) {
    $user[$field] = input($field);
}

are present in 
 - components/OssnProfile/actions/edit.php 
but not in 
 - actions/administrator/user/edit.php

which seems to prevent non required field to be saved / modified by admin

**Comment by lianglee** [comment]
non required fields should be modified by admins,  we'll verify this , thanks for reporting.

**Comment by lianglee** [comment]
Its fixed now. Thanks for reporting.
