### ISSUE TITLE
[E] delete 'upload image' wall entries automatically if pic is deleted 

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1667]
as currently we're getting orphan wall entries which have to be deleted manually when an uploaded picture has been deleted afterwards.

(some kind of code is already in Blog component: if a Blog gets deleted, the accompanying wall posting will be deleted, too)

**Comment by lianglee** [comment]
You mean the picture added via a wall post form? 

![image](https://user-images.githubusercontent.com/805066/74613310-f2ad2380-512e-11ea-868d-580dc969d3d7.png)

**Comment by githubertus** [comment]
no, I meant pictures which have been added to a photo album
(which results in an automatic wall posting)
but this posting is still kept in place - even if the pic has been deleted from the album some time later

**Comment by lianglee** [comment]
Agree,  what about if wall post have multiple images? We need to remove specific guid from wall post (if multiple pictures added).

**Comment by githubertus** [comment]
1. I'm not able to create a wall post with multiple images
2. this request wasn't about wall posts with images, it was about images in photo albums

**Comment by lianglee** [comment]
Sorry let me explain in different way

1. When i go to albums
2. Create new album ABC
3. Add 10 photos to album same time.
4. Those 10 photos will appears on wall post.

**Comment by githubertus** [comment]
Ah, understood. Yes, in this case we would get 1 post showing 10 photos.
So, 
- if up to 9 photos are deleted, the corresponding photo guids have to be removed from post
- if 10 photos are deleted, the complete post needs to be removed

**Comment by lianglee** [comment]
yes that what i was trying to say :) 👍
