### ISSUE TITLE
profile picture comments

### ISSUE THREAD

**Issue by seimei** [opensource-socialnetwork/opensource-socialnetwork#167]
When you open the profile picture of someone, the camera icon in the comments is in the outside 
![ossn2](https://cloud.githubusercontent.com/assets/10389633/5607484/27c17c4e-945e-11e4-832a-5c9d2391c3ed.png)

**Comment by lianglee** [comment]
What is your Ossn version?

**Comment by seimei** [comment]
v. 2.0-dev

**Comment by lianglee** [comment]
will fix it assp

**Comment by lianglee** [comment]
fixed
