### ISSUE TITLE
Minha página inicial está redirecionando para opencode.byethost.com/opencode/installation

### ISSUE THREAD

**Issue by secarioo** [opensource-socialnetwork/opensource-socialnetwork#1670]
Pois a instalação foi um sucesso , pois quando vou acessar a página inicial 
Pois me aparece a seguinte mensagem : It seems the Open Source Social Network is already installed sendo que eu não estou tentando reinstalar mais sim tentando acessar a página inicial do site e se eu excluir a pasta installation parece erro 404

**Comment by githubertus** [comment]
either clean your browser cache completely,
or open your broswers developer console, click the Network tab, check 'disable cache' and load your site again.
