### ISSUE TITLE
Issue with creating new account on my OSSN platform (https://kidafricalive.org/brn)

### ISSUE THREAD

**Issue by neuhovah** [opensource-socialnetwork/opensource-socialnetwork#1677]
i recently updated my OSSN software and since then it has been malfunctioning, i noticed that new users cant sign up on the platform (https://kidafricalive.org/brn, it doesnt say or show any error message but just wont confirm the sign up or send any email message... i think i didnt update the software well

**Comment by lianglee** [comment]
Just saw that because you deleted some fields? did you changed core files?

**Comment by lianglee** [comment]
Regarding no email sent please see https://www.opensource-socialnetwork.org/wiki/view/891/account-activation-email

**Comment by neuhovah** [comment]
> Just saw that because you deleted some fields? did you changed core files?

i didn't change any core files on purpose, i only upgraded the site to the latest update and found out that some files were missing... i was told to save some back up files that i couldn't do it successfully... now the whole site is misbehaving

**Comment by lianglee** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/wiki/How-to-report-a-issue-on-github
