### ISSUE TITLE
[B] Japanese language files including BOM

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1684]
almost all language files of type **ossn.ja.php** which are currently part of Ossn 5.3 dev  come included with a BOM header, resulting in several XHR/JSON issues (last step of new install, switching components on and off, etc)

needs fix before releasing!

**Comment by lianglee** [comment]
components\OssnAds\locale\ossn.ja.php
components\OssnChat\locale\ossn.ja.php
components\OssnComments\locale\ossn.ja.php
components\OssnGroups\locale\ossn.ja.php
components\OssnInvite\locale\ossn.ja.php
components\OssnLikes\locale\ossn.ja.php
components\OssnMessages\locale\ossn.ja.php
components\OssnNotifications\locale\ossn.ja.php
components\OssnPhotos\locale\ossn.ja.php
components\OssnPoke\locale\ossn.ja.php
components\OssnProfile\locale\ossn.ja.php
components\OssnSearch\locale\ossn.ja.php
components\OssnSitePages\locale\ossn.ja.php
components\OssnSmilies\locale\ossn.ja.php
components\OssnWall\locale\ossn.ja.php
locale\ossn.ja.php
