### ISSUE TITLE
[B] getting orphan like records from comments when deleting a post

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1687]
Ossn 5.3 dev
To reproduce:
1. case:
- A creates a Post
- B comments on Post of A
- B likes his own comment
- A deletes the post
--> ossn_likes record of B is still in database

2. case:
- A creates a Post
- A comments on Post of A
- A likes his own comment
- A deletes the post
--> ossn_likes record of A is still in database

This is working:
- A creates comment
- A likes own comment
- B likes comment of A
- A deletes comment
--> both ossn_likes records of A and B are removed from database

So it looks like something is missing/wrong in OssnWall

**Comment by lianglee** [comment]
Fixed
