### ISSUE TITLE
SSL Setup Help

### ISSUE THREAD

**Issue by TheZLabs** [opensource-socialnetwork/opensource-socialnetwork#1689]
I have been trying nearly everything to get this to work and it does not.
I tried following the basic instructions that say to simply edit: ossn.config.site.php and change the url from http to https after disabling cache on the web gui.
There seems to be quite a bit missing here. Where do I configure the certificate paths? I have tried editing the 000-default.conf to listen on 443 instead of 80, install and point at the certs and then look at itself, I've tried editing the default-ssl.cnf file to the certificates I need to use, to no effect. I tried using haproxy on a separate server to do the ssl termination and then redirect to the ossn server. None of this seems to work. I would prefer ssl termination to occur on the server with no third party proxy/ssl term. Can someone please provide information for how to setup ssl with a purchased certificate? I've never had this much trouble with an ssl config on a ubuntu server. Am I missing something simple? I have been messing with this for days to no avail. I really like what I've seen so I am very interested in making this work! Please help!

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/wiki/view/2671/how-to-enable-httpsssl-on-ossn
Please note that configuration server is not a scope of this issue tracking system.

You need to look basic apache forums for installation SSL and see if you get https:// on your site.  
Example

Further make sure you  have openssl installed and mod ssl enabled for apache
```
<VirtualHost *:443>
    ..
    ..
    ..
        SSLEngine on
        SSLCertificateFile /path/to/your_domain_name.crt
        SSLCertificateKeyFile /path/to/your_private.key
        SSLCertificateChainFile /path/to/DigiCertCA.crt #intermediate certificate
</VirtualHost>
```

https://serverfault.com/questions/303744/serve-http-port-80-and-https-port-443-on-same-virtualhost

**Comment by TheZLabs** [comment]
I've done this in multiple configurations but thanks.

**Comment by lianglee** [comment]
@TheZLabs try to install fresh copy of VPS, and then install some panel like vestacp and then install Ossn using on panel as they have all required tools setup.
