### ISSUE TITLE
Ossn Logo

### ISSUE THREAD

**Issue by seimei** [opensource-socialnetwork/opensource-socialnetwork#169]
Could it be that the OSSN logo changes automatically to the default logo after a time?

**Comment by seimei** [comment]
I'm trying To say that I changed the default OSSN Logo To an another, but after a few days the Logo that i replaced changed To the default Logo. Is this possible? thanks

**Comment by sathish4fri** [comment]
I think you have updated the ossn version

**Comment by lianglee** [comment]
@seimei no it does not change logo to default logo, recheck your logo file.

**Comment by seimei** [comment]
No I don't updated the ossn version, but it's ok. Thank you anyway!
