### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by Linux4Life531** [opensource-socialnetwork/opensource-socialnetwork#1696]
Hello,
I thought that it would be good if OSSN had a dark mode feature. Lots of big websites like https://stackoverflow.com/ and Microsoft office online have them. I should be able to code this, if each user can have a 'dark_mode' column in the database, with the user id.

If this feature already exist, please let me know. I am not the system admin so that may be the problem.

Thanks

**Comment by lianglee** [comment]
We have a dark theme though https://www.opensource-socialnetwork.org/component/view/2396/black-theme

**Comment by Linux4Life531** [comment]
Okay, how do you turn that on then if you are not the sys admin.

**Comment by githubertus** [comment]
It's not possible, and actually I see no good reason why it should.
The admin is the one giving his community a unique corporate identity and it's your decision to accept it or not. Aside from that you have enough ways to pep up your own profile with personal pictures, videos, blogs, etc.

**Comment by Linux4Life531** [comment]
Great - Shouldn't each user have its own dark mode boolean setting in the database then.

**Comment by Linux4Life531** [comment]
Okay.
