### ISSUE TITLE
group admins must be able to delete ANY comment in their own group

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#170]
Currently, group admins (owners) have no control on member postings and comments
since I was busy with comments anyway, I gave it a try to make it work. Involved files:
http://ossn.z-mans.net/components/OssnComments/ossn_com.txt
http://ossn.z-mans.net/components/OssnComments/actions/comment/delete.txt

Something similar has to be implemented on posts, too.
But please have a look first, perhaps there's a much simpler way ...

**Comment by lianglee** [comment]
Thanks will look it

**Comment by lianglee** [comment]
fixed
