### ISSUE TITLE
[E] Error signing in

### ISSUE THREAD

**Issue by MateusOFCZ** [opensource-socialnetwork/opensource-socialnetwork#1719]
Hello, I installed the Open Source Social Network through Softaculous, I can't access the administrator panel and the website as a user, I've already tried to reset my password, it doesn't give anything, when logging in the fields are cleared and nothing, like solve this?

**Comment by lianglee** [comment]
@MateusOFCZ ,  remove OSSN using tool you installed and install it manually.

**Comment by lianglee** [comment]
In case something wrong you can ask help here https://www.opensource-socialnetwork.org/community

**Comment by MateusOFCZ** [comment]
Hello, I discovered the problem, I'm using an e-mail business instead of gmail, or something like that, and what happens is that you don't send the verification, so I can't log into my account.

**Comment by lianglee** [comment]
@MateusOFCZ the emails sending is done by your cpanel not by OSSN,  make sure you have no issue to send emails form cpanel. You may use our SMTP module found on github.
