### ISSUE TITLE
Profile Images and Post Images Not Displaying

### ISSUE THREAD

**Issue by ProFarjan** [opensource-socialnetwork/opensource-socialnetwork#1725]
When i install this site all ok but three days later site profile images and post images not displaying
*****error Log*******
[14-May-2020 06:08:47 America/New_York] Error: Call to a member function canModerate() on bool in /home/profcrkh/public_html/shushillife.com/components/OssnWall/plugins/default/wall/siteactivity.php:17
Stack trace:
#0 /home/profcrkh/public_html/shushillife.com/libraries/ossn.lib.views.php(27): include()
#1 /home/profcrkh/public_html/shushillife.com/libraries/ossn.lib.views.php(50): ossn_include('/home/profcrkh/...', Array)
#2 /home/profcrkh/public_html/shushillife.com/libraries/ossn.lib.plugins.php(75): ossn_view('/home/profcrkh/...', Array)
#3 /home/profcrkh/public_html/shushillife.com/components/OssnWall/plugins/default/wall/pages/wall.php(27): ossn_plugin_view('wall/siteactivi...')
#4 /home/profcrkh/public_html/shushillife.com/libraries/ossn.lib.views.php(27): include('/home/profcrkh/...')
#5 /home/profcrkh/public_html/shushillife.com/libraries/ossn.lib.views.php(50): ossn_include('/home/profcrkh/...', Array)
#6 /home/profcrkh/public_html/shushillife.com/libraries/ossn.lib.plugins.php(75): ossn_view('/home/profcrkh/...', Array)
#7 /home/profcrkh/public_html/shushillife.com/libraries/ossn.lib.initialize.php(121): ossn_plugin_view('wall/pages/wall')
#8 /home/profcrkh/public_html/shushillife.com/libraries/ossn.lib.page.php(67): ossn_user_pagehandler(Array, 'home')
#9 /home/profcrkh/public_html/shushillife.com/index.php(22): ossn_load_page('home', Array)

**Comment by githubertus** [comment]
![shames](https://user-images.githubusercontent.com/9904364/82288939-e9d52380-99a3-11ea-9db9-285bd62ccf57.jpg)

That is:

1. you are ashamed to name the originator of the software you are using
1. but you are not ashamed to ask the originator for help

So wouldn't it then make sense to first find out what's going wrong in your head instead of checking error logs?

**Comment by lianglee** [comment]
So sad that you did respected the authors, I am going close this issue.
