### ISSUE TITLE
Getting a user by custom field

### ISSUE THREAD

**Issue by sorxrob** [opensource-socialnetwork/opensource-socialnetwork#1739]
Do we have example on how to get a user by a custom field?

In the docs, we can get a user by `ossn_user_by_email` or `ossn_user_by_guid` but how about custom fields?

Let's say I have a `random_field` field in the users table. And do something like below.

```php
$user = input('random_field');
$user = ossn_user_by_random_field($user); // or whatever

$user->data->another_field = true;
if($user->save()){}
```

Any help would be much appreciated.

**Comment by lianglee** [comment]
Not an issue here since you posted on community, you'll be answerd

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/discussion/view/4236/getting-a-user-by-custom-field
