### ISSUE TITLE
menu control display logic partly inherited from last posting

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#174]
fix is on the way .... one moment ...

Yeah, this is a tricky one and hard to explain. So let's look a the snapshots:
1. Step
Logged in user: honey
last posting: from sys admin
everything ok, no menu icons
![post-control1](https://cloud.githubusercontent.com/assets/9904364/5630039/633f7516-95ba-11e4-8993-dc787530879a.png)
2. Step
Logged in user: honey
honey made a posting in the meantime (last entry now)
honey got a menu icon, that's okay
BUT: all postings below got menu icons too. they don't really open, but they are in place!
![post-control2](https://cloud.githubusercontent.com/assets/9904364/5632704/0f06df2c-95d1-11e4-861b-4a5b39b47a3b.png)
3. Step
Logged in user: santa
same posting state as before, but everything's okay again, because last entry is owned by honey
(if santa would post now, he'll get the same buggy sight)
![post-control3](https://cloud.githubusercontent.com/assets/9904364/5632829/4d05d6e2-95d2-11e4-8f09-a0c58e58dfa9.png)

**Comment by githubertus** [comment]
see zfix 174
http://ossn.z-mans.net/components/OssnWall/ossn_com.txt

**Comment by sathish4fri** [comment]
thanks for your report

**Comment by lianglee** [comment]
fixed
