### ISSUE TITLE
Members aren't getting the email confirmation response. 

### ISSUE THREAD

**Issue by mikeatencio** [opensource-socialnetwork/opensource-socialnetwork#1740]
Members aren't getting the email confirmation response.  This is the error messages I am getting:

1. - Mail Delivery System <mailer-daemon@acclaim.nsjet.com>
To:
atenciomike@yahoo.com

Mon, Jun 8 at 5:09 PM

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  hegreene53@gmail.com
    host gmail-smtp-in.l.google.com [172.217.204.26]
    SMTP error from remote mail server after end of data:
    550-5.7.26 Unauthenticated email from yahoo.com is not accepted due to domain's
    550-5.7.26 DMARC policy. Please contact the administrator of yahoo.com domain
    550-5.7.26 if this was a legitimate mail. Please visit
    550-5.7.26  https://support.google.com/mail/answer/2451690 to learn about the
    550 5.7.26 DMARC initiative. x9si83794vsi.380 - gsmtp

**Show original message

**_I have added the text to my DNS through my hosting company - Now I'm getting this second message._**

2. This message was created automatically by mail delivery software.**

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  halloweengirlforever13@yahoo.com
    host mta6.am0.yahoodns.net [67.195.204.77]
    SMTP error from remote mail server after end of data:
    554 5.7.9 Message not accepted for policy reasons. See https://help.yahoo.com/kb/postmaster/SLN7253.html

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/wiki/view/891/account-activation-email
you can not use notification email like @gmail.com  in the administrator panel -> site settings, notification email.

What is the notification email you have set there?

**Comment by mikeatencio** [comment]
atenciomike@yahoo.com

Michael Atencio 

    On Tuesday, June 9, 2020, 10:08:45 AM EDT, Arsalan Shah <notifications@github.com> wrote:  
 
 


https://www.opensource-socialnetwork.org/wiki/view/891/account-activation-email
you can not use notification email like @gmail.com in the administrator panel -> site settings, notification email.

What is the notification email you have set there?

**Comment by mikeatencio** [comment]
atenciomike@yahoo.com is the email I have there for my email address. Should I use admin@indigomagick.com instead?

Michael Atencio 

    On Tuesday, June 9, 2020, 10:08:45 AM EDT, Arsalan Shah <notifications@github.com> wrote:  
 
 


https://www.opensource-socialnetwork.org/wiki/view/891/account-activation-email
you can not use notification email like @gmail.com in the administrator panel -> site settings, notification email.

What is the notification email you have set there?

**Comment by lianglee** [comment]
Use noreply@indigomagick.com

Make sure this email doesn't created from cpanel this email is always non
existing email.

>

**Comment by mikeatencio** [comment]
I'm sorry. I'm new to all of this. I just found the reply here. I answered through email. I'll change it to noreply. Thank you. Should I create the actual email or just put that in there?

**Comment by mikeatencio** [comment]
I see this is closed but in case anyone sees this, I changed the email to noreply. Thank you again for the fast reply.

**Comment by lianglee** [comment]
Hi Mike,

If your domain name is indigomagick.com and you changed the email to noreply@indigomagick.com and emails still not arriving please confirm.

**Comment by mikeatencio** [comment]
No one has commented back but I have noticed that I don't have to validate the new members now. I'm assuming that is the easy way to confirm. If you want to join to check, please feel free. I can delete you after we check. Thanks for the follow-up. I'm going to bed right now. It's 2 am here.Mike
Michael Atencio 

    On Wednesday, June 10, 2020, 01:22:42 AM EDT, Arsalan Shah <notifications@github.com> wrote:  
 
 


Hi Mike,

If your domain name is indigomagick.com and you changed the email to noreply@indigomagick.com and emails still not arriving please confirm.

**Comment by lianglee** [comment]
It worked for me  got a activation email
