### ISSUE TITLE
message_list get recent messages api

### ISSUE THREAD

**Issue by mayankgirdhar** [opensource-socialnetwork/opensource-socialnetwork#1741]
hey am getting this response if i try to get recent messages using rest api. sending guid 1 {
    "merchant": "AllUChat",
    "url": "http://localhost/",
    "time_token": 1592110155,
    "payload": false,
    "code": "200",
    "message": "No such a user exists"
}

**Comment by lianglee** [comment]
Share your complete endpoint URL and the parameters to admin@opensource-socialnetwork.org

**Comment by lianglee** [comment]
Sending guid 1 , if user with id doesn't exists you get such a error.
