### ISSUE TITLE
app galerie

### ISSUE THREAD

**Issue by goliath037912** [opensource-socialnetwork/opensource-socialnetwork#1742]
Hello, I have a huge problem with your component, the first 30 photos are displayed with a link, but the others, no hands, no link. Why ?

@keyframes slide-in-bck-center{0%{transform:translateZ(600px);opacity:0}100%{transform:translateZ(0);opacity:1}}
/* ----------------------------------------------
* Generated by Animista on 2020-6-14 17:9:47
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation text-blur-out
* ----------------------------------------
*/
@-webkit-keyframes text-blur-out {
0% {
-webkit-filter: blur(0.01);
filter: blur(0.01);
}
100% {
-webkit-filter: blur(12px) opacity(0%);
filter: blur(12px) opacity(0%);
}
}
@keyframes text-blur-out {
0% {
-webkit-filter: blur(0.01);
filter: blur(0.01);
}
100% {
-webkit-filter: blur(12px) opacity(0%);
filter: blur(12px) opacity(0%);
}
}

li.menu-section-item-showcase:before {
/* this replaces the icon '>' or content: "\f1c5" Cheat sheet: https://astronautweb.co/snippet/font-awesome/ /
content: "\f1c5" !important
}
/ [THUMBNAILS] */

gallery {

background:#fff!important;
padding-top:10px;
padding-left:10px;
padding-right:10px;
padding-bottom:10px;
height:auto!important;
border-radius:10px!important; 
border-bottom:8px solid #00ddff!important;
-webkit-box-shadow:2px 2px 7px 2px #ccc!important;
box-shadow: 2px 2px 7px 2px #ccc!important;
max-width: 100%;
margin: 0 auto;
}

gallery img {

border-radius:15px!important;
box-sizing: border-box;
width: 200px;
height: 137px;
padding: 5px;

-webkit-box-shadow:2px 2px 7px 2px #ccc;
box-shadow: 2px 2px 7px 2px #ccc; 
/* fill, contain, cover, scale-down : use whichever you like */
object-fit: cover;
cursor: pointer;
}

gallery img:hover {

border-radius:15px!important;
animation:text-blur-out 1.2s cubic-bezier(.55,.085,.68,.53) infinite alternate-reverse both}
-webkit-box-shadow:2px 2px 7px 2px #ccc;
box-shadow: 2px 2px 7px 2px #ccc;
box-sizing: border-box;
width: 200px;
height: 137px;
padding: 5px;
/* fill, contain, cover, scale-down : use whichever you like /
object-fit: cover; 
cursor: pointer;
}
/ [RESPONSIVE - MOBILE FRIENDLY] */
@media screen and (max-width: 850px) {
#gallery img { width: 33%; }
}
@media screen and (max-width: 640px) {
#gallery img { width: 50%; }
}

/* [LIGHTBOX BACKGROUND] */

lback {

position: fixed;
top: 0;
left: 0;
width: 100vw;
height: 100vh;
z-index: 999;

background-image:url('http://www.kikoo03.fr/img/fond_photo.png');
background-repeat:repeat!important:
opacity: 0;
visibility: hidden;
transition: all ease 0.5s;
}

lback.show {

opacity: 1;
visibility: visible;
}

/* [LIGHTBOX IMAGE] */

lfront {

text-align: center;
position: relative;
top: 50%;

transform: translateY(-50%);
}

lfront img {

border-radius:20px!important; 
animation:slide-in-bck-center 4s cubic-bezier(.25,.46,.45,.94) both;

max-width: 80vw;
max-height: 80vh;
}

/* [DOES NOT MATTER] */
body, html {
padding: 0;
margin: 0;
}

**Comment by lianglee** [comment]
Please provide some screenshot etc.

**Comment by lianglee** [comment]
closing as no response
