### ISSUE TITLE
[E] improve installer to check accessability of directories

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1749]
The installer should be improved to guarantee that the selected data directory is usable (also on different filesystems) and the cache subdirectory can be created.

**Comment by lianglee** [comment]
Agree, but when thing i doesn't understand is we have many component that uses file_put_contents i am afraid if we change only OssnFile class the standard file_put_contents may not work on different files-system. 

Besides that i agree with you to check ossn_data directory if it is writeable and owned by same user then we generate cache. We should also improve checklist page with improve checking feature for directories .

**Comment by githubertus** [comment]
Actually I don't think that there is any working (low-level) replacement for file_put_contents at all.
Because this is just a sequence of fopen, fwrite and fclose.
In other words: Either fopen IS allowed, or not - simply based on the rules of of the apache configuration. 
Or, to put it this way: Not Ossn needs to change its file i/o, but it's the task of the admin to mount his volumes that transparently that they/the permissions comply to rules of his apache configuration. This may be tricky, but possible I think. (for example see https://stackoverflow.com/questions/54507422/php-cannot-access-mounted-drive-in-ubuntu)

But what the installer COULD DO, is checking whether a file_put_contents on the chosen data_directory would work and issue a red warning if it would not.

**Comment by lianglee** [comment]
Nice saw that https://stackoverflow.com/a/54517389 so the only this is its configured properly no need for us to do anything with ossn.

Now with ossn_data directory checking i think we need :

1. During installation create a file with any contents in ossn_data directory specified
2 If done check the contents of files again 

If any of the failed then its not writable.

**Comment by immwi** [comment]
I had the same access issues as a user. 
If a directory is not writable, you can still help a user by showing the commands to execute, e.g.:
find /path/to/your/web/directory -type d -exec chmod 755 {} +
find /path/to/your/web/directory -type f -exec chmod 644 {} +

and to tell that the ownership has to be the webserver-user (maybe there is a nice command too)

cheers

**Comment by githubertus** [comment]
True, yes.
But we have to have those users in mind who don't have shell access.
Thus it would be more elegant if the installer does that job in advance if possible.
