### ISSUE TITLE
site-admin is unable to delete member posting in newsfeed

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#175]
relax, an easy one this time :+1: 
http://ossn.z-mans.net/components/OssnWall/actions/wall/post/delete.txt

**Comment by sathish4fri** [comment]
@githubertus  is this answer for that  or you just showing the code

**Comment by githubertus** [comment]
wrong line is comment out, change is working as is. no further actions necessary.

I've switched your account @ ossn.z-mans.net to admin - you may check yourself if you like. Feel free to add another user with normal permissions for testing.

In general:
If I have no idea, I'm sending a bug report only
If I have a working fix, I'm posting it here with the corresponding "zfix" number
And the fix gets applied to ossn.z-mans.net
If it is included with the next snapshot, the fix is replaced with the regular snapshot code
That's the circle ... :)

**Comment by lianglee** [comment]
Thanks will merge your patch. Hey do you know pull requests in github?

**Comment by sathish4fri** [comment]
may he wants us to give pull reqest . i will verify it and give a pull request bro

**Comment by githubertus** [comment]
@lianglee 
No, I've never used github before.

**Comment by sathish4fri** [comment]
@githubertus  fine bro . we will help you

**Comment by lianglee** [comment]
fixed
