### ISSUE TITLE
[E] thoughts regarding limited usage of ossn_site_settings()

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1752]
I saved some new settings of my theme in ossn_site_settings
and was a little surprised they were not retrievable like `ossn_site_settings('my_custom_setting')`
Okay, that's because OssnSite->getAllSettings() is fetching only the 'reserved' ones, I found.

So, currently I need to run several individual requests like
```
OssnSite->getSettings('my_custom_setting_1')
OssnSite->getSettings('my_custom_setting_2')
```
to get my values back.

So it could be helpful to enhance getAllSettings() like getAllSettings($reserved = true)
and inside add a variant to fetch those settings which are NOT reserved if false is passed to $reserved

This way I could at least get back all my custom_settings at once with just one getAllSettings(false) call.

**Comment by lianglee** [comment]
Done ;)

`echo ossn_dump((new OssnSite)->getAllSettings(false));`

**Comment by githubertus** [comment]
👍
