### ISSUE TITLE
can't clear a setting

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1753]
`public function setSetting($name, $value = '') {
				if(empty($name) || empty($value)) {
						return false;
				}`
Is it really necessary to check for  `empty($value) ` ?

Currently i circumvent by sending a blank, but input() doesn't allow a trailing blank, so I need fallback to $_POST['my_value']

Update: ok, don't mind
I'll change the logic in my action to add a blank if strlen(input()) == 0 
;)

**Comment by lianglee** [comment]
nope only name is required i'll pull new file

**Comment by lianglee** [comment]
fixed

**Comment by lianglee** [comment]
You can do if($input) then value = '')

>
