### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by margesch** [opensource-socialnetwork/opensource-socialnetwork#1775]
I try to install ossn on my environment, meet the requirements, however only "Make sure your files and directories are owned by correct apache user. https://www.opensource-socialnetwork.org/wiki/view/4378/directories-and-files-permissiom" marked pink, how to fix this, i already update .htaccess file then run chgrp usergroup path-to-ossn and chmod g+rwx path-to-ossn with no luck, please reply,,

**Comment by githubertus** [comment]
download the System Info component from
https://www.opensource-socialnetwork.org/component/view/1963/system-info
unzip it locally on your PC
read TOOLS-README.txt section B. and C.
verifyperms.php will tell you which permissions/owners need adjustment.
