### ISSUE TITLE
a little reminder only

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1776]
![verified-reminder](https://user-images.githubusercontent.com/9904364/88379199-c8792500-cda2-11ea-9a8c-8bf5c71baddf.jpg)

**Comment by lianglee** [comment]
Updated, I think this is the best way for me to remember stuff lol

**Comment by githubertus** [comment]
pfff ... still not quite ok ... this way we get verified label on wall comments only, not on entity comments ... (pics, blogs, etc)
should be
`Ossn.verifiedUsersInit('.ossn-wall-item .user a, .comments-item .owner-link', $usernames);`
