### ISSUE TITLE
getMyGroups throws PHP warning if user is not member of any group

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#179]
zfix 179 available, tell me how to pull

**Comment by lianglee** [comment]
Go to https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/master/components/OssnGroups/classes/OssnGroup.php

Edit file, save changes it will automatically redirect you to create pull request page

**Comment by lianglee** [comment]
I think we need to use if($myGroups){ //} ?

**Comment by githubertus** [comment]
right this was my idea. i just sent the pull request.

**Comment by lianglee** [comment]
merged #181
