### ISSUE TITLE
how can we insert image in chat box.

### ISSUE THREAD

**Issue by ajaymauryaftp-s** [opensource-socialnetwork/opensource-socialnetwork#1800]
can we implement new section to send image in chat box

**Comment by rolodexter** [comment]
any file size

**Comment by rolodexter** [comment]
**and

**Comment by ajaymauryaftp-s** [comment]
File size : around 2 mb


Just like facebook they provide option to upload any size of file.
But we can restrict a file size more than 2 mb

Thanks for replying

**Comment by lianglee** [comment]
Yes the functionality can be added. You can ask your developer to do that.   The size of image doesn't depends on the software it depends on your server configuration.  You can ask your provider to increase this for you.
