### ISSUE TITLE
[B] issue with account setting profile tabs

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1812]
please verify
components\OssnProfile\plugins\default\profile\menus\edittabs.php

I'm not quite sure what you were trying to achieve there ...
at least I'm not getting $params['name'] on my site
and so all my tabs look the same like 'profile-edit-tab-item-'
maybe you meant $args['name'] ?

and when I'm trying to pass my own class, it's not merged, but becomes a stand-alone-class

**Comment by lianglee** [comment]
Sorry it should be args['name'] its mistyped

**Comment by lianglee** [comment]
Maybe we can remove it completely profile-edit-tab-item-{$params['name']} as if someone wanted to set name they can use a class arg.
