### ISSUE TITLE
[E] placeholder for input/dropdown

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1813]
While working on the next release of the CountrySelector component
I found that there's currently no way to pass a real placeholder to the input/dropdown plugin
which would be a nice to have feature with the next Ossn.
I'm currently using a label instead but it may disturb the overall appearance
as on the registration form ...
![options-placeholder](https://user-images.githubusercontent.com/9904364/91873851-d3648680-ec79-11ea-93ad-f25e5fab81a7.jpg)

Here that bold printed "Country" doesn't really look good - a placeholder as already shown looks much nicer.
So, for now I ended with some extra jquery like
`$('#country-selector').prepend("<option value=\"\" disabled selected hidden>" + Ossn.Print('com:country:selector:label') + "</option>");`

but of course it would be smarter if input/dropdown would do that automatically if a placeholder is passed.

**Comment by lianglee** [comment]
Done
