### ISSUE TITLE
[E] radio-block css issue

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1814]
The main (outer) radio-block should have a different class than the single radio-block elements inside
![radio-block](https://user-images.githubusercontent.com/9904364/92043609-a1881880-ed7c-11ea-9a96-8cb8d34f449a.jpg)

Currently the class radio-block has no margin-bottom. That is, the next field in a form following the outer radio-block will be placed below without any distance - looking not so nice. Adding a bottom margin is of no real help though, as it would add some space on one hand to the outer block, but increase the distance of the inner blocks, too.

**Comment by lianglee** [comment]
i think parent should be renamed to radio-blocks-container

**Comment by lianglee** [comment]
Seems the issue was fixed in May 9.   Maybe you didn't copied new file https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/547117bf2eda23955d351cc41820321f2e66cd10

![image](https://user-images.githubusercontent.com/805066/98412498-d9238180-2099-11eb-8233-678ded2fe380.png)
