### ISSUE TITLE
MOD_REWRITE check broken with 2.0-dev?

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#182]
Trying to give some help with a screenshot in the forum I just stumbled over a problem:
When I'm trying to install the latest 2.0 dev snapshot, the installer gives RED rewrite not enabled
Old 1.8 installer gives BLUE rewrite okay (which in fact is the truth)
Just saw, that you added apache_rewrite.php 19 days ago
Please verify

**Comment by lianglee** [comment]
Ok thanks will verify it!

**Comment by moneya** [comment]
@lianglee have you verified this...
because i want to update my version to 2.0

**Comment by lianglee** [comment]
@moneya  2.0 is not available. I tested in my local system and its working fine

**Comment by githubertus** [comment]
Sorry, yes: can be closed.
Did a real world test on my providers space now: it's okay.
Seems, the configuration of my virtual machine at home is not quite correct ... missing fully qualified hostname ... things like that...

**Comment by githubertus** [comment]
Update:
The new mod_rewrite check's file_get_contents() failed with "php_network_getaddresses: getaddrinfo failed: Name or service not known.
Even with a correct IP -> servername line in /etc/hosts and having set "files" first in /etc/nsswitch.conf the PHP function insisted on asking the nameserver of my DSL gateway first, which is of course unable to resolve my local intranet addresses. Finally I got it working after installing an additional library (see http://0pointer.de/lennart/projects/nss-myhostname/)
Conclusion:
Perhaps there should be a fallback to the old 1.8 rewrite checking included if 2.0 fails?!?
Because a lot of potentially testers would give up at this point, I think.

**Comment by lianglee** [comment]
i think php_network_getaddresses is disabled in your php config, i need to remove url from file_get_contents() and point to simple file.

**Comment by lianglee** [comment]
in 1.8 its mod_rewrite fails on some devices

**Comment by lianglee** [comment]
How we can fix this"
* If we test rewrite using curl we don't need  file_get_contents::allow_urls enabled in php.ini

Drawbacks:
* many server don't have curl enabled by default, perhaps on installation user will get two errors php curl and apache rewrite

So i think we should choose curl? instead file_get_contents() ?

**Comment by githubertus** [comment]
No drawback if the rewrite check depends on curl. Because curl is needed anyway. But it would make sense to change order on the installation page and list the curl check _before_ the rewrite check.
This way, if the user has got it made to install curl, the rewrite checks prerequisite will be satisfied automatically.

**Comment by moneya** [comment]
@lianglee  it's just for dev. purpose

**Comment by lianglee** [comment]
fixed
