### ISSUE TITLE
Database?

### ISSUE THREAD

**Issue by carlosalvidrez** [opensource-socialnetwork/opensource-socialnetwork#1820]
Hi guys, what is the db or storage method used by this tool?
And, where is the code for it within the repo?
Thanks

**Comment by lianglee** [comment]
MySQL

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v5.x/classes/OssnDatabase.php

**Comment by carlosalvidrez** [comment]
Thank you. Do you have the scripts that define the tables in this repository?
I appreciate the link, yet what I am looking for is the actual DDL... it will accelerate my evaluation of the tool.
Thanks!
