### ISSUE TITLE
[E] New lines didn't appears on post/view/..

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1821]
[E] New lines didn't appears on post/view/.. 

(Need to be verified reported by someone)

**Comment by githubertus** [comment]
Can confirm that.

**Comment by lianglee** [comment]
thanks

**Comment by MaltaCross** [comment]
I also verify. 

In post/view/... the paragraphing formatting is lost, leading to an untidy appearance.

**Comment by lianglee** [comment]
Just tested on latest dev version it worked fine for me.
