### ISSUE TITLE
SSO Integration with Keycloak throught OAuth2 and OpenIDConnect

### ISSUE THREAD

**Issue by gabepurnam** [opensource-socialnetwork/opensource-socialnetwork#1825]
Opensource-socialnetwork can connect to keycloak for identity and authorization? I'm using Keycloak for providing centralized user-login feature for my apps and want to bring up this app to provide to my users a social network.

Thanks for this awesome job!

**Comment by lianglee** [comment]
You should see :  https://www.opensource-socialnetwork.org/discussion/view/4124/login-using-oauth-authentication-code-third-party-login-such-as-wordpress-etc

Everything is possible 💯
