### ISSUE TITLE
Problems with Password Reset by EMAIL inside of Apple Phone.

### ISSUE THREAD

**Issue by kreezxil** [opensource-socialnetwork/opensource-socialnetwork#1833]
We're having an issue with password resets via email that we didn't know existed and it results from the site forgetting our passwords. Or as others have suggested mixing them with other passwords on the site. I am not sure if our problem is related to the others so i have not tried to link them into this ticket.

Excerpt of a discussion with my team to help understand what is going on here.

```
sasakwa: Scott had his password reset on ##########.com.   He did a reset and it put him on a loop on his iPhone
```
![image](https://user-images.githubusercontent.com/3880072/97787205-c3382d00-1b7e-11eb-9eef-82feee003667.png)
```
sasakwa: I  reset his password manually  and he is trying to test to show me exactly what the errors are he gets resetting(edited)
sasakwa: I have reset my password successfully so I don't know why
sasakwa: He changed his password on the site - and it worked... but Apple has a problem with the password reset through email
```
![image](https://user-images.githubusercontent.com/3880072/97787242-fb3f7000-1b7e-11eb-91db-4d24c2ac8e63.png)
![image](https://user-images.githubusercontent.com/3880072/97787279-1316f400-1b7f-11eb-9668-96d819e16a69.png)
```
sasakwa: I surmised that perhaps php does not work so well working indirectly with Apple products
sasakwa: directly changing the password - he can do that on the site.  resetting with a link is the failure
Kreezxil: that's not a php to apple thing
Kreezxil: why did he have to reset this password in the first place?
sasakwa: He went to login and it said his password was wrong.  He said he thought it might be his apple keychain saved what he typed wrong.  So he deleted it and retyped it and still did not work.  Then he asked me if I could help get him into the site.  So I manually reset at that point.  He tested to try and show me what he was seeing (the screenshots) and then he changed it on the site itself in his account settings
```
**Noelle** is our fake test user
```
sasakwa: But Noelle also had a password reset.  I logged her out and she couldn't get in.  I used the reset by password and it worked for me
sasakwa: her password was saved by lastpass - not letting her in tells me it was something with the site itself corrupting the password
```

**Comment by lianglee** [comment]
Do you able to receive email for account activation? 
Which version of OSSN are you running?

Download https://www.opensource-socialnetwork.org/component/view/1963/system-info and provide output of this component.

**Comment by lianglee** [comment]
Further see:  https://www.opensource-socialnetwork.org/wiki/view/891/account-activation-email 
Please answer above questions.

**Comment by kreezxil** [comment]
the user scott receive the email on his iphone. it's that link in
there that failed.

**Comment by lianglee** [comment]
@kreezxil your reply contain not complete answer.  Please specify more details like OSSN version.

Contact me on arsalan@softlab24.com and send me your web hosting details and the website admin details I shall take a look into the issue.

**Comment by lianglee** [comment]
Seems I am facing similar issue on 5.5 , we'll let you know feedback soon, please do not send us anything.

**Comment by lianglee** [comment]
Ok just to update it finally,  it works fine , i was testing on wrong password reset email. What i beleive your user

1. Reset password
2. Waited for email link but email didn't arrived
3. Reset again 
4. Got email but it was actually the first email he was looking for
5. Upon saving password it give him error
