### ISSUE TITLE
I can't get pass this page

### ISSUE THREAD

**Issue by sanubi246** [opensource-socialnetwork/opensource-socialnetwork#1835]
I can't get pass this page what do I do?
![Screenshot 2020-11-06 221312](https://user-images.githubusercontent.com/74085998/98431690-496fda00-207d-11eb-8aab-969740a23570.png)

**Comment by lianglee** [comment]
It make sense because it asked you to upload at least 400px X 400px image but you uploaded 170px x 170px , i have changed your photo it should work now.

**Comment by lianglee** [comment]
We are checking the issue, sorry

**Comment by lianglee** [comment]
you should able to login now
