### ISSUE TITLE
poke issue

### ISSUE THREAD

**Issue by moneya** [opensource-socialnetwork/opensource-socialnetwork#184]
@lianglee @sathish4fri @githubertus 
have you notice this
          i can't poke a friend in 2.0 dev 
gives error   The action you requested is invalid.

**Comment by githubertus** [comment]
thanks for reporting, moneya
just made a pull request.
see https://github.com/githubertus/opensource-socialnetwork/commit/45a7dee46a9b659df5602d0459b49fd585ccde38

**Comment by lianglee** [comment]
Thanks @githubertus (I copied code from your branch, it seems github didn't sent pull request to our repository)
