### ISSUE TITLE
Cant upload images to new posts

### ISSUE THREAD

**Issue by scothost** [opensource-socialnetwork/opensource-socialnetwork#1844]
Hi 

Could you point me towards the File Upload Code?

Each time i create a new post and choose an image to upload  it fails. There is no error logged and the file is on the file system but is always 0B in size, all file permissions are correct. 

If I then add a comment to this post and upload an image on the comment it works perfectly, I get this issue regardless what theme I am using

Debian GNU/Linux 10 (buster)
Apache 2.4. PHP 7.4

**Comment by lianglee** [comment]
Hi, you should see https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error  CASE B and let us know once done
