### ISSUE TITLE
Site on Wheel of death! 

### ISSUE THREAD

**Issue by ulanded001** [opensource-socialnetwork/opensource-socialnetwork#1847]
Dears , I loaded plugins and tried to change the video Background. 
I have Flushed cache , and the  poof! 
The site is not loading.. is there any way to force the site to finish the flush or restart  or save  this situation to make it work again ?

**Comment by ulanded001** [comment]
this is the site : https://ulanded.com/Social_uLanded/

**Comment by githubertus** [comment]
See 
https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error
case B
