### ISSUE TITLE
Will not access administration setup page. 

### ISSUE THREAD

**Issue by jmhodges196** [opensource-socialnetwork/opensource-socialnetwork#1850]
I want to try opensource Social Network. I have installed in Windows Server 2012, with xamp server. In the setup process php shows all extension in green. In the database setup everthing setsup ok. When it goes to setup admin page User and password it gives me the following error.

A system error has occurred. Please try again later. You may email the details of this error to the system administrator at mail@exsample.com.
#1611189777|DAAMFDK51L08M3O61SAG4E1OG1

I can open the application and register new user however it will not send verification to my email so even to register a regular user cannot login do to need to validate email. 

Any advise out there.

**Comment by lianglee** [comment]
See community and provide some details
