### ISSUE TITLE
updating fields in About

### ISSUE THREAD

**Issue by dvaccaro902** [opensource-socialnetwork/opensource-socialnetwork#1851]
When attempting to update fields in users "about" it throws the error "All Fields Are Required" even though those fields are set to NOT REQUIRED in the admin.

**Comment by lianglee** [comment]
Which version of OSSN are you running ? free paid?  which release / version 5 dot what?

**Comment by dvaccaro902** [comment]
Good morning.
We are running the paid version.
5.6


Sent from my mobile device. Please excuse any typos or brevity.

On Jan 23, 2021, at 8:52 AM, Arsalan Shah <notifications@github.com> wrote:

﻿

Which version of OSSN are you running ? free paid? which release / version 5 dot what?

**Comment by jmhodges1968** [comment]
Thank you for answering I was able to fix it. I had installed ver. 8 xampp server in a windows server 2012 environment. That did not work. So I lowered the version xampp to 7.4 and it worked fine. At this time I am running the free version social network. I want to see how it will handle with the equipment I have. If everything good I will purchase the premium. Thanks
