### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by bobqwertyuiop123** [opensource-socialnetwork/opensource-socialnetwork#1853]
<img width="1884" alt="Immagine" src="https://user-images.githubusercontent.com/78279943/106368501-30a85500-634a-11eb-8d26-3f3319a4de9f.png">
Windows 10 Pro
Have been trying to get access through EasyPHP Devserver 17.0
PHP7.1.13 x86
MySQL 5.7.17 x86

**Comment by lianglee** [comment]
We don't support testing on windows
