### ISSUE TITLE
MentionUsers 1.9.1 issue

### ISSUE THREAD

**Issue by Tagoloan** [opensource-socialnetwork/opensource-socialnetwork#1855]
Hello after typing @username or @fullname into the comment section the receiver successfully received the notification in there mobile or desktop device. However upon clicking the notification icon/link both located in the top-right corner and left column in the menu link then redirected to the page where he/she was commented it returned "404 The page you requested is unavailable or may have been deleted."

When there is no deletion happen on my photo.

Any help is highly appreciated. :)

**Comment by lianglee** [comment]
You should contact MentionUsers component developer it is not created by core team but some community member.

**Comment by Tagoloan** [comment]
I understand. Thanks :(
