### ISSUE TITLE
[E] OssnPhotos -> Fancybox issue and feature request

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1858]
1. currently used version 3.0.47 is throwing "Uncaught (in promise) TypeError: Not in fullscreen mode" whenever closing the gallery
I have tested 3.1.20 which would fix this issue. A little outdated, too. But later versions seem to be no more really compatible with Ossn's jquery

2. I'd suggest to load the Fancybox unconditionally to allow other components making use of it.

**Comment by lianglee** [comment]
Will later version work with jQuery 2.2.x ?  I am thinking to move to JQuery 3.x but its too much work we need to rewrite a OssnPagination 3rd party library and boostrap 3.x didn't work with 3.x

**Comment by lianglee** [comment]
Updated to 3.5.7 

Others compnent may include;

```
ossn_load_external_css('jquery.fancybox.min.css');
ossn_load_external_js('jquery.fancybox.min.js');
```
