### ISSUE TITLE
feature request: notification on group joining requests

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#186]
I was not so happy with the current implementation: If you are running many groups, you need to check every group individually whether there are new requests or not. It's much easier if you got notified.
Question: Is anyone of you already working on this?
If not: I got it working!  (check working patch on my testsite)
Yes, yes ... I should have asked in advance ... but I forgot time ... as often when I'm doing things like that ...  :)

**Comment by sathish4fri** [comment]
good . give a pull request

**Comment by lianglee** [comment]
+1, can you post code here? or i'll write new one.

**Comment by sathish4fri** [comment]
write a new one is time waste . better we ask him to give pull request . we must work on other works .

**Comment by githubertus** [comment]
pulls done

**Comment by sathish4fri** [comment]
nice work michale

**Comment by sathish4fri** [comment]
@githubertus pull request not done you just added in your fork project push here

**Comment by githubertus** [comment]
done! 
sorry, I wasn't aware I have an "edit" pencil in the master branch right now.

**Comment by sathish4fri** [comment]
cool

**Comment by lianglee** [comment]
merged
