### ISSUE TITLE
[B] OssnSearch searchstring en-/de-coding issues

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1863]
as reported on
https://www.opensource-socialnetwork.org/component/view/3308/search-posts

**Comment by githubertus** [comment]
not reproducable from my side
search?q=測試 is passed correctly here without being encoded to %xyz
more info requested

**Comment by lianglee** [comment]
Not using that component though but search for users worked : https://demo.opensource-socialnetwork.org/search?q=%E6%B8%AC%E8%A9%A6

> demo.opensource-socialnetwork.org/search?q=測試
