### ISSUE TITLE
[B] Wall site crash when mentioning members under certain conditions.

### ISSUE THREAD

**Issue by scfduffy** [opensource-socialnetwork/opensource-socialnetwork#1865]
I'm running ossn at libsoc.net.

If someone mentions a member in a post and the member mentioned is subsequently deleted, the site squirts out until the mentioned member point is reached then crashes with a call trace dump. This can be fixed by admin by deleting the post but while the post exists, anyone with that post on their feed sees a big ugly crash report.

So member A says 'hello B' and tags member B into a post. Member B gets deleted from userlist and member A,C through Z visit the site and get that post on their feed. The feed stops after that post with a call trace report.

Something like 'if (memberExists(mentionedMember)) {...}' is needed somewhere as on a large site, admins may not be able to see a crash is happening for users with that post on their feed.

**Comment by lianglee** [comment]
Fixed
