### ISSUE TITLE
Are short lifetime cookies a minor issue?

### ISSUE THREAD

**Issue by scfduffy** [opensource-socialnetwork/opensource-socialnetwork#1866]
The cookie expires pretty quickly or its a session cookie. 9/10 I have to login again. Most sites do 7 or 30 day cookies. Id prefer an admin option for cookie expire or a 30 day duration as logging in is a minor inconvenience.

**Comment by lianglee** [comment]
@scfduffy this is session cookie OSSN didn't set any cookie but for session it is set by php. You need to adjust the session time in php settings.
