### ISSUE TITLE
Site slow by images

### ISSUE THREAD

**Issue by jurjendevries** [opensource-socialnetwork/opensource-socialnetwork#1869]
Ossn version: 5.6 paid
PHP version: 7.4
Error message: None
Error Log: n/a
Issue screenshots: n/a
Cache: enabled

The OSSN loading time is very high. Visitors have to wait between 4-8 seconds mostly before a page is showing its content. We used a shared PHP/MySQL hosting, were we used the phpBB forum system before. We didn't had slow loading issues with that system.

According Lighthouse in Chrome DevTools one of the reasons is a lot of low compressed and non-resized images.
![Screenshot 2021-04-05 14 19 46](https://user-images.githubusercontent.com/355488/113573291-23de0100-961a-11eb-864e-2432d7b6cf2b.png)

One of the possibilities to fix this issue is to compress and resize the images within OSSN after the user uploaded an image. WebP is one of the better compressing and widely supported formats https://www.php.net/manual/en/function.imagewebp.php and https://www.php.net/manual/en/function.imageresolution.php are possibly good starting points for devs to embed this in OSSN.

**Comment by lianglee** [comment]
Should try this : https://www.opensource-socialnetwork.org/component/view/3868/reduce-images-size and edit the component based on your need. 

I don't think we need a webp most of the devices don't support it we'll stick to standard images (png, jpeg etc).  Even if we use webp only for output it will still reduce the performance as for each image it need to work again and again to convert image to webp.

**Comment by lianglee** [comment]
@jurjendevries with that component you can add a new one that will reduce image dimensions and with the combination of that component it will surely reduce the size to much more smaller.

```
function change_max_dim_image_upload_init(){
		ossn_add_hook('file', 'image:resolution', 'change_max_dim_image_upload');
}	
function change_max_dim_image_upload(){
		return array(
			'width' => 1048,
			'height' => 1048
		);
}
ossn_register_callback('ossn', 'init', 'change_max_dim_image_upload_init');
```
