### ISSUE TITLE
hide long status post

### ISSUE THREAD

**Issue by moneya** [opensource-socialnetwork/opensource-socialnetwork#187]
add jquery see more feature for long post when status is updated
create infinite pagnation instead of normal pagnation

**Comment by lianglee** [comment]
+1

**Comment by sathish4fri** [comment]
+1

**Comment by sathish4fri** [comment]
@lianglee  this one is completed right .

**Comment by lianglee** [comment]
yes

**Comment by moneya** [comment]
@lianglee  @satish4fri  it's not yet complete   
it remains  this   create infinite pagnation instead of normal pagnation

**Comment by moneya** [comment]
@lianglee@sathish4fri it's not yet completeit remains this create infinite pagnation instead of normal pagnation

**Comment by moneya** [comment]
@lianglee@sathish4fri it's not yet completeit remains this create infinite pagnation instead of normal pagnation

**Comment by moneya** [comment]
@lianglee  @sathish4fri it's not yet completeit remains this create infinite pagnation instead of normal pagnation

**Comment by githubertus** [comment]
Can't follow? What do you mean with LONG status post?
Pagination starts after a specified number of postings - not after a specified number of lines.
So what is your request? To split/paginate one SINGLE overlong posting across two or more browser pages?

**Comment by moneya** [comment]
@githubertus
by infinite pagination i meant something like facebook getting items via ajax,instead of 1,2,3-etc...

**Comment by lianglee** [comment]
use readmore
