### ISSUE TITLE
Site slow by inefficient (4 hours) caching time

### ISSUE THREAD

**Issue by jurjendevries** [opensource-socialnetwork/opensource-socialnetwork#1870]
Ossn version: 5.6 paid
PHP version: 7.4
Error message: None
Error Log: n/a
Issue screenshots: n/a
Cache: enabled

The OSSN loading time is very high. Visitors have to wait between 4-8 seconds mostly before a page is showing its content. We used a shared PHP/MySQL hosting, were we used the phpBB forum system before. We didn't had slow loading issues with that system.

According Lighthouse in Chrome DevTools one of the reasons is due inefficient client side caching time of files such JS/CSS/images.
![Screenshot 2021-04-05 14 38 02](https://user-images.githubusercontent.com/355488/113574581-aff12800-961c-11eb-9864-c4f714e11da8.png)
I agree to this Ligthouse suggestion because a lot of the visitors are returning after 4 hours, while the files are still the same.

One of the possibilities to fix this issue is to provide a TTL setting at the caching admin section of OSSN.

**Comment by lianglee** [comment]
Did you tried this one? https://www.opensource-socialnetwork.org/component/view/3868/reduce-images-size

**Comment by jurjendevries** [comment]
@lianglee I think that is more related to https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/1869 ? This source doesn't had anything to do with caching TTL.

**Comment by lianglee** [comment]
Yes you are right the comment is for #1869  besides that cache time is decided by your server apache settings,  you may try to adjust in apache .htaccess settings.

**Comment by jurjendevries** [comment]
@lianglee I know it can be done in .htaccess or webserver settings, how ever the owner of the license isn't that technical and I don't have access to it. A lot of apps are providing a friendly user experience by giving an option to set this kind of parameters in the admin panel. So this request is to put it in the admin caching setting page.

**Comment by lianglee** [comment]
See
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/226404cd2f5f7ba6af1fe2d51cb6db5dfc26241a/installation/configs/htaccess.dist#L29


Cache expires set to 1 year in config. I am not sure where you are getting
this 4 hours cache time. Must be something on your server settings. Or i am
missing something.
