### ISSUE TITLE
Site slow by render-blocking resources 

### ISSUE THREAD

**Issue by jurjendevries** [opensource-socialnetwork/opensource-socialnetwork#1871]
Ossn version: 5.6 paid
PHP version: 7.4
Error message: None
Error Log: n/a
Issue screenshots: n/a
Cache: enabled

The OSSN loading time is very high. Visitors have to wait between 4-8 seconds mostly before a page is showing its content. We used a shared PHP/MySQL hosting, were we used the phpBB forum system before. We didn't had slow loading issues with that system.

![Screenshot 2021-04-05 15 52 00](https://user-images.githubusercontent.com/355488/113581115-fba8cf00-9626-11eb-81bd-0ae5aacd4964.png)

According Lighthouse in Chrome DevTools one of the reasons is due render-blocking resources. The advice is to eliminate those by suggestions from https://web.dev/render-blocking-resources/ . Related to bootstrap https://stackoverflow.com/questions/59291767/how-to-improve-eliminate-render-blocking-resources-for-lighthouse-report-pwa , and related to jquery https://medium.com/@glenmichaelsen/google-pagespeed-insights-eliminate-render-blocking-javascript-and-css-in-above-the-fold-content-6005881e0e25

**Comment by lianglee** [comment]
Did you tried this one? https://www.opensource-socialnetwork.org/component/view/3868/reduce-images-size

**Comment by lianglee** [comment]
These JS are required and can not be removed if we eliminate these blocks then the site will not work

**Comment by jurjendevries** [comment]
@lianglee I didn't mean remove the Javascript. But as suggested in the links program them differently.

**Comment by jurjendevries** [comment]
@lianglee can you please re-open the issue. I can't find a button for it.

**Comment by lianglee** [comment]
@jurjendevries please let us know why you wanted to open it? how do you wanted to program them differently?

**Comment by jurjendevries** [comment]
@lianglee If I understand you will you closed this issue because you thought that by 'eliminate' the javascripts it is about removing them. I don't mean removing javascript files, but by 'eliminate' I mean eliminate render-blocking. This means optimizing the code how the javascript files are handled so it won't affect first paint of the page. At the links provided in the start of this thread its shown how to program it differently.

**Comment by lianglee** [comment]
There is no way for us to rewrite entire jQuery, Bootstrap and CSS files.
Many of them are external libraries.

**Comment by lianglee** [comment]
Besides that most of these files like jQuery, Bootstrap, CSS must loaded
before the first paint.  They can't be deferred.

If you have any new findings after testing you can share it with some
working solution.

Believe me i have tried these many years ago 😄😄 no luck!

**Comment by jurjendevries** [comment]
@lianglee Have you seen the bottom of https://medium.com/@glenmichaelsen/google-pagespeed-insights-eliminate-render-blocking-javascript-and-css-in-above-the-fold-content-6005881e0e25 , it is described for jquery.

**Comment by lianglee** [comment]
I tried most of things (async, deferred). OSSN entire library requires
jQuery to be loaded first.

However you can give a try in
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/226404cd2f5f7ba6af1fe2d51cb6db5dfc26241a/libraries/ossn.lib.javascripts.php#L159


You can tell me your findings and comparisons.
