### ISSUE TITLE
Security reports bootstrap 3.3.4

### ISSUE THREAD

**Issue by jurjendevries** [opensource-socialnetwork/opensource-socialnetwork#1872]
Ossn version: 5.6 paid
PHP version: 7.4
Error message: None
Error Log: n/a
Issue screenshots: n/a
Cache: enabled

Bootstrap 3.3.4 which is part of OSSN 5.6 is having multiple Cross-site scripting (XSS) securiy reports https://www.cvedetails.com/vulnerability-list/vendor_id-19522/product_id-51406/version_id-286026/opxss-1/Getbootstrap-Bootstrap-3.3.4.html
My suggestion would be to update Bootstrap to the latest version.

**Comment by lianglee** [comment]
See https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/1874#issuecomment-813474191

**Comment by lianglee** [comment]
Bootstrap 5.x will be used in OSSN 6.0 see the changes has been with the great efforts 

https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/4a43b5b5a2774a280c440a1268ccf5211643d60a
