### ISSUE TITLE
Site slow by not bundling and minifying JS/CSS

### ISSUE THREAD

**Issue by jurjendevries** [opensource-socialnetwork/opensource-socialnetwork#1875]
Ossn version: 5.6 paid
PHP version: 7.4
Error message: None
Error Log: n/a
Issue screenshots: n/a
Cache: enabled

The OSSN loading time is very high. Visitors have to wait between 4-8 seconds mostly before a page is showing its content. We used a shared PHP/MySQL hosting, were we used the phpBB forum system before. We didn't had slow loading issues with that system.

According Chrome DevTools multiple JS (10) & CSS (6) files are served.

One of the possibilities to fix this is to minify and bundle JS & CSS files. Minifying JavaScript files can reduce payload sizes and script parse time. Minifying CSS files can reduce network payload sizes. Bundle files keep request counts low.

A good source for PHP to add this functionalities is https://www.purcellyoon.com/insights/articles/php-easily-combine-css-javascript-files

**Comment by lianglee** [comment]
Invalid,  JS and CSS are minified when enabled cache.  There is no way you can remove multiple CSS, JS.  You should avoid this google analysis most of the suggestions are not correct on these tools.
