### ISSUE TITLE
Site slow by not file caching dynamic content

### ISSUE THREAD

**Issue by jurjendevries** [opensource-socialnetwork/opensource-socialnetwork#1876]
Ossn version: 5.6 paid
PHP version: 7.4
Error message: None
Error Log: n/a
Issue screenshots: n/a
Cache: enabled

The OSSN loading time is very high. Visitors have to wait between 4-8 seconds mostly before a page is showing its content. We used a shared PHP/MySQL hosting, were we used the phpBB forum system before. We didn't had slow loading issues with that system.

According to my findings at the admin caching section I am missing server side file caching of dynamic content. This is common for PHP/MySQL applications with a lot of queries. Not having this will put PHP & MySQL in to work for every page/database request. Which can create a heavy load quickly and slows down page load time, especially when the server is limited in resources.

My suggestion is to add server side caching and clear the cache of a specific page when it is updated.

**Comment by lianglee** [comment]
How do you purpose server side caching for dynamic contents? Please provide more details and with examples for dynamic contents like wall post can be changed,  comments can be updated, site settings can be changed and users settings can be changed anytime.

**Comment by lianglee** [comment]
@jurjendevries try using cloudflare.

**Comment by jurjendevries** [comment]
@lianglee Cloudflare doesn't know when a MySQL database is updated. It is for serving pages that are requested many times and doesn't change often.
I don't know the OSSN architecture, so I think it is easier for you to decide how to cache server side exactly. There might be some best practices to deep dive into from other open source PHP/MySQL apps that handle a lot of queries such as Wordpress https://blog.testomato.com/caching-wordpress-website/ & phpBB https://wiki.phpbb.com/Cache

**Comment by lianglee** [comment]
We have cached the things that are possible. You should see what's exactly
in OSSN is cached. Its not only JS and css files.

Besides that database things can not be cached they can change anytime and
nothing is static.

I suggest you to run your network on a VPS with dedicated memory and SSD
like digital ocean and linode offers, you will see a huge difference.
Depending on you users you choose the hardware requirements.

**Comment by jurjendevries** [comment]
@lianglee Okay thanks for informing. Why isn't are clear cache setting or so at the admin cache panel? I also couldn't find any documentation for it.
I think it is too easy to say that the owner has to upgrade its hosting if it is not needed. It costs more, so less money to spent in your software if it is spent to the hosting party. Also using more system resources is bad for the nature environment, because it is costing more electricity. phpBB is also a very large PHP/MySQL project and works very fast on the same shared hosting environment. How ever beside the good speed of phpBB it didn't provided the functions that the owner was looking for, so he decided to move to OSSN.
Did you checked the best practices by Wordpress and phpBB, there are a lot of caching mechanisms such as Page Caching, Database Caching, Object Caching and Opcode Caching.

I also don't understand why you say database things can not be cached. It can be in any PHP/MySQL app, so it can in OSSN. And yes, they can change anytime, but won't change any time. So as long as they are not changed, they can be cached.

**Comment by lianglee** [comment]
You can flush cache (clear cache) from admin panel. On dashboard there is a
button in bottom right corner.

Believe me i tried everything to cache things and caching what is possible
right now. That doesn't mean we stopped looking for different solutions. We
will try our best to facilitate the progress of it.

Since it is open source we welcome any pull request to improve the product.
You can look inside code and provide us a pull request we shall merge it
after reviewing it.

WordPress is a blogging CMS whereas OSSN is a social networking. Cache uses
the file system where as database is more efficient to use.

Would you mind sharing your website URL so i can take a look? (You can open
ticket on softlab24 and tell them i told you to do)

Which release of paid social network are you running? Latest release of 5.6?

You should also note that paid license questions should be asked directly
on softlab24.

These questions of yours relates to free version so i haven't removed them.

🙂👍

**Comment by lianglee** [comment]
@jurjendevries I was going through our discussion again in this thread my question to you for your question `....My suggestion is to add server side caching and clear the cache of a specific page when it is updated......`

How would suggest us to create a page cache for newsfeed page,  users profile page,  messages page,  groups page? as they changes every second.

**Comment by lianglee** [comment]
Closing as no feedback.
