### ISSUE TITLE
Please help me with installion

### ISSUE THREAD

**Issue by rustymarbon** [opensource-socialnetwork/opensource-socialnetwork#1902]
I have taken many steps configuring vps finally got OSSN installed but have blank pages.
have uploaded verifyperms.php and ossninfo.php.

https://aussiecoasterclub.com/OSSN%20Full%20Professional/ossninfo.php

I really appreciate all you do as a team to give the community this software I really like it but sad I have tried every thing

**Comment by githubertus** [comment]
what should your link with spaces give?

**Comment by rustymarbon** [comment]
That was how the folder was named

**Comment by githubertus** [comment]
On a webspace file and directory names with spaces or any other special characters are known to cause issues in general.
You simply should avoid them.
