### ISSUE TITLE
feature request: localization of 'passed time' in postings and comments

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#192]
in English we can simply add an 's' - and day becomes days.
At least in German it's not that easy.
And: we don't say '8 days AGO', we say 'VOR 8 Tagen'

Do you have already a solution for ossn_user_friendly_time() ?
If not, I can provide a working idea I had yesterday.

**Comment by lianglee** [comment]
Let me try

**Comment by githubertus** [comment]
Sorry, does it mean: YOU will work on that?

**Comment by lianglee** [comment]
Hmm, what i have is to edit ossn_user_friendly_time():
* Change return $x . ' ago'; to return ossn_print("ossn:time:ago"; array($x));
* Add ossn_print to each $pds = arrays();
* Add translations to language file?

I have no idea if it works, if you have other solution feel free to share or send pull request.

**Comment by githubertus** [comment]
ok. 2 pull requests sent.

**Comment by lianglee** [comment]
merged
