### ISSUE TITLE
[E] syncing privacy message box with latest setting

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1927]
currently we have the issue:
open newsfeed
privacy icon is set to PUBLIC
click privacy
message box opens
select FRIENDS, close box
privacy icon is set to FRIENDS correctly

click privacy again
message box still shows PUBLIC selected
which is really irritating

to sync the latest setting inside of the message box, 
the fix would be to put that code into forms/OssnWall/privacy

```
$('#ossn-wall-privacy-container input[name="privacy"]').attr('checked', false);
$('#ossn-wall-privacy-container input[value=' + $('#ossn-wall-privacy').val() + ']').attr('checked', true);
```

What do you think about that?

Additionally, we may use a cookie to remember the last setting when visiting a wall again

**Comment by lianglee** [comment]
I think we need to store it in cookie or local storage because many users said their last privacy is not retained in the website if they login again.  

I don't want to waste other DB entry or entity for user so I was thinking to store in local Storage of browser so next time we can get it from there. This requires extra work I think.  

But your solution is good for current implementation.

**Comment by githubertus** [comment]
I gave the cookie solution a try this afternoon, and it's working quite fine already.

What I would ask for is if could make javascript read and write cookie functions globally available for Ossn.
Currently we have these functions already in OssnSound - so I was using them for my tests.
But because we can't rely that everyone has OssnSound enabled, it would be better to move these functions into the system library.
if you would do that, I will remove them from OssnSound.

**Comment by lianglee** [comment]
Yes Agree with moving to system library

**Comment by githubertus** [comment]
please when doing that transfer, make the write function to accept smaller times, at least minutes
maybe we need that sometime ... :)

**Comment by lianglee** [comment]
```
var date = new Date();
date.setTime( date.getTime()+(1*60*1000) );
Ossn.setCookie('test', 'abc', date);
```

**Comment by lianglee** [comment]
```
var date = new Date();
date.setTime( date.getTime()+(1*60*1000) );
Ossn.setCookie('test', 'abc', date);
console.log(Ossn.getCookie('test'));
```

**Comment by githubertus** [comment]
thanks for core cookie lib 👍 
i'm done with changes for post privacy cookies now
see pulls #1935, #1937, #1938, #1939
