### ISSUE TITLE
[B] chat bell almost unreachable

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1933]
maybe due to the new bootstrap or you changed something else
the main upper part of the bell is overlapped now
so there's only a small part left at the bottom which is clickable
![chatbell-overlapping](https://user-images.githubusercontent.com/9904364/117533944-9cf0bf80-afef-11eb-8f9d-7b0a659869c4.JPG)

**Comment by lianglee** [comment]
Yes was facing this issue last night. I will look deeper into it tonight.

**Comment by githubertus** [comment]
fixed with #1942
