### ISSUE TITLE
MOD_REWRITE REQUIRED 

### ISSUE THREAD

**Issue by thushy07** [opensource-socialnetwork/opensource-socialnetwork#1945]
Trying to install the ossn, I am having issue with the MOD_REWRITE REQUIRED 

A server running Ubuntu 18.04 LTS
A non-root user with sudo privileges.

sudo apt-get install apache2 mariadb-server php7.1 php7.1-mysql php7.1-curl php7.1-json php7.1-cgi libapache2-mod-php7.1 php7.1-mcrypt php7.1-xmlrpc php7.1-gd php7.1-mbstring php7.1 php7.1-common php7.1-xmlrpc php7.1-soap php7.1-xml php7.1-intl php7.1-cli php7.1-ldap php7.1-zip php7.1-readline php7.1-imap php7.1-tidy php7.1-recode php7.1-sq php7.1-intl wget unzip -y

I am running in a local box, i am accessing with the local IP to deploy it, but its getting stuck at  "MOD_REWRITE REQUIRED "

any help will be appreciated 
Thank you

**Comment by lianglee** [comment]
Use https://www.opensource-socialnetwork.org/wiki/view/3994/how-to-install-ossn-on-ubuntu-1804-2004-x64-using-command-line  on fresh installation of Ubuntu 18.04 or 20.04
