### ISSUE TITLE
[B] Inconsistency of privacy master wall setting

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#1953]
if set to 'friends-only', posts of no friends are still visisible on profile pages,
see report of Guy Ler Shyze on https://www.opensource-socialnetwork.org/discussion/view/3281/

**Comment by lianglee** [comment]
Yup!

**Comment by lianglee** [comment]
This issue becomes obsolete with commits mentioned in #1960
