### ISSUE TITLE
checkboxes handler for OSSN

### ISSUE THREAD

**Issue by COM2GAY** [opensource-socialnetwork/opensource-socialnetwork#1956]
HI

I need the option to save checkboxes under OSSN.
Unfortunately, OSSN cannot do that by default. How can I do that?

**Comment by githubertus** [comment]
Unfortunately?
I mean, your site would collapse sooner or later if any entered html would be saved BY DEFAULT. ;)
Of course it needs a little coding. Install the GreenByGreen theme and you'll find a working example at
YOURSITE/administrator/settings/GreenByGreen3
![checkbox-saving](https://user-images.githubusercontent.com/9904364/118609471-11c7b480-b7bb-11eb-8d98-769bdb943249.JPG)

**Comment by COM2GAY** [comment]
I suspect that YOU did not understand my question.

The point is that I need the ability to save checkboxes.

Since I'm still new to OSSN and unfortunately haven't found a useful howto that explains how the core works, I thought someone could help me here.

**Comment by githubertus** [comment]
The example I provided DOES save a checkbox (aside from 2 radio buttons).
It's up to you to add as many checkboxes as you want and the code to save/fetch them accordingly

**Comment by COM2GAY** [comment]
The point is that the following scenario should be covered:

Hobbies:

Checkbox 1: Read
Checkbox 2: Listen to music
Checkbox 3: Travel
...
...
...

This works if I only have one checkbox, but if I select several checkboxes, only one is saved.

**Comment by lianglee** [comment]
@githubertus actually we need to make sure input/checkbox have option to take multiple values so we know which are selected options.  Right now it didn't support.

**Comment by githubertus** [comment]
I'm not aiming to spread confusion, but with the AdsInserter component I'm able to save even 4 checkbox settings individually.
![adsinserter-settings](https://user-images.githubusercontent.com/9904364/118657734-05a81b00-b7ec-11eb-8a5b-6b4bc66f2b31.JPG)

**Comment by lianglee** [comment]
Sorry it worked well, closing this ticket.

I was confusing this with radio boxes ,  check boxes can work this way

```
$hobby1_checkbox =  array(
			'name' => 'hobby1',
);
if($user->hobby1 == true){
	$hobby1_checkbox['checked'] = 'checked';	
}
echo ossn_plugin_view('input/checkbox', $hobby1_checkbox);

$hobby2_checkbox =  array(
			'name' => 'hobby2',
);
if($user->hobby2 == true){
	$hobby2_checkbox['checked'] = 'checked';	
}
echo ossn_plugin_view('input/checkbox', $hobby2_checkbox);

```

**Comment by COM2GAY** [comment]
Thanks, but that's not the problem, the output of the options works.
The problem is that the entries are not saved, only the last option is saved.

The Ads Insider component is a system component, where the options are saved differently from the user fields.

**Comment by lianglee** [comment]
@COM2GAY  you seems talking about custom fields component it didn't support officially a checkboxes as suggested you need to wait until its be handled by softlab internally.
