### ISSUE TITLE
notification popup window misplacement

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#196]
(reported in the community yesterday by ashwni kumar)

![notification-placing](https://cloud.githubusercontent.com/assets/9904364/5706364/850afe02-9a80-11e4-8bd7-9a98efe9142a.png)
currently calculation is based on a _fixed_ margin-right: 208px in .ossn-notifications-box
but actually this depends on a _variable_ browser width
thus making the notification window floating to wrong horizontal positions
perhaps jquery can calculate the correct value before opening?!

**Comment by sathish4fri** [comment]
yes +1

**Comment by githubertus** [comment]
just tried something I'll push
I've very little jquery knowledge
it's working basically, but still misses re-calculation on window-size change event

**Comment by githubertus** [comment]
of course: chrome and firefox doing fine, but IE 11 has its own rules. Hate it. :-1: 
Position not totally wrong, but about 11px left floated. I give up on that.

**Comment by lianglee** [comment]
Fixed
