### ISSUE TITLE
Not Working Instal

### ISSUE THREAD

**Issue by shacallbotss** [opensource-socialnetwork/opensource-socialnetwork#1975]
![Screenshot_1](https://user-images.githubusercontent.com/86268650/124838355-0728d080-df5d-11eb-9f00-c6b1be9a6af2.png)

**Comment by lianglee** [comment]
What is your server specification?  
Where you downloaded OSSN? 
What is OSSN version you are trying to install?

**Comment by lianglee** [comment]
Any status?
