### ISSUE TITLE
template issue uncovered with 2.0-dev 2015-01-12

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#198]
First thought, there's something wrong with my German language file, but it's a template issue:

![site-login-template-problem](https://cloud.githubusercontent.com/assets/9904364/5713673/04fc619e-9abf-11e4-8fd8-2ba448f91612.png)

If the language string 'site:login' is longer than 7 characters, things begin to float to the left.

(We didn't notice it before, because in the snapshot from Jan 4th  "Login" seemed to be still hardcoded)

**Comment by lianglee** [comment]
i can fix it

**Comment by githubertus** [comment]
almost fixed in [2.0-dev 2015-01-22 09:30 GMT+1] - still got a minor problem at the bottom, though:
the create button is colliding with the footer.

![frontpage-issue2](https://cloud.githubusercontent.com/assets/9904364/5862823/3f27f3d4-a275-11e4-9e6f-b5ed396a7044.png)

**Comment by lianglee** [comment]
This is bug

**Comment by lianglee** [comment]
fixed
