### ISSUE TITLE
OssnFile.php does not move directories across different volumes

### ISSUE THREAD

**Issue by AntzCode** [opensource-socialnetwork/opensource-socialnetwork#1985]
This bug affects the file ```/classes/OssnFile.php``` at the method ```moveFiles()```.

An error occurs when using the copy() or rename() functions to move a directory from one volume to a different volume. 

Eg:
> PHP Warning: rename(): The first argument to copy() function cannot be a directory

This is a known bug in PHP:

https://bugs.php.net/bug.php?id=54097
https://bugs.launchpad.net/ubuntu/+source/php5/+bug/723330m

The method works as expected when moving files across volumes or when moving directories within the same volume. It is only whenever the ```$from``` and ```$to``` arguments are directories that are mounted on different volumes, then the error occurs.

For example, this will affect installations where ```/ossn_data``` is mounted on a different volume to that which the website files are mounted. When ```$Ossn->userdata``` and ```ossn_route()->www``` are mounted on separate volumes, it is impossible to upload and install components or themes.

While investigating the issue on the [forked project](https://github.com/AntzCode/opensource-socialnetwork/issues/10), I happened to find a simple solution: by recursively calling the ```OssnFile::moveFiles()``` method for any filenames within the directory that are also directories and using the PHP ```rename``` function only if the filename points to a file that is not a directory, then the bug is never encountered:

```
public static function moveFiles($from, $to) {
    // etc.
    $files = scandir($from);
    foreach($files as $fname) {
        if($fname != '.' && $fname != '..') {
            if(is_dir($from . $fname)){
                self::moveFiles($from . $fname . DIRECTORY_SEPARATOR, $to . $fname . DIRECTORY_SEPARATOR);
            }else if(is_file($from . $fname)){
                rename($from . $fname, $to . $fname);
            }
        }
    }
    // etc.
}

```

This is the patch file of that change:

[aa801418980bc0ce28529f292c4f3031f1ba5ee4.patch.txt](https://github.com/opensource-socialnetwork/opensource-socialnetwork/files/6945241/aa801418980bc0ce28529f292c4f3031f1ba5ee4.patch.txt)

**Comment by lianglee** [comment]
Merged already #1987
