### ISSUE TITLE
fakebook theme error..

### ISSUE THREAD

**Issue by ROBOTRIX-EU** [opensource-socialnetwork/opensource-socialnetwork#2013]
After today i updated my instalation, it stopped working..had to uninstal thru softaculous, instaled again, then theme fakebook, but it stoped working simple things like logout and other errors..I closed my acount on the real facebook, and this theme is why i use it for family and friends..but without the fakebook theme properly working with this new release.. and i can't install the older version again thru softaculous, because it installs the newest version.. if someone can look on the theme and see the solution..it is not fully compatible with this new release.. Thank You!

**Comment by lianglee** [comment]
Fakebook theme is outdated and can not work for OSSN 6.0 unless updated.

**Comment by ROBOTRIX-EU** [comment]
Thanks! sad though..

**Comment by lianglee** [comment]
Updated https://www.opensource-socialnetwork.org/component/view/2243/fake-book

**Comment by ROBOTRIX-EU** [comment]
Thanks! Will give it a go! This may inspire others to create opposition to facebook, and, if the color could in future, be easaly customized..that man.. Thanks to coders!
