### ISSUE TITLE
3 state logic for notifications

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#202]
(requested by ashwni kumar in community)
currently we only check NULL or not NULL in 'viewed' column of notification record.
What he likes to have is something like ...
- new notification sets viewed = NULL and increments counter (as before)
- on opening the notification window: loop through records with NULL, replace NULL with 1 and decrement counter
- change frontend logic to display grey background with viewed == NULL || 1, white with 2
- when actually having clicked the notification, mark as read (= set viewed to 2)

This way, the counter will count and show only absolutely new events, and it's up to the user if he really wants to click every single notification or not.

What do you think about that?

**Comment by moneya** [comment]
@githuberus for me Cool logic

**Comment by lianglee** [comment]
Yes we can provide it in 2.x

**Comment by sathish4fri** [comment]
SGTM

**Comment by moneya** [comment]
@lianglee do that

**Comment by lianglee** [comment]
I think we should provide clear all notifications button.

**Comment by githubertus** [comment]
:+1:  Yeah, that's an even better solution. Let the people decide whether they want to keep the notice or not.

**Comment by PaDo90** [comment]
Yeah, a clear all or "Mark as read" / "Als glesen markieren"- Link would be great :)

**Comment by lianglee** [comment]
added
