### ISSUE TITLE
Fixed mod_rewite issue

### ISSUE THREAD

**Issue by ClosetGeek-Git** [opensource-socialnetwork/opensource-socialnetwork#2020]
Add the following after line 221 in 'installation/libraries/ossn.install.php'
```PHP
    if($_REQUEST['ssl_verifypeer'] === 'false') {
        curl_setopt($curlinit, CURLOPT_SSL_VERIFYPEER, false);
    }
```

The complete function should look like
```PHP
function ossn_installation_simple_curl($url = '') {	
    if(isset($url)){
        $curlinit = curl_init();
        curl_setopt($curlinit, CURLOPT_URL, $url);
        curl_setopt($curlinit, CURLOPT_RETURNTRANSFER, 1);
        if($_REQUEST['ssl_verifypeer'] === 'false') {
            curl_setopt($curlinit, CURLOPT_SSL_VERIFYPEER, false);
        }
        $result = curl_exec($curlinit);
        curl_close($curlinit);
    }
    return $result;
}
```
This will be safe. When using curl to access an unfamiliar site it's one thing, but when accessing your own server it can be assumed that you know the source/validity of your own SSL certificates. 

It's interesting that in 'installation/classes/OssnInstall.php' you've added the ability to skip this check all together via $_REQUEST['mod_rewrite_check_skip'] . It's the only prerequisite that the installation script can skip 🤔

**Comment by ecarlseen** [comment]
This doesn't work without TLS enabled either and misreports a mod_rewrite error; we had a similar issue doing internal testing without TLS.

It would be appropriate to test TLS separately and document that requirement, or at least correctly report the error condition.

**Comment by lianglee** [comment]
> This doesn't work without TLS enabled either and misreports a mod_rewrite error; we had a similar issue doing internal testing without TLS.
> 
> It would be appropriate to test TLS separately and document that requirement, or at least correctly report the error condition.

Yes CURL may fail if there is TLS error. I think maybe in case of failed we should give a error returned by CURL instead ,  this would be helpful than no information about error.

**Comment by ecarlseen** [comment]
Also, in testing we got this error if  "AllowOverride All" is not set in the Apache site configuraiton for the installation directory (enabling .htaccess).
