### ISSUE TITLE
community is broken

### ISSUE THREAD

**Issue by wethecom** [opensource-socialnetwork/opensource-socialnetwork#2021]
i have questions i signed up and i can only view questions not ask them
this is not a code issue this is other and ive filed a notice but im not getting a responce

**Comment by wethecom** [comment]
emails were going to spam problem solved ...derp

**Comment by lianglee** [comment]
We do understand the situation you went through but please don't just do that to remove the text , title and description  from your original issue which looks not really professional.

**Comment by wethecom** [comment]
well that seem appropriate them im not a professional. because if i was i would have just deleted it but thats no where to be found

**Comment by lianglee** [comment]
What I mean is when you open a issue before deleting or removing our team need to know what actually happened why the issue really generated.  Would you mind letting us know how did the problem resolved? is this relates to your site? where the users who registers their email goes to the spam?

**Comment by lianglee** [comment]
Don't create issues in first place if you fail to provide a response.
