### ISSUE TITLE
Add user object to ossn_get_entities result

### ISSUE THREAD

**Issue by mirabledictu** [opensource-socialnetwork/opensource-socialnetwork#2028]
Hi, not an issue but is there a way to include the user object when getting data via `ossn_get_entities`?

```php
$entities = ossn_get_entities(array(
    'type' => 'user',
    'subtype' => 'example',
    'page_limit' => false
));
```

Thank you.

**Comment by lianglee** [comment]
No there is no way.  Unless you write your own custom SQL query with JOIN of ossn_entites , ossn_metadata_values,  ossn_users
