### ISSUE TITLE
[E] avoiding unnecessary handling of extra space at comment start

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2029]
on a fresh page load a comment looks like this:
![comment-loaded](https://user-images.githubusercontent.com/9904364/141101863-971969b0-184a-4f98-af30-cd1778609209.png)
after editing and saving that comment it looks like
![comment-edited](https://user-images.githubusercontent.com/9904364/141102385-da616e5f-b111-419b-9603-5ad99815eb53.png)
A hardly noticable difference at first sight, but actually lines 53, 55, 57 of OssnComments/plugins/default/comments/templates/comment.php are adding that extra space in the beginning on load, while after XHR editing and saving this leading space gets lost due to libinput trimming.

Unfortunately, this isn't just a 'cosmetic glitch', because the comment's real string length becomes part of a calculation  when running the ReadMore component. So my former workaround was overwriting the comments original embed action and adding that lost space again.
But I'm not really happy with overwriting core stuff if it's not absolutely necessary and I would like to get rid of that.

So my idea (in case you want that little more distance between user name and the comment's text start) is to remove that space from line 53, 55 and 57 and add a margin-left of 5px to the 'comment-text' class instead.

**Comment by lianglee** [comment]
Totally agree with you,  it must be a css instead of that hardcode space.  Fixing it tonight :)

**Comment by lianglee** [comment]
We even don't need css as its covered by .comment-contents .owner-link

![image](https://user-images.githubusercontent.com/805066/141118315-ae500407-dd57-416f-a011-9a20efc75804.png)

**Comment by lianglee** [comment]
Fixed closing issue.

**Comment by githubertus** [comment]
Thx. :+1:
