### ISSUE TITLE
links on footer only partly accessable when logged in

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#203]
The links seem to be partly overlapped by _ossn-chat-base_.
If I switch ossn-chat-base to _display: none_,
ALL links WORK

Firefox (only the rightmost link is clickable)

![footerline-firefox](https://cloud.githubusercontent.com/assets/9904364/5721202/ebe0cfa4-9b2e-11e4-86fc-c861211ef86f.png)

Chrome and IE 11 behave the same: left side not clickable, right side ok

![footerline chrome](https://cloud.githubusercontent.com/assets/9904364/5721225/36f70f30-9b2f-11e4-9bc6-fbbab89ec4bf.png)

System is Windows 7

**Comment by TheGameHHH** [comment]
it is similar if you want to change the privacy settings for a post. you can save it on your home site if you want that the post will be seen by you friends. otherwise you want to make a post about your profile wall then you can not save the privacy settings.

**Comment by githubertus** [comment]
@TheGameHHH and everyone
Feel free to post any issue with Ossn you've encountered, but please: handle each problem separately
and open a NEW report.
Fixing bugs means fixing one bug after another. Not fixing a little bit here and fixing a little bit there. When the fix is working, the issue can be closed and disappears from the to-do list. Only this way the programming team is able see at first sight, how many issues are still open.

**Comment by lianglee** [comment]
fixed
