### ISSUE TITLE
[B] Emoji issues with post background in new chrome update

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2031]
Not sure if it is chrome only or others

![image](https://user-images.githubusercontent.com/805066/143478645-36c94b57-b016-44b5-85de-b2820dca3531.png)

1. Works fine with firefox. 94.0.2 (64-bit)
2. Same issue with Edge  96.0.1054.34
3. Chrome same issue 96.0.4664.45

**Comment by githubertus** [comment]
https://support.google.com/chrome/thread/136127348/chrome-bold-weight-emoji-broken-version-93-0-4664-45?hl=en

**Comment by lianglee** [comment]
Oh my I hope they won't break anything else.

**Comment by lianglee** [comment]
Fixed in new update of chrome :)
