### ISSUE TITLE
[E] Remove php5 apache config and update post and upload sizes

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2033]
[E] Remove php5 apache config and update post and upload sizes

**Comment by githubertus** [comment]
just a reminder that many providers are using FPM/FastCGI in the meantime
and `.htaccess` values like these are IGNORED then
In order to achieve the same results it needs a `.user.ini` file in Ossn's root
with a settings syntax as in php.ini like
`upload_max_filesize = 3M
`

**Comment by lianglee** [comment]
@githubertus agree however then we need extra handling for checking if exists .user.ini then don't override it otherwise override it.

**Comment by lianglee** [comment]
Generates .user.ini in both cases but access to browser is forbidden
