### ISSUE TITLE
Hide blocked users posts on public posts

### ISSUE THREAD

**Issue by mirabledictu** [opensource-socialnetwork/opensource-socialnetwork#2047]
Currently, this is what I see is working on blocked users:

- unable to see blocked users page
- unable to message blocked user
- unable to poke blocked user

But even if you block someone and they posted publicly, you'll still see their posts but not able to comment on it.

Is this the behavior? Shouldnt we be not seeing posts from blocked users? Im using latest version of OSSN

**Comment by lianglee** [comment]
Make sure you are not a admin user viewing the posts.  Try to disable all 3rd party components one by one to see which is causing the issue.
