### ISSUE TITLE
can't add a discussion on ossn.org/community

### ISSUE THREAD

**Issue by revansx** [opensource-socialnetwork/opensource-socialnetwork#2056]
* I'm registered, email verified, and logged-in at https://www.opensource-socialnetwork.org/discussion/add
* My discussion title is > 35 characters and constructive
* I have written some nice discussion text
* I added at least one tag
* I have chosen a topic  
* I have tried multiple times 

...and the site simply won't allow me to post a discussion. It allows me to submit, but it always responds with a pink banner that says "Cannot add discussion" and that is all. 

Please advise. Thank you!

**Comment by revansx** [comment]
So that I don't loose it.. here is the discussion text I had hoped to be able to post:

OSSN v6.1 new user install experience

Hello, I just learned about OSSN about a week ago and today I just finished installing and tweaking a fresh instance of v6.1 on my personal webserver and I wanted to share my thoughts and ask a few basic questions about the way OSSN currently behaves.

**Environment:**

 - Host: DigitalOcean
 - Centos7
 - Apache 2.4.6
 - Haproxy 1.5.18
 - Firewalld 0.6.3
 - PHP 7.4.26
 - MariaDB 10.6.5
 - OSSN 6.1
 - OSSN Theme: Fake-book 6.2

Note - My entire LAMP stack is managed via Meza [1] which is an ansible project that configures and deploys a fully-featured (media)wiki-farm server and all supporting components including the OS. While meza is not designed for any other web applications, it was straight-forward to create a dedicated virtualhost for OSSN to run along side all the wikis. 

**Install challenges**

 - **mod_rewrite Test** - The mod_rewrite test in the installation check page was a problem. I knew mod_rewrite was enabled, but there is something wrong with the way OSSN gets the site_url at this stage. I think this was primarily due to apache running without SSL behind the proxy server handling the SSL termination.  As a result, I think the OSSN installation was getting http://127.0.0.1:8082 as the site_url at this stage. I was easily able to defeat the check by editing "installation/classes/OssnInstall.php" and making sure that "public static function is_mod_rewrite()" always returns "true" .. that was fun.
 - **blocked:mixed-content** - Once I was able to get past the pre-installation tests I was able to configure OSSN. Setting the database,  Admin account, and other essentials was straight-forward, but once the site was configured and it was time to visit the welcome page, I found that the site was failing due to mixed (http and https) content being served. This was remedied by editing the value of "$Ossn->url" in "configurations/ossn.config.site.php" to be "https" rather than just "http" due to the site_url issue (presumably). 
 - **too many redirects** - Once the mixed-media issue was cleared-up, the welcome page failed with the message "too many redirects". This was tricky. I spent a few hours trying to fix this in ".htaccess" to no avail, but then discovered  (in a discussion here) that there is a javascript function called "ossn_redirect_absolute_url()" in "libraries/ossn.lib.javascripts.php" that performs redirects for a variety of reasons.. to this function I hard-coded "$baseurl" to be my application url and edited all the of the "$redirect = true;" occurrences to "$redirect = false;". And that solved the too many redirects problem.

After that, OSSN worked as intended.

**Questions about standard behavior:**

 - **Regarding Groups**
  - **Secret Groups?** - I noted that the only two options for group privacy are: public, and closed. Is there a way (component) that allows for secret groups?
  - **Invitations to a group** - is there a way to invite friends/users to a group? or do they have to make the request?
  - **Group Photo Albums** - Is there a way (component or otherwise) to add albums in groups?


 - **Regarding Photos**
  - **Upload Progress indicator** - I noticed that when uploading multiple photos that there is no progress indicator. Is this normal/expected? 

**Concluding remarks**
I'd like to extend a very heartfelt thank you to the OSSN development community. Bravo. This is nearly perfect for what I have been hoping to do in 2022 to create a private social media site for my close friends and family. The ability to have a "facebook-like" application that is entirely free of advertisements and 100% controlled by the users (me and mine) is exactly what this world needs. I'm looking forward to contributing to the code as I can and as time permits. 

Truest thanks,
/Rich

[1] https://www.mediawiki.org/wiki/Meza
[2] https://www.mediawiki.org/wiki/Topic:Wnlt4b0nt0dpfzd7

**Comment by lianglee** [comment]
Hi Rich,

Thanks for opening the topic here. Because of spam in in past and abuse we restirred the size of content and title in discussion forums.   Your topic has been moved to community!

Thanks

**Comment by revansx** [comment]
Gotcha. I totally understand. Thanks! What are the new requirements for posting?

**Comment by lianglee** [comment]
@revansx simply post brief discussions :)
