### ISSUE TITLE
invite friends problem

### ISSUE THREAD

**Issue by SMotaee** [opensource-socialnetwork/opensource-socialnetwork#2059]
Hi! I have setup a demo version on my host to test the website, when I invite my friends, i get error. please help me to solve the problem. also, I the problem is attached on this message.
![error](https://user-images.githubusercontent.com/16328109/149726253-b938c268-ea2a-4506-b04e-c2b6710b66f8.jpg)

**Comment by githubertus** [comment]
The escapeshellcmd function is not part of Ossn, it comes included with your PHP environment, but may be de-activated by your provider to prevent spamming and things like that. So please contact your provider and ask for enabling that fucntion.
