### ISSUE TITLE
[B] getting orphan notification records of type comments:post:group:wall

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2060]
if the related post has been deleted
(running Ossn 6.1)

**Comment by githubertus** [comment]
bug confirmed with latest OssnNotifications and OssnComments from Github

**Comment by lianglee** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v6.x/components/OssnComments/ossn_com.php#L169 

Will test out if its right place and will add a fix
