### ISSUE TITLE
custom component to log in a user, does not work in iframe

### ISSUE THREAD

**Issue by str** [opensource-socialnetwork/opensource-socialnetwork#2062]
I created a custom component to integrate with an existing app. The custom component works as a single-sign-on bridge (SSO), and allows the existing app to in users with their existing app accounts. 

The custom SSO component is working perfectly, and after login in I redirect the user to the home page with `redirect('home');`.  I load the custom SSO component in an `<iframe>`. I test it with Firefox, it works fine. If I test it in Google Chrome, I get redirected to the login page instead. This only happens if I use the iframe. If I open the custom SSO component in an new tab, it loads the user without problems.

Any ideas?

**Comment by lianglee** [comment]
Hi, Without looking the component code we have no idea what is causing the issue.  You should try to debug the routine step by step using chrome and see at which step it is causing the issue.  So you set the session in iframe ? which works fine on firefox but not on google chrome is that correct?

Maybe this is helpful for you https://stackoverflow.com/questions/63539472/chrome-not-keeping-my-session-vars-when-coming-from-3rd-party-iframe-but-works
