### ISSUE TITLE
[B] Deleting a group should remove group:joinrequest records

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2066]
- A creates group TMP
- B requests membership for TMP
- A deletes group TMP

A opening notifications gives
PHP WARNING: "Attempt to read property "guid" on bool" in file classes/OssnObject.php (line 157)
PHP WARNING: "Attempt to read property "title" on bool" in file components/OssnGroups/ossn_com.php (line 436)

**Comment by lianglee** [comment]
Will check :)

**Comment by githubertus** [comment]
Independent of that,
Whatever is causing no valid object to be returned here, getObjectById() should immediately return false here instead of proceeding and calling Entities

**Comment by lianglee** [comment]
agree
