### ISSUE TITLE
[B] showFileUploadError() not really working

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2100]
Trying to upload a too large file:
in some places I'm getting this not very helpful 'Something went wrong' message
in other places (e.g. profile cover) I'm getting no message at all

**Comment by lianglee** [comment]
Thanks for pulls :)

**Comment by githubertus** [comment]
ok, i think it's fixed now

**Comment by lianglee** [comment]
Thanks that's a lot of work you have managed I usually avoid the work which involves languages changes lol
