### ISSUE TITLE
A system error has occurred

### ISSUE THREAD

**Issue by balajitsi121** [opensource-socialnetwork/opensource-socialnetwork#2131]
Suddenly getting below errors. I don't know why it's coming.

OssnDatabaseException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away 
 SELECT  o.guid, o.time_created FROM ossn_object as o  WHERE(o.guid='381')  ORDER by o.guid ASC LIMIT 0, 10;  in /home/admin/web/zafoid.com/public_html/staging/classes/OssnDatabase.php:148
Stack trace:
#0 /home/admin/web/zafoid.com/public_html/staging/classes/OssnDatabase.php(281): OssnDatabase->execute(false)
#1 /home/admin/web/zafoid.com/public_html/staging/classes/OssnObject.php(491): OssnDatabase->select(Array, true)
#2 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.objects.php(24): OssnObject->searchObject(Array)
#3 /home/admin/web/zafoid.com/public_html/staging/classes/OssnSystem.php(42) : eval()'d code(234): ossn_get_object(381)
#4 /home/admin/web/zafoid.com/public_html/staging/components/BusinessPage/plugins/default/wall/templates/wall/businesspage/item.php(11): get_business_page(381)
#5 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.views.php(27): include('/home/admin/web...')
#6 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.views.php(50): ossn_include('/home/admin/web...', Array)
#7 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.plugins.php(75): ossn_view('/home/admin/web...', Array)
#8 /home/admin/web/zafoid.com/public_html/staging/components/OssnWall/ossn_com.php(532): ossn_plugin_view('wall/templates/...', Array)
#9 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.system.php(223): ossn_wall_templates('wall:template', 'businesspage', NULL, Array)
#10 /home/admin/web/zafoid.com/public_html/staging/components/OssnWall/ossn_com.php(514): ossn_call_hook('wall:template', 'businesspage', Array)
#11 /home/admin/web/zafoid.com/public_html/staging/components/BusinessPage/plugins/default/bpage/view/bottom.php(34): ossn_wall_view_template(Array)
#12 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.views.php(27): include('/home/admin/web...')
#13 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.views.php(50): ossn_include('/home/admin/web...', Array)
#14 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.plugins.php(75): ossn_view('/home/admin/web...', Array)
#15 /home/admin/web/zafoid.com/public_html/staging/components/BusinessPage/plugins/default/bpage/pages/view.php(159): ossn_plugin_view('bpage/view/bott...', Array)
#16 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.views.php(27): include('/home/admin/web...')
#17 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.views.php(50): ossn_include('/home/admin/web...', Array)
#18 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.plugins.php(75): ossn_view('/home/admin/web...', Array)
#19 /home/admin/web/zafoid.com/public_html/staging/classes/OssnSystem.php(42) : eval()'d code(255): ossn_plugin_view('bpage/pages/vie...', Array)
#20 /home/admin/web/zafoid.com/public_html/staging/libraries/ossn.lib.page.php(73): business_page_handler(Array, 'page')
#21 /home/admin/web/zafoid.com/public_html/staging/index.php(22): ossn_load_page('page', Array)
#22 {main}

**Comment by githubertus** [comment]
As the log shows "General error: 2006 MySQL server has gone away" 
An issue we can't investigate. To find out why your database server stopped, please either contact your webspace provider or have a look into your server log files in case you're running a self hosted Ossn.
