### ISSUE TITLE
OssnComments Feature Request.

### ISSUE THREAD

**Issue by michieal** [opensource-socialnetwork/opensource-socialnetwork#2132]
I thought that I would ask here, if this could be added to the Comments' section of the platform. It would be nice to have a way to add in actionable links to the link bar for each comment. I have hard coded a Reply link in for my own site, but I highly disdain having to do that as it means that with every update I have to change that part of my component, otherwise it breaks, or breaks the site, etc.
Conceptually, it would need to pass to the component using it what type of comment it is (post, object, entity), along with probably the post's guid and comment guid.

Ideally, this would allow for at least a Like, Reply, comment sentiment, and a timestamp link directly to the comment itself.

**Comment by lianglee** [comment]
Answer posted on community already.
