### ISSUE TITLE
Registrations - I am no longer able to register users

### ISSUE THREAD

**Issue by MatrioskaMM** [opensource-socialnetwork/opensource-socialnetwork#2133]
Good evening,

It has been impossible for a few days to register on a social network created for a customer. Entering all the data does not proceed with the registration. Furthermore, the registered cannot log in. Has anyone encountered the same error? If so, how did you solve it? The social network is hosted on siteground. If it can be useful I will provide the link to the site.

**Comment by lianglee** [comment]
Any error you get?
