### ISSUE TITLE
Installation Error  - .htaccess

### ISSUE THREAD

**Issue by Chaviya98** [opensource-socialnetwork/opensource-socialnetwork#2140]
how to create the .htaccess file manually inside the OSSN file directory? what should be the content on the .htaccess file?

**Comment by Millertime67** [comment]
I had an error failing to find index, option not allowing script generated index. 
After reading this I checked for .htaccess , it is there and allowing index.php, thought it shows modified yesterday, and I wasn't in the site or script yesterday. 
So, I tried loading install again and to my surprise the site loaded. I had to create an account and assign admin via phpmyadmin but everything seems to work so far, though the dashboard shows version 6.1 with file version 6.2. 
Should I open another issue for that?
