### ISSUE TITLE
INSTALLATION ERROR  - INSIDE DOCKER

### ISSUE THREAD

**Issue by Chaviya98** [opensource-socialnetwork/opensource-socialnetwork#2141]
I ran OSSN inside a php:8.0-apache docker image and all the INSTALLATION PREREQUISITES were completed then I clicked on the Next button and continue to the http://localhost/installation/?page=settings URL where I was able to add the database related details.
Once I click install after filling the data, necessary tables were created on the MySQL database but the next page is not loading in the installation process.

please find the error below 

HTTP ERROR 500`

**Comment by githubertus** [comment]
Ok,
I will try as soon as you provide a route to your localhost.

**Comment by lianglee** [comment]
see case A
https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error-issue
