### ISSUE TITLE
Ossn version misidentified on admin dashboard

### ISSUE THREAD

**Issue by Millertime67** [opensource-socialnetwork/opensource-socialnetwork#2142]
I realize it probably will not affect the functionality at all, but will definitely catch the attention of some. While the stats and the admin dashboard tell us that the ossn file version is indeed 6.2, the script version is labeled as 6.1.

-

**Comment by Millertime67** [comment]
![Screenshot_20220401-204057_Chrome](https://user-images.githubusercontent.com/102386251/161360820-b5725be6-23fd-46cf-8bb9-42bfb56f70ef.jpg)

**Comment by lianglee** [comment]
Makes sense because Ossn 6.2 not done yet. You are using development
version and its not tested.
