### ISSUE TITLE
[E] Request for new user image classes defining the shape only

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2143]
Now that we have all these different user image sizes like large, small, smaller, etc.
it would be helpful to have derived reliable classes like user-img-large, user-img-small, user-img-smaller
which would define ONLY the border-radius.

This way any 3rd party component like Latest Members or Who Is Online had  a much easier way to display user avatars which would FIT to the style of a theme. So I could simply do a `<img class="user-img-small">` in my component and get the 50px border-radius used by Goblue automatically without a tricky procedure to find out first whether the theme is based on round or rectangular avatars.

**Comment by lianglee** [comment]
Agree

**Comment by lianglee** [comment]
Tried my best to replace it

user-icon-(size)
