### ISSUE TITLE
[B] missing checkbox-block span style

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2145]
not available in Goblue and should be styled according to radio-block

![missing-checkbox-span-style](https://user-images.githubusercontent.com/9904364/162727497-6054e7be-8536-4e5a-bda1-36f920309d5a.png)

**Comment by lianglee** [comment]
Yup :)

**Comment by githubertus** [comment]
Well, meanwhile I had a closer look into all that stuff and I'm wondering why we are not simply using bootstrap classes according to https://getbootstrap.com/docs/5.0/forms/checks-radios/ ?

This way we could get rid of a lot of extra css in our themes ... :)

**Comment by lianglee** [comment]
Yes but now if we use it now we may require to fix already developed stuff

**Comment by lianglee** [comment]
Suppose some component using custom css and now if we add bs classes it may make those css appears strange in custom usages
