### ISSUE TITLE
[T] OssnUser::getFriends() 

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2149]

**Comment by lianglee** [comment]
Verify the use on all places where getFriends() used

**Comment by githubertus** [comment]
used on my 6.2dev without issues at:

./libraries/ossn.lib.users.php:138:
./libraries/ossn.lib.users.php:218:
./libraries/ossn.lib.users.php:223:
./components/bio/classes/Bio.php:68:	
./components/DisplayUsername/ossn_com.php:99:
./components/LatestMembers/widgets/friends_widget.php:17:
./components/OssnChat/classes/OssnChat.php:91:
./components/OssnChat/classes/OssnChat.php:139:
./components/OssnProfile/plugins/default/profile/pages/friends.php:12:
./components/OssnProfile/plugins/default/profile/pages/friends.php:15:
./components/OssnProfile/plugins/default/profile/modules/friends.php:11:
./components/OssnWall/classes/OssnWall.php:181:	
./components/OssnWall/classes/OssnWall.php:322:	
./components/OssnWall/classes/OssnWall.php:384:	
./components/OssnWall/classes/OssnWall.php:435:	
./components/OssnWall/ossn_com.php:112:	
./themes/Flexi/plugins/default/flexi/friends_widget.php:16:

**Comment by lianglee** [comment]
@githubertus  ❤️

**Comment by githubertus** [comment]
i just noticed that it's no longer easy to get a list of latest friends ... because the relationships_id isn't part of the new query result
any idea of what attributes to pass in order to get this back working again?

**Comment by lianglee** [comment]
Latest friends isn't ORDER BY u.guid  DESC  (limit 10, 20 etc) ?

getFriends(id, ['order_by' => 'u.guid DESC']);  ?

**Comment by lianglee** [comment]
I think you are right and I understand about relation id.  Let me check.

**Comment by lianglee** [comment]
One of the way is : 

```
<?php
$r = ossn_get_relationships(array(
		'to'       => ossn_loggedin_user()->guid,
		'type'     => 'friend:request',
		'order_by' => 'r.relation_id DESC',
		'inverse'  => true,
));
if($r) {
		$guids          = implode(',', array_column((array) $r, 'relation_to'));
		$user           = new OssnUser();
		$latest_friends = $user->searchUsers(array(
				'wheres'   => "(u.guid IN ($guids))",
				'order_by' => "FIELD(u.guid, {$guids})",
		));
		echo ossn_dump($latest_friends);
}
```

**Comment by lianglee** [comment]
Other method

```
<?php
<?php
$user           = new OssnUser();
$latest_friends = $user->searchUsers(array(
		'joins'    => array(
				'JOIN ossn_relationships AS r1 ON r1.relation_to = u.guid AND r1.type = "friend:request"',
				'JOIN ossn_relationships AS r2 ON r2.relation_from = r1.relation_to AND r2.type = "friend:request"',
		),
		'wheres'   => '(r1.relation_from = 1)', //replace with loggedin user ID
		'order_by' => 'r1.relation_id DESC',
));
echo ossn_dump($latest_friends);
```

**Comment by lianglee** [comment]
I believe I need to replace latest getFriends with above method so it returns relation.* in field list as it works same.  I will update method soon and test

**Comment by githubertus** [comment]
thank you! and I'm sorry I didn't become aware earlier of this. It's a little strange, I thought I tested it with the changes you did, but maybe my users class wasn't really up-to-date that time.... :(

**Comment by githubertus** [comment]
last one is working almost fine
i have added 'distinct' => true
because otherwise you may get duplicates

**Comment by lianglee** [comment]
Nice, I will try to merge last one with current method because it's useful
to sort out with relation id
