### ISSUE TITLE
[QUESTION] Don't show wall posts user problem without login

### ISSUE THREAD

**Issue by tomasnorre** [opensource-socialnetwork/opensource-socialnetwork#2156]
Is there a way to disable the possibility to show wall posts and profiles when not logged in? I don't want Google etc. to see the content posted. 

I Know I can do something with robots.txt, but don't want it visible for humans, either. 

Thanks for helping out.

**Comment by githubertus** [comment]
You can find numerous components which change, enhance or limit Ossn's default capabilities at https://www.opensource-socialnetwork.org/components/all

I think, Private Network is the one you're looking for ...
https://www.opensource-socialnetwork.org/component/view/1564/private-network
