### ISSUE TITLE
Travou todas as funcionalidades de adiministrador e algumas da area normal após instalar tema goblack

### ISSUE THREAD

**Issue by janiorolim** [opensource-socialnetwork/opensource-socialnetwork#2160]
Estava buscando um tema para deixar a rede mais agradavel, porém, após instalar e ativar um tema "goblack" travou todas as funções na aba de administrador e algumas funções da aba normal. Não consigo acessar nada na aba de administrador, nem desativar o tema que foi instalado.

Preciso de ajuda, por favor.

**Comment by lianglee** [comment]
English please
