### ISSUE TITLE
Deprecated: Required parameter $file

### ISSUE THREAD

**Issue by waldirborbajr** [opensource-socialnetwork/opensource-socialnetwork#2162]
PHP Version 8.0.8

Deprecated: Required parameter $file follows optional parameter $code in /Applications/MAMP/htdocs/thenet/libraries/ossn.lib.languages.php on line 18

**Comment by lianglee** [comment]
Please update you php to at least PHP 8.1

https://externals.io/message/116597

https://stackoverflow.com/questions/65436518/deprecated-required-parameter-to-addr-follows-optional#comment124358853_65436786

**Comment by waldirborbajr** [comment]
Thank you, I'll do it.

**Comment by waldirborbajr** [comment]
Updated to PHP Version 8.1.0 but the message remains appearing. Another alternativa to hide that annoying message?

Thank you in advance

**Comment by lianglee** [comment]
When that message appears? not appearing for me. Please try to download
latest development version from GitHub

**Comment by lianglee** [comment]
Download a linux container and install lampp on virtual machine. Try to run
it on Ubuntu 18.04 or 20.04

There must be problem with your system
If you getting this error all the time on fresh installation then its your
system.
