### ISSUE TITLE
Missing alignment on mobile device

### ISSUE THREAD

**Issue by waldirborbajr** [opensource-socialnetwork/opensource-socialnetwork#2167]
I've tried OSSN on mobile device, and the form of new user, missed alignment as you can see below.

![image](https://user-images.githubusercontent.com/40029512/174805815-a5fc6b42-1f99-4a0b-b7fe-63c9e13569c1.png)

**Comment by lianglee** [comment]
Which theme name and OSSN version are you running?   I tried OSSN 6.3 
![image](https://user-images.githubusercontent.com/805066/174834194-86e37f1c-30d6-459b-ab7b-0f117d16be69.png)

**Comment by waldirborbajr** [comment]
@lianglee I got it... I'm restyling this theme https://www.opensource-socialnetwork.org/component/view/2243/fake-book

I'll take a look.

Thanks for now.
