### ISSUE TITLE
[B] XSS vulnerability in OssnWall

### ISSUE THREAD

**Issue by ToffyMTA** [opensource-socialnetwork/opensource-socialnetwork#2173]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/c36ed2681264f4cb10ab4105edc4cd4d3cadb2fa/components/OssnWall/plugins/default/wall/templates/wall/user/item.php#L53

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/c36ed2681264f4cb10ab4105edc4cd4d3cadb2fa/components/OssnWall/plugins/default/wall/templates/wall/group/item.php#L57

Replace: `<span class="time-created"><?php echo $params['location']; ?></span>`
To: `<span class="time-created"><?php echo strip_tags($params['location']); ?></span>`

**Comment by lianglee** [comment]
Confirmed and we will be looking it soon and remove the issue from here.

**Comment by ToffyMTA** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/pull/2174

**Comment by lianglee** [comment]
Closing as fixed strip tags was no solution here.

**Comment by lianglee** [comment]
Issue has been fixed and deleting the issue from records as its security issue.
