### ISSUE TITLE
[B] Same Friends tag flooding

### ISSUE THREAD

**Issue by ToffyMTA** [opensource-socialnetwork/opensource-socialnetwork#2175]
**1.**
![image](https://user-images.githubusercontent.com/63078659/181012003-383a0ed9-65d8-4cd2-9850-39473a6f368c.png)
![image](https://user-images.githubusercontent.com/63078659/181012071-07076e77-2654-4a3a-b2c5-c8181e44eb9a.png)

There's no limitations in tagging friends, I can tag same person multiple times.
(can easily fill up database - 1 tag = 1 record in table: ossn_notifications)

**2.** (not important)
I can tag people even if we aren't friends by modifying request.

**Comment by lianglee** [comment]
@ToffyMTA thanks for reporting these definitely going to be fixed in next release,  regarding 2 can you provide example.
