### ISSUE TITLE
Hungarian error

### ISSUE THREAD

**Issue by TimiHavran** [opensource-socialnetwork/opensource-socialnetwork#2180]
Hi

I have some errors when I choose Hungarian as a language. Friends, messages and notifications don't work anymore if I switch the language to Hungarian. They work in any other languages.

So if I click on the icons, I don't get a dropbox to see friend requests etc.

**Comment by lianglee** [comment]
OSSN doesn't have Hungarian langauge pack. It need to be translated https://www.opensource-socialnetwork.org/wiki/view/2132/how-to-translate-ossn
