### ISSUE TITLE
[E] Disable admin to change his own type on user edit page (admin panel)

### ISSUE THREAD

**Issue by eyadtamer2121** [opensource-socialnetwork/opensource-socialnetwork#2182]
**OSSN version: 6.4**

Hi,
I recently installed OSSN 6.4 locally for testing.
When I was testing, I tried to change the type of my user (that was the only user which is admin) to normal, and it worked, while it should not.
This is a problem because now, there is no admins in the system/social network, and the only way to fix it is to go to the database and change the user's type from normal to admin.
Please fix it as it is a critical problem.

Regards,
Eyad Tamer

**Comment by lianglee** [comment]
Hi Eyad,  thanks for pointing out we will add enhancement in next version preventing current admin user to not able to change its type.

**Comment by eyadtamer2121** [comment]
You're welcome!
