### ISSUE TITLE
[B] Places service has been sunsetted

### ISSUE THREAD

**Issue by rafaelmamorim** [opensource-socialnetwork/opensource-socialnetwork#2184]
> Places service has been sunsetted: https://algolia.com/blog/product/sunsetting-our-places-feature. Please contact us if you have questions

This message appears on JS console when I tried to add location on customer's site. Also, I tried on demo OSSN version as the same behavior. JS is loaded on this line (https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/aed6c4fa9344106553c01bac48f756233e56c41d/components/OssnWall/ossn_com.php#L43)

I will try a proposal to fix this.

**Comment by githubertus** [comment]
That'S nice, Raphael.
Actually I wasn't aware of that:
https://www.algolia.com/blog/product/sunsetting-our-places-feature/

**Comment by lianglee** [comment]
I wasn't aware too,  it was working few days ago.

**Comment by rafaelmamorim** [comment]
Discarding OSM nominatim option because in usage policy the auto-complete search is an  unacceptable use.

Source: https://operations.osmfoundation.org/policies/nominatim/

**Comment by rafaelmamorim** [comment]
I looked at several APIs providers, but all offer a few requests on a free plan/month. 

I'm considering in develop a new component with the list of cities running in a local database. In this process, the data are from geonames.org, daily updated, such as the GeoNames repo https://github.com/michaeldrennen/Geonames.

Is this a good idea?

**Comment by lianglee** [comment]
Hi Rafael,

It is good solution if it works like old way.   The things I have in mind is

1. Use of any paid service but people won't use it as its paid many people using OSSN as free.
2. Find a alternative 
3. Writing own solution that comes as bundle with OSSN
4. Writing a solution that works with API.

**Comment by lianglee** [comment]
The solution I found is https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-no-map/  we would require to create a new component called OssnLocations that have own settings where user can fill API key.

**Comment by rafaelmamorim** [comment]
Working in OssnLocation component using Mapbox API. However, in future, I'll try to make a new component with local data, if I have some free time.

**Comment by githubertus** [comment]
I have just uploaded a small component (see https://www.opensource-socialnetwork.org/component/view/6097)
which simply prevents these script errors - nothing more. So you may still enter your location manually without hassle. :)

**Comment by rafaelmamorim** [comment]
First functional version in https://github.com/rafaelmamorim/OSSN-OssnLocation

Can you check if it's working properly before making it available for download on opensource-socialnetwork?

**Comment by githubertus** [comment]
Thanks Rafael, 
your component is working flawlessly at my testsite.
The procedure of getting the api-key won't be everybody's darling, I think - but it's fair :)

**Comment by rafaelmamorim** [comment]
OssnLocation is available in OSSN site

https://www.opensource-socialnetwork.org/component/view/6100

**Comment by lianglee** [comment]
Replaced it with modified component 

```
<div class="ossn-page-contents">
	<div id="container"></div>
	<input type="text" id="myinput" />
	<script>
		$(document).ready(function() {
			ossn_location({
				container: '#container',
				input: '#myinput',
				placeholder: 'Enter Something',
			});
		});
	</script>
</div>
```
