### ISSUE TITLE
[B] wrong adjustmment of ossn-like-reactions-panel in mobile view

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2189]
`@media (max-width: 480px) {
	.ossn-like-reactions-panel {
		margin-left: -100px;
`
needs a fix

**Comment by lianglee** [comment]
Yes

**Comment by lianglee** [comment]
-40px solves problems for me 

![image](https://user-images.githubusercontent.com/805066/194572299-c7b9d16a-4351-4af3-9e12-a53daf71e500.png)
