### ISSUE TITLE
[E] Add a filetype block when user try upload video file into OssnWall

### ISSUE THREAD

**Issue by rafaelmamorim** [opensource-socialnetwork/opensource-socialnetwork#2191]
When user try to send a video file in post, without any text, ossn allow a blank post. I've tried in my test site and ossn demo with same results. 

![image](https://user-images.githubusercontent.com/3620428/196830829-82821ef1-1cae-4a43-b242-32c0e301fec4.png)

**Comment by rafaelmamorim** [comment]
Solution starts with add **accept="image/*"** into https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/fef86e5bd44606fa4a238d18b845e01c61340943/components/OssnWall/plugins/default/forms/OssnWall/user/container.php#L35
and in other similar places.

**Comment by lianglee** [comment]
Agree,
