### ISSUE TITLE
[E] prevent loading language files of disabled components

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2192]
I just became aware that language files of a component are getting loaded even if this component is not in use.
Maybe it's possible to circumvent this?

**Comment by lianglee** [comment]
I agree languages for disabled components must not be loaded.  seems bug

**Comment by githubertus** [comment]
it's in `ossn_load_available_languages()`
which currently doesn't do a check on active components and themes
maybe it should have a second parameter to load ALL files only on special demand (e.g. translations check)

**Comment by lianglee** [comment]
oh yes

**Comment by githubertus** [comment]
unfortunately that  requested second parameter to load ALL files on special demand has not been implemented,
and as a result printing messages inside enable.php doesn't work anymore

**Comment by lianglee** [comment]
> ossn_load_available_languages(false, true);
