### ISSUE TITLE
A system error has occurred. Please try again later. 

### ISSUE THREAD

**Issue by helixxger** [opensource-socialnetwork/opensource-socialnetwork#2195]
Ossn V6.4
My server : Openhost247 hosted
Apache-Version | 2.4.54
System PHP Version 7.4.32
PHP Version for WebSite: PHP 8.1 (ea-php81)
MySQL 5.7.40
URL: queermeet.eu

Hey!

When I try to install ossn on Openhost247, I get this error after inserting Database details:

A system error has occurred. Please try again later. You may email the details of this error to the system administrator at xxx@xxxx.xx (censored)

#1667377806|599407036AAC7319737AC15639923C0F

![error](https://user-images.githubusercontent.com/76208371/199689942-a978f549-633f-433a-8183-77c7257f598b.jpg)

[error_log.txt](https://github.com/opensource-socialnetwork/opensource-socialnetwork/files/9927788/error_log.txt)

**Comment by lianglee** [comment]
Your ticket is already received on openhsot247 creating tickets on multiple places won't help please wait

**Comment by helixxger** [comment]
> 

What are you talking about? I never texted openhost247 because of this issue?!

**Comment by helixxger** [comment]
> Your ticket is already received on openhsot247 creating tickets on multiple places won't help please wait

What are you talking about? I never texted openhost247 because of this issue?!

**Comment by lianglee** [comment]
Then please open a ticket there are we will assist you in installing there
in next 3-4 hours.
