### ISSUE TITLE
[B] Ossn 6.5 crashes if OssnLocation is disabled 

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2207]
Error: Call to undefined function ossn_location_load_jscss() in /var/www/ossn/components/OssnWall/ossn_com.php:594

**Comment by lianglee** [comment]
But it is required by https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v6.x/components/OssnWall/ossn_com.xml#L15-L19

**Comment by lianglee** [comment]
Hmm seems I can disable this strange.  It should show used_by

**Comment by lianglee** [comment]
Ah I thought used_by will show automatically lol But it need to be added 

> ossn_add_hook('required', 'components', 'com_blog_asure_requirements');..... example
