### ISSUE TITLE
OSSNLikes on mobile, like panel not completely visible

### ISSUE THREAD

**Issue by helixxger** [opensource-socialnetwork/opensource-socialnetwork#2208]
in components\OssnLikes\plugins\default\css\likes.php

this has to be changed:

@media (max-width: 480px) {
	.ossn-like-reactions-panel {
		margin-left: -100px;
		transform: scale(0.8);
	}

needs to be changed to circa "margin-left: -38px;" otherwise the panel is not completely visible.

I'll attach 2 screenshots

![IMG_2645](https://user-images.githubusercontent.com/76208371/204765927-6f0dcf39-b9f5-406c-a487-9e81b2e893cd.jpg)
![IMG_2646](https://user-images.githubusercontent.com/76208371/204765931-e8da70aa-edcd-4e18-8a87-8fbae0d3e08e.jpg)

**Comment by lianglee** [comment]
Duplicate
https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/2189

You are using old version
