### ISSUE TITLE
Run on IIS with mod_rewrite replacement URL Rewrite

### ISSUE THREAD

**Issue by HannahVernon** [opensource-socialnetwork/opensource-socialnetwork#2215]
I am attempting to get ossn to run on WIndows Server via IIS.   It was pretty trivial to circumvent the `isApache()` function in `/installation/classes/OssnInstall.php` to skip that particular check.

I realize that you don't officially support any of what I'm attempting, however I have PHP 8.1 installed, and the IIS equivalent of `mod_rewrite` running correctly, along with the required MySQL installation, and I figure I should be able to make it work.   I've used git to clone the v6.x branch of the repo onto my server, so I have all the .php files.  When I visit the site, I can see the installation prerequisites page.

I assume the installer sets up specific Apache mod_rewrite rules, however I cannot run the installer on Windows, so I do not know what rewrite rules should be set up.  When I use `curl http://<url>/rewrite.php`, I get back nothing, which prevents the initial installation from doing its work.  Is there a list of the required Apache `mod_rewrite` rules somewhere?  

I would love to get this working 🙂

**Comment by lianglee** [comment]
Hi,

You may edit https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v6.x/installation/configs/htaccess.dist  make sure you edit the htaccess.dist directly not .htaccess file.  I haven't run it on IIS but you may use apache on windows too.

**Comment by lianglee** [comment]
You need to convert rules

https://iis-umbraco.azurewebsites.net/downloads/microsoft/url-rewrite
https://learn.microsoft.com/en-us/iis/extensions/url-rewrite-module/importing-apache-modrewrite-rules

**Comment by HannahVernon** [comment]
Thanks very much for the details around the rules required for mod_rewrite.  I was able to directly convert the rules in the htaccess.dist file to Microsoft's URL Rewrite format quite easily.

**Comment by HannahVernon** [comment]
I've document the changes I made to support IIS, and have created a PR from my clone of your repo.
