### ISSUE TITLE
Delete message on User B screen without reload page 

### ISSUE THREAD

**Issue by rafaelmamorim** [opensource-socialnetwork/opensource-socialnetwork#2226]
Recently I realize that when User A removes the message to all, the message is still in User B's window until their page reloads. Maybe it's interesting to put a function to check from time to time each message status to keep or remove it. 

I tested this my developer OSSN instance and in demo.opensource-socialnetwork.org

Admin reply the message:
![image](https://user-images.githubusercontent.com/3620428/210844471-156b397a-0285-4311-9d66-ceb0907f7348.png)

Admin remove the message, selecting "all"
![image](https://user-images.githubusercontent.com/3620428/210844593-cb7ed5f7-6a6c-49ca-bfb2-6a1c75b974b9.png)

Message is removed in admin screen, but keep on wVandervort's window
![image](https://user-images.githubusercontent.com/3620428/210844697-e15e9176-2771-4ea4-b215-d12a28958712.png)

After the window reload of wVandervort user, message isn't showed.
![image](https://user-images.githubusercontent.com/3620428/210844788-9cf49523-6171-4aaa-9675-cc6de26924fd.png)

**Comment by lianglee** [comment]
That is correct OSSN doesn't support it.  It may result into many XHR requests making system slow.  This can be done easily if its Sockets but providers doesn't support it.

**Comment by lianglee** [comment]
Sorry closing as won't be fixed if you find any solution let us know.  I will open it again if found any resource friendly solution.

**Comment by rafaelmamorim** [comment]
On Jitsi Meet component I create an set of commands to send thru message window from user A to user B.  This commands uses tags like [script=alert(some message)] and PHP convert to <script class="nameClass">alert('some message');</script>. The class is used to hide the message to user on message and I can send virtually any command to user, include some command to remove some message. 

It's not a beautiful solution, but it works.

**Comment by lianglee** [comment]
So you send the command if message delete event triggered? what if message is not in the pagination and user deleted some old message that is outside the pagination? does this event still triggered?

**Comment by rafaelmamorim** [comment]
On my case, I need to delete all the messages with "jitsi-invite-link" CSS class.

**Comment by lianglee** [comment]
Hi Rafael, I quite doesn't understand your above last example about alert,  do you have any example with OSSN or how we can implement with OSSN?

**Comment by rafaelmamorim** [comment]
Go to www.redcrested.net/ossn. Login with demouser/123456789. In another window, access the site again, using camden43/123456789. In one of these users, go to OssnMessages and click on the green button, near by smile icon. 

If possible, keep both windows on view screen when you make the test.

**Comment by lianglee** [comment]
@rafaelmamorim i will check and let you know feedback.

**Comment by lianglee** [comment]
Just checked in your case it checks the status (30000) and then do a ajax to setstatus/getstatus I am trying to figure out to the way to avoid ajax requests so we need some kind of event trigger for both sides when message is deleted if window is opened.
