### ISSUE TITLE
Image in advertisement stays in cache

### ISSUE THREAD

**Issue by rafaelmamorim** [opensource-socialnetwork/opensource-socialnetwork#2229]
Yesterday, while doing a test (in OSSN 6.4 and 6.6), I noticed that after changing the image of an ad it does not update in the edit form (components/OssnAds/.../forms/OssnAds/edit.php).

Then I saw that the same happens in places where advertising is displayed to the user.

Looking at the code, I arrived at the call to the $file->output function (https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/5fd2964779d8dde99551c958625e150be7c0b45a/components/OssnAds/ossn_com.php#L57).

The issue is that in this function, the expires parameter is set to 6 months. Therefore, after changing the image in the advertisement, it is necessary to clear the local cache, or insist with the browser until it willingly accepts reloading the image from the cache.

The question is: what is the best way to solve this problem? Put a modified version of the output function in the OssnAd class or add a second parameter in the OssnFile class so that the expires parameter can be set to now in some cases.

I make the correction and send the PR. I would just like to discuss the solution before making the modification.

**Comment by lianglee** [comment]
Fixed,  technically it shouldn't be cached because e-tag is different for new file but since the URL uses ad id in URL so cached by browser algorithm.
