### ISSUE TITLE
Home Page Not be load if i change in login 2 page to make login with facebook and google. when i try to login a blank page show and stuck on user/login route

### ISSUE THREAD

**Issue by Majid-Bhatti** [opensource-socialnetwork/opensource-socialnetwork#2230]
Home Page Not be load if i change on login 2 page to make login with facebook and google. when i try to login a blank page show and stuck on user/login route. i revert the code again which i add also this site give me same black page of home.

**Comment by lianglee** [comment]
No idea what you mean, are you using social login component? or your own
