### ISSUE TITLE
[B] searchMessages viewed option doesn't work

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2235]

**Comment by githubertus** [comment]
Yeah, actually the line
`if ($message->viewed == 0 && $actual_from !== ossn_loggedin_user()->guid) {`
in recent.php appears strange to me.
I mean, viewed or not viewed is set by the **message->to** user anyway,
so why doing this extra comparison with the loggedin_user and not simply
`if ($message->viewed == 0) {`
?

**Comment by lianglee** [comment]
I believe the logic was 

if($message->viewed == 0 && $actual_from !== ossn_loggedin_user()->guid) {

If message is not viewed but message is sent from loggedin user (it should not add message-new class) in recent message view.  Because loggedin user already seen message by sending it :) So it should not show a different background (as new message) in recent sidebar.

**Comment by githubertus** [comment]
I understand now. Actually I wanted to achieve something different: Has my iown message been viewed by my friend or not?
So I added a change (still using old code) at line 32 like
`if ($message->viewed == 1) {
								$replied = "<i class='fa fa-reply'></i><div class='reply-text'>{$replied} <i class='fa fa-check'></i></div>";
							} else {
								$replied = "<i class='fa fa-reply'></i><div class='reply-text'>{$replied}</div>";
							}
`
![recent](https://user-images.githubusercontent.com/9904364/220089006-1db50138-1e5d-40f9-b11a-10aa4a3aba1a.jpg)

So in this example with the code above I can see:
- Höney has viewed my message already
- Botox has sent me a new message (still unviewed by me, marked grey by your code)

**Comment by lianglee** [comment]
Thanks I will look and add changes here after testing I opened new ticket for this https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/2237
