### ISSUE TITLE
[E] File sizes error not showing on profile photo/cover upload 

### ISSUE THREAD

**Issue by helixxger** [opensource-socialnetwork/opensource-socialnetwork#2243]
in my .htaccess file the maximum allowed size is 5MB for upload. 

When a user tries to upload a 14MB big picture as a profile picture, then the upload is successful and the picture shows on the wall, but not in profile.

If you try to upload the same photo on the wall, then you get an error message saying that the file is too big.

**Comment by lianglee** [comment]
After testing it worked fine for us,  settings 2MB upload size in php.ini it gave us the error.

**Comment by helixxger** [comment]
I set the size in the .htaccess

**Comment by helixxger** [comment]
In my php.ini is the filesize on 2mb, but i still don't get a error message when uploading a profile picture

**Comment by lianglee** [comment]
Fixed in next version
