### ISSUE TITLE
is:issue is:open In the Goblack theme, all the administrator options remain uneditable, and you are unable to switch to another theme 

### ISSUE THREAD

**Issue by al3j4ndr0dark** [opensource-socialnetwork/opensource-socialnetwork#2253]
![Screenshot 2023-03-25 at 18 27 10](https://user-images.githubusercontent.com/81258757/227726709-0b8788b7-54cf-4679-8774-37554ff93f42.png)

**Comment by githubertus** [comment]
Which version of Ossn are you running?

**Comment by al3j4ndr0dark** [comment]
The last one, I just installed it three days ago. I had to reinstall the whole site because it was imposible to switch to another theme. The Goblack Theme has a serious bug

**Comment by lianglee** [comment]
This theme marked as not working with latest version.  https://www.opensource-socialnetwork.org/component/view/2396/black-theme
