### ISSUE TITLE
[B] Emojis shows entities in trimmed message notification

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2257]
![image](https://user-images.githubusercontent.com/805066/232969318-1ff6545e-5bc7-4ccd-b726-f2a11fb0eee7.png)

**Comment by githubertus** [comment]
Actually, I did not check the usage of strl() all over the place yet, but at least for messages this code does the trick:

`function strl($str, $limit = NULL, $dots = true) {
	if (isset($str) && isset($limit)) {
		error_log('STRL: ' . $str . ' LEN: ' . mb_strlen($str, 'HTML-ENTITIES') . ' LIMIT: ' . $limit);
		if (mb_strlen($str, 'HTML-ENTITIES') > $limit) {
			if ($dots == true) {
				return mb_substr($str, 0, $limit, 'HTML-ENTITIES') . '...';
			} elseif ($dots == false) {
				return mb_substr($str, 0, $limit, 'HTML-ENTITIES');
			}
		} elseif (mb_strlen($str, 'HTML-ENTITIES') <= $limit) {
			return $str;
		}
		
	}
	return false;
}`

**Comment by lianglee** [comment]
Really nice!

**Comment by githubertus** [comment]
Sorry, did not check that:
`HTML-ENTITIES` is indeed working correctly for emojis, but not for chars like used in cyrillic language.
should be `UTF-16` instead

Name with 1 emoji + cyrillic ending
STRL: Hö&#x1f600;eyПарооль Bünny LEN: 27 <--- WRONG using HTML-ENTITIES
STRL: Hö&#x1f600;eyПарооль Bünny LEN: 17 <-- CORRECT using UTF-16

**Comment by lianglee** [comment]
Oh so just changing to UTF-16 instead

**Comment by lianglee** [comment]
@githubertus 

```
function strl($str, $limit = NULL, $dots = true) {
	if (isset($str) && isset($limit)) {
		//error_log('STRL: ' . $str . ' LEN: ' . mb_strlen($str, 'UTF-16') . ' LIMIT: ' . $limit);
		//[B] Emojis shows entities in trimmed message notification #2257
		if (mb_strlen($str, 'UTF-16') > $limit) {
			if ($dots == true) {
				return mb_substr($str, 0, $limit, 'UTF-16') . '...';
			} elseif ($dots == false) {
				return mb_substr($str, 0, $limit, 'UTF-16');
			}
		} elseif (mb_strlen($str, 'UTF-16') <= $limit) {
			return $str;
		}
		
	}
	return false;
}

https://translate.google.com/?sl=en&tl=bg&text=System%20Administrator&op=translate

Still breaks

![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/5e17bbf4-ffb6-4e63-87c2-4b982453907c)



```

**Comment by lianglee** [comment]
with UTF-8 it showing fine. 

> HTML-ENTITIES TO UTF-8  

![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/ddece831-bc95-4e09-9577-ce3427852f3e)

**Comment by githubertus** [comment]
yes, but this alone isn't working for emojis

keep utf-8 in place,
but before checking length, convert the string like
`$str = html_entity_decode($str, ENT_QUOTES | ENT_HTML5, 'UTF-8');`

see https://stackoverflow.com/questions/25372068/convert-html-entities-and-special-characters-to-utf8-text-in-php

**Comment by lianglee** [comment]
@githubertus this results to open site to XSS attacks.  We need something else

**Comment by lianglee** [comment]
@githubertus the solution maybe is to use decode and compare and at end encode again

```
function strl($str, $limit = NULL, $dots = true) {
	if (isset($str) && isset($limit)) {
		//error_log('STRL: ' . $str . ' LEN: ' . mb_strlen($str, 'HTML-ENTITIES') . ' LIMIT: ' . $limit);
		//[B] Emojis shows entities in trimmed message notification #2257
		$str = html_entity_decode($str, ENT_QUOTES | ENT_HTML5, 'UTF-8');
		if (mb_strlen($str, 'UTF-8') > $limit) {
			$encoded = mb_substr($str, 0, $limit, 'UTF-8') ;
			$encoded = htmlspecialchars($encoded, ENT_QUOTES, 'UTF-8');
			if ($dots == true) {
				return $encoded. '...';
			} elseif ($dots == false) {
				return $encoded;
			}
		} elseif (mb_strlen($str, 'UTF-8') <= $limit) {
			return $str;
		}
		
	}
	return false;
}
```

**Comment by lianglee** [comment]
Sorry last one didn't worked well it shows large emoji line :)
