### ISSUE TITLE
[E] Add max-height in .ossn-wall-item .post-contents img

### ISSUE THREAD

**Issue by rafaelmamorim** [opensource-socialnetwork/opensource-socialnetwork#2259]
When a portrait image is loaded into the timeline using the GoBlue theme, the image is 1500px tall. It is interesting to add a max-height parameter to the CSS to prevent scrolling to view the image. As this change impacts the width of the image, I also suggest aligning the image in the center of the post. So the selector looks like this:

```
.ossn-wall-item .post-contents img {
     max-width: 100%;
     border: 1px solid #eae8e8;
     display: block;
     margin-bottom: 10px;
     max-height: 80vh;
     margin-left: auto;
     margin-right: auto;
}
```
The image attached here was posted at https://demo.opensource-socialnetwork.org/post/view/42.

![image](https://user-images.githubusercontent.com/3620428/236016976-35b9def8-bebb-4046-8cfe-56d635894d5a.png)

**Comment by lianglee** [comment]
Thank you,  I agree with the images i will merge it after testing.

👍🏻👍🏻
