### ISSUE TITLE
My website is powered by open source. I need help with a technical issue. Mt social log in doesn't work and I need a mirror app for google play and Apple. Can you help ? My website is https://lingochat.online.  

### ISSUE THREAD

**Issue by litzjoseph** [opensource-socialnetwork/opensource-socialnetwork#2264]
My website is powered by open source. I need help with a technical issue. Mt social log in doesn't work and I need a mirror app for google play and Apple. Can you help ? My website is https://lingochat.online.

**Comment by lianglee** [comment]
Hello Joseph, you can contact us https://www.openteknik.com/contact  for the checking the social login and for mirror app with push notifications.
