### ISSUE TITLE
[B] Command to replace slash to backslash missing in vendors/jwt/autoload.php

### ISSUE THREAD

**Issue by rafaelmamorim** [opensource-socialnetwork/opensource-socialnetwork#2274]
Yesterday I want to use OssnJWT class, but I got some errors. After taking a look at the JWT code, I put 
`$path = str_replace('\\','/',$path);` right after https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/859b5e8bb9440f7d2c2a7e2ddd04963aa68f6f01/vendors/jwt/autoload.php#L5 to fix the issue.

**Comment by lianglee** [comment]
Very strange,  how did you use the OssnJWT class? I tested it worked fine without it

My code 
test.php

```
<?php
define('OSSN_ALLOW_SYSTEM_START', true);
require_once 'system/start.php';
$OssnJWT = new OssnJWT(array('data' => 1), 'key');
echo $OssnJWT->encode();

```

It shows correct result.   I tested on Windows Machine,  Test Environment

**Comment by rafaelmamorim** [comment]
Same code on linux produces this log message:

[02-Jul-2023 11:10:30 America/Sao_Paulo] [#1688307030|H3OGHH5FBN6J59QN2NCDOIQSCS] Error: Class "Firebase\JWT\JWT" not found in /home/u592571552/domains/redcrested.net/public_html/ossn/classes/OssnJWT.php:42
Stack trace:
#0 /home/u592571552/domains/redcrested.net/public_html/ossn/test.php(5): OssnJWT->encode()
#1 {main}

**Comment by lianglee** [comment]
Confirmed on linux
