### ISSUE TITLE
.ossn-profile .user-fullname { in Awesome theme CSS is wrong

### ISSUE THREAD

**Issue by queermeet** [opensource-socialnetwork/opensource-socialnetwork#2281]
the rule has 2 font-size options, but the second one "font-size: 2.3vw;" is wrong and causes problems

.ossn-profile .user-fullname {
	color: #FFF;
	font-weight: bold;
	margin-top: -155px;
	font-size: 35px;
	font-size: 2.3vw;

**Comment by lianglee** [comment]
But OSSN free version doesn't have this theme.  So simply remove 2.3vw  
2.3vw is for adjusting the width on screen devices but you can remove this if it help you to resolve the issue.
