### ISSUE TITLE
[E] Add style to checkboxes 

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2291]

**Comment by carlbee1** [comment]
Great think your scams also !carlbeeOn Sep 9, 2023, at 2:08 PM, Arsalan Shah ***@***.***> wrote:Closed #2291 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
