### ISSUE TITLE
[B] non-UTF8 chars in 3 language files of Goblue

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2298]
affected translations: DE, ES, FR

**Comment by lianglee** [comment]
is it BOM char? looks fine for me in editors (notepad++) 

 https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/master/themes/goblue/locale/ossn.de.php

**Comment by githubertus** [comment]
no BOM
hd ossn.de.php gives:
`00000000  3c 3f 70 68 70 0a 2f 2a  2a 0a 20 2a 20 4f 70 65  |<?php./**. * Ope|
`

It's simply wrong encoded
file ossn.de.php gives:
`PHP script, ISO-8859 text
`

while others have
`PHP script, UTF-8 Unicode text
`
or just plain ASCII

**Comment by lianglee** [comment]
Fixed via notepadd++
