### ISSUE TITLE
[B] usage of unavailable font-family in Goblue

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2301]
line numbers 1056, 1938 and 2011 are addressing **Verdana**
which is not guaranteed to be available on every platform
(e.g. Ubuntu is replacing it by a serif font)
why using a different font at all here and not goblue's default PT-Sans?

**Comment by lianglee** [comment]
I wasn't aware of it that it have fonts other than default google fonts we
using.

I will fix it

**Comment by lianglee** [comment]
Removed that font and also fa-lg to adjust with current goblue font size

**Comment by dacCR** [comment]
Hi, where can the update be downloaded from once done?

**Comment by dacCR** [comment]
Thank you for fixing that!
