### ISSUE TITLE
Private site links

### ISSUE THREAD

**Issue by dacCR** [opensource-socialnetwork/opensource-socialnetwork#2303]
Hi, 

I noticed that with a closed site, clicking on most things leads to the login/signup page but clicking on Notifications leads to a 404. I'm not sure why Notifications has a different result so wanted to share that with you.

**Comment by lianglee** [comment]
Seems private network works well in this case it redirects to home page where login form is.  You may also redirect them to specific page by editing PrivateNetwork.php deney() method and redirect('login');
