### ISSUE TITLE
how to create administrator login to ossn hosted site and how to customize it

### ISSUE THREAD

**Issue by srinivv1** [opensource-socialnetwork/opensource-socialnetwork#2308]
### Discussed in https://github.com/opensource-socialnetwork/opensource-socialnetwork/discussions/2213

<div type='discussions-op-text'>

<sup>Originally posted by **ClosetMonkey** December 10, 2022</sup>
Has the forum at opensource-socialnetwork.org been closed? </div>

**Comment by lianglee** [comment]
Administrator login need to be created during installation process.  How did you installed OSSN?

**Comment by srinivv1** [comment]
hi
  i used bluehost shared hosting and the software got installed by
softacaulous. i created the login but now dont know how to access it.
aspirationslashes.com does not take me to administrator login

**Comment by lianglee** [comment]
Remove the installation from it and reinstall it. During setup you may
asked to enter login details.

**Comment by lianglee** [comment]
Closing as no response

**Comment by srinivv1** [comment]
hi
  i went to bluehost.in to use the the login aspirationslashes.com and
password. it takes me to the first  screenshot.
i want to know how to customize it  and add google ad sense to it.  typing
aspirationslashes.com takes me to second screen shot
