### ISSUE TITLE
[B] online friends being removed from Chat tab

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2309]
`$('.friends-list-item').remove();`
of OssnChat.Boot.php
is removing this div from friend-item.php
that's why the list is empty

**Comment by lianglee** [comment]
Yes need to look, $('.friends-list-item').remove(); removing them from the chat tab

**Comment by lianglee** [comment]
Just moved 

```
$('.friends-list').find('.data').html(OssnChat['friends']['data']);	
```

To new place and removed some lines,  works now but let me know if it works on your side

**Comment by githubertus** [comment]
yes, verified your fix is working. thx.

**Comment by githubertus** [comment]
but just found another small glitch getting a red offline dot, although the member is online:
![chat-online-status-Screenshot_2023-10-12_10-13-48](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/9904364/ade15d08-7cab-480f-ac3f-0f97980703e0)

**Comment by lianglee** [comment]
Fixed
