### ISSUE TITLE
A bug error in network.ierta.net

### ISSUE THREAD

**Issue by EragGoshiH** [opensource-socialnetwork/opensource-socialnetwork#2315]
In night, I noticed that in profile page message tab   
didn't work. So I deleted OssnMessage and OssnChat components from admin panel,  I contacted with openteknik by whatsapp business account they made a issue, after fixing issue, they told me to use updated source code, so I downloaded this from GitHub and make OssnMessage.zip & OssnChat.zip then install & enable it by admin panel...... after that it shows that error message
![Screenshot_2023-10-18-23-32-43-737_com kiwibrowser browser](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/117589098/09dcc919-e754-43eb-8036-f9d8dfce2575)

I already booked a ticket in openteknik! But got no response! 

#Plesase help me to fix this bug.

**Comment by lianglee** [comment]
Delete components/ImageInMessages/ folder
