### ISSUE TITLE
Photo uploaded on wall not available in profile

### ISSUE THREAD

**Issue by helixxger** [opensource-socialnetwork/opensource-socialnetwork#2324]
When you upload a photo on OSSNWall it is not available on profile, only on wall.

Would make more sense if it would be available on profile too.

**Comment by lianglee** [comment]
Why does post photos appears on profile?

**Comment by helixxger** [comment]
It’s a normal process on all social media platforms.

It’s also easier than go to profile and upload them there

Just upload to wall and use as profile picture later, if you want too
Am 14. Nov. 2023, 13:04 +0100 schrieb Arsalan Shah ***@***.***>:

**Comment by githubertus** [comment]
@helixxger It makes sense to discuss feature requests in the Ossn forum - and use this place for real bug reports only.
