### ISSUE TITLE
[B] Goblue 6.4 checkbox (checked) display corrupted

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2330]
On the user frontend it looks like
![goblue-checkbox-before](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/9904364/e0e616a8-8476-487c-8852-6dd9f644f57d)

Removing **absolute position** and **transform rotat**e from
.ossn-form input[type="checkbox"]:checked::before

seems to fix that.

Still needs more investigation, because checkbox and text are not aligned prpoerly

**Comment by themattbook** [comment]
I'm unable to duplicate this issue. The formatting seems okay to me? I did remove the positioning and transform from the check and it had the reverse effect as expected.

<img width="240" alt="image" src="https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/12483820/87fa3384-0cce-41fe-bad3-dd180c96d815">

**Comment by githubertus** [comment]
Huuh, that's strange - even your option labels look different! ;)

**Comment by themattbook** [comment]
Haha, noted. But honestly, in the grand laws of CSS, there would have to be some form of transformation happening somewhere. I'm wondering if this isn't a second round of transform and positioning happening?

Which component are you using so I can see this page exactly? I should have asked at the start, but I'm not the sharpest tool in the box, if you know what I mean. Hehe.

**Comment by githubertus** [comment]
We just have these days. ;) Long time ago I opened a file with` fopen` and closed it with `close` - wondering why my machine ran out of file descriptors after a while. I don't remember exactly how many hours I stared at that code, it was definitely more than an hour. German idiom: "Ich bin nicht die hellste Kerze auf der Torte"
But you wanted to know the component: It's Contact Suggestions. 
https://www.opensource-socialnetwork.org/component/view/4880/contact-suggestions

**Comment by lianglee** [comment]
For text adding

```
.checkbox-block span {
	margin-top:5px;
}
```
resolves the text problem and removing absolute and rotate resolves the problem you mentioned. 

![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/24686a1c-9c58-47ae-b876-be9450a5370b)

**Comment by lianglee** [comment]
But creates issue on other places :) investigating as text not aligned if used on newsfeed
