### ISSUE TITLE
Some warnings on Ossn 7.3dev 

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2349]
Undefined variable $notif" in file components/OssnPhotos/ossn_com.php (line 212)
Undefined variable $notif" in file components/OssnProfile/ossn_com.php (line 439)

when uploading a new valid Group cover:
Attempt to read property "guid" on bool" in file components/OssnGroups/classes/OssnGroup.php (line 518)

usage of webp images for covers:
- working fine as profile cover
- not working as group cover ('cannot save the uploaded file')

attaching an image to a message:
Undefined variable $user" in file components/OssnMessages/ossn_com.php (line 236)
Attempt to read property "guid" on null" in file components/OssnMessages/plugins/default/messages/templates/message-send.php (line 14)

**Comment by lianglee** [comment]
[B] Verify submission of non-required empty fields at signup.
