### ISSUE TITLE
[B] Disorted frontpage icons

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2352]
![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/93f0190f-5d87-49e2-93cd-8187bd0b8758)

**Comment by githubertus** [comment]
should they display like that?

![some-centered-icons](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/9904364/f848f489-d6f8-4b59-be97-e038898604a2)

**Comment by lianglee** [comment]
Yes the second one looks good to me

**Comment by lianglee** [comment]
![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/24a862ad-c688-4ba0-afd3-bab778bf673c)

Fixed thanks to @githubertus
