### ISSUE TITLE
Unable to upload high efficiency (.heic) images and videos

### ISSUE THREAD

**Issue by waqasvt** [opensource-socialnetwork/opensource-socialnetwork#2354]
unable to upload images and videos with .heic extension.
Made change i could understand, added mime types in cpanel but nothing is working

**Comment by lianglee** [comment]
Browsers doesn't support heic images https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format#Web_browsers

**Comment by lianglee** [comment]
Without special tool it is not possible!
