### ISSUE TITLE
[B] input of non_required extra fields in signup form is ignored

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#2355]
i was trying to extend my signup form like
`$fields['non_required']['text'][] = $extrafield;`
but the input of that field is not saved on registration (no new entities record)

while this one
`$fields['required']['text'][] = $extrafield;`
saves the input correctly

**Comment by lianglee** [comment]
Thanks fixed it ,  never realized it :)
