### ISSUE TITLE
Spacing issues in OSSNcomments

### ISSUE THREAD

**Issue by AT3META** [opensource-socialnetwork/opensource-socialnetwork#2361]
![IMG_2163](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/58276731/b7fd2ef9-bee7-467d-8d9c-308f73f0554d)
When entering comments and pressing return or enter, the system isn't placing a space or break in the comment line. See screenshot.

**Comment by lianglee** [comment]
![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/7dac6614-138c-439c-a55f-328a1e898d00)

Pressing SHIFT + Enter make new lines works fine

**Comment by AT3META** [comment]
Ok so, Shift + Enter will not work on mobile devices. Secondly, that should be coded in, not something people should be expected to know. Please reopen this issue.
