### ISSUE TITLE
500 error during installation without any message

### ISSUE THREAD

**Issue by felixtech-msp** [opensource-socialnetwork/opensource-socialnetwork#2365]
During the installation process the installer fails with a 500 error. There is no error message displayed, even when error reporting and logging is explicitly enabled in the php.ini. There get some tables in the database created. The PHP version is 8.2.

**Comment by felixtech-msp** [comment]
I found the reason to be a bug where when the data directory is not writable an error message is shown and in the background something gets done to destroy the installation. When the data directory then is made writable, the installation process starts and then fails as the installation is already destroyed.
The solution is then to entirely delete and recreate the database and to delete the whoe OSSN folder and unzip it again.

**Comment by lianglee** [comment]
Glad you resolved the issue.
