### ISSUE TITLE
Created post not showing 

### ISSUE THREAD

**Issue by developer-bhumika** [opensource-socialnetwork/opensource-socialnetwork#2367]
Hello team, 

I have created one wall post, it is successfully created, but when i am trying to retrieve in particular group, its showing no user exist. 

Please refer this screenshots.

Creating post: https://drive.google.com/file/d/18x2F6DuHkVdbYQFuZPRkbpEec0cWnp6t/view
Trying to retrieve post: https://drive.google.com/file/d/1s_8coSx_aSC2kPmkvfgv1pASdvAMTb2t/view

Please update me on this as soon as possible.

**Comment by lianglee** [comment]
If you only want to get the single post that created you need to pass post guid to https://www.opensource-socialnetwork.org/webservices/view/3577/wall-view-post which in your case payload->post->guid which is 119

**Comment by developer-bhumika** [comment]
@lianglee  i tried using 4 too but its same. If i want to fetch particular group post then what i have to pass in uguid?

**Comment by lianglee** [comment]
Your website have no posts https://nihss.joincommunity.net/ where you are trying to add?

I added the test post and it showing fine from the default account

https://nihss.joincommunity.net/api/v1.0/wall_list_user?api_key_token=<token>&uguid=1


![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/5b9d9ab8-4d8b-4720-8d5d-fdf68f6d0632)

**Comment by lianglee** [comment]
For group seems in our documentation end point is wrong use following for group posts list

https://nihss.joincommunity.net/api/v1.0/wall_list_group?api_key_token=(your api key)&guid=1&group_guid=5

![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/e5cc5be1-9b40-4159-b900-9dd5e82f2698)

**Comment by developer-bhumika** [comment]
> https://nihss.joincommunity.net/api/v1.0/wall_list_group?api_key_token=(your api key)&guid=1&group_guid=5

Ok, its working now.

**Comment by developer-bhumika** [comment]
@lianglee i want to discuss about push notification, i want to send push notification to user mobile device while sending messages. Are you providing sending push notification feature?

**Comment by developer-bhumika** [comment]
@lianglee there are few apis missing in the documentation uploaded on your website like edit post, delete grop etc. Can you please provide complete documentation for apis ?

**Comment by developer-bhumika** [comment]
@lianglee any updates on questions i asked?

**Comment by lianglee** [comment]
Already answered your ticket.

Also did you integrated all of existing apis already?

**Comment by developer-bhumika** [comment]
@lianglee 

I have integrated following apis :
1. comment_edit
2. comments_list
3. groups_add
4. groups_edit
5. groups_members
6. groups_view
7. groups_user_memberof
8. comment_delete
9. comment_add
10. wall_delete
11. wall_list_group
12. wall_list_user
13. wall_add
14. user_remove_friend
15. user_add_friend
16. user_is_friend
17. user_edit
18. user_authenticate
19. user_friends
20. user_details

I am not finding following existing apis from document
1. Apis for media tab
2. Group_delete
3. Post edit
4. Image upload
5. Group join
6. Group unjoin
7. Message module

please provide me above apis 

Thanks

**Comment by lianglee** [comment]
![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/9e2f0c31-2512-44dc-9bf6-a73124c75ca8)

![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/05967c8c-1dcd-45d9-bb27-4e37fa46f103)

![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/db992288-9c86-447d-b76b-c491cda1bf31)


Everything is there except post edit there is no post edit api endpoint yet

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/webservices/view/7037/delete-group

https://www.opensource-socialnetwork.org/webservices/view/7038/edit-wall-post

**Comment by developer-bhumika** [comment]
@lianglee 
Please check group join, not working.
![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/86490602/7c3fd96c-99af-4e28-816c-96e7e0d5cf04)

**Comment by lianglee** [comment]
Report it here https://github.com/opensource-socialnetwork/OssnServices

Check for error log and see what is the error.

Enable error reporting and check error_log against that error code

**Comment by developer-bhumika** [comment]
@lianglee regarding media apis, i want to show media by group but in current apis its userwise. I want to show media under the group selection.

**Comment by developer-bhumika** [comment]
@lianglee Is there any way where we can maintain one thread and discuss all issues we are facing ? 
I tried to contact using your website but in that i can not reply to those emails because it has no reply.
