### ISSUE TITLE
[B] Wrong notification shows if commented

### ISSUE THREAD

**Issue by queermeet-dev** [opensource-socialnetwork/opensource-socialnetwork#2373]
When someone comment a post, I get the notification, that he liked it:

![notif2](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/160646911/c1d62896-4af0-4eea-9b68-a20997ffd869)
![notif](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/160646911/0258b039-45bb-4cd0-ae12-69bdd200929d)

I also tested with a complete fresh installation - same problem:

![notif 4](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/160646911/2b3771a8-326b-40a8-85cd-97f50e294ade)
![notif 3](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/160646911/64aa6822-8393-4028-ab96-280e93e4dbfd)

**Comment by lianglee** [comment]
I will check for you. I am just sick right now. I believe translation file
error

**Comment by lianglee** [comment]
Fixed you can download latest premium version its pre-patched now.  Simply copy OssnWall component files

**Comment by queermeet-dev** [comment]
Thanks, it works!!!
