### ISSUE TITLE
buttons in OSSNGroups not correctly placed

### ISSUE THREAD

**Issue by queermeet-dev** [opensource-socialnetwork/opensource-socialnetwork#2374]
The buttons in the form in OSSNGroups to edit the form are not placed correctly

![groups](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/160646911/fd006ac6-82c3-4d77-93eb-33be9c173109)

**Comment by lianglee** [comment]
Update your theme i believe you are using old Awesome theme

**Comment by queermeet-dev** [comment]
Cannot update cause the darkmode component is not working at the moment

--
Regards
________________________________

Dominik Lieger
Am 2. Juni 2024, 14:08 +0200 schrieb Arsalan Shah ***@***.***>:

**Comment by lianglee** [comment]
Try to update layouts folder

**Comment by queermeet-dev** [comment]
I updated layouts folder under themes/Awesome/plugins/default/theme/page

Without success

**Comment by lianglee** [comment]
Replace everything under themes/Awesome/plugins/default/theme/

**Comment by queermeet-dev** [comment]
I'll try today in the evening, sorry for the delay

**Comment by queermeet-dev** [comment]
I replaced everything in the folder, but no success

![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/160646911/cb966745-3699-4133-ac91-61eecb132ac3)

**Comment by lianglee** [comment]
![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/31162fec-f7af-407b-8046-17ad3093d13c)

It works fine for me on the latest theme and version.  Can you test on fresh installation please?  If it works on fresh then check the dark mode component you are using.
