### ISSUE TITLE
Forum images

### ISSUE THREAD

**Issue by compie67** [opensource-socialnetwork/opensource-socialnetwork#2378]
Hi there
@nodesleep 
Arsalan got some private issues, got some problem with the Forum module.
Hope that i am good here.

got only the url image option(no upload?) and this does not work.
Can you point me to right direction, richts ar good. all other modules works fine

regards
Eric

**Comment by nodesleep** [comment]
You don't have the ability to upload images, you're saying? Apologies for the late reply.
