### ISSUE TITLE
[B] Redis password is an undefined var

### ISSUE THREAD

**Issue by dkemens** [opensource-socialnetwork/opensource-socialnetwork#2379]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/master/classes/OssnRedis.php#L32

Should probably be `$settings['password']`. `$password` doesn't exist.

**Comment by lianglee** [comment]
Yes true seems bug thanks for pointing that out

**Comment by dkemens** [comment]
I just had to fix this locally. I was expecting a big performance bump after enabling dcache, but it seems to have had virtually no impact. I recognize that the size of the database is the issue here, but I was hoping upgrading from 5.3 to 7.6 and enabling all cache would have _some_ impact. The fact that this exists on master tells me it's not very well tested and maybe we shouldn't expect any performance improvement?

**Comment by lianglee** [comment]
5.3 is too old first you need to upgrade one by one to new version I think
to ossn 5.6 first then to 6.x till last 6.x and then to 7.0 and then 7.6

Ossn 5.3 have performance issue and without updating all the files you
won't get any speed.

**Comment by dkemens** [comment]
Yeah, I've upgraded from 5.3 to 6.1 to 6.3, than finally to 7.6.
