### ISSUE TITLE
error lines in Sharepost 

### ISSUE THREAD

**Issue by compie67** [opensource-socialnetwork/opensource-socialnetwork#2380]
I hope this is not related but got some messages from my users in nlsociaal.nl that there post and reaction are disapearing.
I have actived the error.log and got directly many error lines on the module sharepost.
[error_log.zip](https://github.com/user-attachments/files/15604916/error_log.zip)

.zip included

**Comment by lianglee** [comment]
This is free version please use ticket and submit the error log and error
there

**Comment by compie67** [comment]
lol my fault, will do

**Comment by compie67** [comment]
add this error to the right place
