### ISSUE TITLE
Banned people still shown as friends

### ISSUE THREAD

**Issue by queermeet-dev** [opensource-socialnetwork/opensource-socialnetwork#2381]
When someone is banned on an OSSN Website, the person is still shown as a friend with a special profile picture, but that makes no sense.

![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/160646911/85eb7c80-5025-48a1-8a24-a323ef7d7837)

**Comment by lianglee** [comment]
Does person profile picture changes to banned one?

**Comment by queermeet-dev** [comment]
yes, but banned people shouldn't be shown as friends anymore

**Comment by lianglee** [comment]
It shown as friend actually.  There is other handling that not shows
friends when they banned what if you unban them those making the query more
complex.

This is not an issue

**Comment by lianglee** [comment]
I mean what you are requesting is not possible it requires editing large
code
