### ISSUE TITLE
Gif as profile photo

### ISSUE THREAD

**Issue by compie67** [opensource-socialnetwork/opensource-socialnetwork#2382]
Is there an way to activate/accept the option for users to upload an gif avatar.
Got fast VPS so that is no problem.

Been searching for while no in the code
;-)
regards
Eric

**Comment by lianglee** [comment]
This place is for reporting bugs only please ask on community i think there
is a way.

**Comment by compie67** [comment]
my bad, post it there en close this

**Comment by compie67** [comment]
add to the right place
