### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by christianloesel** [opensource-socialnetwork/opensource-socialnetwork#2383]
On fresh installation:

OssnDatabaseException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'friend:request' in 'on clause' 
 SELECT DISTINCT  u.guid, u.* FROM ossn_users as u JOIN ossn_relationships AS r1 ON r1.relation_to = u.guid AND r1.type = "friend:request" JOIN ossn_relationships AS r2 ON r2.relation_from = r1.relation_to AND r2.type = "friend:request" WHERE(u.time_created IS NOT NULL AND (r1.relation_from = '1' AND r2.relation_to = '1'))  ORDER by u.guid ASC LIMIT 0, 10;  in /homepages/33/d590823121/htdocs/ossn/classes/OssnDatabase.php:148
Stack trace:
#0 /homepages/33/d590823121/htdocs/ossn/classes/OssnDatabase.php(281): OssnDatabase->execute()
#1 /homepages/33/d590823121/htdocs/ossn/classes/OssnUser.php(735): OssnDatabase->select()
#2 /homepages/33/d590823121/htdocs/ossn/classes/OssnUser.php(487): OssnUser->searchUsers()
#3 /homepages/33/d590823121/htdocs/ossn/components/OssnWall/classes/OssnWall.php(444): OssnUser->getFriends()
#4 /homepages/33/d590823121/htdocs/ossn/components/OssnWall/plugins/default/wall/siteactivity.php(18): OssnWall->getAllPosts()
#5 /homepages/33/d590823121/htdocs/ossn/libraries/ossn.lib.views.php(27): include('/homepages/33/d...')
#6 /homepages/33/d590823121/htdocs/ossn/libraries/ossn.lib.views.php(50): ossn_include()
#7 /homepages/33/d590823121/htdocs/ossn/libraries/ossn.lib.plugins.php(75): ossn_view()
#8 /homepages/33/d590823121/htdocs/ossn/components/OssnWall/plugins/default/wall/pages/wall.php(27): ossn_plugin_view()
#9 /homepages/33/d590823121/htdocs/ossn/libraries/ossn.lib.views.php(27): include('/homepages/33/d...')
#10 /homepages/33/d590823121/htdocs/ossn/libraries/ossn.lib.views.php(50): ossn_include()
#11 /homepages/33/d590823121/htdocs/ossn/libraries/ossn.lib.plugins.php(75): ossn_view()
#12 /homepages/33/d590823121/htdocs/ossn/libraries/ossn.lib.initialize.php(119): ossn_plugin_view()
#13 /homepages/33/d590823121/htdocs/ossn/libraries/ossn.lib.page.php(79): ossn_user_pagehandler()
#14 /homepages/33/d590823121/htdocs/ossn/index.php(22): ossn_load_page()
#15 {main}

I have no Idea, since I only wanted to try out OSSN to find out the features.

**Comment by lianglee** [comment]
This looks like issue with your database at what page you get this error?

How did you installed using OSSN installer?

**Comment by christianloesel** [comment]
When i go from admin to main. I downloaded and unzipped the archive.

**Comment by lianglee** [comment]
Seems issue with your server configuration please change and see if it works on others as it works fine on different test installations.

**Comment by tkindinger** [comment]
OssnDatabaseException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'friend:request' in 'on clause' 
 SELECT DISTINCT  u.guid, u.* FROM ossn_users as u JOIN ossn_relationships AS r1 ON r1.relation_to = u.guid AND r1.type = "friend:request" JOIN ossn_relationships AS r2 ON r2.relation_from = r1.relation_to AND r2.type = "friend:request" WHERE(u.time_created IS NOT NULL AND (r1.relation_from = '1' AND r2.relation_to = '1'))  ORDER by u.guid ASC LIMIT 0, 10;  in /var/www/html/classes/OssnDatabase.php:148
Stack trace:
#0 /var/www/html/classes/OssnDatabase.php(281): OssnDatabase->execute()
#1 /var/www/html/classes/OssnUser.php(735): OssnDatabase->select()
#2 /var/www/html/classes/OssnUser.php(487): OssnUser->searchUsers()
#3 /var/www/html/components/OssnWall/classes/OssnWall.php(444): OssnUser->getFriends()
#4 /var/www/html/components/OssnWall/plugins/default/wall/siteactivity.php(18): OssnWall->getAllPosts()
#5 /var/www/html/libraries/ossn.lib.views.php(27): include('...')
#6 /var/www/html/libraries/ossn.lib.views.php(50): ossn_include()
#7 /var/www/html/libraries/ossn.lib.plugins.php(75): ossn_view()
#8 /var/www/html/components/OssnWall/plugins/default/wall/pages/wall.php(27): ossn_plugin_view()
#9 /var/www/html/libraries/ossn.lib.views.php(27): include('...')
#10 /var/www/html/libraries/ossn.lib.views.php(50): ossn_include()
#11 /var/www/html/libraries/ossn.lib.plugins.php(75): ossn_view()
#12 /var/www/html/libraries/ossn.lib.initialize.php(119): ossn_plugin_view()
#13 /var/www/html/libraries/ossn.lib.page.php(79): ossn_user_pagehandler()
#14 /var/www/html/index.php(22): ossn_load_page()
#15 {main}
