### ISSUE TITLE
GoBlue Theme - notifications box cut off

### ISSUE THREAD

**Issue by queermeet-dev** [opensource-socialnetwork/opensource-socialnetwork#2387]
The notifications box in GoBlue Theme is cut of on smaller devices

In english it's just the "t" in "post", but in German it is more

![image](https://github.com/user-attachments/assets/334fcef4-3f87-4633-aa65-cb5d38387296)

**Comment by lianglee** [comment]
Disable Mark as read component and then show us results please

**Comment by queermeet-dev** [comment]
same as before


![image](https://github.com/user-attachments/assets/21a32af3-4300-4c50-b1ab-bf540b38bb9b)

**Comment by lianglee** [comment]
I will check now.

**Comment by githubertus** [comment]
Sorry, queermeet-dev
but with a Goblue issue report I would expect at least to see a screenshot of Goblue. Yours looks more like some sort of  GoDark, though. And what about that little home icon? Never seen that with Goblue.

Besides that: Please provide the device in use, the Os and the browser.

**Comment by queermeet-dev** [comment]
this is GoBlue, just with the darkmode component...

The little home icon is maybe a component I made myself so mobile users can go back to Newsfeed faster? Thought about that?


Happens with iPhone 15 WebApp, iPhone 15 and Safari, happens also on my windows PC when I activate the device toolbar in Google Chrome Dev Tools - happens on all smaller devices, in this case lower than 480px

**Comment by queermeet-dev** [comment]
Hey, any info on this?

**Comment by queermeet-dev** [comment]
I added:

```
.ossn-notifications-all .data {
    text-wrap: wrap;
	}
```
