### ISSUE TITLE
[B] Close Button (X) of System Messages Overlaps with Dropdown Menu

### ISSUE THREAD

**Issue by queermeet-dev** [opensource-socialnetwork/opensource-socialnetwork#2396]
When you for example editing a wall post and then you are opening the drop-down menu on the top right, the x of the "post successfully saved" message is inside the dropdown and is also clickable inside the dropdown

![image](https://github.com/user-attachments/assets/a8ac0713-bdba-4385-9e68-6f47dbc729e0)

**Comment by lianglee** [comment]
Seems z-index problem can be resolved i will check
