### ISSUE TITLE
OSSN cant recognize Apache.

### ISSUE THREAD

**Issue by celisej567** [opensource-socialnetwork/opensource-socialnetwork#2399]
I have installed Apache2 and enabled mod_rewrite, but ossn cant recognize them for some reason. 

![изображение](https://github.com/user-attachments/assets/cea70ff7-9844-48b7-aa8a-07a979a1fe5f)

I whould like to give something more useful then THIS but im not sure what exactly.

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/wiki/view/3994/how-to-install-ossn-on-ubuntu-1804-2104-2204-x64-using-command-line
