### ISSUE TITLE
New OSSNWall update sends wrong notifications

### ISSUE THREAD

**Issue by queermeet-dev** [opensource-socialnetwork/opensource-socialnetwork#2405]
Since the latest version of OSSNWall i get wrong notifications

I tried on fresh install

When someone comments my post, I get "someone liked"

![commen](https://github.com/user-attachments/assets/41128eeb-4d1b-46a7-a5b7-968bea6f4c67)
![noti](https://github.com/user-attachments/assets/8c2da6e0-ae64-4c29-86f2-d783b2f7388f)

**Comment by githubertus** [comment]
yeah, I think the latest changes of line #177 and #180 need to be reverted

**Comment by lianglee** [comment]
Thanks otherwise it will stay un noticed :)

**Comment by queermeet-dev** [comment]
I copied the whole OssnWall from Github to my server, now I get

```
[26-Oct-2024 14:30:43 UTC] [#1729953043|RD8832ABHRQ1T8V64S5QEGEUGT] ParseError: syntax error, unexpected end of file in /var/www/queermeet/htdocs/mrcrossii/DEVELOPER/components/OssnWall/ossn_com.php:598
Stack trace:
#0 /var/www/queermeet/htdocs/mrcrossii/DEVELOPER/libraries/ossn.lib.components.php(69): OssnComponents->loadComs()
#1 /var/www/queermeet/htdocs/mrcrossii/DEVELOPER/system/start.php(40): include_once('...')
#2 /var/www/queermeet/htdocs/mrcrossii/DEVELOPER/index.php(12): require_once('...')
#3 {main}
[26-Oct-2024 14:30:43 UTC] [#1729953043|RD8832ABHRQ1T8V64S5QEGEUGT] ParseError: syntax error, unexpected end of file in /var/www/queermeet/htdocs/mrcrossii/DEVELOPER/components/OssnWall/ossn_com.php:598
Stack trace:
#0 /var/www/queermeet/htdocs/mrcrossii/DEVELOPER/libraries/ossn.lib.components.php(69): OssnComponents->loadComs()
#1 /var/www/queermeet/htdocs/mrcrossii/DEVELOPER/system/start.php(40): include_once('...')
#2 /var/www/queermeet/htdocs/mrcrossii/DEVELOPER/index.php(12): require_once('...')
#3 {main}
```

**Comment by queermeet-dev** [comment]
Found it, there is an ; missing at the end

**Comment by queermeet-dev** [comment]
I copied the code from Github, but still have the problem with the wrong notifications

**Comment by queermeet-dev** [comment]
Any updates?

With the current code I still get the wrong notifications

**Comment by queermeet-dev** [comment]
The problem is not solved now, any updates????

**Comment by lianglee** [comment]
What do you mean not resolved did you actually tried the fix?

How did you tried to solve it?
