### ISSUE TITLE
site pages view broken with 2015-01-16 snapshot

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#244]
System: Windows7
Chrome: OKAY

Firefox 35.0 -> floated to the right
![sitepages-firefox](https://cloud.githubusercontent.com/assets/9904364/5778064/b630f0b6-9d98-11e4-9e97-cb9a409ce215.png)

IE 11.0.9600 -> floated to the right + toolbar issue
![site-pages-ie11](https://cloud.githubusercontent.com/assets/9904364/5778120/38dff8e0-9d99-11e4-8f31-d7b54cb3612d.png)

**Comment by lianglee** [comment]
fixed
