### ISSUE TITLE
new message bug in 2.0 dev

### ISSUE THREAD

**Issue by moneya** [opensource-socialnetwork/opensource-socialnetwork#267]
i found new bug when trying to send mesage in 2.0 dev
look the image below for details
i will explain as best as i can
when sending the message it doesn't get sent and the message area collapse
![bug1](https://cloud.githubusercontent.com/assets/7353773/5855363/5a42daa0-a1ec-11e4-94ed-99b393f83e9e.png)
![bug2](https://cloud.githubusercontent.com/assets/7353773/5855364/5a496ce4-a1ec-11e4-995b-cd8db414b84b.png)
![bug3](https://cloud.githubusercontent.com/assets/7353773/5855365/5bb891f4-a1ec-11e4-9722-0594501f7231.png)

@satish @lianglee

**Comment by lianglee** [comment]
The sidebar is not updated when message sent we are aware of this its actually not bug we didn't wrote any feature for that.

**Comment by moneya** [comment]
okay cool

**Comment by githubertus** [comment]
The sidebar problem is an old one and has been already reported by me (#110)
No sending at all is new to me. Doesn't happen with [2.0-dev 2015-01-20 20:30 GMT+1].
Will get the latest snapshot right now and verify if that makes a difference. Cu later.

**Comment by moneya** [comment]
@githubertus ok,nope taking a look at it and find a possible solution

**Comment by lianglee** [comment]
I have test it seems there is no issue, try it on fresh installation of ossn and if problem exist report it back.
Report with:
Ossn version
Operating  System,
Web browser

**Comment by moneya** [comment]
okay
