### ISSUE TITLE
ossn wall bug

### ISSUE THREAD

**Issue by moneya** [opensource-socialnetwork/opensource-socialnetwork#273]
text over lays each other
you will understand by looking at this image
![app](https://cloud.githubusercontent.com/assets/7353773/5887780/6aa80642-a398-11e4-981d-68ab265c92d2.png)

**Comment by lianglee** [comment]
please use readmore component by sathish to fix issue.

**Comment by moneya** [comment]
@lianglee  am using readmore by @sathish4fri satish already
