### ISSUE TITLE
#118 still unfixed in chat window

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#277]
Sender:
![chat_sender](https://cloud.githubusercontent.com/assets/9904364/5899539/c3384194-a55c-11e4-8fb0-a60c20827834.png)

Receiver:
![chat_receiver](https://cloud.githubusercontent.com/assets/9904364/5899547/db34ed56-a55c-11e4-8e91-8673001d9567.png)

 [2.0-dev 2015-01-24 18:00 GMT+1]

**Comment by lianglee** [comment]
i have to check why its still encoding chars

**Comment by AkincanD** [comment]
How can I solve this problem?

**Comment by lianglee** [comment]
@AkincanD  we are working on it , will be fixed tonight hopefully

**Comment by lianglee** [comment]
@githubertus 
Its strange its fine on my side i tried "wat ist das äääää" its displaying fine on both side.

Check in Message page if its showing fine or not.

Check messages in database ossn_messages if message is encoded or not. (in latest v2.0 it should not decode any thing)

**Comment by lianglee** [comment]
See: https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/2e80e7a7c3dde7cefd170e3c57e668dd7b4174c0#diff-d44db6d241727d1dff80503e3f317b1cR27

Also make sure you are on latest development version.

**Comment by githubertus** [comment]
updated to snapshot from today, still encoded db records
![messages](https://cloud.githubusercontent.com/assets/9904364/5907835/825bb610-a5a2-11e4-9b74-a910ec6bb1c3.png)

**Comment by lianglee** [comment]
Thanks for fix!
