### ISSUE TITLE
chat linefeed problem

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#278]
[2.0-dev 2015-01-24 18:00 GMT+1]
Problem with Windows7->Chrome and Debian->Chromium (Firefox and IE11 are okay)

![chat-linefeed](https://cloud.githubusercontent.com/assets/9904364/5900391/d39ff674-a568-11e4-8cd7-3efadc5510a1.png)

**Comment by lianglee** [comment]
Let me check

**Comment by lianglee** [comment]
can you confirm it again?

**Comment by githubertus** [comment]
Problem still there.
just verified on Ossn demo site with Chrome on Win 8.1:

![chrome-chat-prob](https://cloud.githubusercontent.com/assets/9904364/6426014/9f82702a-bf43-11e4-9765-bb73c59aa8a1.PNG)

**Comment by lianglee** [comment]
I think we need to trigger a function , that moves scroll down, when message receives.

**Comment by lianglee** [comment]
Its due to the user image loads later and Ossn.ChatScrollMove() triggered before image is fully loaded.

**Comment by lianglee** [comment]
Fixed
