### ISSUE TITLE
feature request: multilanguage themes

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#281]
Currently I'm missing what's already implemented in OssnComponents->loadComs():
a chance to put theme related strings into a 'locale' subdir of a theme package.

Thinking in longer terms it would make sense to move any theme related string from the core locale to theme theme locale, anyway. And keep only those strings in core locale which are really theme independant like error messages and mailer strings.

**Comment by lianglee** [comment]
i agree with you , themes ossn should also automatically register locale/language

**Comment by lianglee** [comment]
Fixed
