### ISSUE TITLE
Notification popup

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#283]
result in chrome
![notification_chr](https://cloud.githubusercontent.com/assets/5566418/5967525/2141edf4-a80e-11e4-9cc3-b33aa9ec2aa2.JPG)

in firefox
![notification_ff](https://cloud.githubusercontent.com/assets/5566418/5967530/2b8aa602-a80e-11e4-94c4-09dd2506668e.JPG)

**Comment by lianglee** [comment]
Make sure your cache is disabled

**Comment by githubertus** [comment]
Same problem here with snapshot from today

**Comment by TheGameHHH** [comment]
@lianglee cache is disabled in ossn. cache browser were cleaned before an update

**Comment by lianglee** [comment]
fixed
