### ISSUE TITLE
there is a little big problem

### ISSUE THREAD

**Issue by DmACKGL** [opensource-socialnetwork/opensource-socialnetwork#297]
the system makes many calls to the DB processors are an I5 100% with only 90 users, it would be possible to minimize this consumption? as the web becomes slow, almost inaccessible

**Comment by lianglee** [comment]
We have plan to minimize in v3.0 Are you on server? or local computer?

**Comment by lianglee** [comment]
Our community site have more than 500 users we are not facing any issue. But we have plan to fix some issues in v3.0

**Comment by djmastermack** [comment]
tengo un servidor, no obstante deberían reducir las consultas que se hacen hacia la base de datos

**Comment by lianglee** [comment]
@djmastermack  we have debugged our code and its seems Ossn is querying the database many times. This should not happen will fix in 3.0 release

**Comment by moneya** [comment]
@Lianglee  would 3.0 support 2.0 components... 
i mean backwards compatibility

**Comment by moneya** [comment]
@lianglee  would 3.0 support 2.0 components... 
i mean backwards compatibility

**Comment by moneya** [comment]
@lianglee would 3.0 support 2.0 components...i mean backwards compatibility

**Comment by lianglee** [comment]
Yes, you have to change manifest little bit

**Comment by moneya** [comment]
ok...cool

**Comment by lianglee** [comment]
Should check with latest ossn v3.0-development with cache enabled.
