### ISSUE TITLE
Profile menu css not aligned proper

### ISSUE THREAD

**Issue by sathish4fri** [opensource-socialnetwork/opensource-socialnetwork#300]
screen shot
![pro](https://cloud.githubusercontent.com/assets/6101473/6040560/41624522-ac99-11e4-8d8d-7ffbd3af4662.png)

**Comment by lianglee** [comment]
its fine on chrome

**Comment by sathish4fri** [comment]
Not good in firefox

**Comment by githubertus** [comment]
firefox on windows 7 is fine. what OS are you running, Sathish4fri?

**Comment by sathish4fri** [comment]
linux and windows 8

**Comment by lianglee** [comment]
merged manually, with 1px padding
