### ISSUE TITLE
page 2 in users list in adminpanel displayed wrongly

### ISSUE THREAD

**Issue by PaDo90** [opensource-socialnetwork/opensource-socialnetwork#307]
when i have activated the german language in basic settings, the users list page 2 have a display error. (administrator/users?offset=2)

Screenshot: http://i.imgur.com/ZMugYSN.png
Browser: Google Chrome
Resolution: 1920 x 1080

**Comment by lianglee** [comment]
Will debug it

**Comment by lianglee** [comment]
Its fixed
