### ISSUE TITLE
after friend request was displayed the wrong message

### ISSUE THREAD

**Issue by PaDo90** [opensource-socialnetwork/opensource-socialnetwork#313]
When i send a user a friend request it shows the wrong message.
It shows the message "You are now friends" but it must show "Your friend request was sent"!

Screenshot: http://i.imgur.com/ETDHxQl.png

**Comment by moneya** [comment]
ok Thanks for bug report.... 
it's an issue with the language string

**Comment by lianglee** [comment]
@githubertus i think we forgot to add this hard coded string to language file?

**Comment by githubertus** [comment]
Yep! Fix is on the way...

**Comment by lianglee** [comment]
fixed
