### ISSUE TITLE
groups in adminpanel

### ISSUE THREAD

**Issue by PaDo90** [opensource-socialnetwork/opensource-socialnetwork#314]
please give an option to list and moderate all groups in adminpanel

**Comment by lianglee** [comment]
You can moderate groups from group profile page.

You can delete posts.
Add/Remove Member

**Comment by PaDo90** [comment]
No i do not mean for users! i mean for admins in adminpanel... Than an admin i can't see all groups who created by random users...

**Comment by githubertus** [comment]
![grouplist-howto](https://cloud.githubusercontent.com/assets/9904364/6092458/16f7912c-aee0-11e4-817d-7cc41fa30349.png)

**Comment by PaDo90** [comment]
oh, wow ... thanks! :D but this is only for admins right?

**Comment by moneya** [comment]
@githubertus is that for admin only 
or member's can do that...

**Comment by moneya** [comment]
but listing all groups in the admin panel would be cool

**Comment by githubertus** [comment]
@moneya 
I'm a little alarmed reading your question. Postings don't work, you said. And now it seems: you don't even have a Search Box on top to try out. What Ossn version are you running, 0.1 ?

**Comment by moneya** [comment]
@githuberus  you miss read what i meant 
i am using 2.0 dev for now i would upgrade in two hours from now
there's  search box.. 
i was asking if that work's for admin only or site members 
for listing all group..

**Comment by moneya** [comment]
@githubertus  you miss read what i meant 
i am using 2.0 dev for now i would upgrade in two hours from now
there's  search box.. 
i was asking if that work's for admin only or site members 
for listing all group..

**Comment by moneya** [comment]
but it would be Cool to list that in the admin panel just like the user's

**Comment by lianglee** [comment]
Please post idea on community site as it become difficult for us to track serious bugs.
