### ISSUE TITLE
rename "repositionieren" in "Neu positionieren" (OssnPhotos -> ossn.de.php)

### ISSUE THREAD

**Issue by PaDo90** [opensource-socialnetwork/opensource-socialnetwork#319]
On "components\OssnPhotos\locale\ossn.de.php" please rename:
'reposition:cover' => 'repositionieren',

in:
    'reposition:cover' => 'Neu positionieren',

it would be a better german! :)

**Comment by lianglee** [comment]
@githubertus

**Comment by githubertus** [comment]
Agreed: "'Neu positionieren" is the better choice. :) 
Thank you for the hint, PaDo90.

Of course, all supplied language files can be customized to your community's demand. Feel free to change all German occurences of "Du" to "Sie" for example. Put exclamation marks at the end of system messages ... what you like ... it's up to you ....
But be careful with the ticks (') !!! Do your changes step by step and verify whether Ossn is still running. One tick missing or one tick too much may lead to unpredictable results.
Yo, dann viel Glück!

**Comment by PaDo90** [comment]
i know but i think it was better for the public version with a better transtalted text :)
i know how to translate :)

Danke für die schnelle Antwort :D gut zu wissen dass es auch deutsche in eurem Team gibt!

**Comment by lianglee** [comment]
changed
