### ISSUE TITLE
ossn wall issue

### ISSUE THREAD

**Issue by moneya** [opensource-socialnetwork/opensource-socialnetwork#320]
i downloaded the latest 2.0 dev version and found something wrong with ossn wall,
note: this is a fresh install.
when i make a post it, does not get shown in the newsfeed..
by post i mean status update.
OS: windows  browser: chrome date:6/feb/2015

**Comment by githubertus** [comment]
I'm currently running a snapshot from yesterday 19:00 GMT+1. (As far as I can see, only the latest confirm box stuff is not included.) And had no issues - except that Readmore is not really compatible with videos. But that's another story.
@moneya:
Anything in the error log? Is the posting stored in db?

**Comment by lianglee** [comment]
Try to disable OssnEmbed

**Comment by moneya** [comment]
nope nothing stored, 
@Lianglee doesn't work, still same issue 
i decided to use a previous ossnwall plugin and it works.. 
note the previous one has no administration settings... 
@ githubertus i downloaded this snapshot on 6/feb/2015

**Comment by sathish4fri** [comment]
video is not playing for me . you guys able to play it ? . we need to modify the object to iframe i think for me its not playing the video

**Comment by sathish4fri** [comment]
Sorry my bad flash player is corrupted in my browser and its working fine

**Comment by moneya** [comment]
@sathish4fri  lol,mine is working like charm

**Comment by githubertus** [comment]
Guys, do we have an issue, or do we have no issue?
I thought, we were talking about POSTINGS no more working at all!
Anyway, I'll do a clean install this afternoon and see what happens....
@moneya: 
Did you try both wall settings?
Did you try it as admin or regular user?

**Comment by lianglee** [comment]
" lol,mine is working like charm"
Its works also for us Both text post and url post.

Worked for both Normal user and Admin user, both wall settings. 

I am closing this issue please re-check otherwise you can let us know your team-viewer details, we can start a team-viewer session with you.

**Comment by githubertus** [comment]
Just finished my clean install.
Can confirm: NO ISSUES with wall.

![dev_download](https://cloud.githubusercontent.com/assets/9904364/6092490/a3d85f26-aee1-11e4-8d10-35d1ae7217ed.png)

**Comment by moneya** [comment]
from git

**Comment by githubertus** [comment]
And the archive was simply named "opensource-socialnetwork-master.zip" ?
And not something like "opensource-socialnetwork -cbe245a7a37a70442c9e7bbdeef87db577f38971.zip?

I'm just asking, because recently I got an archive like that. And it was incomplete!
I think, files like that are temporary ones, created while the archive is getting rebuilt.

**Comment by lianglee** [comment]
You must have Minimum Php 5.4 installed for Ossn 2.0

**Comment by lianglee** [comment]
fixed
