### ISSUE TITLE
wall bug? maybe

### ISSUE THREAD

**Issue by moneya** [opensource-socialnetwork/opensource-socialnetwork#331]
After upgrading to beta,i now understand the wall post issue.. 
when  i switch the settings of the wall to friend only,and  access the site, all my post disappeared... and new post doesn't get showed/updated .... note am using admin user....
when i go back to the wall settings and switch it to all site post  And access the site, they all showed up...and all New post are updated..... 
can someone try it and see..

version : 2.0 beta,  browser : chrome 
user:admin

**Comment by lianglee** [comment]
fixed

**Comment by moneya** [comment]
ok,cool
