### ISSUE TITLE
Different theme on Demo site?

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#335]
Don't know why the user list has drifted to the bottom at https://www.opensource-socialnetwork.org/demo/administrator/users?offset=1
This is not happening with latest beta code.

**Comment by sathish4fri** [comment]
because this
 <td>konyafm42konyafm42@hotmail.com</td> 
gets enlarged instead of comming down thats why . css problem . need to rewirte the css

**Comment by githubertus** [comment]
:+1:  Thanks for verifying, sathish4fri
fixed with #338 and #339

**Comment by sathish4fri** [comment]
cool.. thanks
