### ISSUE TITLE
Comments Text field should scale

### ISSUE THREAD

**Issue by MarcusMoeller** [opensource-socialnetwork/opensource-socialnetwork#340]
When I write a comment, I only got an one-line input box which does not do line-break nor scale.

It would be great to have a scale handle as well (like here on github), where you can dynamically resize the input box vertically.

**Comment by MarcusMoeller** [comment]
Same goes for chat. Per default, I would like to suggest at least extend to two input lines on line-break for chat (similar to facebook chat).

**Comment by lianglee** [comment]
ya i understand, we have to also make comments scale able

**Comment by lianglee** [comment]
Please post idea on community site as it become difficult for us to track serious bugs.
