### ISSUE TITLE
css in profile view

### ISSUE THREAD

**Issue by MarcusMoeller** [opensource-socialnetwork/opensource-socialnetwork#342]
![bildschirmfoto vom 2015-02-13 08 16 23](https://cloud.githubusercontent.com/assets/1267594/6183701/ac8eada2-b358-11e4-9a0a-35aa0f172ea7.png)
In profile view, the buttons in the bar where it says Chronik/Freunde/Fotos are higher than the bar itself. Just a few pixel, but it's noticeable.

**Comment by lianglee** [comment]
Are you using latest beta version?

**Comment by sathish4fri** [comment]
duplicate .. i already reported it

**Comment by MarcusMoeller** [comment]
Yes, latest beta

**Comment by lianglee** [comment]
@sathish4fri it already been fixed with 1px padding

**Comment by lianglee** [comment]
we should try it with german language

**Comment by MarcusMoeller** [comment]
Yes, I am using German interface language.

**Comment by MarcusMoeller** [comment]
![bildschirmfoto_2015-02-13_13-06-31](https://cloud.githubusercontent.com/assets/1267594/6186983/439e2ee8-b381-11e4-921a-f78ce8cff000.png)

1px could also help for the 'Send' / 'Abschicken' Button in full chat view.

**Comment by sathish4fri** [comment]
hmm we will rectify it
