### ISSUE TITLE
Logo should be clickable

### ISSUE THREAD

**Issue by MarcusMoeller** [opensource-socialnetwork/opensource-socialnetwork#343]
It would be great if the logo (logo_2.png) in default theme would be linked to the homepage, so one could click on it to get back to the main page.

**Comment by githubertus** [comment]
Anytime the "home" link is avaiblable. Do we really need another one?

**Comment by MarcusMoeller** [comment]
The home link is on the top right, which is from usability pov not perfect. I think it would be a benefit.

**Comment by PrashantRe** [comment]
@bishopgodsey thanks,It's working.

**Comment by sathish4fri** [comment]
:+1:

**Comment by lianglee** [comment]
fixed
