### ISSUE TITLE
favicon support

### ISSUE THREAD

**Issue by MarcusMoeller** [opensource-socialnetwork/opensource-socialnetwork#344]
It would be great if there could be favicon support within the themes, so that every theme directory could contain it's own favicon which is set when the theme is selected.

**Comment by githubertus** [comment]
To my opinion the favicon is representing the community and should be a unique identifier to the outer world. Regardless of theme you're using.

**Comment by MarcusMoeller** [comment]
I got you option. So should it be possible to set a system wide favicon? I have tried to simply place it in the ossn root, but it does not seem to be applied.

**Comment by githubertus** [comment]
![favicon](https://cloud.githubusercontent.com/assets/9904364/6201473/85768dac-b4ac-11e4-9d28-0632b2fdb199.png)
I'm getting this one when visiting your site with Firefox/Windows7
Since penguins are more used to seafood, you might try a fish instead?

**Comment by MarcusMoeller** [comment]
Yes, you are right. Placing it in the document root worked. Sorry for the noise.
