### ISSUE TITLE
option to edit posts that has already been written

### ISSUE THREAD

**Issue by MarcusMoeller** [opensource-socialnetwork/opensource-socialnetwork#345]
Right now, it's possible to delete existing posts/comment. It would also be great to have an option to edit them, afterwards.

**Comment by PrashantRe** [comment]
+

**Comment by gabrilll** [comment]
![edit](https://cloud.githubusercontent.com/assets/547964/6284115/b4ad2216-b8cb-11e4-908e-f432724e079b.jpg)

**Comment by dgbaker** [comment]
Just upgraded to 2.0b and no edit options available only delete post.

**Comment by lianglee** [comment]
Please post idea on community site as it become difficult for us to track serious bugs.

**Comment by lianglee** [comment]
We don't have any option to edit posts
