### ISSUE TITLE
search function does not find post

### ISSUE THREAD

**Issue by MarcusMoeller** [opensource-socialnetwork/opensource-socialnetwork#346]
Right now, it seems to be possible to search for persons and groups. It would be great if search could also be used to find posts/comments.

**Comment by sathish4fri** [comment]
we will look into it

**Comment by moneya** [comment]
@sathish4fri  i would suggest that should work on public post alone

**Comment by lianglee** [comment]
Please post idea on community site as it become difficult for us to track serious bugs.
