### ISSUE TITLE
links in ads

### ISSUE THREAD

**Issue by MarcusMoeller** [opensource-socialnetwork/opensource-socialnetwork#348]
I guess you already know it, but just to write it down: links in advertisements should also be clickable.

**Comment by moneya** [comment]
it's clickable

**Comment by moneya** [comment]
sorry i meant the text not URL

**Comment by MarcusMoeller** [comment]
Ah, got it. The title is clickable ;)

**Comment by lianglee** [comment]
Titles are clickable
