### ISSUE TITLE
version 2.0b are some problems with the video embed

### ISSUE THREAD

**Issue by ghost** [opensource-socialnetwork/opensource-socialnetwork#350]
i try to embed some video from youtube

**Comment by lianglee** [comment]
It should work, can you share screen shot?

**Comment by noinud** [comment]
I hide som information from  the screens shot

**Comment by githubertus** [comment]
Your hiding is working perfectly. Why don't you simply tell us the url of the youtube video? And which way you were trying to "embed" it? Did you make use of youtubes special embed code or the video url (which would be the correct way)?

**Comment by moneya** [comment]
@githubertus
i found posting the url as this does not embed the videos
www.youtube.com/watch?v=ZSs8cghZOTs

but using 
https://www.youtube.com/watch?v=ZSs8cghZOTs
embeds the video.
i don't think that is user friendly

**Comment by githubertus** [comment]
@moneya 
Even youtube redirects to https://www.youtube.com/ , when  I enter www.youtube.com in my browser.
And all I have to do is copy/paste this link to Ossn
I very much think this IS user friendly.

**Comment by moneya** [comment]
@ githubertus thanks... :D

**Comment by lianglee** [comment]
Its works for us
