### ISSUE TITLE
using ossn in xampp 

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#351]
it's not nice, if you using this social network for testing in xampp. you can't logged in anymore and if you want to install new you can't do it. I get this message "You have old PHP 5.6.3 You need PHP 5.4 or Higher". You have currently php 5.6.3 in xampp.

**Comment by githubertus** [comment]
See prerequisites at bottom of page https://github.com/opensource-socialnetwork/opensource-socialnetwork.
Simly get yourself xampp with PHP 5.5.19. (available for Windows, Linux and MacOS) from https://www.apachefriends.org/download.html

**Comment by TheGameHHH** [comment]
it's going again
