### ISSUE TITLE
can't open a photo

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#352]
I get this error, if I want to open a photo in the photo tab. (everything is new | other xampp version and ossn new installed)

exception 'OssnDatabaseException' with message 'Column 'guid' in where clause is ambiguous SELECT e.guid, e.time_created, e.time_updated, e.permission, e.active, e.owner_guid, emd.value FROM ossn_entities as e JOIN ossn_entities_metadata as emd ON e.guid=emd.guid WHERE(guid ='3') ; ' in C:\Serverci\Server\www\ossn\classes\OssnDatabase.php:76 Stack trace: #0 C:\Serverci\Server\www\ossn\classes\OssnDatabase.php(166): OssnDatabase->execute() #1 C:\Serverci\Server\www\ossn\classes\OssnEntities.php(122): OssnDatabase->select(Array) #2 C:\Serverci\Server\www\ossn\classes\OssnFile.php(264): OssnEntities->get_entity() #3 C:\Serverci\Server\www\ossn\components\OssnPhotos\classes\OssnPhotos.php(98): OssnFile->fetchFile() #4 C:\Serverci\Server\www\ossn\components\OssnPhotos\ossn_com.php(215): OssnPhotos->GetPhoto('3') #5 [internal function]: ossn_photos_page_handler(Array, 'photos') #6 C:\Serverci\Server\www\ossn\libraries\ossn.lib.page.php(60): call_user_func('ossn_photos_pag...', Array, 'photos') #7 C:\Serverci\Server\www\ossn\index.php(21): ossn_load_page('photos', 'user/view/3') #8 {main}

additional
you don't see on the timeline the albums "profile photos" and "profile covers"

**Comment by githubertus** [comment]
About 8 hours ago, a fix has been applied to solve your problem.
(See https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/9195f8794874b4189fcc24bbe80c4a136501027e)

You've decided not to run the regular Beta, but a development version.
That's okay, but in this case it's a good idea to check for available fixes _first_ in order to prevent reports on already outdated snapshots.
Development versions are subject to change any time.

**Comment by TheGameHHH** [comment]
few minutes ago I download ossn again, because the other one was downloaded in afternoon and at me it isn't fixed. i have still this issue and everything at my xampp and the ossn is completely new.

**Comment by githubertus** [comment]
Please verify, that line 120 of classes/OssnEntities.php. reads:
$params['wheres'] = array("e.guid ='{$this->entity_guid}'");

If so, you won't get an OssnDatabaseException with "WHERE(guid ='3')"
The fixed code executes a "WHERE(e.guid ='3')" instead.
Which is correct and wouldn't trigger a database exception like that anymore.

I just downloaded the latest snapshot again. The fix on line 120 is definitely included.
