### ISSUE TITLE
new postings on Wall

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#353]
In version 2.0b I can't write postings anymore. I get no message that something is wrong. It happend nothing on Home or Timeline.

**Comment by TheGameHHH** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/5566418/6205112/523a60d2-b563-11e4-9834-85d5ef738812.JPG)
the result after i tried to make a post in the evening

**Comment by lianglee** [comment]
Its due to settings issue we have to fix this, you ca fix this by going into your admin > OssnWall settings then save it

**Comment by TheGameHHH** [comment]
are you kidding me? I tried it in a virtual machine on my work. I installed Xampp and OSSN. At work I did it on localhost and at home I created a domain for OSSN. I tried it as home with "All site posts" and "Friends posts only". No post in the wall is seeing in both mode.

**Comment by PrashantRe** [comment]
Hello lianglee,  thegamehhh  is telling the truth.
If someone download latest version of opensocial from here>>https://github.com/opensource-socialnetwork/opensource-socialnetwork and install it.User will get this error.I am also getting the same error as mentioned above.

**Comment by lianglee** [comment]
Will fix it soon

**Comment by sathish4fri** [comment]
yes the problem is exit we will rectify it .. @lianglee  problem is due  to access and poster_guid is not  
passing with 2.0b and it get passed on 2.0 dev version ...

**Comment by lianglee** [comment]
fixed
