### ISSUE TITLE
Wrong translation in german

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#357]
You like a profile photo then you will get following notification. " hat Dein Profil-Foto kommentiert". Otherwise if you like a post then you get " gefällt Dein Kommentar" as notification. Better choice is " gefällt dein Profilbild". I use OSSN 2.0b.

**Comment by lianglee** [comment]
@TheGameHHH  if you think its wrong you can send us a pull request with fix here on github

@githubertus  can you check it?

**Comment by TheGameHHH** [comment]
@lianglee i don't know how do i this

**Comment by TheGameHHH** [comment]
I have already discovered the error in the english version for the notification. In a like will something write from comment. 

en
'ossn:notifications:like:entity:file:profile:photo' => "%s commented the profile photo",
should be
'ossn:notifications:like:entity:file:profile:photo' => "%s liked the profile photo",

de
'ossn:notifications:like:entity:file:profile:photo' => "%s gefällt Dein Profil-Foto",

**Comment by lianglee** [comment]
Fixed
