### ISSUE TITLE
[Resolved]Ossnreadmore 

### ISSUE THREAD

**Issue by PrashantRe** [opensource-socialnetwork/opensource-socialnetwork#360]
Hello  sathish
Ossnreadmore is not working in version v2.0b 
https://github.com/sathish4fri/Readmore

**Comment by PrashantRe** [comment]
Resolved

**Comment by sathish4fri** [comment]
:+1:

**Comment by lianglee** [comment]
Please post this issue on component repository its not core component

**Comment by githubertus** [comment]
@PrashantRe You've resolved a problem. Fine. What about to tell the others WHICH WAY you did it?

**Comment by sathish4fri** [comment]
it will work in 2.0b itself
