### ISSUE TITLE
comment bug

### ISSUE THREAD

**Issue by PrashantRe** [opensource-socialnetwork/opensource-socialnetwork#373]
@lianglee  After comment no.6,if I wrote comment no.7 and refresh newsfeed,comment no.7 disappeared. I think we need to hide previous comments,not the latest one.

**Comment by sathish4fri** [comment]
we will check with that .

**Comment by lianglee** [comment]
This already has been fixed in our latest development version.

**Comment by lianglee** [comment]
Please wait for new release
