### ISSUE TITLE
Delete Post

### ISSUE THREAD

**Issue by PrashantRe** [opensource-socialnetwork/opensource-socialnetwork#374]
@lianglee  Users are unable to delete there friend's post appeared on  newsfeed.Only admin able to do this.Need to provide same ablilty to users to delete or hide others post from his/her own timeline.

**Comment by sathish4fri** [comment]
they can't delete the friend's post instead they can hide .

**Comment by PrashantRe** [comment]
But no option found on newsfeed to hide other user's post.

**Comment by sathish4fri** [comment]
i didnt say we have created it . we will create it in next release

**Comment by lianglee** [comment]
they can't delete friends post, simply they can unfriend that user

**Comment by lianglee** [comment]
fixed
