### ISSUE TITLE
Updated messages page and chat box

### ISSUE THREAD

**Issue by gabrilll** [opensource-socialnetwork/opensource-socialnetwork#383]
When sending messages
 to the page it is not updated with the chat box, requiring close the chat box and open it again.

![chat2](https://cloud.githubusercontent.com/assets/547964/6284356/f1adac56-b8cd-11e4-9b31-e0f912066f52.jpg)

**Comment by githubertus** [comment]
This has been addressed with #110 already. Please, take yourself a little time and step through open issues first before opening a "new" one.
