### ISSUE TITLE
User Relationships (romantic and family) module

### ISSUE THREAD

**Issue by illuminati8614** [opensource-socialnetwork/opensource-socialnetwork#388]
Let me know if this feature request can be done :) 

eg. of family options

Mother
Father
Daughter
Son
Sister
Brother
Auntie
Uncle
Niece
Nephew
Cousin (female)
Cousin (male)
Grandmother
Grandfather
Granddaughter
Grandson
Stepsister
Stepbrother
Stepmother
Stepfather
Stepdaughter
Stepson
Sister-in-law
Brother-in-law
Mother-in-law
Father-in-law
Daughter-in-law
Son-in-law
Sibling (gender neutral)
Parent (gender neutral)
Child (gender neutral)
Sibling of Parent (gender neutral)
Child of Sibling (gender neutral)
Cousin (gender neutral)
Grandparent (gender neutral)
Grandchild (gender neutral)
Step-sibling (gender neutral)
Step-parent (gender neutral)
Stepchild (gender neutral)
Sibling-in-law (gender neutral)
Parent-in-law (gender neutral)
Child-in-law (gender neutral)

eg. of romantic options

Single
In a relationship
Engaged
Married
It's Complicated
In an open relationship
Widowed
Separated
Divorced
In a civil union
In a domestic partnership

(if member is a friend then allow request option to be confirmed like how facebook works with autosuggest)

**Comment by PaDo90** [comment]
would be great! ... :)

**Comment by lianglee** [comment]
I think we can do this by relationships model or with objects

**Comment by lianglee** [comment]
Please post idea on community site as it become difficult for us to track serious bugs.
