### ISSUE TITLE
doesn't keep users logged in

### ISSUE THREAD

**Issue by leroymcqy** [opensource-socialnetwork/opensource-socialnetwork#389]
Everytime i log on and go to a different page i am logged out. it doesnt stayed logged on. best if cookies were used instead of sessions as sessions sometimes has issues

**Comment by lianglee** [comment]
Its seems your server is not storing sessions correctly, make sure you disk is not full

**Comment by leroymcqy** [comment]
it was on a hosted site premium it works fine with my own custom site and its not my own cause when i did that it was a fresh install

**Comment by leroymcqy** [comment]
Array
(
    [OSSN_USER] => 
)

seems like your script isn't doing its job.

i can confirm its not my site nor my hosting site. its the script btw i am using the stable 1.8 version.

its a joke learn to code.

i see why you dont want to fix cause you don't even know why its not working. 

welcome to check it out yourself.

http://www.gamingnations.tk/ses.php this is the session print out.

http://www.gamingnations.tk/ here is my site

**Comment by leroymcqy** [comment]
oh well its not worth my time i am glad its opensource. means i didn't waste money on junk
