### ISSUE TITLE
doesn't keep users logged in

### ISSUE THREAD

**Issue by leroymcqy** [opensource-socialnetwork/opensource-socialnetwork#393]
Everytime i log on and go to a different page i am logged out. it doesnt stayed logged on. best if cookies were used instead of sessions as sessions sometimes has issues.

its not my host nor my settings. 

its the files. it doesnt even set up sessions. 

i done print_r($_SESSIONS); i got nothing by phpsid nothing for the script

**Comment by lianglee** [comment]
@leroymcqy did you added lined called: <?php require_once('system/start.php'): ?> on the top of your ses.php file?

**Comment by leroymcqy** [comment]
you don't need that to get all sessions.

print_r prints all variables its the same as var_dump any programmer knows that. 

with session_start(); it gets all sessions. 

and i did it with that:
before login:
Array
(
    [OSSN_USER] => 
)
after login:
Array
(
    [OSSN_USER] => 
)

same again. after login.

**Comment by leroymcqy** [comment]
did someone just sign up by : Arsalan Shah

**Comment by leroymcqy** [comment]
@lianglee 

its not working at all. i have tried it on 3 hosts one is hostgator godaddy and x10. 

i have even tried on localhost nothing working. 

i get details when i log on my own forum with mybb or smf. x10 i only have this script

**Comment by lianglee** [comment]
Send us your cpanel details on http://www.informatikon.com/contact/support
I can see that sessions destroyed automatically in your website.

**Comment by leroymcqy** [comment]
i ain't gonna worry about it. i was mostly looking for something quicker then my site. i was kinda hoping tho to got it working.

**Comment by lianglee** [comment]
Try 2.0b version

**Comment by sathish4fri** [comment]
its working for us perfectly . if u want us to host it in godaddy . i can host and show to you .

**Comment by githubertus** [comment]
Just to make sure we're not talking about different things:
- I start my Firefox browser on Windows7
- I enter the url of my Ossn site
- I log in to my site and I'm redirected to 'http://mysite.com/home'
- in the same browser tab I enter a different url like 'http://google.com'
- using the 'browser back' button I'm navigating back to http://mysite.com/home
And I'm still logged in.
But you're logged off, getting a 404 error page?
So please let us know your OS and browser (brand and version)

**Comment by leroymcqy** [comment]
firefox, w7x32/x64. 

it gives me a 403 in admin 404 in some parts of the main site.

as i said i aint gonna worry about it. 

i just went ahead and uploaded my own site back onto it.

**Comment by lianglee** [comment]
"as i said i aint gonna worry about it." ok good luck
