### ISSUE TITLE
component installer is not working

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#394]
component installer is not working on  packages downloaded from community

**Comment by leroymcqy** [comment]
and i wonder why? 



Array
(
[OSSN_USER] =>
)

seems like your script isn't doing its job.

i can confirm its not my site nor my hosting site. its the script btw i am using the stable 1.8 version.

its a joke learn to code.

i see why you dont want to fix cause you don't even know why its not working.

welcome to check it out yourself.

http://www.gamingnations.tk/ses.php this is the session print out.

http://www.gamingnations.tk/ here is my site


sessions don't work properly. more likely missing the session_start() function.

i get no errors in error log file.

**Comment by lianglee** [comment]
@leroymcqy i think you posted on wrong topic.

component installer is not working #394 fixed

**Comment by lianglee** [comment]
@leroymcqy did you added lined called: <?php require_once('system/start.php'): ?> in your ses.php file?
