### ISSUE TITLE
sql injection

### ISSUE THREAD

**Issue by davidkevork** [opensource-socialnetwork/opensource-socialnetwork#395]
there is sql injection bug in messaging system when you just enter " ' " you will see the error
this is what showed on the official site

exception 'OssnDatabaseException' with message 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1424790859', '0')' at line 1 INSERT INTO ossn_messages (`message_from`, `message_to`, `message`, `time`, `viewed`) VALUES ('1', '36', ''', '1424790859', '0'); ' in /home/syed/public_html/opensource-socialnetwork.org/demo/classes/OssnDatabase.php:76 Stack trace: #0 /home/syed/public_html/opensource-socialnetwork.org/demo/classes/OssnDatabase.php(44): OssnDatabase->execute() #1 /home/syed/public_html/opensource-socialnetwork.org/demo/components/OssnMessages/classes/OssnMessages.php(43): OssnDatabase->insert(Array) #2 /home/syed/public_html/opensource-socialnetwork.org/demo/components/OssnMessages/actions/message/send.php(14): OssnMessages->send('1', '36', ''') #3 /home/syed/public_html/opensource-socialnetwork.org/demo/libraries/ossn.lib.actions.php(51): include_once('/home/syed/publ...') #4 /home/syed/public_html/opensource-socialnetwork.org/demo/system/handlers/actions.php(12): ossn_action('message/send') #5 {main}

**Comment by lianglee** [comment]
You are using 2.0b ?

**Comment by lianglee** [comment]
This has been fixed in #332

**Comment by davidkevork** [comment]
i tried this on the demo wesite

**Comment by lianglee** [comment]
Make sure your components/OssnChat/classes/OssnChat.php file line 171 is:
$message = ossn_input_escape($message, false);
