### ISSUE TITLE
UNABLE TO INSTALL OPEN SOURCE SOCIAL NETWORK

### ISSUE THREAD

**Issue by RSUDHAKARREDDI** [opensource-socialnetwork/opensource-socialnetwork#396]
I AM TRYING TO INSTALL OPEN SOURCE SOCIAL NETWORK SCRIPT BUT I AM GETTING FOLLOWING ERROR(You have old PHP 5.6.6 You need PHP 5.3 or Higher). I THINK IT SEEMS VALIDATION ERROR IT EXPECTING 5.3 HIGHER BUT I AM USING 5.6.x.

**Comment by lianglee** [comment]
We have fixed this error in new beta , you can try to download from here, Ossn didn't work on php 5.6 

Try to download 1.8  i am not sure if it works.

2.0b is under development and is not final release.

**Comment by RSUDHAKARREDDI** [comment]
Yes. might be it is beta version. it is completely for testing purpose. we are unable do cross from 1st step validation how can user test. we are fulfilling basic requirements even we couldn't gohead to next step once it is fix can you update us.

**Comment by RSUDHAKARREDDI** [comment]
I 1.8 version but could find some of features not working for all browsers. and chat module is not working i logged from 3 diffrent users but its showing no one is online. let me know what do i want to do  go with version 2 even beta . 
![explorer](https://cloud.githubusercontent.com/assets/9945249/6362924/e65026c0-bcb7-11e4-9e81-d0354d172fff.png)
![crome_onlineusers](https://cloud.githubusercontent.com/assets/9945249/6362927/ed3c20f6-bcb7-11e4-95e4-2456d018cd50.png)
![firefox](https://cloud.githubusercontent.com/assets/9945249/6362931/f1d3ba70-bcb7-11e4-94d6-8c49f7c41c2d.png)
