### ISSUE TITLE
Registration not possible

### ISSUE THREAD

**Issue by Luzifa** [opensource-socialnetwork/opensource-socialnetwork#399]
To whom it may concern:

I registrate with opensource social network community
I don't get a verification mail
I try to login, nevertheless,
and can't (of course...)

Second try to registrate but
system tells my that my account already exists

Hu?

Please... help... if there is anybody out there. :-)

**Comment by lianglee** [comment]
Please create a support request on www.informatikon.com/contact/support

Provide your email address that you used on community site.

**Comment by Luzifa** [comment]
HI Arsalan,
thanks for your fast reply.
I already wrote a mail to the contact account of Informatikon. But i'm more than ready to give it a new try, wait...
Cheers,Inge

Date: Thu, 26 Feb 2015 04:01:12 -0800

**Comment by lianglee** [comment]
We have validated your account

**Comment by Luzifa** [comment]
Thank you!Cheers,Luzi

Date: Thu, 26 Feb 2015 04:15:39 -0800
