### ISSUE TITLE
posting image on the wall

### ISSUE THREAD

**Issue by amitsang2000** [opensource-socialnetwork/opensource-socialnetwork#400]
When posting an image from(local system) the desktop on the wall , its throwing the following error:
"Cannot create post"

i m using the latest 2.0 beta version [image attached]
![error](https://cloud.githubusercontent.com/assets/4608036/6419168/fb909918-bee0-11e4-8d23-fbb261120f31.png)

**Comment by lianglee** [comment]
You have to write some text i think

**Comment by amitsang2000** [comment]
Yes lianlee, you are right.  After writing text ,its working.

ISSUE-1: the links for images is not getting converted into image on the wall. Its displaying as link.

ISSUE-2:
One more problem is there.
REGISTRATION PROBLEM
Is there any character length limitation for user name?
Any character limitation for username ?

**Comment by lianglee** [comment]
Username must be greater than 4 characters

Images links are not automatically converted to links because we don't have feature for this.
