### ISSUE TITLE
Login and Register issue.

### ISSUE THREAD

**Issue by RawliBeast** [opensource-socialnetwork/opensource-socialnetwork#401]
When ever I try to log-in a message pops up saying "The action you requested is invalid."
and whenever I try to register after I get a pop up saying "Something went wrong! Reload this page and try again."

Pictures
1: http://oi60.tinypic.com/28wpkki.jpg
2: http://oi62.tinypic.com/wmduyx.jpg

I'll give you the website if you need it, Thanks!

**Comment by lianglee** [comment]
It seems you have upgrade your site to 2.x release. Make sure you have latest version of themes

**Comment by RawliBeast** [comment]
Its all upgraded.... and can you explain to me what the themes are, kind of new to the developers scene. :) I hope it doesn't inconvenience you. Thanks.

**Comment by lianglee** [comment]
Try to remove themes folder/directory from your site and upload new themes folder/directory from latest Ossn v2.1

**Comment by RawliBeast** [comment]
Thank You! I'll try it now.

**Comment by RawliBeast** [comment]
I'm using v2.1 already so can I just use v2.0's themes?

**Comment by RawliBeast** [comment]
and sorry if it seems like I'm asking a lot of questions, that will be the last question, and thank you.

**Comment by lianglee** [comment]
Are you using fresh installation of v2.1? Send us your cpanel details on the url;www.informatikon.com/contact/support

**Comment by RawliBeast** [comment]
Yes. :) and will do, I'm doing it right from the zip file right into /public_html/ at https://www.x10hosting.com/

**Comment by RawliBeast** [comment]
And by cpanel details, do you mean login information?

**Comment by RawliBeast** [comment]
and sorry once again for so many questions, just want to get this working. :) I'm happy to provide anything you need.

**Comment by RawliBeast** [comment]
Here's my website: http://rawlibeast.x10host.com/

**Comment by RawliBeast** [comment]
Sent.

**Comment by amitsang2000** [comment]
![image](https://cloud.githubusercontent.com/assets/4608036/6432047/f17e8270-c069-11e4-9e79-c7b4a15db0f7.png)


Users cannot register.
They are getting the above error.

**Comment by RawliBeast** [comment]
...weird... o.o... not showing that on my end.

**Comment by RawliBeast** [comment]
Does anyone have an idea what it could be... ;-;

**Comment by lianglee** [comment]
I have install latest Ossn (https://www.opensource-socialnetwork.org/downloads/ossn-v2.1-1425130850.zip) And its working fine for me.

**Comment by RawliBeast** [comment]
what host do you use....?

**Comment by amitsang2000** [comment]
LAMP PHP 5.X.X , CentOS

**Comment by lianglee** [comment]
worksforme now
