### ISSUE TITLE
 View all comments

### ISSUE THREAD

**Issue by PrashantRe** [opensource-socialnetwork/opensource-socialnetwork#405]
Hello Friends,
                    View all comments option is not working on profile picture.Another issue which is related to comments under post.Older comments are showing and newer comments are hidden.
For eg. If user made 12 comments under post,comment number 1 to 6 is showing under post,but comment number 7 to 12 disappeared.I think need to show newer comments ,not the older one under post.

**Comment by lianglee** [comment]
We had fixed this issue, i will debug it again.

**Comment by lianglee** [comment]
worksforme
