### ISSUE TITLE
Possible error /themes/default/style/default.php

### ISSUE THREAD

**Issue by UWXAdmin** [opensource-socialnetwork/opensource-socialnetwork#406]
Line 1085 reads:
.ossn-notifications-box  .firends {

Should this read(?):
.ossn-notifications-box  .friends {

**Comment by githubertus** [comment]
Typo yes - but error? As long as a misspelled string is consequently used throughout the code (see components/OssnNotifications/js/OssnNotification.php), this is doing no harm. :)

**Comment by UWXAdmin** [comment]
Agreed. But as a programmer, if it was not what was intended, human error, lol. I only discovered the typo when attempting to debug the missing notifications area icons without "new" notifications (using default theme).

**Comment by lianglee** [comment]
Thanks for report.
