### ISSUE TITLE
Post text not wrapping

### ISSUE THREAD

**Issue by UWXAdmin** [opensource-socialnetwork/opensource-socialnetwork#407]
Post text is not "wrapping", thus leaving words split across two lines as unreadable correctly.

**Comment by UWXAdmin** [comment]
You may temporarely disable the component until an update is available or remove the line "word-break: break-all;" from Readmore's css yourself.

**Comment by sathish4fri** [comment]
cleared thanks for the suggestion

**Comment by UWXAdmin** [comment]
Found temporary solution on community just after posting issue.
