### ISSUE TITLE
Request: Group chats

### ISSUE THREAD

**Issue by leonbollerup** [opensource-socialnetwork/opensource-socialnetwork#408]
Hi,

One feature that would be killer is the ability to have group chats.

**Comment by moneya** [comment]
please make your request in the community,git is for reporting bugs,providing fix

**Comment by moneya** [comment]
@lianglee  i think this should be closed cause it is a feature request.

**Comment by lianglee** [comment]
@leonbollerup, you are right, it is not hard to create a group chat,  please create a request on our community site.

**Comment by lianglee** [comment]
@leonbollerup , please create  a request on community site, its a nice idea to create a group chat.
