### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by leonbollerup** [opensource-socialnetwork/opensource-socialnetwork#409]
Hi,

I'v been doing some testing and can't really see that notfications works.. or maybe i missunderstand the way its supose to work.

Any clarification on it ?

**Comment by moneya** [comment]
kindly explain more about your issue.
does the notification work? yes for me.

**Comment by lianglee** [comment]
Notifications work if someone post comment on your post, photos, cover or likes your post, photo.
Can you tell us your website?
