### ISSUE TITLE
how can i creat my own components

### ISSUE THREAD

**Issue by wildshark** [opensource-socialnetwork/opensource-socialnetwork#412]
I have been try to come up with a components. which I do know how to go about it for youtub video please help me out

**Comment by sathish4fri** [comment]
Learn from hello world component . what type of Component your trying to do ? Please post this on community so that we can help ..

**Comment by moneya** [comment]
this question is to be directed at the community site,
@lianglee  i think this should be close?.

**Comment by lianglee** [comment]
Yes @moneya  you are right,
