### ISSUE TITLE
Community Site Not Allowing Registration

### ISSUE THREAD

**Issue by stiadmin** [opensource-socialnetwork/opensource-socialnetwork#413]
I've registered on the community site a few times over the last 2 days. It says it sent out the email but it never comes. I tried two different email addresses, nothing in either inbox.

**Comment by lianglee** [comment]
Can you please send us your email to your support team? they will validated your account manually:
http://opensource-socialnetwork.org/contact

**Comment by sathish4fri** [comment]
is this problem solved . if solved means ? close the issue

**Comment by lianglee** [comment]
Let us know on our contact page.
