### ISSUE TITLE
OssnAds does not properly track clicks

### ISSUE THREAD

**Issue by stiadmin** [opensource-socialnetwork/opensource-socialnetwork#414]
The OssnAds Component shows 32 clicks for all Ads, even if they have never been clicked, or have had multiple clicks.

**Comment by lianglee** [comment]
We don't have any feature that shows clicks

**Comment by stiadmin** [comment]
![clicks](https://cloud.githubusercontent.com/assets/6886458/6941209/c065b75e-d84b-11e4-859b-08f0dce831a5.png)

**Comment by lianglee** [comment]
@stiadmin i just saw code, there is no feature but '32' is placed as static number for all ads, its for reminder for developers to work on this feature.

I marked this ticket as bug.

**Comment by moneya** [comment]
@lianglee this should be mark as a enhancement not bug atm

**Comment by lianglee** [comment]
@moneya  yes i updated my comment.

**Comment by moneya** [comment]
ok cool
