### ISSUE TITLE
Unwanted refresh in message window

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#416]
OSSN 2.3 on Windows 8.1 both Firefox and Chrome

Pointing the browser to a url like
http://myossn.de/messages/message/Someone
either ossnchat/boot/ossn.boot.chat.js or messages/getnew/Someone
is continuously forcing the message window to scroll down back to the bottom.
Thus, it's nearly impossible to scroll up a longer correspondence in order to read what you've written before

**Comment by lianglee** [comment]
i agree, we have to only scroll if there is new message, this also happens in OssnChat i think?

**Comment by githubertus** [comment]
Can't tell. 5 minutes ago I became aware of this problem for the first time while trying to read a message which is larger than the message window.

**Comment by lianglee** [comment]
If you remove following code, it will be fine:

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/master/components/OssnMessages/pages/messages.php#L70

**Comment by githubertus** [comment]
Thanks a lot!

**Comment by moneya** [comment]
@lianglee this is fixed i guess

**Comment by lianglee** [comment]
@moneya , no we have to fix this, we have to only move scroll to bottom if there is new message

**Comment by lianglee** [comment]
Fixed
