### ISSUE TITLE
Starting the installation problem

### ISSUE THREAD

**Issue by skyphil** [opensource-socialnetwork/opensource-socialnetwork#417]
When I want to install the program, I received this message: "You have an old version of PHP 5.6.7 You need PHP 5.4 or PHP 5.5" ... Is the version 5.6.7 not a better version ??? and newer ???
How can I continue the installation ?

**Comment by TheGameHHH** [comment]
if you use xampp then change the version please. i had the same issue with the guys because it is not understandable.

**Comment by lianglee** [comment]
If i remember someone complaint us about php 5.6 that there are alot of errors,  appearing in php 5.6, so i disabled instillation on 5.6.

To Install on php 5.6 go to installation/classes/OssnInstall.php
Find:
    public static function isPhp() {
		$phpversion = substr(PHP_VERSION, 0, 6);
        if ($phpversion >= 5.4 && $phpversion < 5.6) {
            return true;
        }
        return false;
    }

Change it to 

    public static function isPhp() {
            return true;
    }

And run installer again,

**Comment by skyphil** [comment]
Thx for the quick and super answers ... :-)
Have a nice day.
