### ISSUE TITLE
Searched->Found groups pagination bug

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#418]
&type=groups 
is missing in pagenumber links

**Comment by lianglee** [comment]
its fixed i think, https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnGroups/ossn_com.php#L139-L141

**Comment by githubertus** [comment]
bug still present in 3.7, please reopen

**Comment by lianglee** [comment]
Fixed, try again
