### ISSUE TITLE
username already exist

### ISSUE THREAD

**Issue by snitch567** [opensource-socialnetwork/opensource-socialnetwork#419]
the username is not takeing i checked but it wont let me add any members cause it keeps coming up that the username is already takeing :(

**Comment by sathish4fri** [comment]
The name which you choose already taken , try some other name and added it .

**Comment by snitch567** [comment]
but its not takeing on my site how can it be takeing if its not even in use ?

**Comment by sathish4fri** [comment]
what name you used ,can u say it clearly

**Comment by lianglee** [comment]
Let us know your website, also which version of ossn are you using?

**Comment by wildshark** [comment]
I registered on your community but I can login  yet  
 
Date: Thu, 9 Apr 2015 04:43:45 -0700
