### ISSUE TITLE
Component installer problems with certain zip - archives

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#420]
The listing of Moneya's original file gives:
Archive:  chatroom-1-0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2015-04-13 09:18   chatroom/images/
      725  2015-04-13 09:06   chatroom/images/chat.png
      154  2015-04-13 09:06   chatroom/index.php
      685  2015-04-13 09:06   chatroom/ossn_com.php
      410  2015-04-13 09:06   chatroom/ossn_com.xml
       65  2015-04-13 09:06   chatroom/README.md
---------                     -------
     2039                     6 files

The listing of my re-zipped archive gives:
Archive:  cr.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2015-04-13 17:03   chatroom/
        0  2015-04-13 17:03   chatroom/images/
      725  2015-04-13 09:06   chatroom/images/chat.png
      154  2015-04-13 09:06   chatroom/index.php
      685  2015-04-13 09:06   chatroom/ossn_com.php
      410  2015-04-13 09:06   chatroom/ossn_com.xml
       65  2015-04-13 09:06   chatroom/README.md
---------                     -------
     2039                     7 files

Problem:
zipArchive seems to be unable to create the necessary root folder itself if it is not part of the archive. 

So either OSSN component creators have to be informed to make sure it is included, or OSSN's upload function needs more intelligence to traverse the archive first and create missing directories if necessary.

**Comment by moneya** [comment]
@githubertus i would rather go with the other 
OSSN's upload function needs more intelligence to traverse the archive first and create missing directories if necessary.

**Comment by lianglee** [comment]
Reference: https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/master/classes/OssnComponents.php#L82

Ossn component installer first check the root directory at 0 index, 

See: http://stackoverflow.com/questions/17908999/extract-7z-archive-on-linux-web-hosting

Well it should be fixed in Ossn 3.0

**Comment by moneya** [comment]
@lianglee cool
:100:  :+1:

**Comment by lianglee** [comment]
Fixed
