### ISSUE TITLE
installation/classes/OssnInstall.php - v3.0-dev

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#424]
Hi,

I've try to install new 3.0dev.
On file installation/classes/OssnInstall.php
At the end of line 225 it should be:
'sql/opensource-socialnetwork.sql'
at the place of:
'sql/Open Source Social Network.sql'

As the sql file in the sql directory.

Eric

**Comment by lianglee** [comment]
Ossn v3.0 is not for production sites, its under development, thinks for bug report!

**Comment by ctlui** [comment]
Hi,
I know than it's under dev and test it on a computer dedicated to test on local network.
It was a bug for me as the install can't work with the error.

Thanks for correction.

Eric

**Comment by sathish4fri** [comment]
thanks for the bug report @ctlui  . you can test and report bug ...
