### ISSUE TITLE
Ossn 3.0 components coding standard

### ISSUE THREAD

**Issue by moneya** [opensource-socialnetwork/opensource-socialnetwork#426]
i would like to know if there's any changes to 3.0 components coding standard or should we use our old 2.x coding convention?

**Comment by lianglee** [comment]
First of all version 3.0 is under development, 

Yes there is some changes in 3.0 component files structure. Once v3.0 release, i'll create a doc about how to convert 1.x component for 3.x

It will be easy , just moving files into new directories.

**Comment by moneya** [comment]
ok, may i ask if you are adopting mvc coding standard?

**Comment by lianglee** [comment]
Yes we have similar coding standards, but i just say, do what every you want, why follow someone else standards?
