### ISSUE TITLE
OssnAds doesn't display ad titles properly on user profiles

### ISSUE THREAD

**Issue by huckleberrypie** [opensource-socialnetwork/opensource-socialnetwork#428]
Title says all. It looks 'swell whenever I visit the news feed, but not on my user profile or someone else's:
http://imgur.com/a/wXQlV#0

It ain't that of a critical issue, but it still is kind of a show-stopper to me.

**Comment by sathish4fri** [comment]
we will check with this

**Comment by huckleberrypie** [comment]
Sure thing dude, I'm looking forward to it. ;)

**Comment by lianglee** [comment]
Make sure you are not using Ad Blocker, its working fine without ad blocker.
