### ISSUE TITLE
Visiting restricted pages as guest leads to 404 page

### ISSUE THREAD

**Issue by huckleberrypie** [opensource-socialnetwork/opensource-socialnetwork#429]
Title says all. On most sites you'll be prompted to log in upon visiting a page restricted to registered users, but in this case we end up with a rather ambiguous 404 error message.

**Comment by ctlui** [comment]
Yes I saw also this problem, as I include piwik stats on some pages, I saw than some members bookmarks http;//domain.tld/home and they get a 404 when they come back not registred.

**Comment by lianglee** [comment]
Someone of pages are for loggedin users only, non-loggedin users get a 404

**Comment by huckleberrypie** [comment]
Then again if you ask me, the software should've prompted users to log in in order to continue rather than be subjected to a 404, as that could potentially mislead them into believing the page doesn't exist.

**Comment by lianglee** [comment]
You can fix it , you have to remove the code that redirect users
