### ISSUE TITLE
Feature request: Implement scale/crop for images

### ISSUE THREAD

**Issue by huckleberrypie** [opensource-socialnetwork/opensource-socialnetwork#430]
Thought of asking you guys about this as 'tis definitely a crucial feature that we're missing out on. For one, cover photos that are smaller than required show up as it is on a user's profile, without being scaled to fill up the cover space. And it would be convenient for OSSN users to have a photo/avatar crop feature implemented too, similar to the one on Facebook and Gravatar.

Speaking of Gravatar, I think integrating the said API into OSSN as an extension/component would be just as cool, especially for those who aren't generally bothered with having to reupload their avatar every time they register at a website.

**Comment by lianglee** [comment]
I agree about photo crop

**Comment by moneya** [comment]
i disagree with gravater,
lee crop  can be done using an hack from the profile photo crop mechanism

**Comment by lianglee** [comment]
@moneya, we are not going to implement gravater in core but we can implement crop.

**Comment by bukanfbdotcom** [comment]
how do it..

2015-05-17 2:55 GMT+07:00 Arsalan Shah <notifications@github.com>:

**Comment by lianglee** [comment]
As per new terms : 
"Tickets with feature requests will be closed"
https://github.com/opensource-socialnetwork/opensource-socialnetwork/wiki/How-to-report-a-issue-on-github
