### ISSUE TITLE
Cannot install (mod_rewrite)

### ISSUE THREAD

**Issue by WASasquatch** [opensource-socialnetwork/opensource-socialnetwork#432]
Please remove mod_rewrite from your checking. You cannot reliably test for mod_rewrite from what I've researched on the internet (have needed to do the same thing)

And alas, your software tells me "MOD_REWRITE REQUIRED" and doesn't let me install.

However, it is enabled, I use it on HumHub (another Open-Source Social Network) and tested with a simple rewrite

<img src="http://i.imgur.com/KrGFj32.png" />

```txt
RewriteEngine on
RewriteRule ^(.*)$ http://google.com
```

Which indeed, forwarded me immediately to Google. 

Recorded exmaple

<img src="http://probioticgardener.ga/modrewrite.gif" />

**Comment by lianglee** [comment]
Hi there,

You can bypass mod_rewrite check by visiting following url : yoursite.com/installation/?page=settings

There is simple rewrite test rule in .htaccess, try to visit yoursite.com/rewrite.php and let us know what you see.

Thanks

**Comment by WASasquatch** [comment]
Installation never creates a .htaccess.

**Comment by lianglee** [comment]
I agree , we have to generate .htaccess upon installation

**Comment by lianglee** [comment]
I found that many people are complaining about mod_rewrite and the issue is there is no .htaccess file in their installation or its empty, we have to fix this in 3.0, thanks for report

**Comment by WASasquatch** [comment]
Glad the problem was figured out. I'd suggest just keeping a `.htaccess.dist` (distribution) that way, you can just copy the file and make `.htaccess` *and* there is a backup to refer to in case someone is making changes or loses it.

**Comment by lianglee** [comment]
fixed

**Comment by Grunewald17** [comment]
Not Fixed

**Comment by alexraynes** [comment]
I facing problem as well and I do have htaccess

**Comment by smartey** [comment]
Jeeeezzzzzz it is 2021 and this stupid stupid coding brain fart is still around?

So, in case you run your own VPS using Apache 2.4 and php-fpm (which you should) AND you have mod rewrite enabled on SERVER level as in my case, the software STILL bugs out when installing stating mod_rewrite is not enabled while it IS.

In my case I just went to the installer class and commented out everything except the return true and then FINALLY the setup worked as expected. Why not FIX IT or remove it and show a great project to all who's interested?

**Comment by lianglee** [comment]
@smartey jeeeez the issue is the way you are configuring enabling mod rewrite is not enough unless you add Allow override rule in the apache sites.  You need to further check if the DNS of the website points to same IP or not.

**Comment by smartey** [comment]
Sorry but I am the one trying this software out and using a specific VPS setup (nothing strange I just don't use .htaccess for a reason and I do use php-fpm). Anyway, why not simply add some info somewhere addressing this possible issue which does seem to affect more people than just me the past 5? years. And above all, why not simply mention to enable mod_rewrite or the software will not work as supposed to? I mean, there can be many other server configs around, why would you want to "control" everything in your installer (knowing this will not work for everybody) while also having a readme and install info?

Reason for bugging you about this is that it is really nice software, seems to be working great(!) once you get passed this silly extraordinary installer issue. Really, if I wasn't able to read the code and make the changes myself as well as knowing my mod_rewrite is just fine I would simply stop wasting energy in trying it out and move to another social network project.
And THAT would be the real pitty right?

**Comment by lianglee** [comment]
@smartey  I got your point but its hard for installer to find out issues on the VPS setup that is why we offering free setup tool which setups everything https://www.opensource-socialnetwork.org/wiki/view/3994/how-to-install-ossn-on-ubuntu-1804-2004-x64-using-command-line  Besides this tool there are many online tutorials for installing OSSN on VPS.

Using a2enmod rewrite is not enough as you may know that.  You are welcome to open a thread regarding any matter for OSSN on our community.
