### ISSUE TITLE
Notifications for group comments

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#435]
Notifications for group comments doesn't work.
Error should be around line 337 in /ossn/components/OssnGroups/ossn_com.php

I've try to mod taking example from OssnNotifications can get notifications from private group but not for public.
Is it also possible to had an hook and function to get notifications for subscribe groups new posts ?

Test on local server using debian 7

Thanks - Eric

**Comment by lianglee** [comment]
fixed
