### ISSUE TITLE
Cannot Register | Login

### ISSUE THREAD

**Issue by WASasquatch** [opensource-socialnetwork/opensource-socialnetwork#436]
So, I haven't done anything after the theme issue. Went back in to login and get ready to fix the background issue... and I cannot login. No error.

When I register a account, I get no error, but it acts as though I must pick "Female" for gender, or as though I haven't selected a option.

<img src="http://i.imgur.com/yf2hLaN.png" />

**Comment by lianglee** [comment]
See my comment on : http://community.opensource-socialnetwork.org/discussion/view/466/test-the-product-of-ossn-by-sign-up-to-each-other-ossn-join-in-each-others

We are going to add the Redirect Www as a core feature.

**Comment by WASasquatch** [comment]
Path is setup correctly to base path/tld. How do I login to manage anything
else from the inside... ?

**Comment by ctlui** [comment]
May the cause is the username with 3 letters, I think than it should be >4:
if (preg_match("/^[a-zA-Z0-9]+$/", $this->username) && strlen($this->username) > 4)
I wrote a msg about that few months ago:
http://community.opensource-socialnetwork.org/discussion/view/260/username-condition-to-register-and-few-optimisation

**Comment by WASasquatch** [comment]
Thanks. My username is WASasquatch for my admin account. That was just a
test to register. I tried several usernames.

**Comment by lianglee** [comment]
I just created account on your website and its works for me.

![capture](https://cloud.githubusercontent.com/assets/805066/7800424/95635e40-032e-11e5-82d1-a4ecb87c3aed.JPG)
![capture2](https://cloud.githubusercontent.com/assets/805066/7800441/ded08fbc-032e-11e5-901e-ec2946fb7f64.JPG)

**Comment by WASasquatch** [comment]
Thanks, yeah I fixed some file settings. But I still cannot login to my
account or request lost password. :\ The main account made during install.
Where is pass hashing done? I'd like to try to assign a new pass to DB.

On Mon, May 25, 2015 at 10:39 AM, Arsalan Shah <notifications@github.com>
wrote:

> I just created account on your website and its works for me.
>
> [image: capture]
> <https://cloud.githubusercontent.com/assets/805066/7800424/95635e40-032e-11e5-82d1-a4ecb87c3aed.JPG>
> [image: capture2]
> <https://cloud.githubusercontent.com/assets/805066/7800441/ded08fbc-032e-11e5-901e-ec2946fb7f64.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/436#issuecomment-105276441>
> .
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by lianglee** [comment]
@ WASasquatch, 

Create a new account,  login into your DB, go to ossn_users table find your user and new user, copy password and salt form new user account to your old user account. It will work.

Thanks
