### ISSUE TITLE
ossn chat syntax error

### ISSUE THREAD

**Issue by lequy1010** [opensource-socialnetwork/opensource-socialnetwork#437]
I see in file getnew.php at line 15 (foreach ($messages as as $message))
i think have syntax error
if that's a error, please quick update!

**Comment by lianglee** [comment]
You can change that line to (foreach ($messages as $message))

**Comment by lequy1010** [comment]
:)
because it's a framework, so that it should fix for all member
not only for me!

**Comment by lianglee** [comment]
Yes we'll fix it on our next push of v3.0 development.

**Comment by lianglee** [comment]
fixed
