### ISSUE TITLE
Bug with json special char in post

### ISSUE THREAD

**Issue by yellowelise** [opensource-socialnetwork/opensource-socialnetwork#440]
if you try to post something like 

function ensure2Digit($number) {
	settype($number,'integer');
    if($number < 10) {
        $number = '0' . $number;
    }
    return $number;
}

in ossn the result is a blank post.
to resolve this issues you need to add this function:
function escapeJsonString($value) { 
    $escapers = array("\\", "/", "\"", "\n", "\r", "\t", "\x08", "\x0c");
    $replacements = array("\\\\", "\\/", "\\\"", "\\n", "\\r", "\\t", "\\f", "\\b");
    $result = str_replace($escapers, $replacements, $value);
    return $result;
}

in this files:
/components/OssnWall/actions/wall/post/group.php
/components/OssnWall/actions/wall/post/home.php
/components/OssnWall/actions/wall/post/user.php

and replace also in that file
$post = input('post');
with
$post = escapeJsonString(input('post'));

**Comment by lianglee** [comment]
The method you posted , should be in ossn input validate function.

Thanks for informing , we'll fix it.

**Comment by lianglee** [comment]
Its working fine with latest Ossn 3.0 development with php 5.4, please reopen the issue if it exists.

![utf8- 440](https://cloud.githubusercontent.com/assets/805066/8637927/3805ae28-28c3-11e5-84c3-e8eb0c81ff12.JPG)
