### ISSUE TITLE
Installation of v3.0

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#441]
I tried to install the version 3 of ossn but it isn't possible. I want to do this one on a different local domain for checking the different of version 2 and 3. I get 'It seems the Open Source Social Network is already installed' as result.

**Comment by ctlui** [comment]
Just delete ./installation/INSTALLED file and it'll be ok

**Comment by TheGameHHH** [comment]
thanks, it works.

**Comment by lianglee** [comment]
This issue already has been solved
