### ISSUE TITLE
js issue in v3.0-development

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#442]
I am not able with my Firefox, Chrome or Internet Explorer/Edge to use the administration area of OSSN. No dropdown menu is clickable. If I want on a page of the administration I have to use for example the developer tools in Chrome.
![unbenannt](https://cloud.githubusercontent.com/assets/5566418/8339414/862fad2a-1ab7-11e5-8306-a4fec1e78002.JPG)

**Comment by lianglee** [comment]
Try to flush cache, and make sure all JavaScript files are loaded in system,
View source of page and check if url of all javascript files are working.

**Comment by lianglee** [comment]
Please don't mix v3.0 release with v3.0-development ,

**Comment by TheGameHHH** [comment]
It works with the update from today.
