### ISSUE TITLE
ossn system messages css issue on front end

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#443]
In my case a second user isn't unlocked yet. As I tried to log me in for testing if error messages will shown. I discovered that this one will shown over the header and isn't really to see for a normal user.
![unbenannt1](https://cloud.githubusercontent.com/assets/5566418/8339602/fba0c02a-1ab8-11e5-9b1e-0fa60388e38f.JPG)

**Comment by lianglee** [comment]
We are aware of this issue , thanks for report

**Comment by lianglee** [comment]
For core tea: [Fix a system messages for /layout/site]

**Comment by lianglee** [comment]
Fixed
