### ISSUE TITLE
visit other profiles in v3.0-development

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#445]
If I visit the profiles of friends I get only to see a little bit. It looks like the page wouldn't be finished.
![unbenannt](https://cloud.githubusercontent.com/assets/5566418/8356088/6631c07a-1b53-11e5-8a8a-164a70f355e5.JPG)

**Comment by lianglee** [comment]
thanks for report will check it

**Comment by lianglee** [comment]
Its some kind a memory issue, we'll fix it

**Comment by lianglee** [comment]
Memory leakage confirmed, fixed
