### ISSUE TITLE
Administrator Dashboard: Flush Cache button is misspelled as "Flsuh Cache"

### ISSUE THREAD

**Issue by huckleberrypie** [opensource-socialnetwork/opensource-socialnetwork#447]
Title says all. I do know that English isn't the development team's first language, but I couldn't help but notice this, among other spelling/grammar issues that are in need of addressing.

**Comment by lianglee** [comment]
fixed, its was misspelled

**Comment by huckleberrypie** [comment]
Thanks! :D
