### ISSUE TITLE
OSSN 3.0-dev: Wall posts don't show up on timeline.

### ISSUE THREAD

**Issue by huckleberrypie** [opensource-socialnetwork/opensource-socialnetwork#448]
And for some reason, you'd see the same timeline content upon visiting someone else's profile:
http://imgur.com/a/OnvPa

I know v3.0 isn't exactly the thing you'd deploy on a production site for now, but I'm looking forward to it, especially as it seems to perform better than previous builds.

**Comment by lianglee** [comment]
Can you explain in details please?

**Comment by TheGameHHH** [comment]
look at this post https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/446

**Comment by sathish4fri** [comment]
@huckleberrypie can you explain it clearly not able to understand what you mean ?

**Comment by huckleberrypie** [comment]
Alright, what I'm saying is that any new posts that I make show up on the news feed, but not on my timeline, e.g. I post something along the lines of "blahblah this is a test" and it appears to be submitted, but I don't see it on my profile. And for some strange reason, my older timeline items appear even on other users' profiles.

**Comment by lianglee** [comment]
We'll verify and fix it

**Comment by huckleberrypie** [comment]
Alright, I'm looking forward to a fix. ;)

**Comment by lianglee** [comment]
Can you try it with latest github code? if error exist reopen this issue again.

**Comment by huckleberrypie** [comment]
Hmm, that's strange, I DL'd and installed the latest build from here recently, and yet the timeline issue still persists.

**Comment by lianglee** [comment]
i'll check it again

**Comment by huckleberrypie** [comment]
Alright, I'll look forward to it.

**Comment by TheGameHHH** [comment]
It is possible to write some postings again and it will shown in the wall.

**Comment by lianglee** [comment]
Its now working as it supposed to be, check on fresh installation.

**Comment by huckleberrypie** [comment]
Hmm, seems like my database's hosed, then. :(

**Comment by huckleberrypie** [comment]
There, it's fixed now, thanks! <3
