### ISSUE TITLE
load system plugins before components load

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#451]
load system plugins before components load

**Comment by moneya** [comment]
@lianglee  would this help with optimization?

**Comment by lianglee** [comment]
@moneya , actually today i tried to override one file that was core using component but it component was not overriding it, i checked and found that the components plugins files were overwritten by system  files. That is why system plugins should be loaded before we load all components.

I am not sure if you understand, but this will help developers to override system files without directly editing them.

(Like elgg views)

**Comment by lianglee** [comment]
@moneya i will let you know how to hook views to mobile views if user is on mobile device. If i remember you asked me about separate views for mobiles, in 3.0 it will be possible.

**Comment by moneya** [comment]
yea, i did,
that would be nice

**Comment by moneya** [comment]
please alert me when done
