### ISSUE TITLE
after todays update

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#462]
After today's changes I wanted to upgrade my OSSN. During I logged me in as I upgrade this one were no problems. As I went into the admin area I received a whole white page. After this one I have now everywhere a white one.

on a virtual machine I tried to call that page. I can't do it anymore and get an 500 error. other local pages are working.

**Comment by lianglee** [comment]
Its because Ossn v3.0 -development is not for upgrade , we didn't have upgrade scripts yet, that is why i told everyone not to upgrade to 3.0 -development

**Comment by TheGameHHH** [comment]
I already use OSSN in Version 3 and yesterday I upgrade Version 3 with the new changes. Sometimes I think you won't understand the issue because of lack of interest.

**Comment by lianglee** [comment]
@TheGameHHH, i know the issue, there is no upgrade scripts avaialble for 3.0-development, we have made changes in database, in case you upgraded , the files required to get some data from database, your old database is missing some tables,

Try to install fresh version on 3.0-development and try again.

**Comment by lianglee** [comment]
Do you mean you wanted to upgrade old Ossn v3.0 development to new one? , you went to admin page before you upgrade and you have white page error?

The best way to track the error is to see error_log file,  you can turn on errors reporting by running following query:

    UPDATE  `ossn_site_settings` SET  `value` =  'on' WHERE  `ossn_site_settings`.`setting_id` =9;

**Comment by lianglee** [comment]
I saw following message when i tried to run upgrade/upgrade.php

![ossn3-upgrade](https://cloud.githubusercontent.com/assets/805066/8633606/fb545b2a-27e9-11e5-821f-13db30fc1a77.jpg)

**Comment by moneya** [comment]
@TheGameHHH
 I think you
won't understand the issue because of lack of interest.
i don't understand what you meant by lack of interest? 
what did you get from your error  log?
