### ISSUE TITLE
[OSSN 3.x] OssnEmbed in settings

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#466]
In Settings / Components when you click on the OssnEmbed 3.0 it open the OssnComments 3.0 components.

Solution find:
In /components/OssnComments/ossn_com.xml line 4 I've replace
<id>OssnEmbed</id>
by
<id>OssnComments</id>

Ossn: branch 3.x
Php: 5.6.9
Cache: Disable
Apache: 2.4.10
Mysql: 5.5
Website: local server

**Comment by lianglee** [comment]
Fixed
