### ISSUE TITLE
CSS: Pagination with more than 10 users

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#468]
If you have more than 10 users then will not shown the pagination in CSS in User Manager.

Ossn version 3.0 dev after todays update
PHP version 5.5.24
Cache enabled
Apache version XAMPP 5.5.24
MySQL version 5.6.24

**Comment by lianglee** [comment]
Please share the photo

**Comment by lianglee** [comment]
Fixed
