### ISSUE TITLE
ossnblack theme white page issue

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#469]
I can't really confirm it if it is really a cache issue but in following settings I only get a white page.

Theme: OSSN Black
Language: de and en
Cache: deactivate

The solution to go back is if you change the datas in the ossn_site_settings table.

Ossn version 3.0 dev after todays update
PHP version 5.5.24
Cache enabled
Apache version XAMPP 5.5.24
MySQL version 5.6.24

**Comment by lianglee** [comment]
Fixed
