### ISSUE TITLE
messages only at some points

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#470]
New Installation

If I want to write a message to another user I get an error message like 'Something went wrong! Reload this page and try again.'. In the message top bar will nothing shown that I wrote a message to someone. Also It is only to see in database.

Entry in database
![write_1](https://cloud.githubusercontent.com/assets/5566418/8736743/a3efc802-2c1b-11e5-8ce3-ffa230076d4b.PNG)

Messages
![write_2](https://cloud.githubusercontent.com/assets/5566418/8736750/a98156d2-2c1b-11e5-9ffe-18bb01fd736c.PNG)

Message box at top bar
![write_3](https://cloud.githubusercontent.com/assets/5566418/8736753/ac83d2c4-2c1b-11e5-89ef-9e25d62ae0c4.PNG)

Ossn version 3.0 dev
PHP version 5.5.24
Cache enabled
Apache version XAMPP 5.5.24
MySQL version 5.6.24

**Comment by lianglee** [comment]
Fixed
