### ISSUE TITLE
[OSSN 3.x] Bug double post if 1 or 2 white line after the text in a post

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#471]
When you make a new post and after your text you make 1 or 2 enter , the post will apppear twice.
Ex type:

test 1st line [enter]
white line
white line

Post can appear 2 or 3 times

Ossn: branch 3.x
Php: 5.6.9
Cache: Disable
Apache: 2.4.10
Mysql: 5.5
Website: local server

**Comment by lianglee** [comment]
Fixed
