### ISSUE TITLE
SQL exception on running upgrade.php

### ISSUE THREAD

**Issue by huckleberrypie** [opensource-socialnetwork/opensource-socialnetwork#472]
Hmm, I know OSSN 3.0 isn't exactly ready for prime time yet, but since I'm already using it and all, I guess I have no choice but to test it for the time being.

Now on to the real problem: I've just downloaded the latest revision and tried upgrading my install, but I end up with the following exception:

exception 'OssnDatabaseException' with message 'Duplicate column name 'time_created' ALTER TABLE `ossn_users` ADD `time_created` INT(11) NOT NULL AFTER `activation`; ' in /home/klausvfd/fegelbook/classes/OssnDatabase.php:77 Stack trace: #0 /home/klausvfd/fegelbook/upgrade/upgrades/1437590842.php(29): OssnDatabase->execute() #1 /home/klausvfd/fegelbook/libraries/ossn.lib.upgrade.php(93): include_once('/home/klausvfd/...') #2 /home/klausvfd/fegelbook/upgrade/upgrade.php(17): ossn_trigger_upgrades() #3 {main}

Any thoughts on this one?

**Comment by lianglee** [comment]
Upgrade will only work on database based on 2.x, if you upgrade form 2.x to 3.0-dev there wont be any issue

**Comment by lianglee** [comment]
Try to reinstall v3.0 it should be fine
