### ISSUE TITLE
Unable to delete photo album

### ISSUE THREAD

**Issue by huckleberrypie** [opensource-socialnetwork/opensource-socialnetwork#473]
Title says all. I get a message that the album has been deleted, but it's still there despite numerous attempts to do so.

**Comment by lianglee** [comment]
Fixed, 
Please next time read the guidelines before posting new issue.
https://github.com/opensource-socialnetwork/opensource-socialnetwork/wiki/How-to-report-a-issue-on-github

**Comment by huckleberrypie** [comment]
Sorry about that, but thanks for the fix anyway. ;)
