### ISSUE TITLE
[OSSN 3.0-beta] Missing things below div class inner @ home

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#474]
When you open home (not registred) ossn-home-container is empty
<div class="ossn-contents">
    <div class="ossn-home-container">
        <div class="inner">
        </div>
    </div>
</div>
         
Just compare to v2.3 where I have:
<div class="ossn-home-container">
     <div class="inner">
        <div class="home-left-contents"></div>
        <div class="home-right-contents"></div>

Ossn: branch 3.x fresh install last commit 
Php: 5.6.9
Cache: Disable
Apache: 2.4.10
Mysql: 5.5
Website: local server

**Comment by lianglee** [comment]
Download beta2 http://www.opensource-socialnetwork.org/downloads/ossn-v3.0-beta2-1437590842.zip
