### ISSUE TITLE
new issue with OSSN

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#475]
currently I have two domains for OSSN. One is for development or testing by updates and the other one is for live data of the members.
First I updated OSSN on the development domain without any issue. After that I wanted to update the other domain but at this one there are only issues. Both domains are same configured. 
On the second domain I saved the data of database and deleted this. I also deleted the other datas of OSSN and install this one completely new. The datas in database were replaced again by the original. Nothing was really helpful because I get a white index page. As admin I can log me in in the admin area and go into the frontend. If I go into the frontend I get no menu from the top.
I also downloaded OSSN completely new. It wasn't also helpful.

My development domain has a completely new OSSN and it runs. My live domain has a completely new OSSN too and it didn't runs.

Everything runs on Xampp 5.5.27 and should run with OSSN 3.0-beta2.

**Comment by lianglee** [comment]
Try to create a file 'DISPLAY_ERRORS' under root of ossn files.

**Comment by TheGameHHH** [comment]
Can't me log in anymore in administrator area after I activated the option for DISPLAY_ERRORS. The system hasn't create a file.

I discovered another one on the page for administrator.
Live Data OSSN
![ossn](https://cloud.githubusercontent.com/assets/5566418/9022632/2dfe54f6-387d-11e5-8d4d-467475d21574.JPG)

Development OSSN
![ossn dev](https://cloud.githubusercontent.com/assets/5566418/9022635/5622f63a-387d-11e5-9262-898fb4635a4f.JPG)

Perhaps it is helpful, because it isn't exists a cache folder on both domains.

**Comment by lianglee** [comment]
Go to administrator/cache and disable cache

**Comment by TheGameHHH** [comment]
How I should delete the cache files, if both OSSNs were new installed?

Now, it is fixed.

**Comment by lianglee** [comment]
[http://community.opensource-socialnetwork.org/discussion/view/672]
