### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#477]
I don't know if more comes to annotation, but I get an error after login.

This is my error message.
exception 'OssnDatabaseException' with message 'Column 'id' in order clause is ambiguous SELECT count(*) as total FROM ossn_annotations as a, ossn_entities as e , ossn_entities_metadata as emd WHERE(a.type='comments:post' AND e.subtype='comments:post' AND a.subject_guid ='34' AND e.owner_guid=a.id AND e.type='annotation' AND emd.guid=e.guid) ORDER by id ASC ; ' in C:\local\ossn\www\classes\OssnDatabase.php:77 Stack trace: #0 C:\local\ossn\www\classes\OssnDatabase.php(175): OssnDatabase->execute() #1 C:\local\ossn\www\classes\OssnAnnotation.php(319): OssnDatabase->select(Array) #2 C:\local\ossn\www\classes\OssnAnnotation.php(167): OssnAnnotation->searchAnnotation(Array) #3 C:\local\ossn\www\components\OssnComments\classes\OssnComments.php(98): OssnAnnotation->getAnnotationBySubject() #4 C:\local\ossn\www\components\OssnLikes\plugins\default\likes\post\likes.php(42): OssnComments->countComments('34') #5 C:\local\ossn\www\libraries\ossn.lib.views.php(27): include('C:\\local\\ossn\\w...') #6 C:\local\ossn\www\libraries\ossn.lib.views.php(50): ossn_include('C:/local/ossn/w...', Object(OssnObject)) #7 C:\local\ossn\www\libraries\ossn.lib.plugins.php(68): ossn_view('components/Ossn...', Object(OssnObject)) #8 C:\local\ossn\www\components\OssnLikes\ossn_com.php(127): ossn_plugin_view('likes/post/like...', Object(OssnObject)) #9 [internal function]: ossn_post_likes('post', 'likes', NULL, Object(OssnObject)) #10 C:\local\ossn\www\libraries\ossn.lib.system.php(189): call_user_func_array('ossn_post_likes', Array) #11 C:\local\ossn\www\components\OssnWall\plugins\default\wall\templates\wall\user\item.php(89): ossn_call_hook('post', 'likes', Object(OssnObject)) #12 C:\local\ossn\www\libraries\ossn.lib.views.php(27): include('C:\\local\\ossn\\w...') #13 C:\local\ossn\www\libraries\ossn.lib.views.php(50): ossn_include('C:/local/ossn/w...', Array) #14 C:\local\ossn\www\libraries\ossn.lib.plugins.php(68): ossn_view('components/Ossn...', Array) #15 C:\local\ossn\www\components\OssnWall\ossn_com.php(330): ossn_plugin_view('wall/templates/...', Array) #16 [internal function]: ossn_wall_templates('wall:template', 'user', NULL, Array) #17 C:\local\ossn\www\libraries\ossn.lib.system.php(189): call_user_func_array('ossn_wall_templ...', Array) #18 C:\local\ossn\www\components\OssnWall\ossn_com.php(313): ossn_call_hook('wall:template', 'user', Array) #19 C:\local\ossn\www\components\OssnWall\plugins\default\wall\templates\activity-item.php(11): ossn_wall_view_template(Array) #20 C:\local\ossn\www\libraries\ossn.lib.views.php(27): include('C:\\local\\ossn\\w...') #21 C:\local\ossn\www\libraries\ossn.lib.views.php(50): ossn_include('C:/local/ossn/w...', Array) #22 C:\local\ossn\www\libraries\ossn.lib.plugins.php(68): ossn_view('components/Ossn...', Array) #23 C:\local\ossn\www\components\OssnWall\plugins\default\wall\siteactivity.php(59): ossn_plugin_view('wall/templates/...', Array) #24 C:\local\ossn\www\libraries\ossn.lib.views.php(27): include('C:\\local\\ossn\\w...') #25 C:\local\ossn\www\libraries\ossn.lib.views.php(50): ossn_include('C:/local/ossn/w...', Array) #26 C:\local\ossn\www\libraries\ossn.lib.plugins.php(68): ossn_view('components/Ossn...', Array) #27 C:\local\ossn\www\components\OssnWall\plugins\default\wall\pages\wall.php(27): ossn_plugin_view('wall/siteactivi...') #28 C:\local\ossn\www\libraries\ossn.lib.views.php(27): include('C:\\local\\ossn\\w...') #29 C:\local\ossn\www\libraries\ossn.lib.views.php(50): ossn_include('C:/local/ossn/w...', Array) #30 C:\local\ossn\www\libraries\ossn.lib.plugins.php(68): ossn_view('components/Ossn...', Array) #31 C:\local\ossn\www\libraries\ossn.lib.initialize.php(109): ossn_plugin_view('wall/pages/wall') #32 [internal function]: ossn_user_pagehandler(Array, 'home') #33 C:\local\ossn\www\libraries\ossn.lib.page.php(67): call_user_func('ossn_user_pageh...', Array, 'home') #34 C:\local\ossn\www\index.php(21): ossn_load_page('home', false) #35 {main}

I'm using Xampp 5.5.27.

**Comment by lianglee** [comment]
I working to write few things, i faced same issue, i fixed it now
