### ISSUE TITLE
Minify some js

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#478]
Hi,

Some js files are write as minify but they are not:

/vendors/jquery/
jquery-1.11.1.min.js
jquery-1.6.4.min.js
jquery-ui.min.js

/vendors/tinymce/tinymce.min.js

Also can you try look at optimisation with https://developers.google.com/speed/pagespeed/insights/
or he've a plugin for chrome to test in local.

Thanks - Eric

**Comment by lianglee** [comment]
Fixed
