### ISSUE TITLE
Time created column not presented in database

### ISSUE THREAD

**Issue by sathish4fri** [opensource-socialnetwork/opensource-socialnetwork#479]
time created column not presented when updating the ossn to 3X . And its throwing fatal error

exception 'OssnDatabaseException' with message 'Unknown column 'time_created' in 'field list' SELECT DATE_FORMAT(FROM_UNIXTIME(time_created), '%Y') AS year, DATE_FORMAT(FROM_UNIXTIME(time_created) , '%m') AS month, COUNT(guid) AS total FROM ossn_users WHERE(time_created > 0) GROUP by DATE_FORMAT(FROM_UNIXTIME(time_created) , '%Y%m') ; ' in /var/www/html/ossn/classes/OssnDatabase.php:77 

and admin design is not coming properly

**Comment by lianglee** [comment]
Have you visited the upgrade/upgrade.php ?

**Comment by sathish4fri** [comment]
first time i tried with upgrade but not worked , again i replaced the file with github upgrade and working
