### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by nitestryker** [opensource-socialnetwork/opensource-socialnetwork#480]
the .htaccess file is causing a 500 internal server error
I removed the .htaccess file it works fine.

**Comment by nitestryker** [comment]
I commented out the first line  1. AddHandler application/x-httpd-php54 .php .php5 .php4 .php3
and it fixed the problem on my server

**Comment by lianglee** [comment]
Thank you for report, its your server issue.
