### ISSUE TITLE
Likes: list users in ossnbox

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#483]
List of users missing when you click to see the other personn who likes a post.
Correction made and seems to work:

components/OssnLikes/ossn_com.php
Line 149:
'contents' => ossn_view('components/OssnLikes/pages/view'),
change to:
'contents' => ossn_plugin_view('likes/pages/view'),

components/OssnLikes/plugins/default/likes/pages/view.php
Line 28:
echo ossn_view("system/templates/output/users_list", $users);
change to:
echo ossn_plugin_view("output/users_list", $users);

I've make a quick search with system/templates/output/users in the source, and it appear also at:
components/OssnProfile/plugins/default/profile/pages/friends.php line 13 so may be there something wrong there.

Thanks - Eric

**Comment by lianglee** [comment]
Fixed thanks
