### ISSUE TITLE
Problem redirect install OSSN 3.01 in port 9090

### ISSUE THREAD

**Issue by amjf10** [opensource-socialnetwork/opensource-socialnetwork#485]
When I am installing the OSSN on port 9090 http: // localhost: 9090 / OSSN / installation / page = settings to give me click Install redirected to http: // localhost / OSSN / installation / page = account by removing the port which does not leave me because I have to continue istalado apache to run on port 9090.

I hope I can help indicate what would be the shutdown can.

**Comment by lianglee** [comment]
See my comment on : https://www.opensource-socialnetwork.org/discussion/view/784/problem-redirect-install-ossn-301-in-port-9090

**Comment by lianglee** [comment]
Fixed

**Comment by ctlui** [comment]
Last commit https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/00db169c47cc87268be693465530be144e632204 for ossn.lib.javascripts.php break my ssl site.
Get a blank page with too many redirect and a 301 header.
My site doesn't use www (https://sub.domain.tld)
