### ISSUE TITLE
Change small to 40 x 40 ?

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#486]
Hi,

Not an issue but may be improvement.
In /libraries/ossn.lib.image.php
line 247 he've:
'small' => ' 50x50',

But I don't find image using size 50 x 50, They used a 40 x 40 size, so they're resize.
May be it'll be better to have 40 x 40 ?
I think they're used in OssnProfile and OssnWall.

Also some img src don't have dimensions, icon on ossn-menu-newsfeed, /avatar/small & smaller.
Here what I've mod in /components/OssnChat/classes/OssnChat.php
line 100 to 116:
https://github.com/ctlui/opensource-socialnetwork/blob/3.x/components/OssnChat/classes/OssnChat.php

I like very optimisation and test with pagespeed to optimize.
I can search all missing size if you want.

Thanks - Eric

**Comment by lianglee** [comment]
These sizes are used in profile images, we have to find other way to optimize images.

**Comment by lianglee** [comment]
See: https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnProfile/actions/photo/upload.php#L41-L46
