### ISSUE TITLE
OSSNADS

### ISSUE THREAD

**Issue by dorobantu** [opensource-socialnetwork/opensource-socialnetwork#487]
Hi

I just installed your script and I tried to add new Ads. It says "Cannot create ad!"

How can I fix this or what is the problem? 

Thank you.

**Comment by TheGameHHH** [comment]
if you have filled in every field, it's working.
---------
just saw that in siteurl column is the description in admin area

**Comment by lianglee** [comment]
It appears you don't have write access to database?
