### ISSUE TITLE
Some corrections width='100' height="100"

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#489]
Hi,

In some files images dimensions are write like this:
width='100' height="100"
May be shoukd be:
width="100" height="100"

I don't jknow if he affect anything as I'm not dev.

List find:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnGroups/plugins/default/groups/pages/members.php
line 17

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnGroups/plugins/default/groups/pages/requests.php
line 19

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnGroups/plugins/default/groups/search/view.php
line 17

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/system/default/output/users.php
line 17

**Comment by moneya** [comment]
thanks for reporting.
it does not create any issues.
it's just a typo

**Comment by lianglee** [comment]
It doesn't create any issue , both works fine.

**Comment by lianglee** [comment]
Changed now
