### ISSUE TITLE
blank post when have a tabulation in text

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#494]
Yesterday evening I've try to post change for the update in a post but get nothing in post.
After some search I've found than it was the tabulation at line 50.
So to test just post lines 49,50 and 51 from https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/CHANGES.txt

Just finish all the test and the only time than I don't have the bug is on my local test server with debian 8, apache 2.4, php 5.6 and mysql 5.5.

I've do the test on my dedicated server using debian 7, apache 2.2, php 5.4 & mysql 5.5
and also try a clean install on a vps who have same config of the dedicated server and got the bug on this 2 servers.

Even if the post doesn't appear in the timeline, he's in the database and it's write the same thing in the description field of ossn_object on the 3 servers:
	{"post":"Additions:\r\n \r\n * Implementd plugins for components."}

May be the problem is from the php version.

Thanks - Eric

**Comment by lianglee** [comment]
It should work on php 5.4, can you try to switch to php 5.6?

**Comment by lianglee** [comment]
its issue with json_decode

**Comment by lianglee** [comment]
The best we can do is replace tab with space before saving post into database

**Comment by ctlui** [comment]
Yes best solution as it work with php 5.6 and we know it.
Passing all my night to test but just like to find why and tought it was a problem on my config.

Thans very much.

Eric

**Comment by lianglee** [comment]
its actually bug, we'll fix it soon

**Comment by lianglee** [comment]
Fixed
