### ISSUE TITLE
http external css in themes with https site

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#495]
With Firefox when using https site, http external component are blocked.
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/themes/default/ossn_theme.php
Line 40 change http to https

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/themes/ossnblack/ossn_theme.php
Line 42 change http to https

Or it's possible to put the css file into the theme.

**Comment by lianglee** [comment]
Oh yes we have to check if connection is https then change google fonts to https, thanks for report we'll fix it tonight

**Comment by lianglee** [comment]
Fixed
