### ISSUE TITLE
Error after #485 ossn.lib.javascripts.php

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#496]
Last commit 00db169 for ossn.lib.javascripts.php break my ssl site.
Get a blank page with too many redirect and a 301 header.
My site doesn't use www (https://sub.domain.tld)
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/libraries/ossn.lib.javascripts.php#L333
&& $_SERVER['SERVER_PORT'] !== 80 && $_SERVER['SERVER_PORT'] == '443'){
change to:
&& $_SERVER['SERVER_PORT'] !== ':80' && $_SERVER['SERVER_PORT'] == ':443'){

**Comment by lianglee** [comment]
thanks we'll fix today!

**Comment by lianglee** [comment]
I think we have to change to : 

    && $_SERVER['SERVER_PORT'] !== '80' && $_SERVER['SERVER_PORT'] !=='443'

Can you try with this?

**Comment by ctlui** [comment]
Test & confirm ! it works.

 I thought than needed to write it like that because it's write ':80' & ':443' line 325
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/libraries/ossn.lib.javascripts.php#L325

I just look test try & compare as I don't know nothing.

Thanks - Eric

**Comment by lianglee** [comment]
Merged
