### ISSUE TITLE
Runs very very slow on my localhost

### ISSUE THREAD

**Issue by okechukwu** [opensource-socialnetwork/opensource-socialnetwork#498]
first i must say its a fantastic FB clone but i dont seem to know why its very slow on my local network.
My laptop runs on Windows10,4GRAM, 300GB Hard Disk.

so i dont think its my system specification thats making the site slow.

Can some one pls tell me what to do to make it optimized, thus to make it run smoothly and fast like FB does!

**Comment by TheGameHHH** [comment]
if you want help we should know what is your test environment

**Comment by lianglee** [comment]
Yes , please let us know which environment you are using? what is Ossn version?

If you are on v3.01 please try to enable cache.

**Comment by lianglee** [comment]
Closing issue as no response from user
