### ISSUE TITLE
Home link in main site and admin top bar

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#499]
In top bar menu link to hoome or view site in admin part send to http://domain.tld and then redirect to http://domain.tld/home
May be it's better to add home to gain a redirect.
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/themes/default/plugins/default/theme/page/page.php#L88
change
<?php echo ossn_site_url(); ?>">
to 
<?php echo ossn_site_url(); ?>home">

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/themes/ossnblack/plugins/default/theme/page/page.php#L88
change:
change
<?php echo ossn_site_url(); ?>">
to 
<?php echo ossn_site_url(); ?>home">

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/libraries/ossn.lib.admin.php#L38
change:
ossn_register_menu_link('viewsite', 'admin:view:site', ossn_site_url(), 'topbar_admin');
to:
ossn_register_menu_link('viewsite', 'admin:view:site', ossn_site_url('home'), 'topbar_admin');

Thanks - Eric

**Comment by lianglee** [comment]
Very good , Eric!

**Comment by lianglee** [comment]
Fixed see #502 #501
