### ISSUE TITLE
Translation not 100% in locale files

### ISSUE THREAD

**Issue by hazyapps** [opensource-socialnetwork/opensource-socialnetwork#508]
Hey i wrote a dutch language file by translating the english one but some values seem to be missing can you please point out to me in wich file(s) those are located so i can creat a dutch version for that as well

**Comment by ctlui** [comment]
You need to look inside each components, he also have locale directory with file to translate.

**Comment by lianglee** [comment]
Please follow as @ctlui said

**Comment by hazyapps** [comment]
yes thanks guys, i will  start buildin that dutch languagepack tomorrow @lianglee sorry for trying to pull  mor langage changes, did not yet read  your reply. as you might have seen in my acccount history i do not have a lot of expereince with the whole github thingy

**Comment by lianglee** [comment]
@hazyapps fee free to ask me any question related to Ossn.

**Comment by hazyapps** [comment]
Hey lianglee,

Thank you for your help so far, is there maybe a more direct way i can cotnact you? say trough skype or any other chat client?

As many of your webiste users i am looking to build a mobile site/frontend (start very basic and  add component for component and would like to share some ideas

**Comment by lianglee** [comment]
skype: buddyexpress
email: arsalan[at]buddyexpress.net
