### ISSUE TITLE
SQL exception on running upgrade.php, redux

### ISSUE THREAD

**Issue by huckleberrypie** [opensource-socialnetwork/opensource-socialnetwork#512]
Hmm, decided to move to a stable version after a few months of trying out the SVN, but I ended up with this:

exception 'OssnDatabaseException' with message 'Duplicate column name 'time_created' ALTER TABLE `ossn_users` ADD `time_created` INT(11) NOT NULL AFTER `activation`; ' in /home/klausvfd/fegelbook/classes/OssnDatabase.php:77 Stack trace: #0 /home/klausvfd/fegelbook/upgrade/upgrades/1439295894.php(31): OssnDatabase->execute() #1 /home/klausvfd/fegelbook/libraries/ossn.lib.upgrade.php(93): include_once('/home/klausvfd/...') #2 /home/klausvfd/fegelbook/upgrade/upgrade.php(17): ossn_trigger_upgrades() #3 {main}

I was hoping maybe you guys have an SQL script similar to the one you offered me some time ago, so yeah.

**Comment by lianglee** [comment]
Its because you updated to v3.0-dev , before it production release. Backup your database and try to remove a time_created column form ossn_users table and then run upgrade.
