### ISSUE TITLE
remove chart legend code form chart.min.js

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#517]
I saw than chart.legend.js is added at the end of Chart.min.js
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/vendors/Chartjs/Chart.min.js#L15
chart.legend.js is loaded from https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/libraries/ossn.lib.javascripts.php#L34

May be can be deleted in Chart.min.js

Found that as I was looking to load those js from some cdn.

Thanks - Eric

**Comment by lianglee** [comment]
Yes, we have to delete one of them.
