### ISSUE TITLE
Open link in new tab (enhancement)

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#518]
May be can be add by default, just to open link in post or comments in a new tab:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnEmbed/vendors/linkify/linkify.php#L52
Replace:
```$url_replace = '$1$4$7$10$13<a href="$2$5$8$11$14">$2$5$8$11$14</a>$3$6$9$12';```
by:
```$url_replace = '$1$4$7$10$13<a href="$2$5$8$11$14" \\1 target="_blank">$2$5$8$11$14</a>$3$6$9$12';```

**Comment by lianglee** [comment]
Agree
