### ISSUE TITLE
Problem of characters lenght on the instant messenger

### ISSUE THREAD

**Issue by michel2107** [opensource-socialnetwork/opensource-socialnetwork#520]
Hello,

Just this message to report you something about the instant messenger (chat window).
When we type a message, if we arrive at the end of the input mask, the 3 or 4 last characters are hidden. We don't see what we type.

Regards,
Michel

**Comment by lianglee** [comment]
Will be fixed in next release.

**Comment by lianglee** [comment]
Can you provided some screenshots and version of Ossn?

**Comment by David111567** [comment]
All versions.  And it's hard to give screenshots of this, since it runs off the visible area.  When you type, it scrolls past the right-hand edge of the chat box.... so you can't see what you are typing.

**Comment by michel2107** [comment]
I made a screenshot (i just hide the pseudo)
I wrote "This is an example for OSSN Community"
It miss the "ity" of Community
![ossn](https://cloud.githubusercontent.com/assets/14145632/10371023/bbcee450-6de1-11e5-96bb-20664a66a7bf.png)

**Comment by David111567** [comment]
^^^^^^^ What HE said!!  Exactly!

**Comment by lianglee** [comment]
Issue has been confirmed and marked as bug will be fixed in next release.

**Comment by lianglee** [comment]
Fixed
