### ISSUE TITLE
Accounts manager

### ISSUE THREAD

**Issue by michel2107** [opensource-socialnetwork/opensource-socialnetwork#521]
Hello,

I think it would be great to add 3 things in the accounts manager.

1 - I think it would be great to allow to certify the accounts. 
These certifications could be managed in the administration panel (in
the user list with a check box beside each account. When the case is
checked, a logo "certified" could appear just after the pseudo).

2 - I would like to know if there is component allowing to block indelicate members (by his ip address for example). When we delete a rude member, nothing prevents him to create another account to continue to be rude.

3 - I remarked that when a member is deleted, his messages are always present in the database mysql (so the instant messenger with this member is still in the discussion list even if the member not on the site anymore so to delete the messages of the member, we need to delete manually the messages in mysql with the id of the member). 

Thanks a lot
Regards,
Michel

**Comment by lianglee** [comment]
Thanks for suggestions, the one i liked is we have to delete user messages when user is deleted.

:+1:

**Comment by michel2107** [comment]
Ok course i spoke about private messages (not about messages posted on the wall).
