### ISSUE TITLE
Photos limit issue, only 7 displays

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#523]
REF: https://www.opensource-socialnetwork.org/discussion/view/926/great-site-questions-from-a-newbie

"Why does the photo only show 7 when I upload? I have a lot of photos to upload.
Is there a way members can make their own pages?"

**Comment by moneya** [comment]
hmm lee can you explain more about this?

**Comment by lianglee** [comment]
I have not tested but the user said , there are only 10 or 7 photos shows up on photos page. 
I think its due to the limit of get limit, the default value for getting data is 10, we have to remove this limit for photos by add [limit] => false while fetching photos.
