### ISSUE TITLE
Cannote see posts

### ISSUE THREAD

**Issue by superbuc** [opensource-socialnetwork/opensource-socialnetwork#524]
![screenshot 2015-09-10 18 05 29](https://cloud.githubusercontent.com/assets/14220882/9793686/0aa8757a-57e7-11e5-9974-78a7848eeb14.jpg)
I cannot see any post on my www.newhere.eu even if I've already posted them !

No error message, but cannot see anything !
Please help, I recently added your social network software, and I hope I can use it for time (and develop)

**Comment by TheGameHHH** [comment]
which version do you have? which system runs with ossn?

at my ossn will create posts.

**Comment by superbuc** [comment]
Version is 3.0, system is hosting Siteground, with PHP 5.3.29

Thanks
Fabrizio


Il giorno 10/set/2015, alle ore 18:19, TheGameHHH <notifications@github.com> ha scritto:

which version do you have? which system runs with ossn?

at my ossn will create posts.

**Comment by ctlui** [comment]
Don't know if it's the cause but you need minimun php 5.4
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/e9f9294eff672521903f48a7854c89c047c4c87d/installation/classes/OssnInstall.php#L94

https://www.opensource-socialnetwork.org/wiki/view/706/how-to-install-open-source-social-network

**Comment by lianglee** [comment]
You need minimum php 5.4

**Comment by superbuc** [comment]
I’ve updated to php7 and now everything seems to be ok !
How to add google analytics best way ?

Thanks


Il giorno 10/set/2015, alle ore 20:46, Arsalan Shah <notifications@github.com> ha scritto:

You need minimum php 5.4
