### ISSUE TITLE
htaccess.dist remove duplicate contents

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#526]
Hi,

In https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/installation/configs/htaccess.dist#L55-L62 instructions mod_expires & FilesMatch are writing 2 times.
Line 27 to 34 & 55 to 62

Thanks - Eric

**Comment by lianglee** [comment]
Yes there is duplicate code.
