### ISSUE TITLE
Trying to enter administration backend on demo site

### ISSUE THREAD

**Issue by oscaredmu** [opensource-socialnetwork/opensource-socialnetwork#527]
exception 'OssnDatabaseException' with message 'Unknown column 'time_created' in 'field list' SELECT DATE_FORMAT(FROM_UNIXTIME(time_created), '%Y') AS year, DATE_FORMAT(FROM_UNIXTIME(time_created) , '%m') AS month, COUNT(guid) AS total FROM ossn_users WHERE(time_created > 0) GROUP by DATE_FORMAT(FROM_UNIXTIME(time_created) , '%Y%m') ; '

**Comment by lianglee** [comment]
Fixed, sorry demo was based on old version, during restore we didn't updated the database. Now its working.
