### ISSUE TITLE
Add an image resizing for the timeline (enhancement)

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#528]
Hi,

What do you think about an image resizing for the timeline ?

Problem is that now people get nice camera even from phone with big resolution and weight.
So some image can be more than 2mb in the timeline.

Image are at 500px on the timeline but keep original width and height.

For now I manually change resolution to max 1024 px width and max 768 px height to get bigger image for the fancybox component.

Thanks - Eric

**Comment by lianglee** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/classes/OssnFile.php#L217

As in Ossn core we regenerate image upon upload to save some bandwidth,  the default core size for all images is 2048x2048

I'll add hook for it to change.

**Comment by lianglee** [comment]
Hook is available now, but you still have to set default image resolution, if actual image resolution is less then specified resolution then image is saved with actual resolution,  example how to use hook in your component:

    ossn_add_hook('file', 'image:resolution', 'change_size');
    function change_size() {
        return array(
            'width' => 3000,
            'height' => 3000
        );
    }
