### ISSUE TITLE
Image cache on wall post

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#529]
I've found that images on wall aren't cached.
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0

I think it's here: https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnWall/ossn_com.php#L202
I just add:
header('Expires: ' . gmdate('D, d M Y H:i:s \G\M\T', strtotime("+6 months")), true);
header("Pragma: public");
header("Cache-Control: public");
header("Content-Length: $filesize")

Images are cached now but don't know how to and if it need etag.

Thanks - Eric

**Comment by lianglee** [comment]
added
