### ISSUE TITLE
language string missing no:messages

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#530]
Hello,

In https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnMessages/locale/ossn.en.php 
he missing string 'no-messages'  (https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnMessages/locale/ossn.de.php#L18) 
for https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnMessages/plugins/default/messages/pages/messages-none.php#L2

Thanks - Eric

**Comment by lianglee** [comment]
Added
