### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by mali110** [opensource-socialnetwork/opensource-socialnetwork#531]
Hello Guys,

I just installed ossn on my website but i saw a blank page on website or on admin page. can anyone please help.

here is the website link:
http://mb.brandinizer.com/

Thanks

**Comment by TheGameHHH** [comment]
Deactive your cache of OSSN.

**Comment by mali110** [comment]
how to do this?

**Comment by lianglee** [comment]
Make sure your server at least have 1GB ram to run Ossn and make sure all files are uploaded. Try disable and enable cache.

NOTE: Cache makes your website run faster.
