### ISSUE TITLE
dactivate OSSN cashe

### ISSUE THREAD

**Issue by mali110** [opensource-socialnetwork/opensource-socialnetwork#532]
How to deactivate OSSN cache?

**Comment by lianglee** [comment]
By default its deactivated,  it seems your server is slow follow the steps to enable cache:

Login using http://yourwebsite.com/administrator/
Go to http://yourwebsite.com/administrator/cache 
Enable It

**Comment by mali110** [comment]
login page is also showing black. can't login to my website.

http://mb.brandinizer.com/

**Comment by lianglee** [comment]
Where your website is hosted? it seems your server is too slow. Contact your hosting provider.

**Comment by mali110** [comment]
Its hosted on web hosting buzz

**Comment by lianglee** [comment]
You can buy a Ossn based hosting from http://www.a2hosting.com/5926-0-1-139.html or see :https://www.opensource-socialnetwork.org/hosting

**Comment by mali110** [comment]
Thanks Friend
