### ISSUE TITLE
Array error in profile menu

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#534]
I have my OSSN updated with the release of a few minutes ago. I made it on my development domain and my major domain. I had no issues in my development domain, but in my major domain I get an array error at all three menu points. The error says 0.

I also set back the release on the version of yesterday, where are no issues and returned to the current release. The issue is still there.

I use it on XAMPP 5.5.27.

Addition
I also got this error as I made OSSN on my major domain completely new.

**Comment by lianglee** [comment]
Can you attach a picture?

**Comment by TheGameHHH** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/5566418/10073043/6587aa26-62c6-11e5-9151-2c71f5433bac.JPG)

yes

**Comment by lianglee** [comment]
Try to flush cache

**Comment by lianglee** [comment]
or try to download latest branch with latest changes

**Comment by TheGameHHH** [comment]
![unbenannt1](https://cloud.githubusercontent.com/assets/5566418/10073280/01ab844e-62c8-11e5-9efc-c5b5ca4f1366.JPG)

this is from the admin area and i try to flush cache via the database.

**Comment by lianglee** [comment]
I doubt you are using old theme files? try to update theme/yourtheme/plugins/default/menus/ with latest  theme/default/plugins/default/menus/

**Comment by lianglee** [comment]
If you are using ossnblack theme try now i just now pushed new commits

**Comment by lianglee** [comment]
Issue confirmed with ossnblack theme , its has been fixed now.
