### ISSUE TITLE
fix typo in link href javascript

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#536]
Hi,

That's the report from firebug console and get Uncaught SyntaxError: Unexpected token : in Chrome console.
Didn't list all errors but here's the links where i got it:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnNotifications/page/topbar.php#L27
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnNotifications/page/topbar.php#L41
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnNotifications/page/topbar.php#L54
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnGroups/ossn_com.php#L84
...
I thinks I got it everytime H have href="javascript::;"

Thanks - Eric

**Comment by lianglee** [comment]
it should be like javascript::void(0); i think

**Comment by lianglee** [comment]
Fixed
