### ISSUE TITLE
change profile icon urls

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#537]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnPhotos/ossn_com.php#L88
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnProfile/ossn_com.php#L375
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnWall/ossn_com.php#L99
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/components/OssnWall/ossn_com.php#L144

**Comment by moneya** [comment]
@lianglee  can you explain more about this?

**Comment by lianglee** [comment]
Fixed
