### ISSUE TITLE
Message Inbox section - layout error

### ISSUE THREAD

**Issue by David111567** [opensource-socialnetwork/opensource-socialnetwork#542]
The "Inbox" on the left side floods the page and goes on endlessly down the side. It even spills over into the "Copyright" area and the footer menu. 
![scroll](https://cloud.githubusercontent.com/assets/10092107/10121761/821dcb2a-64c9-11e5-9f33-18714f27046a.jpg)

**Comment by lianglee** [comment]
Fixed in v3.6
