### ISSUE TITLE
Installation Help Needed For OSSN

### ISSUE THREAD

**Issue by antoinelbanks** [opensource-socialnetwork/opensource-socialnetwork#547]
Hi.

I'm trying to install your script into http://blackbook.cu.cc, but I'm receiving the following message: "Invalid data directory or directory is not writable."

Now, I know that my directory is writable, because I'm on a Windows server.

Please PM me for the specs if you're able to help me. Thanks.

**Comment by lianglee** [comment]
Did you create a data directory before installing? 

See: https://www.opensource-socialnetwork.org/wiki/view/706/how-to-install-open-source-social-network

## Create a data folder
OSSN needs a special folder to store uploaded files including profile icons and photos. You will need to create this directory.
For security reasons, this folder MUST be stored outside of your document root. If you created it under /www/ or /public_html/, you’re 
doing it wrong. Once this folder has been created, you’ll need to make sure the web server OSSN is running on has permission to write to and create directories in it.
