### ISSUE TITLE
registration email

### ISSUE THREAD

**Issue by AlphabetoPT** [opensource-socialnetwork/opensource-socialnetwork#549]
Hello i recently installed the new version of OSSN but i am not receiving any confirmation email.
Can you please guide me?
Is there any process i need to do after instalation?
owner email: zionpt.mine@gmail.com
Notification email: geral@zionportugal.com

Thanks

**Comment by lianglee** [comment]
Please see: https://www.opensource-socialnetwork.org/wiki/view/891/account-activation-email

**Comment by AlphabetoPT** [comment]
I am at OVH do i have trouble with php mail?

**Comment by lianglee** [comment]
Try to install Exim MTA

**Comment by ctlui** [comment]
Please open a suject in community site as not an issue, will try to help as I test on OVH and it's working well.

Thanks - Eric

**Comment by AlphabetoPT** [comment]
Oh Sorry. 
It was my fault.
I was missing the MTA package. 

Solved since yesterday. Thanks

**Comment by BillPackard** [comment]
Not possible receive email-s. E-mails not in spam folder, but server enabled the PHP send mail. Another site in server better working email send. No error log in OSSN directory. All better but email not send.

**Comment by lianglee** [comment]
@BillPackard , Please see : https://www.opensource-socialnetwork.org/wiki/view/891/account-activation-email

**Comment by BillPackard** [comment]
My server send this PHP send mail from my private script, the server side mail send is ok. But OSSN system absolutely not send any email.

**Comment by BillPackard** [comment]
The problem is Varnish function. Need off Varnish on server! After better
working.

*Csernák Sándor*

2015-11-15 15:04 GMT+00:00 Arsalan Shah <notifications@github.com>:
