### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by AlphabetoPT** [opensource-socialnetwork/opensource-socialnetwork#551]
Hello i installed a favicon.ico at my website root.
Not working,
Later i added some lines at: webroot/themes/default/plugins/default/theme/page/page.php

<link rel="icon" 
      type="image/ico" 
      href="http://net.zionportugal.com/favicon.ico">

Still not working...
Some help please?

**Comment by lianglee** [comment]
Make sure you tried to clear your browser cache and when you open http://net.zionportugal.com/favicon.ico it should show you a icon file.
