### ISSUE TITLE
Cannot create post! Please try again later.

### ISSUE THREAD

**Issue by pachiromver** [opensource-socialnetwork/opensource-socialnetwork#552]
Hello Everyone,
Every time I try to POST it gives me this ERROR (Cannot create post! Please try again later.) can anyone please help me?
![post](https://cloud.githubusercontent.com/assets/14921971/10217106/a1e6ac94-67e2-11e5-8b7e-2e4bcae8b73d.png)

**Comment by sathish4fri** [comment]
without typing text it wont allow you to post the image .

**Comment by pachiromver** [comment]
Thank You! It Worked

**Comment by lianglee** [comment]
We should change error text
