### ISSUE TITLE
ossn message box, user who liked comment

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#554]
popup a list of users who liked a comment (as already implemented with postings)

**Comment by lianglee** [comment]
:+1:

**Comment by lianglee** [comment]
Moving the enhancement for v4.0

**Comment by henrydjunaedi** [comment]
just for note, currently popup doesn't work for likes inside comment

**Comment by lianglee** [comment]
Fixed on #DEV
