### ISSUE TITLE
OssnWall Settings (Homepage Posts)

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#555]
Hi,

When setting to Friends posts only, friends users can see only 1 page on the wall.
It's ok for the admin only.

Thanks - Eric

**Comment by lianglee** [comment]
Seems bug with wall for friends page, i'll look it, maybe it is missing pagination as far as i can think

**Comment by BrennanButler** [comment]
Is this fixed? Seems to not happen to mine.

**Comment by ctlui** [comment]
Issue is only on non admin members.

**Comment by BrennanButler** [comment]
I've tried it on non-admin members and it seems to work fine. Mind if you post a screenshot? @ctlui

**Comment by ctlui** [comment]
Have you set to Friends posts only for OsnnWall in admin panel as write in 1st post ?

**Comment by BrennanButler** [comment]
I have and it seems to work for me.

**Comment by lianglee** [comment]
Can we try to test on fresh test site?
