### ISSUE TITLE
Admin Dashboard users graphic appear in January

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#557]
I'll call this the october issue :)
On this line:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/system/plugins/default/javascripts/dynamic/admin/dashboard/users/users.php#L20
it's delete the 0 for 10 (october) so give 1 and users created this month appear in January.

Thanks - Eric

**Comment by lianglee** [comment]
Ah yes, we have to change that line to something:
       
     if((int)$item->month !== 10){
            $item->month = str_replace(0, '', $item->month);
      }

**Comment by ctlui** [comment]
Thanks Arsalan, test it ok.

**Comment by lianglee** [comment]
Fixed
