### ISSUE TITLE
Problem with group comments showing up via notification link

### ISSUE THREAD

**Issue by David111567** [opensource-socialnetwork/opensource-socialnetwork#559]
When you click on the notification, to see the comment....
It takes you to the post, but there are no comments at all. Just the original post.
![glitch2](https://cloud.githubusercontent.com/assets/10092107/10262231/7f2bfb36-698c-11e5-9108-33b5dc4904b2.jpg)

**Comment by lianglee** [comment]
Thanks for report,

For developers only:
Non-tested fix: OssnWall/plugins/default/wall/templates/wall/group/item.php

      if(!isset($params['ismember'])){
	     $group = ossn_get_group_by_guid($params['post']->owner_guid);
	      if ($group->isMember(NULL, ossn_loggedin_user()->guid)) {
		   $params['ismember'] = 1;
	      }
       }

**Comment by ctlui** [comment]
Just test and it works

**Comment by David111567** [comment]
Where do I insert this code.. like... what line?

**Comment by lianglee** [comment]
Fixed
