### ISSUE TITLE
user chart's height growing endlessly when browser window size is changing

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#561]
whenever I change the width or height of my browser (while watching the admin panel) the chart's height is growing bigger and bigger.
a working fix for me is surrounding the chart's canvas with an additional div with a fixed height:
![userchart](https://cloud.githubusercontent.com/assets/9904364/10264307/b761aca0-6a07-11e5-87db-31f9cb5cb3af.png)

see --> http://stackoverflow.com/questions/28162810/why-is-chart-js-canvas-not-respecting-the-padding-of-the-container-element

**Comment by lianglee** [comment]
I am not sure if we use fixed height because we don't know how long this graph will be in height. I am worried about numbers on left side.

**Comment by githubertus** [comment]
Sure, the number of users will increase, but this can't mean a linear growth of the y-axis. Otherwise we'll end in some meters of scrolling with a large community. ;)
I think, all we need is a reasonable scaling factor, computed from the total number of members and then change the legend accordingly (like x 10, x 100, and so on)

**Comment by lianglee** [comment]
Any solution ?

**Comment by lianglee** [comment]
Fixed on div, by Eric
