### ISSUE TITLE
I can't login by administrator mode

### ISSUE THREAD

**Issue by sajalbdt** [opensource-socialnetwork/opensource-socialnetwork#562]
Dear support team,
                              Some days ago i was migrated my site on different server but now i can't login.
I already checked all directory or file but no problems founded there. My ossn version is 3.3.

So in that case i expected a suggestion for this problems. my site is insideblog.net 

Thanks/
Sajal Mondal

**Comment by lianglee** [comment]
Please provide following details: https://www.opensource-socialnetwork.org/wiki/view/705/how-to-report-a-issue-on-github

**Comment by lianglee** [comment]
Closing as no response.
