### ISSUE TITLE
hardcoded paths in theme's css

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#563]
not really a bug, but since it's not very likely that someone is creating his own theme from scratch, most of the time theme development will happen like: making a copy of default, renaming it, applying changes. 

problem: there are a lot of instances still pointing to the 'default' theme directory, and that's why it would be nice to have a function named ossn_theme_url() instead of building the path like ossn_site_url() / themes/HARDCODED_NAME/....

**Comment by lianglee** [comment]
I am fully agree

**Comment by moneya** [comment]
nice idea.

**Comment by lianglee** [comment]
Added
