### ISSUE TITLE
wall tag a friend , GUID issue

### ISSUE THREAD

**Issue by henrydjunaedi** [opensource-socialnetwork/opensource-socialnetwork#566]
When tagging a friend, and the friend's name is not valid (may happen when user did not select from the suggested list and submit post), in database ossn_object.description will be written as, for example, {"post":"test","friend":"john"}
while the correct one is, for example,
{"post":"test","friend":"3"}
This somehow leads to a broken HTML when viewing the wall.home

![image](https://cloud.githubusercontent.com/assets/15110928/10462487/2d22ce52-7209-11e5-8d2a-749b54b21d1d.png)

**Comment by henrydjunaedi** [comment]
thanks man. I did come with the same solution, the broken HTML is fixed, but now it can't tag a friend at all. Can you take another look?

**Comment by lianglee** [comment]
It has been fixed now, check latest commit.
