### ISSUE TITLE
Missing back button to photos

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#570]
When you are in covers, profil or others albums he miss a button to back to photos.

Thanks - Eric

**Comment by githubertus** [comment]
Oh yeah, that old one (#126)
Closed for some reason and not re-implemented. :)
(Once we had a backlink there, but pointing to a wrong destination)

**Comment by lianglee** [comment]
@githubertus  you are right, i didn't implemented this from long ago. I'll look into this , its nice to have a back button.

**Comment by lianglee** [comment]
Fixed
