### ISSUE TITLE
missing lang strings in ossn.de.php

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#572]
I've seen in ossn.en.php are 2 more language strings as in ossn.de.php.

I've found these 2 strings in ossn.en.php and searched where these strings will be used.
'admin:menu' => 'Admin Panel',
'feedback' => 'Send feedback',

I found no use and would like to ask what these strings should happen now.

**Comment by lianglee** [comment]
I didn't remember when i have added feedback string. Maybe we merged some wrong pull request long ago.

**Comment by lianglee** [comment]
Removed
