### ISSUE TITLE
Issue with social network

### ISSUE THREAD

**Issue by carlbee1** [opensource-socialnetwork/opensource-socialnetwork#573]
Hi can you help im having issues with your social network firstly i cant make posts cause i get a error and also when i refresh page it goes to a error page then when i try sign in it dont recognise my login details even though they are correct can you please look into this my url is youdle.mega-hosts.co.uk my user is admin and password is password please can you fix all errors thanks !

**Comment by lianglee** [comment]
It seems you upgraded your website to v3.7? Please make sure you update all files, try to download latest v3.7 release and replace your existing files with latest file.

Also it seems your theme files are old. Please upgrade your all files.
