### ISSUE TITLE
Issue with social network

### ISSUE THREAD

**Issue by carlbee1** [opensource-socialnetwork/opensource-socialnetwork#574]
Hi i made a post here yesterday and now i dont see it ???

**Comment by TheGameHHH** [comment]
Your issue has been closed. OSSN has for your Issue an forum. https://www.opensource-socialnetwork.org/community

**Comment by lianglee** [comment]
Please see: https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/573
We already posted reply. Please use our community website for discussions.
