### ISSUE TITLE
new feature addon

### ISSUE THREAD

**Issue by moneya** [opensource-socialnetwork/opensource-socialnetwork#58]
ability for users to hide items from newsfeed
adding cover photo for groups
using loadmore for pagination
auto resizing uploaded images
auto resizing uploaded images for coverphoto
auto resizing uploaded images in the newsfeed section
using html pop up image viewer

**Comment by lianglee** [comment]
As we are no longer accept feature request on github. You can only post bugs here, use community site for posting feature requests.
