### ISSUE TITLE
Images wont show up

### ISSUE THREAD

**Issue by helliongames** [opensource-socialnetwork/opensource-socialnetwork#581]
I am having an issue with a fresh install, no images will show up when I change my cover photo or profile picture
![image](https://cloud.githubusercontent.com/assets/7268695/10736185/95285be6-7bd9-11e5-8c34-03cd3187c165.png)

**Comment by sathish4fri** [comment]
check your file permission for  data folder .

**Comment by helliongames** [comment]
No folder called data but I assume you mean the root directory and its set to 777

**Comment by helliongames** [comment]
Figured it out.. it was OpenBase in Sentora
