### ISSUE TITLE
Wall post not showing external direct image link as an image

### ISSUE THREAD

**Issue by henrydjunaedi** [opensource-socialnetwork/opensource-socialnetwork#588]
Wall post not showing external direct image link as an image, it's shown as text.
Please advise

**Comment by lianglee** [comment]
Please note that Ossn is not same as facebook

**Comment by ChartTec** [comment]
But a link to youtube shows the embedded video? It would be nice to show the picture instead of the text-link... Perhaps in the next version?

**Comment by ctlui** [comment]
With youtube you can get https url, all external will not get ssl, so it'll add a vulnerabilty.
