### ISSUE TITLE
poster image display problem with profile pics < 32 x 32

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#592]
![poster-image-probs](https://cloud.githubusercontent.com/assets/9904364/10888896/f0f674b6-818e-11e5-80c6-0c22e6e16d0d.png)

**Comment by lianglee** [comment]
agree

**Comment by lianglee** [comment]
can you send pull request?

**Comment by lianglee** [comment]
Merged Pull Requests
