### ISSUE TITLE
ossnlikes 3 error

### ISSUE THREAD

**Issue by auggy91** [opensource-socialnetwork/opensource-socialnetwork#597]
Fatal error: Call to a member function iconURL() on a non-object in C:\Program Files (x86)\Ampps\www\components\OssnLikes\ossn_com.php on line 156

**Comment by lianglee** [comment]
Please follow rules to report issue https://github.com/opensource-socialnetwork/opensource-socialnetwork/wiki/How-to-report-a-issue-on-github

Did you deleted users manually from database?  please provide necessary details mentioned in above URL.

**Comment by lianglee** [comment]
Closing as no response

**Comment by githubertus** [comment]
Checked it yesterday: User A liked several items of User B. Then I removed User A (regular way from the Admin dashboard): No problems.
