### ISSUE TITLE
Deleting a Comment cut´s Thread

### ISSUE THREAD

**Issue by ChartTec** [opensource-socialnetwork/opensource-socialnetwork#601]
When someone deletes his comment, the whole thread is cut and the following comments are no longer visible on the wall. In the personal timeline the deleted comment and all following comments are visible. Wouldn´t it be better, that the deleted comment is really deleted but the following comments can be seen on the wall and in the personal timeline?

**Comment by githubertus** [comment]
Please read https://www.opensource-socialnetwork.org/wiki/view/705/how-to-report-a-issue-on-github
and provide more information

**Comment by ChartTec** [comment]
Ossn version				3.8 	
    PHP version				5.6
    Description			When someone deletes his comment, the whole thread ends there and the following comments are no longer visible on the wall. Sometimes, the deleted comment and all following comments are visible in the personal timeline. But later, they are deleted in the SQL-Database.
    Error Log				---
    Issue screenshots			---
    Cache enabled/disabled		enabled
    Apache version (optional)		---
    MySQL version (if possible)		MySQL5.1
    Your website link (if possible)		trading-chatroom.de

I can´t provide a screenshot but that´s what happend: the comments vanish. They are deleted in the SQL-Database. First I thougt they vanish when someone deletes his comment. Meanwhile I am not sure if they vanish without action from a user...

**Comment by lianglee** [comment]
What i understand is , when you delete a comment it also deletes a thread at same time? is it what you mean?

**Comment by ChartTec** [comment]
Not the whole thread is deletetd but the comments "below" the deleted comment. And they are not deleted at once but some times later. I didn´t find out why and when...

**Comment by lianglee** [comment]
@githubertus and @ctlui can you check this please

**Comment by ChartTec** [comment]
Where did OSSN store the comments (MYSQL: which table? I don´t find them there) 
When a user deletes his comment, is the comment marked/flagged as "deleted" and still stored in the database or is it really deleted in the database?

**Comment by lianglee** [comment]
@ChartTec, its deleted from database, Ossn database is dynamic and comments are not stored only in one table. Data is stored in parts.

We'll check the issue you are referring and will notify you asap.

**Comment by ctlui** [comment]
Make some testing but can't get this issue.
Can you give us your parameters and how to reproduce the issue ?
What about your hosting 1&1 ?
Apache version ? MySQL 5.1 is 2 years old now.

**Comment by ChartTec** [comment]
I have copied the data to a new MySQL5.5 - Database. I will test it with this one.
1&1 one is one of the big player here in germany. Until now, I haven´t any problems with them.
Apache: I have to ask the support team. phpinfo() only returns "Apache" (it´s not "my" server).
Merci beaucoup pour votre aide et à tout de suite...

**Comment by githubertus** [comment]
I have created 2 test postings (user: honey) at trading-chatroom.de
So far, everything looks okay. I'll check daily for disappearing comments.
If possible, please log any action, especially deleting postings or comments from now on

**Comment by ChartTec** [comment]
Is it possible, that the trouble starts, wenn User #1 tries to delete a comment from User #2?
I tried something like this: comment #1 from User #1, comment #2 from User #2, comment #3 from User #1, User #2 tries to delete comment #3 (not his own), system deletes comment #2 (or somethin else)?

**Comment by githubertus** [comment]
Yeah, this is pointing to the right direction. I just tested this:
Starting with a post of Admin Instrator, we have 4 comments:
First screenshot = Admin Istrator is logged in
![admin-view](https://cloud.githubusercontent.com/assets/9904364/11088879/e11eb8f4-8865-11e5-8247-af607dab8643.png)
Next screenshot = Micha Zet is logged in
![micha-view](https://cloud.githubusercontent.com/assets/9904364/11088931/3ec0cbfa-8866-11e5-87a4-056c880491bc.png)

1.) We have permission bug:
Micha Zet (a normal user) is able to delete the comment No. 26, owned by Admin Istrator
2.) But: If we have a closer look, this delete action wouldn't delete comment No. 26, it deletes comment No. 23, that's Micha Zet's latest own comment "4"

**Comment by ctlui** [comment]
Ok I've reproduce. On image below I'm user 2 account from a post make from user 1 and try deleting the last comments from user 1 and it'll be delete last from user 2.
It's normal as user can't delete comments from other users.
But the arrow to delete this comment (comment 3 from User 1) musn't be here.

![delete_comments](https://cloud.githubusercontent.com/assets/11196998/11089026/c9fc27d2-8866-11e5-9c62-5111a27d8f24.jpg)

**Comment by lianglee** [comment]
Fixed

**Comment by lianglee** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/91375e7a5f270555b42d1ee1d4e702ce23383b13
