### ISSUE TITLE
Profile cover is not updating

### ISSUE THREAD

**Issue by amanwas** [opensource-socialnetwork/opensource-socialnetwork#602]
I upload a profile cover image but then I try to change it.. When I upload new cover image it shows properly first time but when I click another link (any link) it comes back to previous cover photo..

Please check

**Comment by lianglee** [comment]
Its seems browser cache issue , did you tried with latest version and fresh installation?

**Comment by amanwas** [comment]
Yes i fixed buy clearing my cache.. But i think there is still some issue
with that feature.. I will try again n let u know..

Btw many thanks to this great piece of software.. Why dont you sell it like
other companies do?

**Comment by lianglee** [comment]
I am closing this ticket, please reopen it once you tested again.

We designed it as open source,  and it will be free for ever, we are not going to sell it. It will be free.

**Comment by lianglee** [comment]
A preview for v4.0 (future) version.

![message-view](https://cloud.githubusercontent.com/assets/805066/11021555/ab6b0a10-8666-11e5-8d73-365486bc81ac.png)

**Comment by amanwas** [comment]
Good

**Comment by amanwas** [comment]
If i post a picture i have to add some text also.. This is not good.. How
can i fix that?

**Comment by lianglee** [comment]
@amanwas  you can change the error text, we are going to fix this in v4.0. To change message see: 

https://www.opensource-socialnetwork.org/discussion/view/1134/i-need-to-translate-the-photo-error

Please use community site for discussion, this website is for posting only bugs.

**Comment by amanwas** [comment]
Hello..

My hosting is reporting some malicious activity after I host your software
on it.. Please see this..



*Your account was scanned with anti-malware script and it detected some
issues requiring your attention. Find below the scan log. Please check the
log and proceed accordingly, or you can contact us and we can provide you
guidence on fixing this issue.*

------------------------------

Nov  9 21:09:22 srv30 cxs[287638]:
['/home/practic2/public_html/ossn/vendors/tinymce/plugins/jbimages/ci/system/core/CodeIgniter.php']
- Script version check [OLD] [CodeIgniter v2.1.3 < v3.0.1]


It is CodeIgniter.php file which is malicious.. Can you please tell me
details why is it so? my site is working fine btw..


Thanks

**Comment by lianglee** [comment]
We don't have CodeIgniter.php in Ossn framework,  Make sure your cache is enabled in Ossn, if you are on shared hosting you should move to vps or find better host provider.

**Comment by lianglee** [comment]
CodeIgniter.php is part of tinymce 3rd party component, You can find it in /vendors/tinymce/plugins/jbimages/

**Comment by amanwas** [comment]
Hello..

Can you please provide me link to documentation for SEO of Ossn?

I installed it at practicalislam.com and I want to add some keywords on
homepage and other pages.. also need to add meta information..

How can I do that?


Also if you can guide me how can I remove the sub-folder name in my url
that would be great.. It redirects to practicalislam.com/ossn

Thanks

**Comment by lianglee** [comment]
If you wanted to remove sub-folder, you have to move installation.

First Disable Cache
Move your files to root
Edit configuration files in configuration directory.

We don't provide any SEO service.

**Comment by sathish4fri** [comment]
https://www.opensource-socialnetwork.org/component/view/462/metatags
you can add your metatags using this plugin it will add it in all the pages .

**Comment by amanwas** [comment]
Ok thanks..

**Comment by amanwas** [comment]
I installed this plugin but I don't see anything new in admin panel?

Where can I set the keywords ?

**Comment by sathish4fri** [comment]
in the configure -> metatags 

in the keywords  input box type all the keywords .
 and inspect and check it and you can see the keywords

**Comment by amanwas** [comment]
Oh sorry.. I found it after enabling the plugin in the list..

Ok I will check and write back to you..

**Comment by amanwas** [comment]
I put keywords and other info but when I view source I don't see any of
these keywords or description..

Anyway I will check again .. Thanks for your wonderful support so far..

If you can please tell what to write in this field.. that' would be nice..

Robots is used by search engine to Crawling or Crawl your website pages
Example: index,follow,noindex,nofollow,none,noarchive.

Thanks

**Comment by sathish4fri** [comment]
if its not working report it on component i will verify with that
