### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by goldkey0070** [opensource-socialnetwork/opensource-socialnetwork#608]
As a admin i tried to make another person admin and when i try to save it says this address is already taken. i just went into the database and changed manual . just wanted to let you know

**Comment by githubertus** [comment]
Sure, because it makes sense to have unique email addresses. Can't see the point.

**Comment by lianglee** [comment]
Closing as no response.

**Comment by goldkey0070** [comment]
no, i used different emails...
