### ISSUE TITLE
orphan notification after posting/comment has been deleted

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#609]
Ossn 3.8:
micha makes a posting
honey comments on this posting
micha receives a notification
![screenshot_1](https://cloud.githubusercontent.com/assets/9904364/11184627/188fe5e4-8c79-11e5-8a0f-5d285d33b6b1.png)
-----------------
micha deletes the posting
but notification is still in place (clicking gives 404 page)

-----------------
![screenshot_2](https://cloud.githubusercontent.com/assets/9904364/11184765/a743f9b0-8c79-11e5-91e9-6ca99a6bbc00.png)

-----------------
Actually there seems to be no code to delete the notifcation when a posting or comment has been deleted.

**Comment by lianglee** [comment]
Agree to delete notifications once subject is deleted.

**Comment by lianglee** [comment]
We'll need to write new method called deleteNotfication(); or similar i'll look into it
