### ISSUE TITLE
pictures not showing, different php error

### ISSUE THREAD

**Issue by squire-bob** [opensource-socialnetwork/opensource-socialnetwork#613]
PHP WARNING: 2015-12-09 19:49:39 (MST): "filesize(): stat failed for /var/uploaderuser/1/profile/photo/topbar_115b9d2705ceceb6a60be165406dcd07.jpg" in file /var/www/html/ossn/components/OssnProfile/ossn_com.php (line 295)

recently installed & everything worked great except for the pictures.  My data directory had been accepted so I wasn't sure what the issue was.  I check the error log and the above error is what I saw repeatedly.  It looks to me like it's missing a backslash between 'uploader' (the directory I created) & 'user'.

I tried looking at ways to change the data directory from within but i'm not seeing it.  I'm not an expert so there's a good chance I missed it.  I was hoping that maybe I could add a tailing backslash to what I originally entered to fix it.

Thank you for taking the time to help me.

**Comment by sathish4fri** [comment]
Check with the permission of the folder and give rights to it .

**Comment by squire-bob** [comment]
The directory I created has the correct permissions.  If you notice the error from my post says it's trying to pull from "/var/uploaderuser" which doesn't exist.  The correct directory is "/var/uploader".  Other than the initial setup I don't see a way to change or update that directory.

**Comment by sathish4fri** [comment]
can you please tell what content you have in ossn.config.site.php IN configuration folder of your ossn. may be data dir path you entered missing /

**Comment by squire-bob** [comment]
$Ossn->url = 'http://10.0.0.6/';
$Ossn->userdata = '/var/uploader';

AH thank you!  this is what I was looking for.   I changed it & NOW i'm getting the permission errors.  that's easily fixed though.

thank you for your help.
