### ISSUE TITLE
Admin Page Error

### ISSUE THREAD

**Issue by ljfreelancer88** [opensource-socialnetwork/opensource-socialnetwork#615]
Ossn version: 3.9
PHP version: 5.6
Error message: Every time I click a menu in Admin page, it always gives me 404 and i need to log-in again.
Issue screenshots (I can't able to provide because it always logged me out.)
Cache enabled/disabled: Disabled(Fresh Installed)
Apache version (optional)
MySQL version: MariaDb 10

**Comment by ctlui** [comment]
What about your browser & cookies ?
Try disable your extensions.
Just tell you that as I get similar thing sometimes ago.

**Comment by ljfreelancer88** [comment]
I used Private Browsing in Firefox, Incognito in Chrome and Opera but still i got the same error.

**Comment by lianglee** [comment]
Ossn didn't supported MariaDB. Make sure your sessions are properly created.

**Comment by ljfreelancer88** [comment]
Oh see, I think Ossn team will consider MariaDb in their next major update. Thanks anyway.
