### ISSUE TITLE
small bug with menu 

### ISSUE THREAD

**Issue by sathish4fri** [opensource-socialnetwork/opensource-socialnetwork#617]
Need to add this in core . tab is not closing so user wont able to access the menus 
$('.ossn-topbar-dropdown-menu').click(function(){
			$('.ossn-notifications-box').hide();
});

![screenshot from 2015-12-17 11 04 06](https://cloud.githubusercontent.com/assets/6101473/11863315/eb8e5c58-a4b8-11e5-8c2a-d46eb19eedf4.png)

**Comment by lianglee** [comment]
When you click on notification icon first and then click on dropdown , same situation happens.

Click On friends icon or messages or notifications and then then click on dropdown icon. It will appear same,

The fix only works when notification box opened first.

**Comment by sathish4fri** [comment]
the code which i gave will work . or you have to re modify as you wish bro
