### ISSUE TITLE
Loosing typed in data when clicking Terms and Conditions link

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#620]
![register](https://cloud.githubusercontent.com/assets/9904364/11871996/4e1a30e4-a4d3-11e5-937b-0f4e6ebc616e.png)

**Comment by ctlui** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/system/plugins/default/forms/signup.php#L45
```<a target="_blank" href="<?php echo ossn_site_url('site/terms'); ?>"><?php echo ossn_print('site:terms'); ?></a>```

should work
