### ISSUE TITLE
Notification window display issues on small devices

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#621]
![messages-window](https://cloud.githubusercontent.com/assets/9904364/11872859/ea5212de-a4d7-11e5-8e82-226c109e73fb.png)
(width: 463)

**Comment by ctlui** [comment]
What's viewport ? 
test @ http://www.mydevice.io/
On my smartphone get 360px and display is correct even if on chrome desktop it's like your photo

**Comment by githubertus** [comment]
Sorry, yes: no issue. a Firefox display problem.
Chrome in 'device emulation mode' does the job correctly I just found out.
