### ISSUE TITLE
'Reposition/Change Cover' buttons on top of notification

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#622]
a funny effect, yes. :) 
perhaps giving the notification window a higher z-index will do
![buttons on top](https://cloud.githubusercontent.com/assets/9904364/11874665/322f69ea-a4e1-11e5-94eb-9513f5d958dc.png)

**Comment by sathish4fri** [comment]
yes i agree z-index must be little higher

**Comment by lianglee** [comment]
Fixed, @sathish4fri  z-index won't work
