### ISSUE TITLE
image src is missing 

### ISSUE THREAD

**Issue by sathish4fri** [opensource-socialnetwork/opensource-socialnetwork#623]
image src is missing when update the profile pic and if you see in newsfeed image src is missing 
![image](https://cloud.githubusercontent.com/assets/6101473/11875215/a773ed0c-a509-11e5-9dd1-50d036c6a0e6.png)

**Comment by sathish4fri** [comment]
same error present for profile cover changes also

**Comment by githubertus** [comment]
has been fixed alread by Arsalan this morning. Get latest snapshot.
