### ISSUE TITLE
pictures in single view are drifting rightwards out of place

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#629]
reason: fixed width of 'ossn-photo-viewer class' - should be 100% instead

![picture right drift](https://cloud.githubusercontent.com/assets/9904364/11894468/ba7487e0-a577-11e5-9c01-0f3cce59de70.png)

**Comment by lianglee** [comment]
.ossn-photo-viewer must be 100% width , hmm maybe i left fixed width from 3.x code

**Comment by githubertus** [comment]
images still overlapping,
i think, '.image-block img' also needs width:100%

**Comment by lianglee** [comment]
Max width 700px, is find for large screen on phone and tablets the img width is 100% now
