### ISSUE TITLE
selecting a CLOSED group I'm neither member nor owner of gives Warning

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#632]
opening a group page like http://MYSITE/group/34 gives:

"Argument 1 passed to ossn_wall_view_template() must be of the type array, boolean given, called in /var/www/ossn-4.v3/components/OssnWall/plugins/default/wall/group.php on line 32 and defined" in file /var/www/ossn-4.v3/components/OssnWall/ossn_com.php (line 383)

the same happens when requesting for membership of a CLOSED group.
no more warnings, when membership is approved

PUBLIC groups are ok.

**Comment by lianglee** [comment]
This has been fixed already, re-open if it exists : selecting a CLOSED group I'm neither member nor owner of gives Warning #632
