### ISSUE TITLE
 My (admin) profile page is distorted.

### ISSUE THREAD

**Issue by Ramzu** [opensource-socialnetwork/opensource-socialnetwork#633]
Hi. I am sure i did something wrong as my profile page is now distorted though it was working fine before i started making some adjustments. I am using version 2.3. Please inform me of how to correct it. Thanks a lot

**Comment by lianglee** [comment]
Try to copy a OssnProfile from 2.3 package and replace your current OssnProfile directory to new one.

If page is while blank page, go to admin and enable error-reporting and then see what error actually is.

**Comment by Ramzu** [comment]
@lianglee Thanks a lot bro. Trying now

**Comment by Ramzu** [comment]
where might i find OssnProfile?

**Comment by lianglee** [comment]
You can find directory in components/

**Comment by Ramzu** [comment]
yes sir. I see it. thanks

**Comment by Ramzu** [comment]
still the same. looks like this:
![printscreen](https://cloud.githubusercontent.com/assets/14142470/11899225/8feadc38-a56b-11e5-9b8e-d7409253edd4.png)

**Comment by lianglee** [comment]
Please enable the Display Errors in admin panel. Download the source of page and share it here.

**Comment by Ramzu** [comment]
ok

**Comment by Ramzu** [comment]
[source.pdf](https://github.com/opensource-socialnetwork/opensource-socialnetwork/files/66727/source.pdf)

**Comment by lianglee** [comment]
Please enable the errors from basic settings in admin panel and then visit the page and send us error_log file

**Comment by Ramzu** [comment]
are you talking about the my OSSN site admin panel?

**Comment by lianglee** [comment]
Yes, go to site admin panel and enable logs from basic settings.

**Comment by Ramzu** [comment]
[source.pdf](https://github.com/opensource-socialnetwork/opensource-socialnetwork/files/66739/source.pdf)
[view-source_www.nationtime.org_u_Ramzu_ref=ossntb - 1.zip](https://github.com/opensource-socialnetwork/opensource-socialnetwork/files/66740/view-source_www.nationtime.org_u_Ramzu_ref.ossntb.-.1.zip)

**Comment by Ramzu** [comment]
everyone else's profile is fine. its just mine with this problem

**Comment by lianglee** [comment]
Just saw the code i have no idea why its not working, do you have some thing in error_log file of Ossn ?

**Comment by Ramzu** [comment]
where can i find that or do you mean the log for the site in my c-panel?

**Comment by lianglee** [comment]
You can find log in public_html/error_log  Make sure your site display error is 'ON' in your ossn admin basic settings.

**Comment by Ramzu** [comment]
ok going now

**Comment by Ramzu** [comment]
[error.pdf](https://github.com/opensource-socialnetwork/opensource-socialnetwork/files/66836/error.pdf)

**Comment by Ramzu** [comment]
or can i just delete the profile? i tried on a test site and the whole website messed up

**Comment by lianglee** [comment]
From error log i came to conclusion that you are missing files, the file system/start.php didn't found which is base of Ossn.

**Comment by Ramzu** [comment]
ok. i was trying some things while trying to make the site go fast. i have the system/start.php there but i will reinstalll

**Comment by Ramzu** [comment]
could i just delete the profile without causing any problems?

**Comment by lianglee** [comment]
You can create new admin profile and then delete old profile. If issue still exists then you should re-install it.

**Comment by Ramzu** [comment]
ok. i will do that. thanks a lot for taking the time. peace
