### ISSUE TITLE
"Unfriend" message not quite okay

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#639]
Using the same action for denying a friend request and ending a friendship leads to a not so meaningful message when unfriending someone. Perhaps we should add a different action with its own message some time in the future...

**Comment by lianglee** [comment]
There already have two actions. friend/add friend/remove

Not sure which action you are referring, on profile page , the friend/unfriend have different action.

**Comment by githubertus** [comment]
I'm referring to friend/remove. It's used for
- denying a new friend request (here the message is alright)
- unfriending someone who is already a friend of yours 
here the message should be something like "friendship terminated"

**Comment by lianglee** [comment]
Can you send pull request? i'll merge it

**Comment by githubertus** [comment]
I had a closer look, and this is more difficult than at first sight. Because currently Ossn makes no difference between a friend-request which is still pending and a confirmed friendship. In both cases the the same 'Unfriend' button is shown. Thus, as long as the button doesn't reflect the the real state of the relation to the other member (request still pending or confirmed friend), we don't know which action (cancel or terminate) to call.
