### ISSUE TITLE
comment field overlapping user icon on viewport < 1200px

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#640]
![commentfieldoverlapping](https://cloud.githubusercontent.com/assets/9904364/11913290/73e84440-a65f-11e5-82d7-66301a6db2e4.png)

**Comment by lianglee** [comment]
No idea about < 1200, i have tested with all available options in firefox and chrome (view-port emulator) 
![fafasfasf](https://cloud.githubusercontent.com/assets/805066/11913553/539d52fa-a689-11e5-94ef-b91115daae62.jpg)

**Comment by githubertus** [comment]
I've tested again in chrome emulator: the problem range is > 991 < 1200
Browsers: MS Edge, Firefox, Chrome on Win10 (same result)

**Comment by githubertus** [comment]
might be a Bootstrap issue, just found on
http://www.sitepoint.com/responsive-web-design-tips-bootstrap-css/
![bootstrapissue](https://cloud.githubusercontent.com/assets/9904364/11913867/946a964c-a672-11e5-9aa4-0c73739c36cb.png)

**Comment by githubertus** [comment]
just saw that:
.comments-item .col-md-11 {
    padding-left: 0;
}
which is obviously not good for that range between 992 and 1199
6px looks better

**Comment by lianglee** [comment]
Test #642, #644, #640 and repoen if not works
