### ISSUE TITLE
old style icons on search result type

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#643]
And: Shouldn't the member icons be rounded on this page, too?

![old-style icons in search results](https://cloud.githubusercontent.com/assets/9904364/11913423/99c797de-a663-11e5-8932-ec239a6b84a3.png)

**Comment by lianglee** [comment]
We'll may completely remove support for facebook theme in v5 so in v5 we'll replace these static icons.

**Comment by ctlui** [comment]
May be find a way to change it in GoBlue.
All changes are made in the theme:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/menus/search.php#L22
Change:
```<div class='text'>{$text}</div>```
to:
```<div class='{$menu}'>{$text}</div>```
to get a different classes names for each text as that we can put font-awesome before.

In css default:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L1152
delete:
```.ossn-menu-search li a img```

https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L1156
Change it to:
```display: none;```

Add somewhere in the css:
```.search-users:before {```
```    font-family: FontAwesome;```
```    content: "\f007";```
```    display: absolute;```
```    padding-right: 10px;	```
```    vertical-align: middle;```
```	float: left;
}```

```.search-groups:before {```
```    font-family: FontAwesome;```
```    content: "\f0c0";```
```    display: absolute;```
```    padding-right: 10px;	```
```    vertical-align: middle;```
```	float: left;
}```

Et voilà :)

**Comment by lianglee** [comment]
@ctlui, i totally forgot about font-awesome injection. That's cool i'll change it
