### ISSUE TITLE
latest chat message almost completely hidden

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#648]
sorry, forgot to enable my chat for long time ...
as you can see, latest message is unreadable, control buttons are displaced

fullscreen 1366x768
Firefox, Chrome and Edge on Win10

![chat](https://cloud.githubusercontent.com/assets/9904364/11919033/8efe8e04-a747-11e5-81ec-cabc626fa401.png)

**Comment by lianglee** [comment]
Its due to long-name check it now with latest ref commit.
