### ISSUE TITLE
current chat emoticons have no transparency

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#649]
which looks a little ugly with new colored speech bubbles
so, i have added transparency to 2 emoticons as test. (see screenshot)
Which one do you like more:
old style = using 14x14 emoticons scaled up to 16x16 (which give a little more blur)
new style = putting 14x14 emoticon in tranparent 16x16 container (a little sharper but smaller)

![chatemoticons](https://cloud.githubusercontent.com/assets/9904364/11920641/a0e0c636-a775-11e5-8d85-332a27e2aacd.PNG)

**Comment by lianglee** [comment]
putting 14x14 emoticon in tranparent 16x16 container <= this one looks much better.

**Comment by githubertus** [comment]
My opinion, too. So I'll provide the complete set of new transparent emoticons today.
