### ISSUE TITLE
chat: annoying procedure on pressing just [Enter] without any input

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#651]
To be forced to do a complete page reload just because some input is missing doesn't feel really comfortable.

Isn't it possible to either
- accept a pure linefeed
- or silently reject a submit like that (no popup / no reload) ?

**Comment by lianglee** [comment]
where? comments?

**Comment by githubertus** [comment]
Chat:

![schief2](https://cloud.githubusercontent.com/assets/9904364/11937143/baaf2650-a812-11e5-9a41-8b45326ba3ab.png)

![schief1](https://cloud.githubusercontent.com/assets/9904364/11937152/c5b629e0-a812-11e5-9c85-8c9faec5bd70.png)

**Comment by lianglee** [comment]
Sounds bug, we have to add code in send message before send function like (just idea, will check it tomorrow):

     Ossn.ChatSendForm = function($user) {
        Ossn.ajaxRequest({
          url: Ossn.site_url + "action/ossnchat/send",
          form: '#ossn-chat-send-' + $user,

        beforeSend: function(request) {
            if($('#ossn-chat-send-' + $user).find("input[type='text']").val() == ''){
                 request.abort();
            } 
            $('#ftab-i' + $user).find('.ossn-chat-message-sending').show();
        },
        callback: function(callback) {
            if (callback['type'] == 1) {
                $('#ftab-i' + $user).find('.ossn-chat-message-sending').hide();
                $('#ftab-i' + $user).find('.data').append(callback['message']);
                $('#ftab-i' + $user).find('input[name="message"]').val('');
                Ossn.ChatScrollMove($user);
            }
        }
      });
    };
