### ISSUE TITLE
Chat: minutes in chat timestamps appear to be a constant (=12) / no update

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#653]
Talking about the time format HH:MM PM

HH is correctly updated
MM is a constant (=12) anytime

**Comment by lianglee** [comment]
Ah yes those are constant , it will require a complex update of entire OssnChat application. It only updated when you refresh page. Other hack is using JavaScript , just guessing.

**Comment by githubertus** [comment]
No, something really funny, will make a pull request in a minute ...

**Comment by lianglee** [comment]
ah so 'm' mean months lol
