### ISSUE TITLE
double height header with longer sitenames

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#655]
I've just updated my sitename from b2 to brc to reflect the current version I'm running, and I was surprised to see a new line appearing. Opinions may vary how long an avarage sitename should be - but I won't consider this length to be that extreme. That's why I think it's worth a thought on how to allocate a little more space by
- removing bold
- using a smaller fontsize
- no auto capitalization

I don't like the latter one anyway. If people really WANT capital letters, they may enter them manually. (Same goes for the footer)

![doubleheightheader](https://cloud.githubusercontent.com/assets/9904364/11941960/813b1bc4-a833-11e5-8984-f05bf583ac11.png)

**Comment by ctlui** [comment]
Try on
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/theme/page/elements/topbar.php
To change col:
md-4 -> md-2
md-4 -> md-7
md-4 -> md-3

**Comment by githubertus** [comment]
Yep, good solution. Looks much better now, no more newline
