### ISSUE TITLE
addtional space under group header with viewport 481 to 992

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#656]
![addbottom](https://cloud.githubusercontent.com/assets/9904364/11944183/85940404-a844-11e5-9663-32b4cf1e021b.png)

**Comment by ctlui** [comment]
Here:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L1938

**Comment by lianglee** [comment]
What should be height under view port 481 to 992 ?

**Comment by ctlui** [comment]
I've deleted:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L1937-L1939
