### ISSUE TITLE
Handling of longer member names on profile not satisfying

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#657]
On one hand, available space on larger displays is not used

![longmembernames](https://cloud.githubusercontent.com/assets/9904364/11944744/97a52e8a-a848-11e5-8169-74ab00830206.png)

while on smaller displays the name isn't shortened enough

![longmembernames2](https://cloud.githubusercontent.com/assets/9904364/11944805/018f00e6-a849-11e5-8e20-397d37fc52ef.png)

**Comment by ctlui** [comment]
Can be adjust by changing font-size value to vw or px + vw:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L1003

ex: 
font-size: 2.9vw;
or
font-size: calc(16px + 2vw);

Value need to be adjusted.
https://css-tricks.com/viewport-sized-typography/

**Comment by lianglee** [comment]
@ctlui, Just need to add     font-size: calc(8px + 2vw); to class .ossn-profile .user-fullname ? as far as i understand.

**Comment by ctlui** [comment]
Yes, I need to make some test to find the best font-size & maw-width for each media queries.

**Comment by lianglee** [comment]
Done
