### ISSUE TITLE
right alignment of group memberlist

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#658]
viewport < 481 : too small

![memberlist1](https://cloud.githubusercontent.com/assets/9904364/11954267/6b71062c-a8a7-11e5-9d78-cc474b57f855.png)

viewport >= 481 : too large

![memberlist2](https://cloud.githubusercontent.com/assets/9904364/11954282/87346dea-a8a7-11e5-929e-3ec7426dbfe0.png)

**Comment by ctlui** [comment]
Can delete:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L1872-L1875
and put this in general section:
 .ossn-group-members {
        margin-right: 5px;
    }

Could be also added something in:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L648
to adjust height when profile img is hide:
.ossn-group-members { 
      height: 75px !important;  
    }
