### ISSUE TITLE
group description dragging out of bounds

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#660]
![dragging-group-description](https://cloud.githubusercontent.com/assets/9904364/11954690/b8d39116-a8aa-11e5-9b0c-06c6ec117dc1.png)

**Comment by ctlui** [comment]
Could add inside:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L14-L25
resize:vertical;

**Comment by lianglee** [comment]
Works fine in chrome hmm. I also added the fix now.
