### ISSUE TITLE
No member tagging on group newsthread?

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#661]
![group-member-tagging](https://cloud.githubusercontent.com/assets/9904364/11954799/c9410ed8-a8ab-11e5-85b8-5371dda88220.png)

**Comment by ctlui** [comment]
Feature is not present in v3.x

**Comment by superbuc** [comment]
Il giorno 22/dic/2015, alle ore 14:27, Eric <notifications@github.com> ha scritto:

Feature is not present in v3.x

**Comment by lianglee** [comment]
There is no need to tag friends in groups. Can save this idea for future.
