### ISSUE TITLE
selecting a CLOSED group like MYSITE/group/123/ gives warning

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#663]
Argument 1 passed to ossn_wall_view_template() must be of the type array, boolean given, called in /var/www/ossn-4.v3/components/OssnWall/plugins/default/wall/group.php on line 32 and defined" in file /var/www/ossn-4.v3/components/OssnWall/ossn_com.php (line 383)

no warning with public group

**Comment by lianglee** [comment]
Should be fixed now
