### ISSUE TITLE
Different sanity checks on uploading images?

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#667]
UPLOADING ...
A. Wrong file type (eg. .txt)

1. Group cover:
-error popup
-system log
Missing argument 1 for OssnEntities::deleteEntity(), called in /var/www/ossn-4.v3/components/OssnGroups/classes/OssnGroup.php on line 414 and defined" in file /var/www/ossn-4.v3/classes/OssnEntities.php (line 330)
-result: NOT OK, old cover is removed

2. Profile cover:
-no popup
-no syslog
-result: ok, old cover kept in place

3. Profile picture:
-no popup
-no syslog
-result: ok, old picture kept in place

4. Adding picture to album:
-no popup
-no syslog
-result: ok, pic not uploaded/shown

5. Posting picture
-no popup
-no syslog
-result: ok, pic not uploaded/shown

6. Commenting picture (postings and entities)
-no popup
-no syslog
-result: NOT OK, 0 byte jpg created and shown

B. Too small image (1x1 jpg)

1. Group cover:
-error message: minimal size has to be 800x300
-system log
Missing argument 1 for OssnEntities::deleteEntity(), called in /var/www/ossn-4.v3/components/OssnGroups/classes/OssnGroup.php on line 414 and defined" in file /var/www/ossn-4.v3/classes/OssnEntities.php (line 330)- 
result: NOT OK, old cover is replaced

2. Profile cover:
-error message: minimal size has to be 800x300
-no system log
-result: NOT OK, old cover is replaced

C. Too small image (special case 0 byte fake jpg)

1. Group cover:
-no error message
-system log
Missing argument 1 for OssnEntities::deleteEntity(), called in /var/www/ossn-4.v3/components/OssnGroups/classes/OssnGroup.php on line 414 and defined" in file /var/www/ossn-4.v3/classes/OssnEntities.php (line 330)- 
-result: NOT OK, old cover is replaced

2. Profile cover:
-no error message
-no system log
-result: NOT OK, old cover is replaced

**Comment by lianglee** [comment]
Fixed, one thing when i upload small image, 1x1 it shows error message but image didn't updated, can you try with latest build ?
