### ISSUE TITLE
smiley borders

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#668]
I'd suggest to add 'border: 0 !important' to .ossn-smiley-item class

![smileyborder](https://cloud.githubusercontent.com/assets/9904364/11975843/25ff033e-a972-11e5-817d-487ffeb0963c.png)

![smileyborder2](https://cloud.githubusercontent.com/assets/9904364/11975910/d551394c-a972-11e5-9810-d39491e0bf14.png)

**Comment by lianglee** [comment]
Agree
