### ISSUE TITLE
Nodes Compatible Feature Resquest

### ISSUE THREAD

**Issue by royalterra** [opensource-socialnetwork/opensource-socialnetwork#673]
Hi look very nice but not will be more nice if you make can communicate nodes and be also compatible with the federation. Something like is Hubzilla. 
If you make like that sure your social network become really popular I not think is much work in that state is now

**Comment by lianglee** [comment]
At the moment Ossn works with Apache or lighttpd server, we'll surely provide support for other servers in future.

**Comment by royalterra** [comment]
What need to need to be Apache with all that ??? Hubzilla Friendica Redmatrix GNu social Andstatus all works with apache2 and php the only I say will be nice all the users from other networks can interact with you social network that is call federation . And they can do that.
Nodos is every INstallation can see the users of other  installation and also to have interaction . I believe is clear my proposal
