### ISSUE TITLE
Issue again

### ISSUE THREAD

**Issue by royalterra** [opensource-socialnetwork/opensource-socialnetwork#674]
What need to need to be Apache with all that ??? Hubzilla Friendica Redmatrix GNu social Andstatus all works with apache2 and php the only I say will be nice all the users from other networks can interact with you social network that is call federation . And they can do that.
Nodos is every INstallation can see the users of other installation and also to have interaction . I believe is clear my proposal

**Comment by lianglee** [comment]
I'll discuss it with my team, thanks.

**Comment by lianglee** [comment]
If you any other question please ask it to our community website. Our repository at Github is only meant for bug reports and development.
