### ISSUE TITLE
how can we achieve better control on footer menu link array order?

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#675]
Due to the fact, that the current order is
1. a_copyrights
2. about
3. powered
4. privacy
with some viewports (here 360px) it isn't guaranteed  that the Powered ... link appears right aligned (float right doesn't help in this case). And the result is:
![footer1](https://cloud.githubusercontent.com/assets/9904364/12003037/0111cea8-ab11-11e5-9134-c626bac8b774.png)
And as a side effect the separator '|' is missing

Manually reordering the array to
3. privacy
4. powered
gives a much better result like
![footer2](https://cloud.githubusercontent.com/assets/9904364/12003076/1021c654-ab12-11e5-9c56-3129a2cbb095.png)

So what to do?
- renaming 'powered' to something like 'z_powered' to force another array order?
- keep the 'powered' but display this link in a separate column?

**Comment by lianglee** [comment]
1.) Yes this can also work
2.) We need priority feature for menu items.
