### ISSUE TITLE
Oinitial only: no smileys in comments

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#696]
![oi-nosmileys](https://cloud.githubusercontent.com/assets/9904364/12023290/4e8e9d30-ad98-11e5-8e51-f02c07698a76.png)

**Comment by lianglee** [comment]
OMG PIC Lol

**Comment by githubertus** [comment]
Yeah, I need some fun when testing :)

**Comment by lianglee** [comment]
Hmm smiles worked for me on latest build and Oinitial

**Comment by githubertus** [comment]
I see: Smiley (with border) appears correctly after submitting new comment.
But after editing comment/reloading page the smiley is gone.

**Comment by lianglee** [comment]
I see, i'll take a look

**Comment by lianglee** [comment]
After editing comment/reloading page the smiles worked for me.

**Comment by githubertus** [comment]
ja, it's working here now, too. style still missing - will do pull request in a minute
