### ISSUE TITLE
android only: no message notification sound with Chrome Browser

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#698]
Firefox: Sound o.k.

**Comment by lianglee** [comment]
No idea, not sure if this can be fixed.

**Comment by ctlui** [comment]
Here's debug log for android chrome:
Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.
opensource.socialnetwork.js:1796 

Ossn.playSound = function() {
    document.getElementById('ossn-chat-sound').play();
};
```

**Comment by ctlui** [comment]
Can't be fixed
need to change flag on chrome:
chrome://flags/#disable-gesture-requirement-for-media-playback

**Comment by lianglee** [comment]
Closing as can not be fixed
