### ISSUE TITLE
timeline cover picture Repostion button doesn't work 

### ISSUE THREAD

**Issue by iamhemlock** [opensource-socialnetwork/opensource-socialnetwork#705]
IN timeline cover picture's repostion button doesn't work at all..

**Comment by lianglee** [comment]
Which version are you using? please provide necessary details before posting issue. https://www.opensource-socialnetwork.org/wiki/view/705/how-to-report-a-issue-on-github

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/wiki/view/705/how-to-report-a-issue-on-github

Reopen with providing necessary details.
