### ISSUE TITLE
'people who liked post' window must not be larger than physical screen height

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#707]
window should be adapted to browser height
and pagination / scrollbar added if number of likers doesn't fit
![liked-window](https://cloud.githubusercontent.com/assets/9904364/12071572/23651e68-b0b3-11e5-9efc-6ce51a68265c.png)

**Comment by lianglee** [comment]
We may need some fix height and we need a scroll too

**Comment by githubertus** [comment]
yeah, but handling of message box in general needs to be improved first, I think
because it doesn't fit completely onto screen, right side partly cut-off between 481 and 547
actually, it's never really centered above 480, I will investigate issue this evening

![message-box-centering](https://cloud.githubusercontent.com/assets/9904364/12095920/25c763e4-b312-11e5-9e1a-bd41426f0301.png)

**Comment by githubertus** [comment]
current dev state is having reduced red bootstrap buttons and scrollbar:
Still to discuss: Do we want floating to the bottom like screenshot, or entries fixed to let's say 5 members?

![ll-small-button](https://cloud.githubusercontent.com/assets/9904364/12170778/5fea85d6-b544-11e5-8820-ae48de0c4f71.png)

**Comment by lianglee** [comment]
I think scroll bar is good. Later we can add load-more likes features in v4.0 future release.

**Comment by sathish4fri** [comment]
Yes we must  add the  features

**Comment by githubertus** [comment]
latest snapshot 08.01.2016 - 15:17 has problems with larger button strings:

![likerlist-button-de](https://cloud.githubusercontent.com/assets/9904364/12204771/9c95fa9a-b636-11e5-99d2-53335a282720.png)

**Comment by ctlui** [comment]
Should change https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L1686
width: 240px;
seems ok for German

**Comment by githubertus** [comment]
I've checked German, Polski, Turkish, Russian and French, too: they're okay with 240px.

**Comment by lianglee** [comment]
perhaps we need to hide these buttons ,  ossn-likes-box .a {display:none } there is no need for these buttons in like box

**Comment by githubertus** [comment]
I'm totally with you, Arsalan.! 
(that's what I wrote in my mail "Re: Question regarding likerlist" from 5.1. 16:40)

**Comment by lianglee** [comment]
I have to improve user_list file and put param like show_controls => false , so html didn't loaded. Instead of hiding buttons using css.

**Comment by githubertus** [comment]
Eric has fixed it by css meanwhile, optical issues are gone
don't know if you want to close it now, because first fetching the list in order not to display it in the end is .... hmm ... naja ... :)

**Comment by lianglee** [comment]
Yes i know as i said i have to change api though ;)
