### ISSUE TITLE
cover image dimension-check issues

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#715]
I'm trying to upload a jpg of 801 x 301 - and I'm still getting the image-too-small error

on profile page the image is saved, though
on groups page it is rejected

used image is http://z-mans.net/ossn-reports/imgtest/nightlife-q-c-801-301-9.jpg

**Comment by lianglee** [comment]
As strange issue, don't know why condition is fails
    even width > 850 and height is also > 300 condition must be false
    if (width < 850 || height < 300)

**Comment by githubertus** [comment]
if (width < 850 || height < 300)
that's the condition
but our error message is:
The cover picture must be at least 800 x 300 or greater.
No wonder, that my picture fails, it's smaller than 850, it's 801
Ergo: we either have to change condition to 800 or message to 850 :)

**Comment by lianglee** [comment]
lol i never realized

**Comment by lianglee** [comment]
We need to change message to 850
