### ISSUE TITLE
chat userlist scrollbar issue with IE and Edge

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#723]
memberlist scrollbar is overlapped by browser scrollbar, that means: hidden
A workaround I found on the web is
html {
   -ms-overflow-style: scrollbar;
}
this works for me, no issues with chrome and firefox so far,
but please verify if this is the right solution.

![chat-userlist-scrollbar](https://cloud.githubusercontent.com/assets/9904364/12081398/af93a218-b277-11e5-93d8-618f44d8691c.png)

**Comment by ctlui** [comment]
Where did you add it ?

**Comment by githubertus** [comment]
I put it in the css of OssnChat
so far, no negative side effects here

but because it's changing the main html, I thought I'd better let you check it first before doing a pull request

**Comment by githubertus** [comment]
fixed with #738
