### ISSUE TITLE
reminder to add capitalization css to admin backend footer

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#725]
sitename appears no more upppercase since strtoupper in libinitialize is gone

**Comment by ctlui** [comment]
After https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/administrator.php#L230
add:
```
footer a{
	    text-transform: uppercase;
}
```
