### ISSUE TITLE
quirks in pagination logic

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#737]
Issue 1: 
logged in as ADMIN (who should see all entries) I got [page 1 to page 10] at the bottom 

choosing page 10, there are 0 postings
choosing page 9, there are 3 postings
So, why am I getting page 10 at all, if page 9 still isn't complete?

Issue 2:
logged in as BOTOX (NO friend of ADMIN) I got the same number of pages (10)
choosing page 10, there are 0 postings, okay, we know already
choosing page 1, there are no postings, too!
Why? because the latest 15 postings were PRIVATE postings of ADMIN

That's #558, if I'm not wrong :)

This might not harm in a small test environment, but with a larger community and a lot of private talk it'll become a trial and error game to click the right page number on the paginator in order to find something at all, because every series of 10 private postings will result in a blank page.

**Comment by ctlui** [comment]
Yes it's the same as #558 
For admin you have 10 pages due to posts in groups.
For BOTOX you find the answer it's private posts from non friends.

**Comment by githubertus** [comment]
I have no problem to understand the current technical background.
But honestly: if I had 100 or more pages listed at the bottom of my forum, and I click Page 1: blank! Page 2: blank! Page 33 blank, ... I'd give up.
So we either need a cleverer fetch or some other method to trash the unreadable postings BEFORE calculating the max number of pages and displaying the pagination bar.

**Comment by lianglee** [comment]
@githubertus actually we need to make advance searching , needed complex sql code, like search with relationships. I'll look into this.

**Comment by lianglee** [comment]
Fixed with new code
