### ISSUE TITLE
strl function not utf-8 compatible

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#748]
as we can see, it depends where \&szlig; is cut into pieces ... :)
should be handled by css, as we did with strtoupper some days ago

chat friends:
![strl1](https://cloud.githubusercontent.com/assets/9904364/12175957/499c7430-b565-11e5-8126-5fada10b0eed.png)

admin userlist:
![strl2](https://cloud.githubusercontent.com/assets/9904364/12175990/7ba2187c-b565-11e5-9072-70f794a4c000.png)

**Comment by githubertus** [comment]
Perhaps we should add green border around online users instead of dots - and this way saving some more space for names, BTW?

![online](https://cloud.githubusercontent.com/assets/9904364/12187035/6c5f2f42-b5a8-11e5-9655-c5ba37407bc7.png)

**Comment by lianglee** [comment]
Green border also look fine

**Comment by githubertus** [comment]
Yeah, but back to bug in function:
Besides of cutting entities, currently strlen is not counting the real length of the string, it's counting additional chars of html entities, too! That's why we must first do the decoding on top of function anyway.

In order to make it work correctly, I changed it like


	$str = html_entity_decode($str, ENT_QUOTES, "UTF-8");
        if (strlen($str) > $limit) {
            if ($dots == true) {
                return htmlentities(substr($str, 0, $limit), ENT_QUOTES, "UTF-8") . '...';
            } elseif ($dots == false) {
                return htmlentities(substr($str, 0, $limit), ENT_QUOTES, "UTF-8");
            }
        } elseif (strlen($str) <= $limit) {
            return htmlentities($str, ENT_QUOTES, "UTF-8");
        }

Doing it that way, we'd get a fast solution without any css changes

**Comment by githubertus** [comment]
chat component already fixed now,
will do other parts tomorrow

**Comment by githubertus** [comment]
chat component already fixed now,
will do other parts tomorrow ...

Do you remember this one from early days of support forum (endless looping and window never opens) ? 

![message_see_all](https://cloud.githubusercontent.com/assets/9904364/12251475/8eba6a8c-b8cf-11e5-8d5c-b06931e2f153.png)


This is also caused by strl function, when having a mix of normal/utf-8 chars in your box (for testing purposes I'm doing a lot in cyrillic currently :) ) it happens if strl splits 2-byte utf-8 chars on odd boundary, and result is:
[12-Jan-2016 00:42:07 UTC] PHP WARNING: 2016-01-12 00:42:07 (UTC): "json_encode(): Invalid UTF-8 sequence in argument" in file /var/www/ossn-4.v3/components/OssnNotifications/ossn_com.php (line 127)

**Comment by githubertus** [comment]
admin part (user list and unvalidated users) fixed now
waiting on input/ideas how to handle messages section

**Comment by lianglee** [comment]
Actually function working fine the issue is with the function getting html encoded string =D so it cause issues.
