### ISSUE TITLE
Non core components cannot be enable

### ISSUE THREAD

**Issue by facemechat** [opensource-socialnetwork/opensource-socialnetwork#762]
Hello I uploaded many of the non core components into my site, using version 4.0RC, but i was unable to enable them whatsoever,

The following are the components
1, About User,
2, Verify Account
3, Ad Clickable
4, Fake User
5. Metatags
6, Html Sidebar
7. Home Sliders
8, Profile Access

Please is there anything I can do to get them enabled?

**Comment by ctlui** [comment]
Nothing to do in core dev, and not an issue, please close your issue and ask your question in related components comments or community support.

**Comment by lianglee** [comment]
Closing,

v4.0 is not released and not meant for production use.
