### ISSUE TITLE
Turkish Language Package

### ISSUE THREAD

**Issue by aytacengin** [opensource-socialnetwork/opensource-socialnetwork#769]
I completed ın below link Turkish Language for 4.0 RC versiyon. 
https://www.opensource-socialnetwork.org/component/view/1282

But when I upload Languages files. Some of page not working.
You can test it. Could you prive fix ? How can I fix this issue?

**Comment by githubertus** [comment]
Ossn has a lot of pages. :) 
Please, try to give _exact_ description (page url).
What happens? Do you see English instead? Are you getting no output at all?
What you can do:
From Admin panel -> Basic settings, enable Error loggin at the bottom.
Then check file named "error_log" in Ossn installation directory of your server

**Comment by lianglee** [comment]
Go to site admin page and go to site basic settings enable display errors after that visit the page on which you are facing the issue. 

At the end please share error_log file.

**Comment by githubertus** [comment]
Fixed version uploaded to Component store. Can be closed
