### ISSUE TITLE
OSSN Installation Error

### ISSUE THREAD

**Issue by SouravMondol** [opensource-socialnetwork/opensource-socialnetwork#783]
After filling all details, when I click INSTALL button, always shows this error (Screen Shot attached). Kindly solve this problem. Also note that my website server supports this all -
– PHP 5.4
– MySQL 5
– Apache web server
– Apache mod_rewrite
– PHP Function curl
– PHP GD Library
– JSON Support
– XML

![ossn](https://cloud.githubusercontent.com/assets/16731153/12371628/03eb6e90-bc5f-11e5-8cbb-dbb278ff7881.JPG)

Now give me resolution to solve this error problem.

**Comment by lianglee** [comment]
Make sure you are running php 5.4 or larger. Please contact softaculous.com as this ossn is not on our end. Try to install manually.

See: https://www.opensource-socialnetwork.org/discussion/view/10/how-to-install-open-source-social-network-ossn

**Comment by SouravMondol** [comment]
I have already contacted with Softaculous. They told me that Softaculous does not provide support for any software. Visit Support Site. I am not able to install it manually. If I provide cPanel details,can you install it on behalf of me please?

**Comment by lianglee** [comment]
We can try, you can send us cpanel details

**Comment by SouravMondol** [comment]
How will I send you cpanel details? Actually I don't want to share this details in public place. I want to send this details through personal e-mail ID Or any others private medium. Kindly provide me please.

**Comment by lianglee** [comment]
Send it here: http://softlab24.com/

**Comment by SouravMondol** [comment]
I have not send details still now. Because I have changed host. After changing the host, I have tired to install OSSN manually. After successfully install, shows a error. Kindly check this installed link: http://aiodweb.com/chatbook
Now give me your resolution regarding this issue please.
