### ISSUE TITLE
how to handle utf-8 chars in usernames?

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#790]
Since currently we're doing
(preg_match("/^[a-zA-Z0-9]+$/", $this->username)
utf-8 chars are not accepted 

This may not be too bad with languages like Turkish, which use enough 1-byte chars too. But what about countries like Russia, who use cyrillic keyboard?

**Comment by lianglee** [comment]
i won't allow to use utf characters usernames , it will cause trouble in future.

**Comment by lianglee** [comment]
Can't be handled i think , closing.

**Comment by githubertus** [comment]
wrong re-open. should be #748
