### ISSUE TITLE
loaded new version timing out

### ISSUE THREAD

**Issue by Ramzu** [opensource-socialnetwork/opensource-socialnetwork#820]
the site had begun to load just takes a few minutes.  it moves slow. getting such log reports as:

mod_fcgid: read data timeout in 300 seconds, referer: https://www.nationtime.org/login

Premature end of script headers: index.php, referer: https://www.nationtime.org/login

**Comment by lianglee** [comment]
We are finding issues with data we collected from your website. You can restore v3.x until we notify you.

**Comment by Ramzu** [comment]
thanks. how do i restore?

**Comment by lianglee** [comment]
Do you have backup?

**Comment by Ramzu** [comment]
yes i have back up

**Comment by Ramzu** [comment]
when i tried before just showed a white screen

**Comment by lianglee** [comment]
Please hold on while we look into the issue. We are currently working on it.

**Comment by Ramzu** [comment]
ok

**Comment by lianglee** [comment]
Please contact us on live chat

**Comment by Ramzu** [comment]
on which site?
