### ISSUE TITLE
Notifications box speed

### ISSUE THREAD

**Issue by Ramzu** [opensource-socialnetwork/opensource-socialnetwork#822]
Hi,
Is there a way to speed up the opening of the Notifications box such as reducing the number of notifications shown? Thanks

**Comment by lianglee** [comment]
It requires limit the notification in OssnNotifcation::get() method

**Comment by Ramzu** [comment]
ok. what would be the script?

**Comment by lianglee** [comment]
Will update the file and let you know where you can download
