### ISSUE TITLE
Incorrect Hyphenation in the theme GoBlue 3.0

### ISSUE THREAD

**Issue by ChartTec** [opensource-socialnetwork/opensource-socialnetwork#824]
In GoBlue 3.0, the postings and commentaries lacks correct hyphenation. Words are cut when the text field ends and not, when there are spaces for example.

The postings look like that:

Ein Ende der Abwärtsbewe
gung ist, meiner Meinu
ng nach, derzeit noch nich
t unbedingt absehba

In Ossn First 3.0 it´s much better...

**Comment by ctlui** [comment]
In https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/themes/goblue/plugins/default/css/core/default.php#L310
change line to:
word-break: break-word;
if you prefer like that.

**Comment by ChartTec** [comment]
Thank you, now it looks much better (in my opinion). I changed the line 485 for the comments, too.

**Comment by lianglee** [comment]
@ctlui , should we use break-word instead of break-all ? i don't know why i added break-all.

**Comment by ctlui** [comment]
I'm at work and try shortly this morning, I think than it was for link than it was like that, but may be  possible to add a rule with a 'a', didn't try.

**Comment by ctlui** [comment]
Seems to be useless but correct should be:
word-break: keep-all;
Also can add:
text-align: justify;
