### ISSUE TITLE
video player

### ISSUE THREAD

**Issue by sermander** [opensource-socialnetwork/opensource-socialnetwork#825]
Hi. YouTube URL. Adding content. video small. this is what file correction
learn. Please
http://i.hizliresim.com/rZz403.jpg

**Comment by sermander** [comment]
Hi. YouTube URL. Adding content. video small. this is what file correction
learn. Please
http://i.hizliresim.com/rZz403.jpg

**Comment by ctlui** [comment]
Hi,
Can you please provide a youtube link than we can try to reproduce.

**Comment by sermander** [comment]
Hi, youtube url https://www.youtube.com/watch?v=KdLe7GDI7N4  kopy > http://hedefinibul.com  (kopy PX problem)

**Comment by ctlui** [comment]
Just made a clean install of v3.9 as suppose to be and it work correctly.
Need all informations than we can reproduce.

![issue_825](https://cloud.githubusercontent.com/assets/11196998/12806548/517ad3c4-cb07-11e5-8826-d4430ba3dff9.jpg)

**Comment by sermander** [comment]
hi. thanks. you the necessary information. To send. I want e-mail address.

**Comment by lianglee** [comment]
You can send at team@opensource-socialnetwork.org

**Comment by sermander** [comment]
Hi. necessary information. email sent

**Comment by lianglee** [comment]
Thank you for email, we shall revert back to you.

**Comment by sermander** [comment]
Hello githup.
I did not get help. I'm still waiting

**Comment by lianglee** [comment]
You issue has been solved.
The cause: You edited core files.

**Comment by sermander** [comment]
Hello github.
thanks lianglee.

**Comment by sermander** [comment]
Hello github.
arrangement. Which file operation. how.
The new setup was required. I got the same error
Please.

**Comment by sermander** [comment]
arrangement. Which file operation. how.
The new setup was required. I got the same error
Please.

**Comment by sermander** [comment]
hi. since 3 days. My eyes snapped. I could not find a solution.

**Comment by lianglee** [comment]
Please wait until its properly checked on our side, Your issue is under our view, We cannot make any guarantees as to when your ticket will be resolved.

**Comment by sermander** [comment]
Thanks.

**Comment by sermander** [comment]
???

**Comment by sermander** [comment]
?
