### ISSUE TITLE
online frnd list issue

### ISSUE THREAD

**Issue by 1998himanshu** [opensource-socialnetwork/opensource-socialnetwork#826]
Your site is awesome but has one fault
As we reduce the size of the screen the online friends list go off the screen.
and i have some suggestion
 that we can bring 
#left scren scroll for online frnd list(like in facebook lite )
#right screen scroll for all that menu in site 
pls help me

**Comment by lianglee** [comment]
> As we reduce the size of the screen the online friends list go off the screen.

Please provide us some more information, which version of Ossn are you using? provide us screen shot

**Comment by lianglee** [comment]
Closing as no response
