### ISSUE TITLE
profile issue can not select cover picture

### ISSUE THREAD

**Issue by trfatih61** [opensource-socialnetwork/opensource-socialnetwork#830]
After I activated the verified account component site looks in pic 2
without activation
![bildschirmfoto 2016-02-08 um 14 43 09](https://cloud.githubusercontent.com/assets/17123873/12887157/c2b63614-ce72-11e5-91d6-03508f3e4d95.png)
With enabling verified account
pic 2
![bildschirmfoto 2016-02-08 um 14 45 05](https://cloud.githubusercontent.com/assets/17123873/12887163/d42b05a0-ce72-11e5-80a8-23d822002438.png)

**Comment by lianglee** [comment]
Verified account is not core component, you should contact the component owner.
