### ISSUE TITLE
 "Username is invalid" response when registering

### ISSUE THREAD

**Issue by Ramzu** [opensource-socialnetwork/opensource-socialnetwork#832]
some users are getting the "Username is invalid" response when registering. what is causing such and how can it be fixed? thank you

**Comment by lianglee** [comment]
The username must be at least 7 characters. Maybe that is the issue.

**Comment by Ramzu** [comment]
thanks

**Comment by lcx** [comment]
it would be great if the error message would show the reason the username is invalid.
