### ISSUE TITLE
Vanishing Comments

### ISSUE THREAD

**Issue by ChartTec** [opensource-socialnetwork/opensource-socialnetwork#837]
I also have the problem, that the comments vanishes after some time. Sorry, but I can´t provide more information as I found no pattern oder action that can be responsible for that.
Where can I found the comments in the database? Shouldn´t they be stored in the table "_objects" (for example "ossn_object"? There I can found the postings on the wall, but no comments. Is there a cache, where the comments were stored but not written back to the SQL?
I can write the comment, I can see the comment, but I cant find it in the Database. Maybe this is the problem?
I am using ossn 4.0b latest Release and MySQL5.5

**Comment by ChartTec** [comment]
I finally found the comments in "ossn_entities_metadata", but there are some missing id/guid.

**Comment by lianglee** [comment]
First of all please provide us your database,  second update your Ossn to latest version. 
You can send us your db at team@opensource-socialnetwork.org

**Comment by lianglee** [comment]
One other question,  did you modified your Ossn core files?

**Comment by ChartTec** [comment]
It seems to be possible, that the error only occurs, when the setting "cache" is "on". I have changed this setting yesterday and since that, no comment has vanished. I try to send you the database later.

**Comment by lianglee** [comment]
Fixed: https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/3ee460771ddde4598cd76fb87f2a9182257ffda4
