### ISSUE TITLE
Strict Standards: date(): It is not safe to rely on the system's timezone settings

### ISSUE THREAD

**Issue by ChartTec** [opensource-socialnetwork/opensource-socialnetwork#838]
My OSSN is hosted in germany (timezone: Europe/Berlin). Yesterday, for some testing, I switched back to "english" / "error reporting" and received this error:

Strict Standards: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CET/1.0/no DST' instead in /homepages/3/d75028171/htdocs/ossn/libraries/ossn.lib.system.php on line 700

**Comment by lianglee** [comment]
Please see: http://stackoverflow.com/questions/5696833/it-is-not-safe-to-rely-on-the-systems-timezone-settings
