### ISSUE TITLE
Comments: not vanishing any longer, but not displayed

### ISSUE THREAD

**Issue by ChartTec** [opensource-socialnetwork/opensource-socialnetwork#840]
Thank you for fixing the problem with the _deleted_ comments. 
But there is another problem with the comments: they are shown only on the first page of the wall (or on the user-page). 
From the second page on ( /home?offset=2 ) they are not _displayed_

**Comment by githubertus** [comment]
Thanks for reporting, Chartec.
Pull requests #841 and #842 should solve the problem
If you like, please verify.

**Comment by lianglee** [comment]
Fixed

**Comment by ChartTec** [comment]
Great, thank you! Now I see all comments and I think, that since the last fix, no comment vanished.
