### ISSUE TITLE
Issues on Chrome Browser on chat window

### ISSUE THREAD

**Issue by cdrame** [opensource-socialnetwork/opensource-socialnetwork#857]
I am running 4.0
However I am friend with one guy, but when I use chrome I can access his page and change his profile picture. I have noticed this doesn't happen on Firefox. 
![2016-03-02](https://cloud.githubusercontent.com/assets/12101017/13483150/041bd2bc-e0c0-11e5-9898-bc711d969998.png)
![2016-03-02 1](https://cloud.githubusercontent.com/assets/12101017/13483153/079fe252-e0c0-11e5-9b48-62f23114c414.png)

**Comment by cdrame** [comment]
I only have one friend. I am pretty sure, this issue can be replicated. Quick fix will be appreciated because this is scary.

**Comment by lianglee** [comment]
Thanks for reporting issue, we shall fix it sooner

**Comment by lianglee** [comment]
Can you tell us more details? 

1.) What do you mean by accessing his page?
