### ISSUE TITLE
Invalid data directory or directory is not writeable.

### ISSUE THREAD

**Issue by awadid** [opensource-socialnetwork/opensource-socialnetwork#858]
please can somone help ? whenever i try to install the website it shows me this "Invalid data directory or directory is not writeable." iam using http://cpanel.ihostfull.com/ i try to make root it to 755 but nothing change

**Comment by greenlanegreb** [comment]
Hi, I second this, just been sitting there racking my brains for ages. Database is definitely accessible and database writeable, I have tried removing the trailing slash in the data directory, trying a differently named directory without an underscore and I have ensured that there are no symbols in my password.

**Comment by greenlanegreb** [comment]
I have found this https://www.opensource-socialnetwork.org/discussion/view/191 just going to look into what the goodness it actually means :)

**Comment by lianglee** [comment]
Please see: https://www.opensource-socialnetwork.org/wiki/view/706/how-to-install-open-source-social-network
**Create a data folder**
OSSN needs a special folder to store uploaded files including profile icons and photos. You will need to create this directory.
For security reasons, this folder MUST be stored outside of your document root. If you created it under /www/ or /public_html/, you’re 
doing it wrong. Once this folder has been created, you’ll need to make sure the web server OSSN is running on has permission to write to and create directories in it.

**Comment by akramheros2016** [comment]
I didnt find the solution

**Comment by anonys** [comment]
Just create a data folder and call it ossn_data. give it writeable permission

**Comment by Rebelee32** [comment]
I

> 
> 
> Just create a data folder and call it ossn_data. give it writeable permission

I did exactly as said. but still get the same message. I have a host tech guy to verify this. 
 I'm stuck and need a solution..

**Comment by lianglee** [comment]
@Rebelee32 then its problem with your hosting,  you should contact your hosting guy! for more information post your problem to opensource-socialnetwork.org/community

**Comment by Rebelee32** [comment]
Are you sure they deal with open source help?
I've been hunting for the error there
    On Saturday, February 1, 2020, 1:31:30 PM CST, Arsalan Shah <notifications@github.com> wrote:  
 
 
@Rebelee32 then its problem with your hosting, you should contact your hosting guy! for more information post your problem to opensource-socialnetwork.org/community

**Comment by lianglee** [comment]
@Rebelee32 they should help you.  Please use opensource-socialnetwork.org/community for more detailed discussion on this.

**Comment by Rebelee32** [comment]
Thank you for your help and suggestion


    On Saturday, February 1, 2020, 1:36:26 PM CST, Arsalan Shah <notifications@github.com> wrote:  
 
 
@Rebelee32 they should help you. Please use opensource-socialnetwork.org/community for more detailed discussion on this.

**Comment by Rebelee32** [comment]
I solved the problem. the Zipped file of OSSN Unzipped into in own link.
You have to move the unzipped folder to Public_Html and change the code on the install page
to show a data folder in your domain instead of the installs wrong link.
Notice how I edited the link to reflect the domain Dir..
It works!

![image](https://user-images.githubusercontent.com/60549701/73598993-667ee780-4504-11ea-8d6f-022c10045f0d.png)
