### ISSUE TITLE
Uploaded photos are showing on everyone's timeline, not just friends

### ISSUE THREAD

**Issue by locutus451** [opensource-socialnetwork/opensource-socialnetwork#859]
When I upload a new photo, this photo is showing on everyone's timeline, not just mine and my friends.

**Comment by lianglee** [comment]
Do you mean on newsfeed page or the profile page?

**Comment by locutus451** [comment]
they are showing on the newsfeed page.

On Tue, Mar 8, 2016 at 12:21 AM, Arsalan Shah <notifications@github.com>
wrote:

> Do you mean on newsfeed page or the profile page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/859#issuecomment-193623749>
> .
>



-- 
Mike Flynn

**Comment by lianglee** [comment]
Please change you wall settings in admin panel
