### ISSUE TITLE
No puedo instalar paquete

### ISSUE THREAD

**Issue by satsaid** [opensource-socialnetwork/opensource-socialnetwork#860]
Me aparece problema con el mo_witriable,del hosting me dicen que esta habilitado,encima lo borro y vuelve a aparecer,agradeceria su ayuda,gracias

**Comment by lianglee** [comment]
English Please

**Comment by satsaid** [comment]
I get problem with mo_witriable , hosting enabled tell me over and erase it reappears, appreciate your help, thanks
