### ISSUE TITLE
I can not install package

### ISSUE THREAD

**Issue by satsaid** [opensource-socialnetwork/opensource-socialnetwork#861]
I get problem with mo_witriable , hosting enabled tell me over and erase it reappears, appreciate your help, thanks

**Comment by lianglee** [comment]
Are you using vps? If you are sure that mod_rewrite is working then you can bypass check using yourwebsite.com/installation/?page=settings

**Comment by satsaid** [comment]
From already thank you very much for answering ... the module is activated ... not a VPS server ... with that link and enter ... but to enter all data and put install, get error 500, and if we delete the htacces reappears , no longer know what to do ...

**Comment by lianglee** [comment]
http://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2
