### ISSUE TITLE
Issues! Issues everywhere!!

### ISSUE THREAD

**Issue by seabunny26** [opensource-socialnetwork/opensource-socialnetwork#862]
Where do I begin? I have had users have difficulty uploading profile photos, I have had users have issue just uploading photos period! I have to manually go into their profiles to upload their photos for them! But at least those people can get in, others have had issues just trying to make and account on the site! I have had people have issues getting verified! I have had issues with people wanting to use certain names and cannot do so because the system will not let them! HELP!!

**Comment by lianglee** [comment]
Please see: https://www.opensource-socialnetwork.org/wiki/view/705/how-to-report-a-issue-on-githubcommunity
