### ISSUE TITLE
Fresh install = blank page

### ISSUE THREAD

**Issue by MrJacK67** [opensource-socialnetwork/opensource-socialnetwork#865]
Hi,

I did a fresh server (Ubuntu 14 LTS) and Ossn install for the first time.
Installation wizard launch ok, requirements ok but when i setup my db and click ok -> blank page (installation/?page=account), no error message, nothing
I also get the same blank page now on http://mysite.tld/

Ossn 4.0 (i have try with the zip and a git clone)
PHP 5.5.9
Mysql 5.5.47
In Apache Error log : PHP Notice:  A session had already been started - ignoring session_start() in /var/www/vhost/mysite.tld/system/start.php on line 11, referer: http://mysite.tld/installation/?page=settings
Apache 2.4.7

Thank you in advance for your help

**Comment by lianglee** [comment]
Make sure you have php mcrypt and curl extension installed.

**Comment by MrJacK67** [comment]
Mcrypt was the problem, installed but not enabled with php5enmod
Thank you for your help !

**Comment by sdavides** [comment]
Hi, in my VPS Centos 6.x OSSN work ONLY php 5.4.
I have blank page after installation.
For blank page verify:
1. mysqld is started.
2. php 5.4 version and dependencies for OSSN
3. check /var/www/html/ossn/configurations/ossn.config.site.php $Ossn->url = 'https://yourdomain.com/'; whit the "/" final.
4. check the mysql configuration /var/www/html/ossn/configurations/ossn.config.db.php whit your setting.
5. don't change line 20 in /var/www/html/ossn/locale/ossn.en.php
	'powered' => 'Powered by the Open Source Social Network.',
