### ISSUE TITLE
After creating account activation mail not comig

### ISSUE THREAD

**Issue by wandershyam** [opensource-socialnetwork/opensource-socialnetwork#867]
When i read the documentation and contact hosting provider to check mailing detail and the provider ask me which mail i used in my registration form? Please help elaborately to get out from this problem. I could not understand the documentation that is given in official site to solve this problem. Please tell me another procedure as soon as possible

**Comment by lianglee** [comment]
Make sure your server is running SMTP server, you usually need to specify the not existing email to notification email field.

**Comment by wandershyam** [comment]
Server running in SMTP server. When i install it i used normal gmail id in my admin mail field. It is any, reason for this disturbance?

**Comment by lianglee** [comment]
You can use any id in admin field,  who is your server provider? is it shared hosting? or vps?

**Comment by wandershyam** [comment]
share hosting and hosting from big rock

**Comment by lianglee** [comment]
You can try to use https://github.com/opensource-socialnetwork/SMTP

You need to specify your account username, and password. All emails will be sent from your real email address.

I am closing this issue,  it seems there is some kind of limitation set by your hosting provider or php mail() , sendmail is disabled.
