### ISSUE TITLE
message notifications doesn't display

### ISSUE THREAD

**Issue by hakeel** [opensource-socialnetwork/opensource-socialnetwork#868]
message notifications are not displaying in my site.... though any one got message it shows the msg count but when they click on the icon it shows no messages and if i wist conversation through profile then i can see message conversation. the only problem is no messages are displayed when clicked on messages icon

**Comment by lianglee** [comment]
How many messages does the counter shows? Did you installed any 3rd party component? did you tried to disabled non-core components?
