### ISSUE TITLE
installation process fails to continue

### ISSUE THREAD

**Issue by rahmanih** [opensource-socialnetwork/opensource-socialnetwork#869]
Hello,
I'm trying to install ossn on my fedora machine.

I follwed the steps in the video below
https://youtu.be/XVB-WGJ7Mg0

but the "account" page didnt load and is shown empty.
I'm using the firefox 42.0

do you have any idea how to fix the issue ?

thanks in advance.
Haithem

**Comment by githubertus** [comment]
isn't there anything logged in your apache error logfile?

**Comment by rahmanih** [comment]
Hi,
Yes I've the following log:


[Tue Mar 15 19:17:24.809658 2016] [suexec:notice] [pid 785] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Mar 15 19:17:24.902163 2016] [auth_digest:notice] [pid 785] AH01757: generating secret for digest authentication ...
[Tue Mar 15 19:17:24.903096 2016] [lbmethod_heartbeat:notice] [pid 785] AH02282: No slotmem from mod_heartmonitor
[Tue Mar 15 19:17:33.146924 2016] [mpm_prefork:notice] [pid 785] AH00163: Apache/2.4.10 (Fedora) PHP/5.6.15 configured -- resuming normal operations
[Tue Mar 15 19:17:33.146998 2016] [core:notice] [pid 785] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Tue Mar 15 19:17:33.816142 2016] [:warn] [pid 1462] ./mod_dnssd.c: No services found to register
[Tue Mar 15 19:20:46.408703 2016] [:error] [pid 2612] [client 127.0.0.1:41364] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/html/ossn/system/start.php on line 11, referer: http://127.0.0.1/ossn/installation/?page=settings

any idea?
thanks

**Comment by lianglee** [comment]
Something with suexec , make sure you server have php mycrypt and php curl extension installed.
