### ISSUE TITLE
Can't view all comments on cover photo update

### ISSUE THREAD

**Issue by KCNgo** [opensource-socialnetwork/opensource-socialnetwork#871]
Hello,

I've been able to see the "View all comments" menu item on a wall post. However, if I update a profile picture or a cover photo, the "View all comments" menu item is missing, but it will still show the last 5 comments made (the previous comments are hidden). Is the cover photo post different from a normal wall post?

Using version 4.0.

**Comment by lianglee** [comment]
Thank you for bug report,  we shall fix it next version.

**Comment by lianglee** [comment]
Fixed in next version
