### ISSUE TITLE
4.0 OSSN "Group" post edit -returns- to Wall. instead of staying in "Group".. :/

### ISSUE THREAD

**Issue by x1705** [opensource-socialnetwork/opensource-socialnetwork#872]
I noticed that when i "edit" a POST within a "Group", after it saves the new Edit...
It returns to the Main/Wall.. :/ I would like my screen to Stay in where I am at. (a Group)
....

i think this is a bug. ?

slight inconvenience, but noteworthy, imho, for more user_friendly experience with OSSN.

--------------------------------------------------------

afaik, this file, /components/OssnGroups/actions/group/edit.php shows this:

```
if ($edit->updateGroup($name, $desc, $group->guid)) {
ossntriggermessage(ossnprint('group:updated'));
redirect("group/{$group->guid}");
} else {
ossntriggermessage(ossnprint('group:update:fail'), 'error');
redirect(REF);
}

```
i think in line #3, redirect("group/{$group->guid}"); is correct?

but it returns display to Public Wall.
I will let you know if i find what to do.
thanks.

**Comment by lianglee** [comment]
Fixed in #856
