### ISSUE TITLE
Problem creating a custom field in register form

### ISSUE THREAD

**Issue by gesquivelob** [opensource-socialnetwork/opensource-socialnetwork#875]
Hi! i wanna add a custom field in the register form, and I did this:

in the actions > user > register.php file

introduced this: 
`$user['usertags'] = input('usertags');`

and this:
`$add->usertags = $user['usertags'];`

in the respective spaces.

And in the themes > my theme > plugins > default > forms > singup.php file, I've writted this

`<input type="text" name="usertags" placeholder="Gustos e intereses, separados por comas" class="long-input"/>`

to add the field in the form. And in the database I've added a field named: usertags in ossn_users table.

but when i register a new user, the action dont save the "usersertags" in the Database, what more I need to do?

This is my website: www.howller.com
My OSSN version is 4.0

**Comment by lianglee** [comment]
This is not bug , this place is only for discussion of bugs.
