### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by RRizki** [opensource-socialnetwork/opensource-socialnetwork#876]
I noticed that when i "edit" a POST within a "Group", after it saves the new Edit... 
It returns to the Main/Wall.. :/ I would like my screen to Stay in where I am at. (a Group)
....

i think this is a bug. ?

slight inconvenience, but noteworthy, imho, for more user_friendly experience with OSSN.

Thanks?
G

**Comment by lianglee** [comment]
Duplicate : https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/872
