### ISSUE TITLE
Group 2nd page edit comment

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#877]
Test made on cleanossn
Step to reproduce:
create a group
make 11 post to have 2 pages
first error in log appear when going or refresh page 2:
"Invalid argument supplied for foreach()" in file /components/OssnGroups/classes/OssnGroup.php (line 250)

Add some comments in post 1 (which is on page 2)
Make a refresh
When you click on the arrow to edit or delete comment, you just have the option to edit the comment, delete is missing.
When you click on edit comment, page stay at the animation ossn-loading ossn-box-loading.
Just got this error i console when I click:
POST https://domain.ndd/comment/edit/undefined?ossn_ts=1458793116&ossn_token=3797f461fd1ba43b50048bbd79de900b 404 (Not Found)   jquery-1.11.1.min.js:4 

![issue1](https://cloud.githubusercontent.com/assets/11196998/14008302/9e7ea94a-f17f-11e5-9354-2c01431a92b4.jpg)

**Comment by lianglee** [comment]
I found the reason , its must be due to offset

**Comment by lianglee** [comment]
Try to enable error reporting and first monitor ajax requests,  now try to edit you will see exact error message.
