### ISSUE TITLE
Comments disapearing????

### ISSUE THREAD

**Issue by sonicmaster** [opensource-socialnetwork/opensource-socialnetwork#881]
Hello i´m using OSSN 4.O when someone posts a comment they disappear from the Newsfeed.

**Comment by lianglee** [comment]
Did you deleted the user from database ? please try to upgrade to latest version to OSSN v4.1 

https://www.opensource-socialnetwork.org/discussion/view/1531/ossn-v41-has-been-released-please-upgrade-your-website

Closing as similar to , Ticket #837

**Comment by sonicmaster** [comment]
Hello, no i didn t delete the user, its my users and all users comments, but i´m upgrading as we speak, ill report if it stll happens. thanks, by the way congrats on OSSN , i converted all my Elgg users to OSSN with no problems, how can i join the team?

Thanxxx

**Comment by lianglee** [comment]
If you wanted to Join team you can send us issues and send us fixes if possible.
