### ISSUE TITLE
Slow and crashes after 10 users or more are logged in

### ISSUE THREAD

**Issue by sonicmaster** [opensource-socialnetwork/opensource-socialnetwork#884]
Hello after 10 or more users are logged in the system becomes unstable and starts to crash completly im hosting on a VPS 1GB RAM SSD ? Can a cache system be developed.  With some tests i noticed that it turns slow in page swaps, maybe if the news feed add ajax feeds the issue was partly resolved and a page cache would be a great improvemment.

**Comment by lianglee** [comment]
Please provide more details,  which version of OSSN are you using ? did you enabled the cache in administration page?
