### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by antoinelbanks** [opensource-socialnetwork/opensource-socialnetwork#887]
Hi.

So, last time, I mentioned that I was having a hard time installing sites, because I didn't know where the /ossn_data directory went. Well, this time, I uploaded the script to my domains that I planned to you, added the /ossn_data outside of public view. I even made sure the /ossn_data directory was writable; in fact, I made sure that everything that was going to be in the directory was also going to be writable.

Well, when, I tried to install one of my domains, I got the following message “Invalid data directory or directory is not writeable.” What's the deal?

The following domains that I plan to run the script on are:
http://asianbook.cuccfree.com
http://blackbook.cuccfree.com

Please let me know if you would like to log into my ftp and fix the issues and I'll give you the info that's needed. Thanks.

**Comment by lianglee** [comment]
It seems you are using non cpanel hosting panel,   you can try to install on sub folder

**Comment by will2022** [comment]
Same also use cuccfree.com have same problem

**Comment by lianglee** [comment]
@will2022  please see https://www.opensource-socialnetwork.org/wiki/view/706/how-to-install-open-source-social-network
