### ISSUE TITLE
 Uncaught exception 'OssnDatabaseException' with message 'User 'u136452689_root' has exceeded the 'max_questions

### ISSUE THREAD

**Issue by Generalgwill** [opensource-socialnetwork/opensource-socialnetwork#891]
Fatal error: Uncaught exception 'OssnDatabaseException' with message 'User 'u136452689_root' has exceeded the 'max_questions' resource (current value: 10000) SELECT * FROM ossn_site_settings ; ' in /home/u136452689/public_html/classes/OssnDatabase.php:77 Stack trace: #0 /home/u136452689/public_html/classes/OssnDatabase.php(175): OssnDatabase->execute() #1 /home/u136452689/public_html/classes/OssnSite.php(35): OssnDatabase->select(Array, true) #2 /home/u136452689/public_html/libraries/ossn.lib.system.php(29): OssnSite->getAllSettings() #3 /home/u136452689/public_html/system/start.php(36): include_once('/home/u13645268...') #4 /home/u136452689/public_html/index.php(11): require_once('/home/u13645268...') #5 {main} thrown in /home/u136452689/public_html/classes/OssnDatabase.php on line 77

**Comment by Generalgwill** [comment]
please any body here to help me out??

**Comment by lianglee** [comment]
Please change your hosting provider.

**Comment by alexraynes** [comment]
Am facing the same problem, I change my hosting provider to another Hosting and it spend a couple of weeks I started experiencing the same problem

**Comment by lianglee** [comment]
Use VPS and you'll never face such a aissue
