### ISSUE TITLE
Probleme with ossn 4

### ISSUE THREAD

**Issue by jobayr** [opensource-socialnetwork/opensource-socialnetwork#894]
Please forgive my bad english.
   I installed ossn 4 on localhost sucsefully , but i cant put entitys in all site , like i cant edit profile and i cant add new group and i cant comment , seems like there is a probleme with saving entity in database .
   please can you help me ?

**Comment by masrukin404** [comment]
What a problem like? ,  and are you using linux or local wrb server on yoir pc?

**Comment by jobayr** [comment]
i am using wampserver on localhost . The probleme is i cant create any
groupe or page or blog or modify profile or..., that like the tables in
database dont accept any new entity .
  My installation was great , mean no probleme in installation ossn

2016-06-11 14:33 GMT+00:00 masrukin404 <notifications@github.com>:

**Comment by masrukin404** [comment]
Okay , i dont kno what the spesific of error but may this solution can help you,

First check the permission of files and folder, is there are correct, usualy

Second try to check your connection database, 
If there are no problem with db, doing the step 3

Third , this is may the last solution, try to change your web server, usualy this is one of many reason why the script can't be running, i recommended xampp web server, and sorry if may english so bad

**Comment by lianglee** [comment]
Please follow the above suggestion by @masrukin404

**Comment by jobayr** [comment]
this is an exemple for problemes ( look at photos ) , my english also bad
so i can speak arabic or french.
the first photo is for adding post in the wire of home page , and the
second is for adding post on the wire of groups , and i cant edit my
profile or my avatar , and many other problemes.  i cheked my database is
well , i have other CMS's like elgg and wordpress both work very well on
the same sever

2016-06-13 11:29 GMT+00:00 masrukin <notifications@github.com>:
