### ISSUE TITLE
up cover did not responsive, please review and fix

### ISSUE THREAD

**Issue by masrukin404** [opensource-socialnetwork/opensource-socialnetwork#896]
Up cover did not responsive ,

Spoiler at web view http://imgur.com/Zipx54X

And then this is at mobile view, 

Spoiler for mobile view http://imgur.com/9k6qgkf

Previous patch https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/888#event-638779831 just for fixing image at wall and wall profile, but not at cover

**Comment by lianglee** [comment]
The image can not be made responsive in current OSSN support, if you know solution please let us know
