### ISSUE TITLE
Switch statements may only contain one default clause in OssnSitePages

### ISSUE THREAD

**Issue by WebCrew** [opensource-socialnetwork/opensource-socialnetwork#897]
If I try to open configure/site pages then only a white page is shown to me. No edit feature, no content, nothing only a white blank page.
I use latest OSSN 4.1

**Comment by lianglee** [comment]
Try to first go to admon -> basic settings -> enable display error and then visit site pages and let us know if you get any error message.

**Comment by WebCrew** [comment]
I have already done this, but I got no error log or error message, but only a blank white page - thats all. Thats realy a crazy problem because normaly if I set debug on then it should show me a error result, but I got none.

**Comment by WebCrew** [comment]
Here is a gif to show it to You:
![SitePages Error](http://i.makeagif.com/media/6-12-2016/43vFSP.gif)

**Comment by lianglee** [comment]
Did you tried on some other hosting ?

**Comment by WebCrew** [comment]
I`ll not buy me a extra new hosting and my hoster is up to date with latest technologies I cant find a better one. All major PHP scripts are updated to its latest versions.

**Comment by lianglee** [comment]
It very strange that it shows you white page.  Did you tried to disable all 3rd party components ?

^_^

**Comment by WebCrew** [comment]
Its default installation with no extra components.

**Comment by lianglee** [comment]
Fixed for PHP7

**Comment by WebCrew** [comment]
Yeah so it was about php 7 ok I`ll check it out now - Thank You mates and good luck for the future.

**Comment by OGZG** [comment]
Nah, dont work.

**Comment by lianglee** [comment]
@OGZG there is no such a error its been solved in 4.x
