### ISSUE TITLE
PHP ZipArchive EXTENSION REQUIRED

### ISSUE THREAD

**Issue by julianlozan** [opensource-socialnetwork/opensource-socialnetwork#901]
i dont know the problem for install.

PHP ZipArchive EXTENSION REQUIRED

**Comment by masrukin404** [comment]
That's problem come from your hosting, it's look like php ziparchive has been diaabled by web hosting , try to change your web hosting or if you are using vps or you install with your own web server try read this post to solving php ziparchive problem http://stackoverflow.com/questions/12477837/enable-ziparchive-on-localhost, hope your problem will be solved,
