### ISSUE TITLE
OssnDatabaseException' with message 'Incorrect integer value

### ISSUE THREAD

**Issue by jobayr** [opensource-socialnetwork/opensource-socialnetwork#904]
A system error has occurred. Please try again later. You may email the details of this error to the system administrator at jobayr2015@gmail.com.
exception 'OssnDatabaseException' with message 'Incorrect integer value: '' for column 'time_updated' at row 1 INSERT INTO ossn_entities (`owner_guid`, `type`, `subtype`, `time_created`, `time_updated`, `permission`, `active`) VALUES ('2', 'user', 'cover_time', '1466459108', '', '2', '1'); ' in C:\wamp\www\ossn\classes\OssnDatabase.php:77 Stack trace: #0 C:\wamp\www\ossn\classes\OssnDatabase.php(44): OssnDatabase->execute() #1 C:\wamp\www\ossn\classes\OssnEntities.php(99): OssnDatabase->insert(Array) #2 C:\wamp\www\ossn\classes\OssnEntities.php(202): OssnEntities->add() #3 C:\wamp\www\ossn\classes\OssnUser.php(1056): OssnEntities->save() #4 C:\wamp\www\ossn\components\OssnProfile\classes\OssnProfile.php(184): OssnUser->save() #5 C:\wamp\www\ossn\components\OssnProfile\plugins\default\profile\pages\profile.php(16): OssnProfile->getCoverURL(Object(OssnUser)) #6 C:\wamp\www\ossn\libraries\ossn.lib.views.php(27): include('C:\\wamp\\www\\oss...') #7 C:\wamp\www\ossn\libraries\ossn.lib.views.php(50): ossn_include('C:/wamp/www/oss...', Array) #8 C:\wamp\www\ossn\libraries\ossn.lib.plugins.php(75): ossn_view('components/Ossn...', Array) #9 C:\wamp\www\ossn\components\OssnProfile\ossn_com.php(248): ossn_plugin_view('profile/pages/p...', Array) #10 [internal function]: profile_page_handler(Array, 'u') #11 C:\wamp\www\ossn\libraries\ossn.lib.page.php(67): call_user_func('profile_page_ha...', Array, 'u') #12 C:\wamp\www\ossn\index.php(21): ossn_load_page('u', 'mounia/edit') #13 {main}

**Comment by lianglee** [comment]
Did you deleted those comments?

**Comment by emryssss** [comment]
got the same error here.... any fix?

**Comment by lianglee** [comment]
https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/a768d98d5c3335c9b0bd0d52d9a079808c3efc82
