### ISSUE TITLE
Problem with stylesheet

### ISSUE THREAD

**Issue by ScarletN** [opensource-socialnetwork/opensource-socialnetwork#905]
Hi. After moving all data files to a new server and new domain name, I notice that the site is not reading the stylesheet properly therefore no styles on the frontend. 
Can someone help please.
Here is the url to the site.
[http://footballbuzz.net](http://footballbuzz.net)
Thanks

**Comment by lianglee** [comment]
Make sure there is .htaccess file present in your public_html directory

**Comment by ScarletN** [comment]
I don't see a .htaccess file in my public_html directory. How do I get one created?

**Comment by lianglee** [comment]
Try to visit yourwebsite.com/installation/
