### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by emryssss** [opensource-socialnetwork/opensource-socialnetwork#907]
after the installation processes, on getting to create admin account, i get the error message

>  Account registration failed! Please try again later.

what could be the problem and how do i fix it?

**Comment by lianglee** [comment]
Check the database privileges and make sure you have given full rights to database user.

**Comment by emryssss** [comment]
Did that but still get same error message 

> Account registration failed! Please try again later

**Comment by lianglee** [comment]
Please try to change your hosting provider
