### ISSUE TITLE
rewrite test is not working upon new installation

### ISSUE THREAD

**Issue by zozo6015** [opensource-socialnetwork/opensource-socialnetwork#909]
Hello,

I am installing a new instance of OSSN and however I have the rewrite module enabled the test is always failing.

this is what I see in the error.log

[Sun Jul 03 06:42:20.705133 2016] [:error] [pid 12146] [client IP:50573] script '/var/www/html/ossn/rewrite.php' not found or unable to stat

**Comment by lianglee** [comment]
Please see : https://www.opensource-socialnetwork.org/discussion/view/1732/rewrite-test-is-failing-when-installing-opensource-social-network
