### ISSUE TITLE
Ossn notification for messages not working

### ISSUE THREAD

**Issue by youngrichu** [opensource-socialnetwork/opensource-socialnetwork#913]
i'm using the 4.1 version. when ever i got a message or request the red notification with number popups, but when i click it the message says " Nothing to show"  and when i check the message on the sidebar the same things happen but on the chat the messages are still there . pls help me fix this

**Comment by lianglee** [comment]
Please provide us error_log

**Comment by youngrichu** [comment]
i'm new to OSSN ... where can i find the error_log ?

thanks in advance

**Comment by youngrichu** [comment]
i don't know if this can help..

![ossn](https://cloud.githubusercontent.com/assets/3649930/16689056/cce83f6e-4529-11e6-9e97-7a0dd4432dac.PNG)

**Comment by lianglee** [comment]
We shall debug the issue and get back to you shortly

**Comment by lianglee** [comment]
Fixed with v4.2
