### ISSUE TITLE
components not working on ossn 4.2

### ISSUE THREAD

**Issue by emryssss** [opensource-socialnetwork/opensource-socialnetwork#914]
i installed ossn 4.2 and noticed the follwing components not working properly

- poke: returns error message
- video call: doesn't function
- can't add photo's to profile album with mobile
- html sidebar: doesn't accept html code
- uploaded photo's appear large on newsfeed
-users can't can't make their about fields private

**Comment by lianglee** [comment]
Did you tried to disable non-core components? 
OSSN didn't have video call,  which video call you are talking about?

**Comment by lianglee** [comment]
Ticket shall be close with 2 days if no response received.
