### ISSUE TITLE
Installation problems on ossn

### ISSUE THREAD

**Issue by Anthony1071** [opensource-socialnetwork/opensource-socialnetwork#916]
Hello, can anyone help me please ?

I have install ossn on my personal server.

Ubuntu 15.10
ossn ver 4.2
php 5.6
mysql
apache2
mod_rewrite is ok
php curl & gd are ok
etc.

I fill in the server settings and click next, But the next page is a blank page.
![captureossn1](https://cloud.githubusercontent.com/assets/20513049/17079699/49ff656c-5129-11e6-8608-ee06821e2100.PNG)
![captureossn2](https://cloud.githubusercontent.com/assets/20513049/17079700/49ffe514-5129-11e6-8d2a-1b18ab2c8bb1.PNG)
![captureossn3](https://cloud.githubusercontent.com/assets/20513049/17079701/4a2602b2-5129-11e6-943c-41d685258e6e.PNG)

**Comment by lianglee** [comment]
Please make sure all php extensions enabled, gb, mcrypt, curl, openssl,  etc

**Comment by Anthony1071** [comment]
Thank you for your reply. you are a genious !!
phpmcrypt was missing.
thanks again

**Comment by Anthony1071** [comment]
Hello Arsalan,


I am presently testing ossn, and I truly find it a very top social engine.


Thank you very much for your help [cid:b0ee0a32-248f-48c8-b5db-fae966cccef0]


After the testing phase I am seriously considering buying the premium to install on my server.


But there are some questions about it and your offers that I would like to put the light on.


Can we talk here or should I send an email on :- info@softlab24.com ?


Thank you again for your help

Regards

Anthony

**Comment by lianglee** [comment]
Yes please contact us using the email above for premium requests.
