### ISSUE TITLE
How to enable user login by credentials alredy existing on other site

### ISSUE THREAD

**Issue by techsandeep** [opensource-socialnetwork/opensource-socialnetwork#917]
Hello I have just purchased a pro version of OSSN and I setup it on my intranet. But I don't want user registration as we have alreedy my employee Mgt system and want to authenticate user from there and if user successfully authenticate then user post feed on OSSN setup.

**Comment by lianglee** [comment]
Please send request to softlab24 team directly for support of pro version.
