### ISSUE TITLE
How to separate theme for admin and front?

### ISSUE THREAD

**Issue by techsandeep** [opensource-socialnetwork/opensource-socialnetwork#919]
Hi Team,

I am new to OSSN development and I have purchased premium version of ossn. But now I am facing a major issue in ossn development as there are common theme for admin and front but I want to change layout and design of front end. I sent 3 mails from support system after login on softlab24 but i didn't get any response neither i can check status of my tickets. Please help how to solve this issue to make separate theme for front end?

**Comment by lianglee** [comment]
We have checked your tickets requests on softlab24 and found that your tickets has been answered. 
If you have premium version please also include your transaction id while contacting them.
Do you wanted to change layout ? you can easily change from themes/goblue/ directory.

**Comment by techsandeep** [comment]
Actually I want to customize front end without changing admin section and fro this we have to change all css and js of front end.

**Comment by lianglee** [comment]
Yes you can change that in themes/goblue/plugins/default/css/core/default.php

**Comment by techsandeep** [comment]
Hi lianglee,
I copy my css from style.css of my html and paste in default.php now how to include fonts path in this file and in which folder i keep my fonts.

Thanks

**Comment by techsandeep** [comment]
Also I have some external js files how to include these.
