### ISSUE TITLE
How to make login page default landing page?

### ISSUE THREAD

**Issue by techsandeep** [opensource-socialnetwork/opensource-socialnetwork#921]
Hi Team,
I want to make login page default landing page currently registration page is default.

**Comment by lianglee** [comment]
The github is for posting bugs please post your question to community website.

**Comment by techsandeep** [comment]
Is there any way we can check status of my tickets?

**Comment by lianglee** [comment]
Can you explain which ticket ?

**Comment by techsandeep** [comment]
I have asked few question via mail but i didn't received any reply.

**Comment by matrixshopping** [comment]
How do I get the login page as the default landing page instead of the registration page
