### ISSUE TITLE
OSSN is not working after installation.

### ISSUE THREAD

**Issue by mrtinkz** [opensource-socialnetwork/opensource-socialnetwork#925]
Hi,

I have installed the OSSN in wamp. Below are some issues i am seeing

![image](https://cloud.githubusercontent.com/assets/377147/17638327/f9a0f820-60ae-11e6-8d4a-042ae86f84a5.png)

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/ossn/css/view/ossn.default.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/ossn/js/view/ossn.language.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/ossn/js/view/opensource.socialnetwork.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/ossn/js/view/ossn.language.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/ossn/js/view/opensource.socialnetwork.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css Failed to load resource: the server responded with a status of 403 (Forbidden)
localhost/:26 Uncaught ReferenceError: Ossn is not defined
localhost/:1 Uncaught ReferenceError: Ossn is not defined
browser-bundle.js:1 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.
http://localhost/ossn/css/view/bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/ossn/css/view/ossn.default.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by lianglee** [comment]
Your mod_rewrite not working please check it with your hosting provide and make sure you have .htaccess file present in your root of ossn.
