### ISSUE TITLE
(community:report) Only 10 friends are visible on friends list page

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#926]
(community:report) Only 10 friends are visible on friends list page.

More info required:

* Is there any pagination present ?

**Comment by starbride** [comment]
No pagination is available....

**Comment by lianglee** [comment]
Thanks for reporting the issue shall be fixed soon

**Comment by lianglee** [comment]
@starbride , ok i have tested on oinitial theme and the pagination is visible ,  can you tell me are you using oinitial theme of default theme from 3.x ?

Tested on both themes and its show pagination on  webiste.com/u/< user >/friends

**Comment by starbride** [comment]
I use Oinitial and there is no pagination in the friends-list. It shows the first 10 friends only.

**Comment by lianglee** [comment]
@starbride , please provide the exact URL of friends page you are referring, i am sorry that i am having difficulty to understand it.

**Comment by starbride** [comment]
No problem --> sweetnet.org/ossn

**Comment by starbride** [comment]
The url of friends list is --> http://sweetnet.org/ossn/u/starbride/friends

**Comment by lianglee** [comment]
It seems working fine on our installation, there might be issue with your installation or ossn version,  try to install locally on Ossn v4.2

**Comment by starbride** [comment]
I changed the theme to GoBlue, now nothing starts up, the whole site does not appear.
I give up.

**Comment by lianglee** [comment]
@starbride go database ossn_site_settings change goblue to your old theme name

**Comment by starbride** [comment]
No, it did not work, I changed the db-settings to the old theme, still blank site.
thanks anyway.

**Comment by starbride** [comment]
However, after the site was updated and all is fine again, I like to confirm that the friends list now shows pagination. Problem is solved.
thank you,
Sally K

**Comment by lianglee** [comment]
Thanks for confirmation
