### ISSUE TITLE
cover photo dimensions restriction

### ISSUE THREAD

**Issue by sathish4fri** [opensource-socialnetwork/opensource-socialnetwork#93]
for cover photo lets add a particular size  for default if the file dont have default size means . we shouldn't allow that image to be uploaded ..

**Comment by dorobantu** [comment]
Hi

I tried to add new cover photo and personal photo but without any success...
You know why?

Thanks.

**Comment by anamassien76** [comment]
I am also having this problem, after 3.0 upgrade covers nor avatar upload work on profiles.

**Comment by lianglee** [comment]
@anamassien76, can you send us your error_log file?

**Comment by Igorinus** [comment]
hi to all im new in here and apologize me if i talk bad , my english is not so well but i try to make my self understandable the cover it is  in did a problem for the big pictures and same for  profile pciture if is  possible to be made a ERROR that apepar in screen something like "We recomand you to not upload larger files then Z x Y" and if the user still try to appear error like "the images was to large please rezise and try again to upload"

**Comment by lianglee** [comment]
Since our v4.0 release will be totally based on bootstrap, we have to write something that automatically scale small pictures, but it should shows some warning if picture is too small.

**Comment by ctlui** [comment]
fixed on local server
