### ISSUE TITLE
Can't delete private messages

### ISSUE THREAD

**Issue by ROMike** [opensource-socialnetwork/opensource-socialnetwork#931]
There is no button to delete a private message.

OSSN v4.2

**Comment by lianglee** [comment]
This should be provided in next release.

**Comment by magnus505** [comment]
so.. There is the update?

**Comment by homelancer** [comment]
I have created a private delete message functionality for the chat but I'm new to this GitHub. How can I contribute the changes?

**Comment by Lablnet** [comment]
simply add new file in ossn or if you change create poll request

**Comment by homelancer** [comment]
Added a delete private message functionality to the pull request see (
see [Delete a chat message functionality #1118](https://github.com/opensource-socialnetwork/opensource-socialnetwork/pull/1118) )

**Comment by lianglee** [comment]
Allow to delete message that user own #1332
