### ISSUE TITLE
After login nothing is showing only blank page

### ISSUE THREAD

**Issue by manukhms** [opensource-socialnetwork/opensource-socialnetwork#935]
after a user log in only the theme design come without any icons or anything .
[News Feed _ COGNITIA 2016.pdf](https://github.com/opensource-socialnetwork/opensource-socialnetwork/files/441339/News.Feed._.COGNITIA.2016.pdf)

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug
