### ISSUE TITLE
As soon as i enable cache, (BLANK SCREEN)

### ISSUE THREAD

**Issue by Vegas10128** [opensource-socialnetwork/opensource-socialnetwork#937]
So i have tried to get plugins to work that i found on your site. Obviously NONE of them worked. 
There were no answers to questions. Only leading to more questions. 
As soon as i enable cache?  A WHOLE BUNCH OF NOTHING. Blank screen.  Deleted all the files and folders, and re uploaded them again, and gives me user registration error. 
After finally trying to fix that?  back to blank screen. 
Im already sold on my decision. 
I will not be using this platform again. 
This has support just as bad as Boonex aka Dolphin.

**Comment by lianglee** [comment]
Can you tell me if there is anything in error_log file?
