### ISSUE TITLE
logout not working administrator page

### ISSUE THREAD

**Issue by digiapps** [opensource-socialnetwork/opensource-socialnetwork#939]
Hi Team,

I clicked on logout but its only reload the page and not destroyed session. I also checked this functionality on your demo link and there was same issue there also.

Please help me how to logout user from system.

**Comment by lianglee** [comment]
Did you tried on different browser?

**Comment by techsandeep** [comment]
Yes I tried on Mozilla and Chrome.

**Comment by lianglee** [comment]
Hi i checked http://demo.opensource-socialnetwork.org/ and logout is working fine.  Please see if there is anything in error_log file.

**Comment by lianglee** [comment]
see https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/7883d0e4c6bed4b596949fb8cdc3fc1abf2f7fb4
