### ISSUE TITLE
OssnGroups : Incorrect integer value: '' for column 'item_guid' 

### ISSUE THREAD

**Issue by gianbisso** [opensource-socialnetwork/opensource-socialnetwork#942]
Trying to join a group i got this error:

A system error has occurred. Please try again later. You may email the details of this error to the system administrator at Gian.

OssnDatabaseException: Incorrect integer value: '' for column 'item_guid' at row 1 INSERT INTO ossn_notifications (`type`, `poster_guid`, `owner_guid`, `subject_guid`, `item_guid`, `time_created`) VALUES ('group:joinrequest', '1', '5', '7', '', '1473418486'); in /var/www/html/ossn/classes/OssnDatabase.php:77 Stack trace: #0 /var/www/html/ossn/classes/OssnDatabase.php(44): OssnDatabase->execute() #1 /var/www/html/ossn/components/OssnGroups/classes/OssnGroup.php(293): OssnDatabase->insert(Array) #2 /var/www/html/ossn/components/OssnGroups/actions/group/join.php(17): OssnGroup->sendRequest('1', '7') #3 /var/www/html/ossn/libraries/ossn.lib.actions.php(51): include_once('/var/www/html/o...') #4 /var/www/html/ossn/system/handlers/actions.php(12): ossn_action('group/join') #5 {main}

In file components/OssnGroups/classes/OssnGroup.php i found:
$params['names']  = array(
                                                                                'type',
                                                                                'poster_guid',
                                                                                'owner_guid',
                                                                                'subject_guid',
                                                                                'item_guid',
                                                                                'time_created'
                                                                );
$params['values'] = array(
                                                                                $type,
                                                                                $from,
                                                                                $group_owner,
                                                                                $group,
                                                                                NULL,
                                                                                time()
);

bun in table ossn_notifications field item_guid can't be NULL:
+--------------+------------+------+-----+---------+----------------+
| Field        | Type       | Null | Key | Default | Extra          |
+--------------+------------+------+-----+---------+----------------+
| guid         | bigint(20) | NO   | PRI | NULL    | auto_increment |
| type         | text       | NO   | MUL | NULL    |                |
| poster_guid  | bigint(20) | NO   | MUL | NULL    |                |
| owner_guid   | bigint(20) | NO   | MUL | NULL    |                |
| subject_guid | bigint(20) | NO   | MUL | NULL    |                |
| viewed       | varchar(1) | YES  |     | NULL    |                |
| time_created | int(11)    | NO   | MUL | NULL    |                |
| item_guid    | bigint(20) | NO   | MUL | NULL    |                |
+--------------+------------+------+-----+---------+----------------+

Changing NULL with 0 it looks working.

**Comment by lianglee** [comment]
Thanks for reporting issue we shall fix it soon

**Comment by lianglee** [comment]
"This is an sql-mode issue, the mode defines what SQL syntax should be supported and what kind of data validation should be performed. In my problem MySQL is trying to assign an empty string to an auto-increment INT field and, as we should all know, strings into INTs don't go. Cue errors and the script dies.

Edit the my.cnf (my.ini in windows) file and find and comment out the line:

       #sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
The STRICT_TRANS_TABLES or it might be STRICT_ALL_TABLES is the bit that is causing the problem for me and with that line gone, STRICT mode is disallows invalid or missing values in a statement and aborts the command.

With this line commented out, STRICT mode is no longer applied and MySQL should now insert adjusted values for invalid or missing values and more specifically, it should allow my empty string to be put into the int column.

"

**Comment by gianbisso** [comment]
item_guid is not auto_increment and NULL is not like an empty string.

Anyway try to insert NULL in a field that's set to don't accept NULL value hoping mysql settings will accept that and convert it in an int, doesn't looks like a good practice.

**Comment by lianglee** [comment]
It should work,  if know you need to find correct settings for your respective database version.

**Comment by gianbisso** [comment]
It looks like a typical clash between dev and sysadmin. 

Anyway it doesn't work coz if i comment sql-mode in my my.cnf mysqld falls back to default settings that in my case (Ubuntu 16.04.1 LTS, mysql 5.7.13) are 
mysql> SELECT @@GLOBAL.sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@GLOBAL.sql_mode                                                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+

so instead of comment it, solution is to delete STRICT_TRANS_TABLES from sql-mode strings.

Btw i already had to change sql-mode during installation to unset ONLY_FULL_GROUP_BY.

Anyway i still think that correct solution should be fix the code and avoid it tries to with a NULL value in a field where NULL is not allowed.

**Comment by lianglee** [comment]
The NULL should be 0 i think
