### ISSUE TITLE
refused to execute script from because strict mime type

### ISSUE THREAD

**Issue by timeandspacecadet** [opensource-socialnetwork/opensource-socialnetwork#944]
cant add profile pic or post pic in chrome but can with firefox.
cant add group either but can in ff

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug

**Comment by timeandspacecadet** [comment]
nothing happens when I click on any of the 3 icons tag friens, enter location or to add a pic in chrome but works in fire fox
Current PHP version: 5.6.25
OSSN - OPEN SOURCE SOCIAL NETWORK 3.9

**Comment by lianglee** [comment]
Please try on OSSN 4.x ,  the support for 3.x has been ended, make sure you are using default theme with your 3.x installation.

**Comment by timeandspacecadet** [comment]
will update in the next day or 2 and let you know the outcome, I installed the version That I did because it was the version that the Softaculous installer from my host installed.

**Comment by timeandspacecadet** [comment]
according to Softaculous its 4.2 , I had looked at the changelog.txt which said 3.9 there is also a changes.txt and that says 4.2 so looks like it is  4.2

**Comment by lianglee** [comment]
Did you tried to update chrome?

**Comment by timeandspacecadet** [comment]
just did chrome update, it lets me choose a new profile pic, but it doesn't change.
and still cant post a pic.

**Comment by timeandspacecadet** [comment]
join up here and try for yourself http://www.franzjosef.info/franzbook/home

**Comment by lianglee** [comment]
It seems you are using proxy server ? The issue is directly coming from your server restricting some JavaScript files to load.

**Comment by carlbee1** [comment]
Ok thank you will make note !!!

**Comment by timeandspacecadet** [comment]
It still works fine using Firefox and the post a pic

**Comment by carlbee1** [comment]
Ok does my site load fine and what site are you checking ???

**Comment by timeandspacecadet** [comment]
http://www.franzjosef.info/franzbook

**Comment by timeandspacecadet** [comment]
have started a support ticket with my host. there are no proxy servers.... have checked that javascript is enabled in chrome and no extensions are interfering

**Comment by lianglee** [comment]
![image](https://cloud.githubusercontent.com/assets/805066/18609058/f6d24926-7d11-11e6-90cd-5883d4f81e41.png)

**Comment by timeandspacecadet** [comment]
there is no directory franzjosef.info/franzbook/js/

**Comment by lianglee** [comment]
Try to change line https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/v4.x/system/plugins/default/javascripts/libraries/languages.php#L11
To  : 

     header('Content-Type: application/javascript; charset=utf-8');

**Comment by timeandspacecadet** [comment]
THAT DID IT :-)
YAY thank you
