### ISSUE TITLE
Profile cover comment and likes notification not appears

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#945]
Profile cover comment and likes notification not appears

**Comment by githubertus** [comment]
At a first glance there are hooks missing of type:
comments:entity:file:profile:cover
like:entity:file:profile:cover
in OssnProfile.

And there are no corresponding language strings in OssnNotifications/locale

**Comment by githubertus** [comment]
fixed

**Comment by lianglee** [comment]
Thanks ;)
