### ISSUE TITLE
memberlist may disappear if browser is running in zoomed mode

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#946]
running the browser in full screen mode and enlarging it with several "Strg +" commands makes the memberlist disappear.
maybe here's some hints how to detect the browser's zoom level
http://stackoverflow.com/questions/1713771/how-to-detect-page-zoom-level-in-all-modern-browsers

**Comment by lianglee** [comment]
You mean the member list in sidebar (OssnChat) ?

**Comment by githubertus** [comment]
right

**Comment by lianglee** [comment]
I am not sure what to do with this,  if user have less resolution screen it will surely disappear but after resize it appears again.

**Comment by lianglee** [comment]
Closing.... the member list will get hidden due to it set in OssnChat js ,  it should show new list in bottom of page (bottom chat)
