### ISSUE TITLE
numerous warnings with several actions sending json_encoded data

### ISSUE THREAD

**Issue by githubertus** [opensource-socialnetwork/opensource-socialnetwork#947]
Ossn 4.2, PHP 5.5.36
PHP WARNING: 2016-09-19 12:41:34 (UTC): "Cannot modify header information - headers already sent by (output started at actions/friend/add.php:23)" in file libraries/ossn.lib.actions.php (line 53)

**Comment by lianglee** [comment]
The header problem caused due to some free spaces before some pure php files,  i'll try to check on my side

**Comment by lianglee** [comment]
It didn't shows error for me....

**Comment by githubertus** [comment]
ya strange ... just tried it again ... I'm getting this error on my site with a lot of more actions e.g. commenting a post

**Comment by lianglee** [comment]
There seems issue with some language file (space on start of file) of pure php  check of your custom work (ossn_com.php,  ossn_theme.php)

**Comment by githubertus** [comment]
No, this cannot be the reason.
It started right from the beginning with a completely new installation of ossn-v4.2-1468404691 onto zet.z-mans.net and running default en language and goblue - no custom work involved at that time.
But I remember something starting with php > 5.3 ... let me just check ...

**Comment by githubertus** [comment]
Got it: When error reporting is turned on, with some servers you're getting warnings like 

"Warning: scriptname(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in ...."

The problem: with buffered IO you won't really see this message, instead this message leads to the same result as - like you said - a file with extra spaces in the beginning - and thus forcing the "cannot modify" message. 

In fact, I was able to fix the problem on my other server (hosting zytanien) by adding the line
@ini_set('date.timezone', 'Europe/Berlin');
to ossn.config.site.php

But it doesn't help on z-mans.net. So, most likely there's another hidden warning there, but I have no idea how to grab it ...

**Comment by lianglee** [comment]
Try to disable all core components , if except profile,

**Comment by githubertus** [comment]
finally, adding an "exit;" after the "echo json_encode() function solves the problem for me.

**Comment by lianglee** [comment]
Can you send pull request for action, we shall put it in core (exit)

**Comment by githubertus** [comment]
please, see my last skype posting
