### ISSUE TITLE
Ajax wall post not work it display post after reloading page

### ISSUE THREAD

**Issue by digiapps** [opensource-socialnetwork/opensource-socialnetwork#949]
Hi Team,

I am facing an issue when posting any post ajax loader is showing on submit click and after some times hide and empty the form but post is not appending post top but reflecting after page reload. I write alert in ajax file its alert empty then I echo $get = ossn_wallpost_to_item($get); this line in user.php file its alert following array

Array
(
    [post] => OssnWall Object
        (
            [data] => stdClass Object
                (
                )

            [guid] => 84
            [time_created] => 1474460705
            [created] => 2016-09-21 17:55:05
            [img] => 
            [owner_guid] => 1
            [description] => {"post":"Test test tets etsteb st"}
            [title] => 
            [type] => user
            [subtype] => wall
            [poster_guid] => 1
            [access] => 3
            [sentiment] => 
        )

    [friends] => Array
        (
            [0] => 
        )

    [text] => Test test tets etsteb st
    [location] => 
    [user] => OssnUser Object
        (
            [guid] => 1
            [type] => admin
            [username] => admin
            [email] => sandeep.yadav@mydomain.com
            [password] => 695bb7d92d3c4809d0bb087a1a75df9d
            [salt] => 4f056b56
            [first_name] => Sandeep
            [last_name] => Yadav
            [last_login] => 1474458449
            [designation] => Manager
            [department] => IT
            [l1] => Sandeep Gaur
            [l2] => 
            [address] => N3, N-Block Marketi,
110034
            [city] => Gurgaon
            [zone] => North
            [last_activity] => 1474460705
            [activation] => 
            [time_created] => 1466075833
            [fullname] => Sandeep Yadav
            [birthdate] => 02/09/1985
            [mobilelogin] => 9891568630
            [gender] => male
            [cover_time] => 1474275105
            [language] => en
            [file:profile:photo] => profile/photo/00b062e29cd90fa594c1ea8b62485d05.jpg
            [icon_time] => 1473254117
            [file:profile:cover] => profile/cover/18157a092839503ffc32ac436d53f47f.jpg
            [cover_position] => ["0px","0px"]
            [data] => stdClass Object
                (
                )

        )

    [image] => 
)

Please help to fix the issue

**Comment by digiapps** [comment]
Actully I am getting Null in ossn_set_ajax_data(array(
								'post' => ossn_wall_view_template($get)
						));
While $get is an array of posted data.

**Comment by lianglee** [comment]
Invalid, its not related to OSSN
