### ISSUE TITLE
sharing videos and photos 

### ISSUE THREAD

**Issue by royal27** [opensource-socialnetwork/opensource-socialnetwork#95]
Make a share videos and photos after you insert the link in posting field to appear the video or photo small like fb,implement more sharing social site,vimeo,youtube,twitter,google+,deviantart,soundcloud,imgur,flickr,instagram,metacafe,daylimotion,ted,twitpic,slideshare,hulu,dotsub,collegehumor,revision3,videojug,,blip,screenr,funny or die
 also i`ve made 2 printscreens below

![demo](https://cloud.githubusercontent.com/assets/9817400/5083712/afaf4d4a-6eaf-11e4-86b1-ac7d1ead973f.png)
![demo2](https://cloud.githubusercontent.com/assets/9817400/5083713/afb30a34-6eaf-11e4-8c78-75e6a9585009.png)

**Comment by lianglee** [comment]
As we are no longer accept feature request on github. You can only post bugs here, use community site for posting feature requests.
