### ISSUE TITLE
Error In inner pages for loggedout user

### ISSUE THREAD

**Issue by digiapps** [opensource-socialnetwork/opensource-socialnetwork#950]
Hi,

I am facing a problem when any user is logged out and he accessed any inner page , header and footer is not showing only component's view part is showing without any css style. Can anyone help me to redirect from any inner page to site home page if user is not logged in?

I tried if(!ossn_isLoggedin()) { redirect();} but after that I am unable to access site with error "domainname redirected you too many times".

**Comment by lianglee** [comment]
Invalid, its not related to OSSN

**Comment by digiapps** [comment]
What is invalid in this question?

**Comment by lianglee** [comment]
The invalid in this question is,  its not related to core ossn issue,  are you facing issue on fresh installation of your OSSN, without any modification?  

The github is for only reporting bugs for OSSN, without any modification.
