### ISSUE TITLE
Profile Image roatating 90 degree when uploading Portrait Images

### ISSUE THREAD

**Issue by digiapps** [opensource-socialnetwork/opensource-socialnetwork#957]
Hi,
When trying to upload a portrait image in profile its rotating image to 90 degree but ok  when uploading landscape image

**Comment by githubertus** [comment]
Please read and follow https://www.opensource-socialnetwork.org/wiki/view/705/how-to-report-a-issue-on-github

- are you talking about the member or the cover  image on profile?
- give precise dimensons of the image you're trying to upload

**Comment by digiapps** [comment]
-Yes I am talking about member pic
-Image dimension- 960 X 1280px
-Trying to upload from laptop

**Comment by githubertus** [comment]
Thank you.
Please create an acoount at zet.z-mans.net. That's a plain vanilla Ossn 4.2. If you're experiencing the same problem there, attach your image here with another posting.

**Comment by lianglee** [comment]
closed as no response

**Comment by matrixshopping** [comment]
Yes I am getting the same thing happens to me

**Comment by lianglee** [comment]
@matrixshopping this issue has already been fixed in next version please wait for next version.
