### ISSUE TITLE
OSSN Notification

### ISSUE THREAD

**Issue by pbhuvanesh** [opensource-socialnetwork/opensource-socialnetwork#966]
Hello the notifications does not work properly unless the page is reloaded or unless the notification icon is clicked which the user wouldnt do unless required. Please look into this issue.

**Comment by githubertus** [comment]
please be more precise and provide an example like:
1. Member A made a posting
2. Member B liked the posting of Member A
Member A is (is not?) notified automatically
For me, the above example is working correctly. Member A is receiving a notification ~ 10 seconds later without reloading his page.

Besides that, please install the system-info component,
provide a link to your page,
and name the device/browser you are using

**Comment by lianglee** [comment]
closing as no response
