### ISSUE TITLE
Need to add more genders

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#968]
Need to add more genders 4.4 or >

**Comment by githubertus** [comment]
I don't understand. Besides 'female' and 'male', what else are you thinking of?

**Comment by lianglee** [comment]
Can be closed lol

**Comment by lianglee** [comment]
The reason was i was on debate and someone asked about it that you have only two genders,  i told him look i created ticket. But i don't think it makes sense to add more genders.

**Comment by HannahVernon** [comment]
What purpose does it server to include a gender question?  Either allow the person signing up to specify their gender by typing into a free-form text field, or don't ask for it.  In the very least you need to include `non-binary`, and `other` in the list.  Having only `male` and `female` in the list makes this software absolutely obsolete and completely out of touch with reality.

**Comment by HannahVernon** [comment]
Would you be open to accepting PRs around the gender question?

**Comment by lianglee** [comment]
@HannahVernon You can add more genders https://www.opensource-socialnetwork.org/component/view/3523/add-more-genders

**Comment by HannahVernon** [comment]
I don't see that file in my `components` folder, and looking at the `6.x` branch in GitHub, I don't see the file listed.  I did a search for any file named `*gender*` in the repo, and don't see anything named that.

**Comment by HannahVernon** [comment]
Would you accept a pull request with edits to support `Non Binary`, or should I just create my own fork?

**Comment by lianglee** [comment]
That is very strange skipped the process.  Not sure if you followed https://www.opensource-socialnetwork.org/wiki/view/2006/how-to-install-and-update-components ?

**Comment by lianglee** [comment]
*you skipped the installation process of component.

**Comment by HannahVernon** [comment]
ok, that seems to work, thanks!
