### ISSUE TITLE
The action you requested is invalid.

### ISSUE THREAD

**Issue by amacooldude** [opensource-socialnetwork/opensource-socialnetwork#984]
After installing many times and seeing reported issues by others it seems many have the same issue.
When installing is done and try to log in many recipients see this notice "The action you requested is invalid." maybe this could be due to PHP configuration settings, i,e, the current PHP version being used.
As is, my current PHP version is 7.0 and still i cant login.
Maybe a good idea would be if on notice "The action you requested is invalid." we had more information on what the issue could be, plus maybe a link on footer with helpful info.
Regards 
Gordon

**Comment by lianglee** [comment]
Did you tried on some other hosting provider?

**Comment by lianglee** [comment]
closing as no response

**Comment by githubertus** [comment]
There's a simple way to retrieve more info in situations like that: turn on error_reorting. See
https://www.opensource-socialnetwork.org/wiki/view/1954/how-to-enable-ossn-error-reporting
