### ISSUE TITLE
Adminitrator page error (new installation, not yet touch)

### ISSUE THREAD

**Issue by hard1** [opensource-socialnetwork/opensource-socialnetwork#985]
Ossn V4.2.
My server : Ubuntu 16
Php 7, Mysqli

A system error has occurred. Please try again later. You may email the details of this error to the system administrator at admin@mayatama.tv.

OssnDatabaseException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mysocialnetwork.ossn_users.time_created' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by SELECT DATE_FORMAT(FROM_UNIXTIME(time_created), '%Y') AS year, DATE_FORMAT(FROM_UNIXTIME(time_created) , '%m') AS month, COUNT(guid) AS total FROM ossn_users WHERE(time_created > 0) GROUP by DATE_FORMAT(FROM_UNIXTIME(time_created) , '%Y%m') ; in /home/mayatama/public_html/classes/OssnDatabase.php:77 Stack trace: #0 /home/mayatama/public_html/classes/OssnDatabase.php(175): OssnDatabase->execute() #1 /home/mayatama/public_html/classes/OssnUser.php(949): OssnDatabase->select(Array, true) #2 /home/mayatama/public_html/system/plugins/default/javascripts/dynamic/admin/dashboard/users/users.php(13): OssnUser->countByYearMonth() #3 /home/mayatama/public_html/libraries/ossn.lib.views.php(27): include('/home/mayatama/...') #4 /home/mayatama/public_html/libraries/ossn.lib.views.php(50): ossn_include('/home/mayatama/...', Array) #5 /home/mayatama/public_html/libraries/ossn.lib.plugins.php(75): ossn_view('/home/mayatama/...', Array) #6 /home/mayatama/public_html/system/plugins/default/pages/administrator/contents/dashboard.php(156): ossn_plugin_view('javascripts/dyn...') #7 /home/mayatama/public_html/libraries/ossn.lib.views.php(27): include('/home/mayatama/...') #8 /home/mayatama/public_html/libraries/ossn.lib.views.php(50): ossn_include('/home/mayatama/...', Array) #9 /home/mayatama/public_html/libraries/ossn.lib.plugins.php(75): ossn_view('/home/mayatama/...', Array) #10 /home/mayatama/public_html/libraries/ossn.lib.admin.php(204): ossn_plugin_view('pages/administr...') #11 /home/mayatama/public_html/libraries/ossn.lib.page.php(67): ossn_administrator_pagehandler(Array, 'administrator') #12 /home/mayatama/public_html/index.php(21): ossn_load_page('administrator', Array) #13 {main}

**Comment by rodrigodemacedo** [comment]
With me too!!!

**Comment by lianglee** [comment]
This has to do with your sql settings : http://stackoverflow.com/questions/23921117/disable-only-full-group-by

**Comment by hard1** [comment]
solve... thanks..

**Comment by ngoussong** [comment]
I got this error when installing. Can someone help me please??



A system error has occurred. Please try again later. You may email the details of this error to the system administrator at arthurngoussong@gmail.com.
Error: Call to undefined function mcrypt_get_iv_size() in /var/www/html/ossn/libraries/ossn.lib.system.php:651 Stack trace: #0 /var/www/html/ossn/libraries/ossn.lib.initialize.php(199): ossn_string_decrypt('&\xFA\xABG\x89\xF9T\xBA', 'ossn') #1 /var/www/html/ossn/libraries/ossn.lib.initialize.php(62): ossn_pow_lnk_args() #2 /var/www/html/ossn/libraries/ossn.lib.system.php(226): ossn_initialize('ossn', 'init', NULL) #3 /var/www/html/ossn/system/start.php(40): ossn_trigger_callback('ossn', 'init') #4 /var/www/html/ossn/installation/pages/account.php(12): require_once('/var/www/html/o...') #5 /var/www/html/ossn/installation/libraries/ossn.install.php(76): include('/var/www/html/o...') #6 /var/www/html/ossn/installation/libraries/ossn.install.php(149): ossn_installation_include('/var/www/html/o...') #7 /var/www/html/ossn/installation/index.php(32): ossn_installation_page() #8 {main}
