### ISSUE TITLE
Cant add birthdate while Creating an in 0ssn 4.2 website

### ISSUE THREAD

**Issue by Kacc4u** [opensource-socialnetwork/opensource-socialnetwork#991]
While filling sign up form from mobile phones, my users are not able to add birth-date, this makes sign up incomplete, because it requires all fields to be filled. 

Is it possible for users to sign up with their Phones??

**Comment by githubertus** [comment]
What do you mean exactly with "are not able to add" :
- Is there no calendar popping up when clicking the **Birthdate** field ?
- or there is a calendar popping up, but no date can be selected?
- or there is a calendar popping up, a date can be selected, but after the calendar popup closed, the Birthdate line is still blank?

I've just tried with 2 different Android devices without problems.

Please answer the question above, and and additionally provide the device's manufacturer/model and Operating System and version.
