### ISSUE TITLE
No refesh after submit

### ISSUE THREAD

**Issue by SamueldeSmet** [opensource-socialnetwork/opensource-socialnetwork#992]
When I submit something (text, pixture, ...) then the wheel keeps on turning and the page doesn't refesh.
The content is there after a manual refesh of the page.
The site is behind a nginx reverse proxy that does ssl offloading. Can this be the reason why submit isn't working properly?

**Comment by lianglee** [comment]
We only supported the apache , maybe nginx is causing the issue. For more information please post the details to our community website.
