### ISSUE TITLE
Registeration Page ISSUE with Birthdate

### ISSUE THREAD

**Issue by 1415003** [opensource-socialnetwork/opensource-socialnetwork#993]
Users are not able to register in website due to unable to select the birthdate option....please help with it as soon as possible as i m working for my project.... please check the link and see 
Both in system and mobile device its not poping up any calendar or anything....

calendar is not popping up when clicking the Birthdate field
https://leasychat.000webhostapp.com/

**Comment by githubertus** [comment]
just tried your site with latest Edge, Firefox and Chrome on Windows10 : no problems, calendar is popping up correctly.
And I was able to register a new member, which wouldn't work if birthdate field is not working.
(Your validation email is not working- but that's another story.)

Please provide more details about the OS and Browser you are using, and install and enable the System Info component.
