### ISSUE TITLE
mobile upload

### ISSUE THREAD

**Issue by matrixshopping** [opensource-socialnetwork/opensource-socialnetwork#994]
mobile upload not working but on desktop it is working. what is the fix?

**Comment by githubertus** [comment]
**what kind** of files are you trying to upload **where**  in Ossn? Which mobile device are you using?

**Comment by lianglee** [comment]
I think the mobile pictures are too big to uploaded and not supported by his hosting provider.

**Comment by matrixshopping** [comment]
yes in ossn,  im using a s5 galaxy.

**Comment by matrixshopping** [comment]
It says JPG on the mobile and on the computer the file is JPEG so i don't know if that might be a problem

**Comment by lianglee** [comment]
I think your server upload limit is 2M (which most of servers have) and your image size is larger can you confirm :

- Your server upload size limit
- Your photo size

**Comment by matrixshopping** [comment]
My server upload is set to 4GB so it can't be that.

**Comment by githubertus** [comment]
Would you please answer my question I asked in the beginning: WHERE in Ossn are you trying to upload images? 
On your Profile: Profile Picture, Profile Cover ?
On an  Album Page?
On the Newsfeed?

Or doesn't it work in any place?

Next: Did you switch On Error Reporting from your Ossn Admin Panel? If not, do so and look into the file named "error_log"

**Comment by matrixshopping** [comment]
I am trying to upload on the newsfeed 
How do I turn on error reporting

**Comment by lianglee** [comment]
To turn on report go to : admin panel -> basic settings - > change display errors to on and save settings
After that again upload photos and after few minutes you will see error_log file into your folder where ossn is installed.

**Comment by matrixshopping** [comment]
Tthank you so much it seems like the photo upload from the phone is working now going and try the video upload. Thanks once again

**Comment by matrixshopping** [comment]
It seems that you can't upload video from the news feed uploader only pictures can you confirm if this is true

**Comment by githubertus** [comment]
Photos only, yes. But what did you change that photo upload is working now?

**Comment by matrixshopping** [comment]
All I did was turn on the error reporting and it seems to work now. But when taking a picture landscape from my phone camera it shows up side ways when I upload it.

**Comment by matrixshopping** [comment]
It seems I can't upload portrait pictures from the phone camera it goes back to news feed page each time but I can upload landscape but it shows sideways when uploaded. All this is direct from the camera on the phone.

**Comment by matrixshopping** [comment]
Now it seems even landscape pictures are not working it keep reseting to the login page.

**Comment by matrixshopping** [comment]
Sorry I got land scape and portrait mixed up. So when I used landscape I meant portrait. And when I said portrait I meant landscape.

**Comment by matrixshopping** [comment]
I'm getting a 404 error the page you are requesting  is unavailable or might have been deleted. After I take the picture with the camera it goes to this page then I have to login back

**Comment by lianglee** [comment]
Please make sure you are loggedin before posting any picture,   refresh you page to check if you are logged in or not.  Please note that you can only upload photo from newsfeed wallpost box not videos.

**Comment by matrixshopping** [comment]
a person sign up on my website and it seems he has no email when i look and press to edit in admin it looks like my email was used. what is going on here.

**Comment by githubertus** [comment]
Well, I think it's time to clear up things with your new co-admin first
Maybe he was the one to switch some parts of Ossn temporarely off without letting you know?!

**Comment by matrixshopping** [comment]
Who is the co-admin I have no idea do you know

**Comment by lianglee** [comment]
@matrixshopping as far as we know there is no way to create/edit account without email option,  there is no co-admin he is guessing if you have any co-admin please discuss with him if you don't have any co-admin please ignore it.

This topic is about picture upload,  the 50GB is size of your cpanel fileupload i guess? You need to check with your hosting provider and ask them what is default fileupload via php script.

**Comment by matrixshopping** [comment]
So do I need to start a new topic because I will take screen shots and show you. You have so many bugs in this script is unbelievable

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug

First, don't expect a developer to have any supernatural powers, a seventh sense ... whatever.

Thus, if your report just looks like "My community appears to be corrupted all of a sudden", the core team is as clueless as you are. At that point, you know at least the URL of the corrupted site - while we know absolutely nothing. And without any background nobody will be able to help you.

So, with every bug report please provide at least some useful information which may help us getting an idea what's going wrong. For more details refer to https://www.opensource-socialnetwork.org/wiki/view/705/how-to-report-a-issue-on-github. The more we know in advance the better the chance to track down the problem and to find a fix.

Thank you.

**Comment by matrixshopping** [comment]
if this is how you talk to customers. First, don't expect a developer.....

you need to go back and do customer service classes.

**Comment by githubertus** [comment]
This is how we talk to Admins. We don't expect admins to be developers, but we expect a basic knowledge of the software they're using, their server and provider environment and such. As these are fundamental prerequisites for running a community successfully.

**Comment by lianglee** [comment]
"...You have so many bugs in this script is unbelievable..."

If this is how you talk to people who are trying to help you then you need to go back and take a classes on how to ask for help.
