### ISSUE TITLE
when i poke someone,something wrong

### ISSUE THREAD

**Issue by globetour** [opensource-socialnetwork/opensource-socialnetwork#996]
exception 'OssnDatabaseException' with message 'Incorrect integer value: '' for column 'subject_guid' at row 1 INSERT INTO ossn_notifications (`type`, `poster_guid`, `owner_guid`, `subject_guid`, `item_guid`, `time_created`) VALUES ('ossnpoke:poke', '1', '2', '', '', '1480828350'); ' in /data/wwwroot/default/ossn/classes/OssnDatabase.php:77 Stack trace: #0 /data/wwwroot/default/ossn/classes/OssnDatabase.php(44): OssnDatabase->execute() #1 /data/wwwroot/default/ossn/components/OssnPoke/classes/OssnPoke.php(53): OssnDatabase->insert(Array) #2 /data/wwwroot/default/ossn/components/OssnPoke/actions/user/poke.php(13): OssnPoke->addPoke('1', '2') #3 /data/wwwroot/default/ossn/libraries/ossn.lib.actions.php(51): include_once('/data/wwwroot/d...') #4 /data/wwwroot/default/ossn/system/handlers/actions.php(12): ossn_action('poke/user') #5 {main}

**Comment by lianglee** [comment]
http://stackoverflow.com/questions/2536199/1366-incorrect-integer-valuemysql
