### ISSUE TITLE
This is what appeared after installing.

### ISSUE THREAD

**Issue by Fly34567** [opensource-socialnetwork/opensource-socialnetwork#999]
Can someone help me?
`Error: [] operator not supported for strings in /home/647/331647/public_html/components/OssnWall/classes/OssnWall.php:345 Stack trace: #0 /home/647/331647/public_html/components/OssnWall/plugins/default/wall/siteactivity.php(19): OssnWall->getAllPosts(Array) #1 /home/647/331647/public_html/libraries/ossn.lib.views.php(27): include('/home/647/33164...') #2 /home/647/331647/public_html/libraries/ossn.lib.views.php(50): ossn_include('/home/647/33164...', Array) #3 /home/647/331647/public_html/libraries/ossn.lib.plugins.php(75): ossn_view('/home/647/33164...', Array) #4 /home/647/331647/public_html/components/OssnWall/plugins/default/wall/pages/wall.php(27): ossn_plugin_view('wall/siteactivi...') #5 /home/647/331647/public_html/libraries/ossn.lib.views.php(27): include('/home/647/33164...') #6 /home/647/331647/public_html/libraries/ossn.lib.views.php(50): ossn_include('/home/647/33164...', Array) #7 /home/647/331647/public_html/libraries/ossn.lib.plugins.php(75): ossn_view('/home/647/33164...', Array) #8 /home/647/331647/public_html/libraries/ossn.lib.initialize.php(119): ossn_plugin_view('wall/pages/wall') #9 /home/647/331647/public_html/libraries/ossn.lib.page.php(67): ossn_user_pagehandler(Array, 'home') #10 /home/647/331647/public_html/index.php(21): ossn_load_page('home', Array) #11 {main}`

**Comment by lianglee** [comment]
Please see: https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug

**Comment by Fly34567** [comment]
Ok, I am think it may be the web host itself because it is having problems.

**Comment by Fly34567** [comment]
Website Url: https://wound-up-pond.000webhostapp.com
Ossn version: Ossn 4.3.1
PHP version
Error message `Error: [] operator not supported for strings in /home/647/331647/public_html/components/OssnWall/classes/OssnWall.php:345 Stack trace: #0 /home/647/331647/public_html/components/OssnWall/plugins/default/wall/siteactivity.php(19): OssnWall->getAllPosts(Array) #1 /home/647/331647/public_html/libraries/ossn.lib.views.php(27): include('/home/647/33164...') #2 /home/647/331647/public_html/libraries/ossn.lib.views.php(50): ossn_include('/home/647/33164...', Array) #3 /home/647/331647/public_html/libraries/ossn.lib.plugins.php(75): ossn_view('/home/647/33164...', Array) #4 /home/647/331647/public_html/components/OssnWall/plugins/default/wall/pages/wall.php(27): ossn_plugin_view('wall/siteactivi...') #5 /home/647/331647/public_html/libraries/ossn.lib.views.php(27): include('/home/647/33164...') #6 /home/647/331647/public_html/libraries/ossn.lib.views.php(50): ossn_include('/home/647/33164...', Array) #7 /home/647/331647/public_html/libraries/ossn.lib.plugins.php(75): ossn_view('/home/647/33164...', Array) #8 /home/647/331647/public_html/libraries/ossn.lib.initialize.php(119): ossn_plugin_view('wall/pages/wall') #9 /home/647/331647/public_html/libraries/ossn.lib.page.php(67): ossn_user_pagehandler(Array, 'home') #10 /home/647/331647/public_html/index.php(21): ossn_load_page('home', Array) #11 {main}`
Error Log
Issue screenshots: 
![image](https://cloud.githubusercontent.com/assets/15278051/21104983/98bbfb6a-c056-11e6-99db-6def82777a27.png)
Cache enabled/disabled: Enabled
I can not find other things.

**Comment by lianglee** [comment]
You can replace file (components/OssnWall/classes/OssnWall.php) with this file :  https://raw.githubusercontent.com/opensource-socialnetwork/opensource-socialnetwork/v4.x/components/OssnWall/classes/OssnWall.php
